### ISSUE TITLE
Unable to instantiate backend

### ISSUE THREAD

**Issue by sands6** [NetApp/trident#10]
I am getting some errors when I invoke the launcher-pod. Here is my backend.json:

"version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "x.x.x.x",
    "dataLIF": "y.y.y.y",
    "svm": "Trident-NFS",
    "username": "admin",
    "password": "zzzzzz"
}

Here is the error output from Trident-ephemeral pod:

$ [master +4 ~6 -0 !] kubectl logs trident-ephemeral
time="2017-02-24T17:27:55Z" level=warning msg="Unable to find key Backends.  Continuing bootstrap, but consider checking  integrity if Trident installation is not new."
time="2017-02-24T17:27:55Z" level=warning msg="Unable to find key StorageClasses.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-02-24T17:27:55Z" level=warning msg="Unable to find key Volumes.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-02-24T17:27:55Z" level=warning msg="Couldn't retrieve volume transaction logs: Unable to find key"
time="2017-02-24T17:27:55Z" level=info msg="trident bootstrapped successfully."
time="2017-02-24T17:27:56Z" level=info msg="API server REST call." duration=162.993µs method=GET route=ListBackends uri="/trident/v1/backend"
time="2017-02-24T17:27:56Z" level=error msg="Unable to instantiate backend:  Post https://y.y.y.y/servlets/netapp.servlets.admin.XMLrequest_filer: dial tcp y.y.y.y:443: getsockopt: connection refused" backend= handler=AddBackend
time="2017-02-24T17:27:56Z" level=info msg="API server REST call." duration=117.017513ms method=POST route=AddBackend ur
i="/trident/v1/backend"

**Comment by sands6** [comment]
comment to add to the above note, the ontap backend is on same subnet as that of host network of kubernetes cluster.

**Comment by kangarlou** [comment]
There seems to be an issue with your networking setup. The ONTAP backend should also be reachable from your pod network. You can verify network connectivity by bringing up a basic pod (e.g., a pod based on debian:latest) that pings your storage backend.

**Comment by innergy** [comment]
If you verify network connectivity from your pod and still see this, let us know!
