### ISSUE TITLE
Possibility to provide the the images for trident and etcd as part of install script

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#103]
Most of the times customers cannot directly pull the images from docker hub as most enterprise environments are secure and don't allow that.
For that reason they have to download and push images to their local secure registry.
They then need to update the trident demployment and launcher  yamls with their local image names.
This is many times not very clear to customers.
The request is to actually be able to provide local image names as part of the install script and also add this process in documentation for environments which cannot pull from docker hub.

**Comment by clintonk** [comment]
Hi, Kapil.  Trident 18.04 will contain a completely rewritten installer, and it should support this use case.

A few notes:
- Launcher is gone, as are the install/uninstall scripts
- tridentctl handles the installation
- 'tridentctl' offers two arguments, --generate-custom-yaml and --use-custom-yaml, that allow you to customize the Trident deployment, including the image names for the trident-main and etcd containers.
- This customization process is documented.

Please try this and let us know if it serves the need.

**Comment by kapilarora** [comment]
Sure, when will the beta be out?
Thanks Clinton!

**Comment by adkerr** [comment]
18.04 is due out this month

**Comment by Klaas-** [comment]
I think this would pair fine with #91

**Comment by korenaren** [comment]
Fixed in a0805a4a13888d8a52eb4c3fad2cf1bd2e718f17
