### ISSUE TITLE
ETCD image in case of RedHat OpenShift Container Platform (Enterprise)

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#104]
Most OpenShift customers want to use redhat provided/supported etcd image when installing Trident in OpenShift Enterprise (OCP) environment.
e.g. registry.access.redhat.com/rhel7/etcd

How do we enable that for the customers to choose the right etcd image for their deployment?

**Comment by adkerr** [comment]
I think this should be possible already by updating the yaml files in the installer bundle to point to the rhel7 etcd image. I'm not sure we've tested that it works though.
