### ISSUE TITLE
Protecting Storage system credentials from the K8S/OpenShift admin

### ISSUE THREAD

**Issue by kaparora** [NetApp/trident#106]
Usecase: 
Service  provider Managed OpenShift/K8S. 
Service provider creates an account for openshift env.
Customer has cluster rights for the openshift/k8s cluster
Service Provider would not like the user to see SF credentials as that gices access to other accounts

possible solution:
1) encrypt credentials in db (i am not sure if this is good enough though) where will be the encryption key?
2) SF provides api user accounts which are limited to a tenant. this of course is not in pour hands

What do you think, any other ideas?

**Comment by ToroNZ** [comment]
How are credentials stored exactly? secrets?

**Comment by jason43017** [comment]
My customer is also very interested to have this option.

**Comment by kangarlou** [comment]
@jason43017 This feature is on the roadmap, but I should note that with the default install method where etcd is deployed as part of the Trident pod, only the Trident container can access etcd as the etcd container is locked down to the Trident pod. We also recommend installing Trident in its own namespace (`tridentctl install -n trident`) to ensure that the Trident pod is isolated from the rest of the Kubernetes cluster and nobody can `kubectl exec` into the etcd container and retrieve the Trident state.

**Comment by gnarl** [comment]
As of Trident 20.07 the storage backend credentials are stored in Kubernetes secrets. As of Trident 21.04 a TridentBackendConfig CR can be created where a Kubernetes secret that contains the backend credential is specified. Closing this issue as the original concerns are resolved.
