### ISSUE TITLE
Compatibility with Docker Kubernetes

### ISSUE THREAD

**Issue by acsulli** [NetApp/trident#107]
Using Trident for Kubernetes with the [Docker Kubernetes](https://www.docker.com/kubernetes) provides a consistent experience for containers deployed across different value-add platforms built on Kubernetes.

It is understood that "fully supported" and "tested and believed to work" are not the same thing.  Additionally, this request is specifically for Kubernetes + UCP leveraging Trident's k8s integration, not Trident for Docker and the existing Swarm + UCP functionality.

Andrew

**Comment by innergy** [comment]
Delivered with 18.07 under https://github.com/NetApp/trident/commit/6923137d75e25ffd20a77eb4194754480c6b10fe
