### ISSUE TITLE
Assign QoS policies to ONTAP volumes provisioned by Trident

### ISSUE THREAD

**Issue by acsulli** [NetApp/trident#108]
To support multiple service levels, such as those defined as the result of a Service Management Workshop, Trident should create a QoS policy and assign it to the volume when it is created.  At a minimum, this should support QoS maximums, ideally support for QoS minimums and Adaptive QoS policies would also be available.

**Comment by forgosh** [comment]
This feature is needed by a very large customer with a requirement for Adaptive QOS as the main selling point for the solution.

**Comment by anungw** [comment]
Hi, when will this feature available?

**Comment by clintonk** [comment]
@anungw  Due to an ONTAP limitation, probably not any time soon.

**Comment by gnarl** [comment]
The team is looking at adding support for Adaptive QoS.

**Comment by gnarl** [comment]
With the Trident 21.01 release, ONTAP traditional and adaptive QoS policies are supported.

**Comment by rajshrivastava22** [comment]
Thanks Team.

Does this mean that with below Trident version, Trident can create QOS Policy group and assign it to the provisioned volume?

With the Trident 21.01 release, ONTAP traditional and adaptive QoS policies are supported.
Best Regards
Raj
HCL Technologies
TSCL - Online Storage
+919740985298

Wear Mask and Stay Safe.

Planned vacation : 18th Jan, 25th-29th Jan, 2021

**Comment by balaramesh** [comment]
@rajshrivastava22 yes. With Trident 21.01, you can use the `qosPolicy` and `adaptiveQosPolicy` parameters in the defaults block of your backend definition file. An example backend will look like this:

```
{
  "version": 1,
  "storageDriverName": "ontap-nas",
  "backendName": "customBackendName",
  "managementLIF": "10.0.0.1",
  "dataLIF": "10.0.0.2",
  "svm": "trident_svm",
  "username": "cluster-admin",
  "password": "password",
  "nfsMountOptions": "nfsvers=4",
  "defaults": {
    "qosPolicy": "premium",
    "snapshotPolicy": "default",
    "snapshotReserve": "10"
  }
}
```

You will need ONTAP 9.8 and above for this feature. You can also take a look at examples and all config parameters [here](https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/operations/tasks/backends/ontap/ontap-nas/configuration.html)

**Comment by forgosh** [comment]
Bala
The descriptions for qosPolicy and adaptiveQosPolicy are confusing… On first read they seem to be the same but I think they are actually saying you can only choose one or the other. Is that right?

Seth Forgosh
Solution Architect
Open EcoSystem and Virtualization

NetApp
908.415.0911 Direct Phone
forgosh@netapp.com<mailto:forgosh@netapp.com>

[A picture containing bird  Description automatically generated]<http://netapp.com/>


[signature_1033368733]<https://www.facebook.com/NetApp>   [signature_1389680416] <https://www.instagram.com/netapp/>    [signature_423235238] <https://www.youtube.com/netapp>    [signature_969937969] <https://www.linkedin.com/company/netapp/>    [signature_792801578] <https://twitter.com/NetApp>

**Comment by balaramesh** [comment]
Yes that is correct. Users can choose from `qosPolicy` or `adaptiveQosPolicy` to make use of a pre-defined QoS policy group (traditional or adaptive). Each storage pool takes one QoS Policy Group. If defining backends without Virtual Storage Pools, each backend definition takes either one `qosPolicy` or one `adaptiveQosPolicy`. If the backend contains multiple Virtual Storage Pools defined, then each storage pool can contain one `qosPolicy` or `adaptiveQosPolicy`.

**Comment by rajshrivastava22** [comment]
Thanks Team.

Best Regards
Raj
HCL Technologies
TSCL - Online Storage
+919740985298

Wear Mask and Stay Safe.

Planned vacation : None

**Comment by ravilr** [comment]
@gnarl @clintonk  looks like as part of this feature, Trident dropped support for ontap backend version < 9.3 .  But the Release Changelog Notes for https://github.com/NetApp/trident/releases/tag/v21.01.0 doesn't mention anything about this.  Can we have release notes clearly capture backend support/compatibility changes clearly going forward.
