### ISSUE TITLE
Trident deployment fails for ONTAP Select backend with error Unknown Aggregate type VMDISK

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#11]
Deployment fails with ONTAP Select NAS backend with error unknown Aggregate type VMDISK. 

Here are the logs from trident-ephemeral pod:

root@akapila-openshift:/trident/trident-installer# kubectl logs trident-ephemeral
time="2017-03-01T12:29:14Z" level=warning msg="Unable to find key Backends.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-03-01T12:29:14Z" level=warning msg="Unable to find key StorageClasses.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-03-01T12:29:14Z" level=warning msg="Unable to find key Volumes.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-03-01T12:29:14Z" level=warning msg="Couldn't retrieve volume transaction logs: Unable to find key"
time="2017-03-01T12:29:14Z" level=info msg="trident bootstrapped successfully."
time="2017-03-01T12:29:14Z" level=info msg="API server REST call." duration=124.135µs method=GET route=ListBackends uri="/trident/v1/backend"
time="2017-03-01T12:29:15Z" level=info msg="Successfully initialized Ontap NAS Docker driver version 1.3.1 [trident-1.0]"
time="2017-03-01T12:29:15Z" level=error msg="Aggregate aggr1_select4n_01 has unknown type vmdisk" backend= handler=AddBackend
time="2017-03-01T12:29:15Z" level=info msg="API server REST call." duration=290.114107ms method=POST route=AddBackend uri="/trident/v1/backend"

**Comment by adkerr** [comment]
Tracked internally by [DE295](https://rally1.rallydev.com/#/47479883219d/detail/defect/96276680484)

**Comment by innergy** [comment]
Fixed in 17.04.0

**Comment by clintonk** [comment]
@oz123 Can you provide more details of what you are seeing?  I just installed Trident 18.04 without issue on ONTAP Select 9.3, and we routinely test Trident with ONTAP Select.

I do see the warning about the unknown vmdisk media type, and I can get that fixed for the next release, but that should not prevent you from installing or using Trident (unless you have storage classes that specifically require a specific media type).

**Comment by oz123** [comment]
@clintonk 

Here some info of my setup:
```
Normal  Started                5s    kubelet, k8s-node01vn-nbg4.senacor-lbb.noris.de  Started container
root@k8s-master01vn-nbg4:~/trident-installer # ./tridentctl logs -n trident
ephemeral log:
time="2018-05-25T13:27:48Z" level=info msg="Running Trident storage orchestrator." binary=/usr/local/bin/trident_orchestrator build_time="Thu Jan 25 00:42:53 UTC 2018" version=18.01.0
time="2018-05-25T13:27:48Z" level=info msg="Starting REST interface on :8000"
time="2018-05-25T13:27:48Z" level=info msg="Added frontend." name=REST
time="2018-05-25T13:27:48Z" level=warning msg="Couldn't retrieve volume transaction logs: Unable to find key"
time="2018-05-25T13:27:48Z" level=info msg="trident bootstrapped successfully."

root@k8s-master01vn-nbg4:~/trident-installer # kubectl get pods
No resources found.
root@k8s-master01vn-nbg4:~/trident-installer # kubectl get pods -n trident
NAME                READY     STATUS    RESTARTS   AGE
trident-ephemeral   1/1       Running   0          27s
```
my config is:
```
 # cat setup/backend.json 
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "10.11.3.4",
    "dataLIF": "10.11.1.7",
    "svm": "svm1_c1n6a_lbb",
    "username": "kubernetes",
    "password": "XXXXXX",
    "defaults": {
      "spaceReserve": "volume",
      "exportPolicy": "kubernetes"
    }
}

``` 

The log says `time="2018-05-25T13:27:48Z" level=info msg="trident bootstrapped successfully."`

Which isn't very helpful together with a warning about a none found key.
I am a total noob in NetApp ... I actually need to talk to people who have no clue about kuberentes here so we kind of struggle to understand how to use trident.

Questions:
 - Which key is trident looking for?
 - Why is `trident-ephemral` pod getting stuck?

```
 # kubectl get pods -n trident
NAME                READY     STATUS    RESTARTS   AGE
trident-ephemeral   1/1       Running   0          5m
```

**Comment by clintonk** [comment]
@oz123 You don't appear to be using the latest Trident release.  18.04 has an all-new installer that's easier to use and debug, and the ephemeral pod is no longer needed.  I suggest grabbing that and retrying.

Your backend.json file seems OK.  I assume your 'kubernetes' export policy includes rules that allows any host in your K8S cluster to mount the NFS volumes that Trident creates.  I don't know what permissions you have granted to the 'kubernetes' user, but we mostly test Trident with either _admin_ (cluster credentials) or _vsadmin_ (SVM credentials); it might be good to try vsadmin if you see issues with the new installer.

**Comment by oz123** [comment]
@clintonk  the [code distribution for 18.04 ](https://github.com/NetApp/trident/releases/download/v18.04.0/trident-installer-18.04.0.tar.gz)has no installer . So I opted for an earlier version.

These are the permission my user have:

![unbenannt](https://user-images.githubusercontent.com/1083045/40602226-11f6512a-6258-11e8-8304-1593731e885f.PNG)

**Comment by clintonk** [comment]
@oz123 OK, please post the output from running the 18.04 installer (or tell us what you did to get it working).
