### ISSUE TITLE
Ansible for Trident deployment and management

### ISSUE THREAD

**Issue by acsulli** [NetApp/trident#114]
Kubernetes and OpenShift both have Ansible playbooks for deployment and management of the cluster.  Having playbooks which can be used to deploy, configure, and manage Trident as a part of that would enabled end-to-end hands off deployment of the solution.  Ideally, functionality would include:

- Install
- Upgrade
- Add/remove backend
- Verify backends are present with expected configuration options

Additionally, having example playbooks for creating/managing/verifying storage class objects would be extremely helpful.

Andrew

**Comment by wavezhang** [comment]
I've just made  a pssh one which can deploy and configure Triedent with one click. 
See https://github.com/wavezhang/trident-deploy.

**Comment by innergy** [comment]
That's awesome! I'd love to hear what people think.

**Comment by rendhalver** [comment]
We use Ansible to deploy Trident.
We don't have an upgrade option yet but we will be adding one soon.

**Comment by gnarl** [comment]
Feel free to reopen this request. Recently most of our customers have been requesting a Trident Operator to assist with automation. The Trident Operator was delivered with the 20.04 release.
