### ISSUE TITLE
Error creating Flexvol for qtree.

### ISSUE THREAD

**Issue by r0ss3** [NetApp/trident#117]
Hi,

When provisioning the our first qtree with the ontap-nas-economy driver, we run into the problem that the flexvol for the qtree cannot be provisioned due to a '-' in the name.

> time="2018-04-20T07:44:03Z" level=error msg="Flexvol location/creation failed. Error creating Flexvol for qtree. Error creating Flexvol. API status: failed, Reason: Invalid character '-' in volume name. It can have '_' and alphanumeric characters., Code: 13001"
> time="2018-04-20T07:44:04Z" level=warning msg="Failed to create the volume on this backend!" backend=ontapnaseco_tda01 error="Volume creation failed." pool=tda01_data1 volume=pnu-dev-trident-test-economy-97b63
> time="2018-04-20T07:44:04Z" level=warning msg="Kubernetes frontend couldn't provision a volume: Encountered error(s) in creating the volume: [Failed to create volume pnu-dev-trident-test-economy-97b63 on storage pool tda01_data1 from backend ontapnaseco_tda01: Volume creation failed.] (will retry upon resync)" volume=pnu-dev-trident-test-economy-97b63

I think trident usually maps invalid characters like '.' and '-' to '_' , but it looks like this is not the case for the name of the flexvol where the qtree is to be created.

Can this be fixed? Is there a way to create the flexvols manually to work around this?

**Comment by adkerr** [comment]
For an immediate fix you can update your backend in trident to change the `-`s in your storage prefix to `_`s and it should work fine. Changing the json file you originally used with the updated prefix and “adding” the backend again will update the existing driver.

I know that Trident will convert `.`s but I’m less confident about `-`s. It’s certainly something we can look into.

**Comment by r0ss3** [comment]
aha, I was under the impression it used the namespacename for the flexvol name, which also includes -s in my case.  But you're right, it works when the storagePrefix does not contain -s.

thanks!
