### ISSUE TITLE
Trident should throw a proper error when the configured NetApp ONTAP backend SVM has no Aggregate assigned to it.

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#12]
When setting up Trident for the first time the  ONTAP SVM backend sometimes don't have any aggregates assigned. In this case trident should add a check and throw a proper error message to the user.

Here is the logs when we try to deploy trident with ONTAP NAS backeend with no aggr assigned to SVM.

root@akapila-openshift:/trident/trident-installer# kubectl logs trident-ephemeral
time="2017-03-01T12:27:04Z" level=warning msg="Unable to find key Backends.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-03-01T12:27:04Z" level=warning msg="Unable to find key StorageClasses.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-03-01T12:27:04Z" level=warning msg="Unable to find key Volumes.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-03-01T12:27:04Z" level=warning msg="Couldn't retrieve volume transaction logs: Unable to find key"
time="2017-03-01T12:27:04Z" level=info msg="trident bootstrapped successfully."
time="2017-03-01T12:27:05Z" level=info msg="API server REST call." duration=110.054µs method=GET route=ListBackends uri="/trident/v1/backend"
time="2017-03-01T12:27:05Z" level=info msg="Successfully initialized Ontap NAS Docker driver version 1.3.1 [trident-1.0]"
time="2017-03-01T12:27:05Z" level=info msg="Newly added backend satisfies no storage classes." backendName="ontapnas_10.65.59.165" protocol=file
time="2017-03-01T12:27:05Z" level=info msg="Added a new backend." backend="ontapnas_10.65.59.165" handler=AddBackend
time="2017-03-01T12:27:05Z" level=info msg="API server REST call." duration=289.057936ms method=POST route=AddBackend uri="/trident/v1/backend"
time="2017-03-01T12:27:05Z" level=info msg="API server REST call." duration=165.514µs method=GET route=GetBackend uri="/trident/v1/backend/ontapnas_10.65.59.165"
time="2017-03-01T12:27:05Z" level=info msg="No backends currently satisfy provided storage class." storageClass=trident-basic
time="2017-03-01T12:27:05Z" level=info msg="Added a new storage class." handler=AddStorageClass storageClass=trident-basic
time="2017-03-01T12:27:05Z" level=info msg="API server REST call." duration=203.921µs method=POST route=AddStorageClass uri="/trident/v1/storageclass"
time="2017-03-01T12:27:05Z" level=error msg="No available backends for storage class trident-basic!" handler=AddVolume
time="2017-03-01T12:27:05Z" level=info msg="API server REST call." duration=138.34µs method=POST route=AddVolume uri="/trident/v1/volume"

**Comment by adkerr** [comment]
Tracked internally by [US2312](https://rally1.rallydev.com/#/47479883219d/detail/userstory/96275411716)

**Comment by innergy** [comment]
Fixed in 17.04.0
