### ISSUE TITLE
Support for IPv6

### ISSUE THREAD

**Issue by laxvik** [NetApp/trident#122]
Looking for support of IPv6 in Trident, to be able to deploy it in IPv6 environments (running Kubernetes v1.9+).

**Comment by themaizer** [comment]
@adkerr @netapp-ci Has there been any development on this request?

**Comment by korenaren** [comment]
It's on our list for the future, but no commitment on timeframe at this time.

**Comment by korenaren** [comment]
Making progress on this... what backends are you interested in?

**Comment by themaizer** [comment]
Thanks Marty,

A300 and A700 are the backends that I have interest in.

On Fri, Dec 20, 2019 at 1:28 PM Marty <notifications@github.com> wrote:

> Making progress on this... what backends are you interested in?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_NetApp_trident_issues_122-3Femail-5Fsource-3Dnotifications-26email-5Ftoken-3DAMYZARFEAFVLNPLTX23XSLLQZUFGVA5CNFSM4E5HWYF2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEHNYZJQ-23issuecomment-2D568036518&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=wNU-od0RymUpb8aGGfn1Lp5ispRbsJtUi4k0op4NXPw&m=Vjg7tNFvGu5ZvalgNfL8U7_yRw0t4U45MYu4-nl4Xn0&s=Ca4mOqHjcKXvwquFi1s_6USe-lmZKUsWWVUZjG7tUaI&e=>,
> or unsubscribe
> <https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AMYZARAIS3DTRXQYJTXMVRTQZUFGVANCNFSM4E5HWYFQ&d=DwMCaQ&c=udBTRvFvXC5Dhqg7UHpJlPps3mZ3LRxpb6__0PomBTQ&r=wNU-od0RymUpb8aGGfn1Lp5ispRbsJtUi4k0op4NXPw&m=Vjg7tNFvGu5ZvalgNfL8U7_yRw0t4U45MYu4-nl4Xn0&s=Y4PlHIqk-hgS5GFDq5U3oWXJWXE5UGv8dqbcSPOZ5Yw&e=>
> .
>


-- 
Eric Maiz | Verizon | Network Technology Strategy and Planning | VCP Far
Edge & WebScale | O: 908-203-5712 | M: 908-625-3895

**Comment by laxvik** [comment]
Great to see progress here!
I'm interested in the following backends; FAS8200/A300, A400, A700s and A800.

**Comment by korenaren** [comment]
Our first release of IPv6 support will be for the ONTAP drivers, so you should be covered.

**Comment by gnarl** [comment]
IPv6 support was delivered with the Trident 20.01 release.
