### ISSUE TITLE
Trident install with NetApp Cloud Manager generates volume which is not exposed through NFS

### ISSUE THREAD

**Issue by CalvinHartwell** [NetApp/trident#124]
Hi all,

I'm hitting an issue when using the Trident install with the NetApp Cloud Manager. When I run tridnet install, trident creates its initial volume on the NetApp cloud manager called trident_trident:

![trident storage](https://raw.githubusercontent.com/CanonicalLtd/canonical-kubernetes-third-party-integrations/master/cdk-netapp-trident/images/NetApp-OnCommand-CloudManagerGUI-wkenv-NOMOUNT.png "NO MOUNT OPTIONS")

As you can see, the mount command is greyed out and not available, this will usually give you the mount command used to mount the NFS share on the file system. This is because Trident or the Cloud Manager has not given the new volume a custom export policy, so I have to edit the volume and set it:

![trident storage](https://raw.githubusercontent.com/CanonicalLtd/canonical-kubernetes-third-party-integrations/master/cdk-netapp-trident/images/NetApp-OnCommand-CloudManagerGUI-wkenv-fix.png "Mount Fixed")

As trident doesn't automatically delete its own volume during the uninstall process we're good. I run trident uninstall and then trident install and it gets configured correctly. My guess is that this is an API issue with Trident itself. 

All subsequent volumes mounted via PV/PVC are error free and do not suffer this problem it is only the initial volume creation which causes the problem. 

I have described it in more detail here: [https://github.com/CanonicalLtd/canonical-kubernetes-third-party-integrations/tree/master/cdk-netapp-trident#deploying-netapp-trident](https://github.com/CanonicalLtd/canonical-kubernetes-third-party-integrations/tree/master/cdk-netapp-trident#deploying-netapp-trident). 

Feel free to ask questions, I can record a video of the issue if required. 

Cheers,

- Calvin

**Comment by adkerr** [comment]
Another option could be to set a default export policy in your backend.json file to points to an appropriate custom export policy on the filer. That way you don’t have to expose all non-trident volumes by default (this is slightly more secure than the opening the `default` policy)

**Comment by CalvinHartwell** [comment]
@adkerr thanks for the quick reply, do you know how to set the default SVM policy within the cloud manager?

**Comment by adkerr** [comment]
@CalvinHartwell I’m afraid I’m not familiar with Cloud Manager. I know how to do it in straight ONTAP. Sorry

**Comment by CalvinHartwell** [comment]
@adkerr no worries, but it would be good to get this integration seemless. Is there any chance you could flag this at your end? I don't think you can actually set what you require using the Cloud Manager so it seems like a feature request for that product. I can use the official channels if required.

**Comment by adkerr** [comment]
Official channels would be best for the cloud manager product. I don’t personally have any contacts there and external requests usually get more weight anyway.

**Comment by phoebegoh** [comment]
It would be good if it were possible to specify the export policy for the trident_trident volume during installation, perhaps.  I encountered this last week as well and it wasn't clear why the install had failed.  The assumption that the default policy on the SVM allows access is the opposite of what OCCM defaults to which is that default=no access.  (It creates a policy per volume).

@CalvinHartwell I'll also reach out to the OTC team, I spend more time in Cloud Manager than I do with k8s.

**Comment by CalvinHartwell** [comment]
thanks @phoebegoh !

@adkerr @phoebegoh do you have an example backend file for multiple OnTAP devices?

**Comment by adkerr** [comment]
@CalvinHartwell you have 1 backend file per backend. You can then add multiple backends to trident using the various files

**Comment by innergy** [comment]
You should be able to specify the export policy used for Trident’s metadata volume using the “exportPolicy” field in the “defaults” section of the backend configuration that you use during installation. Is that not working?

http://netapp-trident.readthedocs.io/en/stable-v18.04/kubernetes/operations/tasks/backends/ontap.html#backend-configuration-options

**Comment by innergy** [comment]
@CalvinHartwell Apologies, I was responding to @adkerr, where he suggested that Trident required a properly configured `default` export policy, but even for the metadata volume you can specify any export policy of your choosing, and that's the one that Trident will use when it provisions the volume.

Cloud Manager actually creates an export policy for the whole SVM when you first configure it:

![image](https://user-images.githubusercontent.com/8595842/39969938-71c9ee02-56b1-11e8-9105-155d6f8fcf41.png)

That's the one you want to use. I believe the trouble you're having is that you don't know the names of the policies that are getting created for you. (Cloud Manager can also create a separate export policy for each volume, but Trident doesn't support volume-granular policies like that today.)

Here's what those policies look like, from an ONTAP Cloud instance I'm running:

ontapcloud::vserver export-policy> show
Vserver          Policy Name
---------------  -------------------
svm_ontapcloud   default
svm_ontapcloud   export-svm_ontapcloud
svm_ontapcloud   export-svm_ontapcloud-vol1
3 entries were displayed.

Based on the formatting above, the export policy name you want to specify in your backend configuration file is `export-<SVM Name>`, where `<SVM Name>` is the name of the SVM that you see on the lower-left if you click `Information` from within your working environment in Cloud Manager:

![image](https://user-images.githubusercontent.com/8595842/39970052-f87e5cb6-56b2-11e8-9170-650c4d0502e4.png)

Regarding your last question, you cannot currently tie storage classes to specific named backends. You can either specify generic properties that may match multiple backends, or a list of specific storage pools discovered within specific backends. See this section of the documentation for more details: https://netapp-trident.readthedocs.io/en/stable-v18.04/kubernetes/concepts/objects.html#kubernetes-storageclass-objects

**Comment by CalvinHartwell** [comment]
@innergy thanks for the reply, very useful information. Hopefully I will test this out one evening this week and update my guide + this Issue. I think I can get it to work but like you said, Cloud Manager generates an export policy and I'm not sure how to check it - I can probably work this out now given some time. 

I understand the storage pool concept and the attributes for the backend, but I'm quite interested in how the OnTap devices (or other devices) as part of a storage pool are picked, is it based on remaining size? round robin? 

If I have say, 3 storage devices in a pool, I'd like the load to be shared. I was also interested in exposing OnTAP device (or other storage devices) using other protocols to Kubernetes like using iSCI, is that supported? 

Cheers

**Comment by acsulli** [comment]
@CalvinHartwell Currently, Trident selects from the matching storage pools randomly.  You can see the code for the operation [here](https://github.com/NetApp/trident/blob/master/core/orchestrator_core.go#L688-L716). 

We have an open feature request (#64) to improve the intelligence here.  If it's something you're interested in, please +1 that request along with any additional comments you have.

Andrew

**Comment by korenaren** [comment]
Closing this one. Please open a new issue if there are remaining requests here.
