### ISSUE TITLE
Docker CE 18.03 version supported ?

### ISSUE THREAD

**Issue by rverpillot** [NetApp/trident#127]
Are recent versions of docker CE supported ?
The versions requirements in the documentation site are 17.12 and older, and docker-ce 18.06 will be released soon.

**Comment by adkerr** [comment]
Docker CE 18.03.1 is supported. There is a critical bug in 18.03.0 and it should not be used with our plugin.

**Comment by adkerr** [comment]
I should also mention we test with the latest edge branch in our CI, so we also support 18.04 and 18.05 currently as well.
