### ISSUE TITLE
Docker plugins not enabled after host reboot or docker service restart

### ISSUE THREAD

**Issue by forgosh** [NetApp/trident#129]
I verified that with Trident 18.01, when the host or docker service is restarted the plugins are automatically enabled. With Trident 18.04, the plugins are disabled and have to be manually enabled. This is reproducible with the following:
```
$ sudo install -y vim epel-release
$ sudo yum install -y yum-utils   device-mapper-persistent-data   lvm2
$ sudo yum-config-manager     --add-repo     https://download.docker.com/linux/centos/docker-ce.repo
$ sudo yum install docker-ce
$ sudo systemctl enable docker
$ sudo systemctl start docker
$ sudo systemctl status docker
$ sudo vim /etc/netappdvp/config.json
Copy in configs
$ docker plugin install netapp/trident-plugin:18.04.0 --alias netapp --grant-all-permissions
$ docker plugin ls
$ systemctl restart docker
$ docker plugin ls
```

**Comment by dsmorse** [comment]
We reverted back to 18.01 to dodge around this

**Comment by Routhinator** [comment]
Also seeing this. It's been quite some time without any word from devs. Any work being done for this? This bug makes claims that this driver is "ready for production" quite questionable.

**Comment by innergy** [comment]
Does it really?

We've been looking into this for a while. Unfortunately Docker unexpectedly introduced a number of tight timeouts in their 18.03 release that forced us to re-architect Trident's entire initialization process. Much of that work was done in 18.04, and improvements have been made in 18.07, but there appear to be some additional timing gaps that are unaccounted for that we're working to close.

**Comment by silentpete** [comment]
@innergy,
Just tested Trident Plugin fix for #129, works great! 

Do we know when the next beta will be released or an actual release?

**Comment by korenaren** [comment]
@silentpete Thank you for breaking your silence to let us know! We are working feverishly to get our official 18.07 release out by end of July, so should be any day now.

**Comment by silentpete** [comment]
@korenaren your welcome!  👍 

Cool!! 
Thank you so much everyone!
