### ISSUE TITLE
Provision a volume by cloning from snapshot

### ISSUE THREAD

**Issue by carlcantprogram** [NetApp/trident#13]
Is there a way to specify a volume/snapshot/pv to clone from when creating a PVC? We want to provide bulk test data to a POD on startup.

**Comment by carlcantprogram** [comment]
Any thoughts on adding this functionality to the plugin?

**Comment by bnaylor** [comment]
You're going to be pleasantly surprised....

**Comment by kangarlou** [comment]
Kubernetes doesn't currently support volume snapshots or clones. The good news is that supporting snapshots and creating a volume from a snapshot are currently being discussed in the the Kubernetes Storage SIG. We're watching this space and will add support once APIs and their functions finalize in Kubernetes.

**Comment by kapilarora** [comment]
Any updates on this?

**Comment by kapilarora** [comment]
Do we have any plans on extending the clone functionality to 'Clone from Snapshot'? 
Any updates on Snapshot APIs in general in k8s?

**Comment by kangarlou** [comment]
These topics are currently being discussed by the community. Snapshots may be supported in k8s 1.12 and other volume operations like clone from snapshots are targeted for later.

**Comment by forgosh** [comment]
Cloning from the PVC limits clones to the same namespace. Cloning either from a snapshot or an existing PV is needed to be able to clone to a different namespace.

**Comment by kangarlou** [comment]
Cloning a volume to a different namespace is currently being discussed by the community: https://github.com/erinboyd/community/blob/patch-3/contributors/design-proposals/storage/cloning.md. The manual solution is the recommended approach for now. Once Trident supports volume import (https://github.com/NetApp/trident/issues/74), Trident can manage the manually provisioned volumes.

**Comment by korenaren** [comment]
Available in 19.07 with the CSI provisioner.
