### ISSUE TITLE
Support for ETCD Member service start/stop in Trident Pod with built-in etcd

### ISSUE THREAD

**Issue by mani88451** [NetApp/trident#140]
We are in the process of backup/restore the Trident ETCD database incase of DR situation. Normally we follow below procedure to restore ETCD backup
1. Copy the backup files into ETCD member
2. Stop the ETCD member service using systemctl
3. Delete the data directory and restore the backup

But in default container we dont have systemctl binary to stop the member service also we dont find any other option to stop the member service in default trident etcd container. So please let us know how to stop the etcd service to delete the data directory for restoring the backup.. If you have any other easy way to restore also please suggest us.

**Comment by innergy** [comment]
If this is impacting you now, your best bet is to open a support case. This isn't really a great venue for interactive troubleshooting.
