### ISSUE TITLE
Artificially limit logical capacity of the underlying volumes provisioned by the economy driver

### ISSUE THREAD

**Issue by cgajan** [NetApp/trident#141]
Hello Trident Team,

ontap-nas-economy driver create automatically new ONTAP volume to host ONTAP qtree
A provisioned volume will be filled up to 200 qtrees
This seems to be the only "sizing" criteria to trigger the creation of a new volume
Moreover this limit is hardcoded

We would like to have the 2 enhancements below

1. The "maxQtreesPerFlexvol" constant limit must be configurable (see trident/storage_drivers/ontap/ontap_nas_qtree.go). Could be a new storageclass driver attribute or a newbackend options

2. The amount of provisioned qtree quota must be a new criteria to consider a volume as not eligible to host a new qtree. This new "maxAmountQuotaPerFlexvol" limit must also be configurable. Could be a new storageclass driver attribute or a newbackend options. To be eligible the sum of quota (included the new requested qtree) hosted by the volume must be lesser than "maxAmountQuotaPerFlexvol"

Regards

**Comment by cgajan** [comment]
### Proposed code to implement enhancement 2 (maybe not 100% correct)

modified code is `storage_drivers/ontap/ontap_nas_qtree.go`

- usage of `getOptimalSizeForFlexvol` function in the `getFlexvolForQtree` code help to implement with a minimum of effort enhancement 2
- Notice that `sizeBytes` must be forward from `Create ` function to the `getFlexvolForQtree`


>248     maxAmountQuotaPerFlexvol := utils.GetV(opts, "maxAmountQuotaPerFlexvol", d.Config.maxAmountQuotaPerFlexvol)

>260 	flexvol, err := d.ensureFlexvolForQtree(
>261		aggregate, spaceReserve, snapshotPolicy, enableSnapshotDir, encrypt, sizeBytes)
		
>506     func (d *NASQtreeStorageDriver) ensureFlexvolForQtree(
>507 	aggregate, spaceReserve, snapshotPolicy string, enableSnapshotDir bool, encrypt *bool, sizeBytes uint64,
>508     ) (string, error) {
>509
>510  	// Check if a suitable Flexvol already exists
>511 	flexvol, err := d.getFlexvolForQtree(aggregate, spaceReserve, snapshotPolicy, enableSnapshotDir, encrypt, sizeBytes,)		
		
		
>610     func (d *NASQtreeStorageDriver) getFlexvolForQtree(
>611 	aggregate, spaceReserve, snapshotPolicy string, enableSnapshotDir bool, encrypt *bool, >sizeBytes uint64,
>612     ) (string, error) {
>613
>614 	// Get all volumes matching the specified attributes
>615 	volListResponse, err := d.API.VolumeListByAttrs(
>616 		d.FlexvolNamePrefix(), aggregate, spaceReserve, snapshotPolicy, enableSnapshotDir, >encrypt)
>617
>618 	if err = api.GetError(volListResponse, err); err != nil {
>619 		return "", fmt.Errorf("error enumerating Flexvols: %v", err)
>620 	}
>621
>622 	// Weed out the Flexvols already having too many qtrees
>623 	var volumes []string
>624 	for _, volAttrs := range volListResponse.Result.AttributesList() {
>625 		volIDAttrs := volAttrs.VolumeIdAttributes()
>626 		volName := string(volIDAttrs.Name())
>627		
>628 		volAmountQuota, err := d.getOptimalSizeForFlexvol(volName, sizeBytes)
>629 		if err != nil { volAmountQuota := sizeBytes }
>630		
>631 		count, err := d.API.QtreeCount(volName)
>632 		if err != nil {
>633 			return "", fmt.Errorf("error enumerating qtrees: %v", err)
>634 		}
>635
>636         maxAmountQuotaPerFlexvolUint := strconv.ParseUint(maxAmountQuotaPerFlexvol, 10, 64)
>636 		if volAmountQuota < maxAmountQuotaPerFlexvolUint {
>637 		    if count < maxQtreesPerFlexvol {
>638 			    volumes = append(volumes, volName)
>639 		    }
>640 		}
>641 	}
>642
>643 	// Pick a Flexvol.  If there are multiple matches, pick one at random.
>644 	switch len(volumes) {
>645 	case 0:
>646 		return "", nil
>647 	case 1:
>648 		return volumes[0], nil
>649 	default:
>650 		rand.Seed(time.Now().UnixNano())
>651 		return volumes[rand.Intn(len(volumes))], nil
>652 	}
>653 }

**Comment by innergy** [comment]
The limit on the number of qtrees we provision in a volume may seem arbitrary and the sort of thing that should be configurable, but it's actually based on a careful analysis of several constraints that we're managing for you within the driver. We don't have any intention of making that configurable at this time. If the current limit is causing a specific problem, we'd love to hear more about that.

I believe we'll satisfy your second requirement with the changes we're making for #64. Can you confirm?

**Comment by cgajan** [comment]
Thank you  for the consideration you have for each request made. Whatever you final choice, we  appreciate

Controlling the number of qtree in a volume is not the most important feature (we can forget it). What is important for us is to control the maximum amount of data hosted on a volume (second requirement). Maybe changes considered for #64 can satisfy our wish, but it not very clear for me what you plan to do for #64.  The #64 requestor talk about:

> Allow Trident to be configured so that we only continue to provision qtrees in a flexvol until the underlying aggregate is X percentage full or Y percentage oversubscribed

But for us, it is important to control the size on the volume not only aggregate free space.
Why controlling the volume size ? Two reasons for that in our context:
- All our volumes are backed up. To Restore we use NDMP, and NDMP performance depends on volume size (inode). So our best practices say to not go up 30TB
- We play a lot with volume move to host volumes on the right aggregate depending of application activity life cycle. So having too large volumes is a drawback when you have to move them. So our best practices say to not go up 30TB

Could you please provide us some details about what you plan to do regarding #64, so I can tell you if that could satisfy us.

**Comment by innergy** [comment]
Thanks for the additional detail. That makes sense.

The work we were planning for #64 is based completely on the aggregate. The use case there is to decrease the likelihood that we would run out of physical capacity when thin provisioning.

Your use case is different, though. You want to arbitrarily limit logical capacity. Something you can already do with the other drivers, but not the economy driver. I'll refactor this issue and we'll consider addressing both at the same time.
