### ISSUE TITLE
RFE: wish ontap-nas-economy driver spawn external process at flexvol and qtree creation

### ISSUE THREAD

**Issue by cgajan** [NetApp/trident#142]
**Hello Trident Team,**

Each time that ontap-nas-economy driver create a new flexvol to host a new qtree, it would be great to be able to trigger an external local command with some parameters relative to the new created flexvol. This allow us to be able to trigger custom operation relative to a new volume creation as register the volume in a CMDB ... The external local command would maybe merely trigger a remote command through SSH, DB connect or REST API.
A weakness of using such local external commands is the need to reinstall them each time that trident is updated (manual install in the trident-main container) but it is better than nothing.

We wish a same mechanism for qtree creation and deletion. So we need 3 backend options to define absolute path of our 3 commands

- `volumeCreationHook`
- `qtreeCreationHook`
- `qtreeDestroyHook`

_example_: `volumeCreationHook: /usr/local/hook/bin/volumeCreation.sh`

**Below a draft code proposal**

**in the 'Create' function around line 294 in storage_drivers/ontap/ontap_nas_qtree.go**
	
>	// Create the qtree
>	qtreeResponse, err := d.API.QtreeCreate(name, flexvol, unixPermissions, exportPolicy, securityStyle)
>	if err = api.GetError(qtreeResponse, err); err != nil {
>		log.Errorf("Qtree creation failed. %v", err)
>		return createError
>	}
>	qtreeCreationHook := utils.GetV(opts, "qtreeCreationHook", d.Config.qtreeCreationHook)
>	sizeBytesStr := strconv.FormatUint(sizeBytes, 10)
>	qtreeCreateHookCmd, err := exec.Command(qtreeCreationHook, name, flexvol, unixPermissions, exportPolicy, secirityStyle, sizeBytesStr)
>	if err != nil {
>        log.Errorf("Qtree Creation Hook spawn failed. %v", err)
>    }
	
**in the 'ensureFlexvolForQtree' function around line 521 in storage_drivers/ontap/ontap_nas_qtree.go**
	
>	// Nothing found, so create a suitable Flexvol
>	flexvol, err = d.createFlexvolForQtree(aggregate, spaceReserve, snapshotPolicy, enableSnapshotDir, encrypt)
>	if err != nil {
>		return "", fmt.Errorf("error creating Flexvol for qtree: %v", err)
>	}
>	volumeCreationHook := utils.GetV(opts, "volumeCreationHook", d.Config.volumeCreationHook)
>	volCreateHookCmd, err := exec.Command(volumeCreationHook, flexvol, aggregate, spaceReserve, snapshotPolicy)
>	if err != nil {
>        log.Errorf("Volume Creation Hook spawn failed. %v", err)
>    }
>	
>	return flexvol, nil	
	
**in the 'Destroy' function around line 377 instorage_drivers/ontap/ontap_nas_qtree.go**
	
>	destroyResponse, err := d.API.QtreeDestroyAsync(deletedPath, true)
>	if err = api.GetError(destroyResponse, err); err != nil {
>		log.Errorf("Qtree async delete failed. %v", err)
>		defer d.API.QtreeRename(deletedPath, path)
>		return deleteError
>	}
>	qtreeDestroyHook := utils.GetV(opts, "qtreeDestroyHook", d.Config.qtreeDestroyHook)
>	qtreeDelHookCmd, err := exec.Command(qtreeDestroyHook, name, flexvol)
>	if err != nil {
>        log.Errorf("Qtree Destroy Hook spawn failed. %v", err)
>    }	
>
>	return nil

**Comment by cgajan** [comment]
Thanks for your open and honest answer. Currently my plan is to implement a post-processing job which check new volume emergence and do the needed actions (add in CMDB, configure a backup, ...) So yes I have a solution, certainly less integrated to Trident but good enough to go forward. Thanks you for mentioning Trident REST API, because I forgot this possibility and this can make the work easier.

**Comment by innergy** [comment]
Excellent! Let us know how it goes!
