### ISSUE TITLE
etcd hangs forever waiting for a lock

### ISSUE THREAD

**Issue by r0ss3** [NetApp/trident#145]
Hi All,

This is trident 18.04 running in an openshift environment.  We have ephemeral openshift nodes, so for patching and maintenance nodes are removed and replaced with new ones.  Sometimes it happens that trident does not recover from such a stop/restart.  In this case etcd waits for a lock immediatly after the restart on another node.  

> oc logs -f trident-76fb9bc964-97b9k -c etcd
> 2018-06-22 10:02:25.794371 I | etcdmain: etcd Version: 3.1.12
> 2018-06-22 10:02:25.797261 I | etcdmain: Git SHA: 918698add
> 2018-06-22 10:02:25.797269 I | etcdmain: Go Version: go1.8.7
> 2018-06-22 10:02:25.797275 I | etcdmain: Go OS/Arch: linux/amd64
> 2018-06-22 10:02:25.797280 I | etcdmain: setting maximum number of CPUs to 8, total number of available CPUs is 8
> 2018-06-22 10:02:25.804451 W | etcdmain: found invalid file/dir .snapshot under data dir /var/etcd/data (Ignore this if you are upgrading etcd)
> 2018-06-22 10:02:25.804489 N | etcdmain: the server is already initialized as member before, starting as etcd member...
> 2018-06-22 10:02:25.804763 I | embed: listening for peers on http://127.0.0.1:8002
> 2018-06-22 10:02:25.804833 I | embed: listening for client requests on 127.0.0.1:8001
> 2018-06-22 10:02:26.863564 W | etcdserver: another etcd process is running with the same data dir and holding the file lock.
> 2018-06-22 10:02:26.863598 W | etcdserver: waiting for it to exit before starting...

This is the second time we have seen this in our environment.  This particular instance was waiting like this for 12 days before we noticed new volumes were not being created.  A restart of the pod did help this time.  The first we ran into this we had to revert to a snapshot of etcd to get it up and running again.

Anyone any ideas why this is happening?

**Comment by kangarlou** [comment]
Hi @r0ss3. The main culprit for `etcdserver: another etcd process is running with the same data dir and holding the file lock` is not waiting long enough for the previous instance of Trident to go down (e.g., via `tridentctl uninstall`) and before bringing up a new instance (e.g., via `tridentctl install`). We have also added liveness probes for trident and etcd containers, which makes detecting and recovering from this problem easier. This feature is available in https://github.com/NetApp/trident/releases/tag/v18.07.0-beta.1.

**Comment by r0ss3** [comment]
Thanks for the quick response.  Good to hear that 18.07 will have liveness probes!

Do you know how long this lock is held?  And does this mean etcd does not exit correctly when the pod is stopped?

**Comment by kangarlou** [comment]
The lock is held as long as there is a running etcd instance using it. Any new instance you bring up in the meantime, will wait and retry to acquire the lock for a limited period of time (initially it was 10s; now it's a little longer) and then it gives up, which was the scenario you encountered.

etcd exits correctly if you bring down the pod; you just have to give it enough time to properly shut down before you bring up a new instance (i.e., make sure the old Trident pod is gone before you bring up a new instance).

**Comment by r0ss3** [comment]
Our trident deployments run with .spec.strategy.type==Recreate, so I don't think it is possible that 2 instances run at any given time.  However I've added the liveness probes so if it happens again the situation should resolve itself now.

**Comment by r0ss3** [comment]
Reopening because it seems the liveness probe does not really fix it.  I have a trident instance now restarting because of the liveness probe for almost a full day:

```
$ oc get pod trident-597c7c7578-tcfkp
NAME                       READY     STATUS             RESTARTS   AGE
trident-597c7c7578-tcfkp   0/2       CrashLoopBackOff   685        21h
```

So even with .spec.strategy.type==Recreate we sometimes run into this lock.  The lock is still held after more than 21 hours, and the liveness probes do not make it any better :(

**Comment by kangarlou** [comment]
Have you tried running https://github.com/NetApp/trident/releases/tag/v18.07.0-beta.1? This version runs etcd v3.2.19. Trident v18.04 uses etcd v3.1.5.

**Comment by kangarlou** [comment]
With etcd v3.1.5 (shipped with Trident v18.04) and v3.2.19 (shipped with Trident v18.07), the wait time is 1 second: 
https://github.com/coreos/etcd/blob/v3.1.5/etcdserver/server.go#L279:L283
https://github.com/coreos/etcd/blob/v3.2.19/etcdserver/backend.go#L61:L64

With etcd 3.3, timeout has been increased to 10 seconds:
https://github.com/coreos/etcd/commit/0365a9dee80f004200e157bf834a6a9210e95b49

We haven't qualified Trident with etcd v3.3.X, but I'm curious to see if the problem occurs with this version of etcd. One workaround is to provision the etcd volume on an ONTAP SAN SVM if that's an option for you. That way NFS locking wouldn't be an issue.

To debug NFS locking, you may find the `vserver locks show` command useful: https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-cmpr-940/vserver__locks__show.html
I would run this command when no Trident pod (etcd) is running.

**Comment by r0ss3** [comment]
I upgraded to 18.07.0 with etcd 3.2.19 today, and it seems the etcd 3.2 does handle the file lock better.  It still sees the lock, but it seems to continue successfully now:

> 2018-08-14 09:26:13.477669 I | etcdmain: etcd Version: 3.2.19
> 2018-08-14 09:26:13.477775 I | etcdmain: Git SHA: 8a9b3d538
> 2018-08-14 09:26:13.477779 I | etcdmain: Go Version: go1.8.7
> 2018-08-14 09:26:13.477785 I | etcdmain: Go OS/Arch: linux/amd64
> 2018-08-14 09:26:13.477789 I | etcdmain: setting maximum number of CPUs to 4, total number of available CPUs is 4
> 2018-08-14 09:26:13.489576 W | etcdmain: found invalid file/dir .snapshot under data dir /var/etcd/data (Ignore this if you are upgrading etcd)
> 2018-08-14 09:26:13.489605 N | etcdmain: the server is already initialized as member before, starting as etcd member...
> 2018-08-14 09:26:13.490031 I | embed: listening for peers on http://127.0.0.1:8002
> 2018-08-14 09:26:13.490102 I | embed: listening for client requests on 127.0.0.1:8001
**> 2018-08-14 09:26:14.608328 W | etcdserver: another etcd process is using "/var/etcd/data/member/snap/db" and holds the file lock.
> 2018-08-14 09:26:14.608903 W | etcdserver: waiting for it to exit before starting...**
> 2018-08-14 09:26:15.926735 I | etcdserver: recovered store from snapshot at index 220022
> 2018-08-14 09:26:15.928923 I | etcdserver: name = etcd1
> 2018-08-14 09:26:15.928938 I | etcdserver: data dir = /var/etcd/data
> 2018-08-14 09:26:15.928944 I | etcdserver: member dir = /var/etcd/data/member
> 2018-08-14 09:26:15.928948 I | etcdserver: heartbeat = 100ms
> 2018-08-14 09:26:15.928952 I | etcdserver: election = 1000ms
> 2018-08-14 09:26:15.928955 I | etcdserver: snapshot count = 100000
> 2018-08-14 09:26:15.928969 I | etcdserver: advertise client URLs = http://127.0.0.1:8001
> 2018-08-14 09:26:25.685054 I | etcdserver: restarting member 9ca0c7938a0c3dc5 in cluster d5856e2bc623615e at commit index 225018
> 2018-08-14 09:26:25.687497 I | raft: 9ca0c7938a0c3dc5 became follower at term 13
> 2018-08-14 09:26:25.687540 I | raft: newRaft 9ca0c7938a0c3dc5 [peers: [9ca0c7938a0c3dc5], term: 13, commit: 225018, applied: 220022, lastindex: 225018, lastterm: 13]
> 2018-08-14 09:26:25.775883 I | etcdserver/api: enabled capabilities for version 3.1
> 2018-08-14 09:26:25.775914 I | etcdserver/membership: added member 9ca0c7938a0c3dc5 [http://127.0.0.1:8002] to cluster d5856e2bc623615e from store
> 2018-08-14 09:26:25.775921 I | etcdserver/membership: set the cluster version to 3.1 from store
> 2018-08-14 09:26:25.780773 W | auth: simple token is not cryptographically signed
> 2018-08-14 09:26:25.783250 I | etcdserver: starting server... [version: 3.2.19, cluster version: 3.1]
> 2018-08-14 09:26:25.784404 I | etcdserver: 9ca0c7938a0c3dc5 as single-node; fast-forwarding 9 ticks (election ticks 10)
> 2018-08-14 09:26:26.382978 I | raft: 9ca0c7938a0c3dc5 is starting a new election at term 13
> 2018-08-14 09:26:26.383008 I | raft: 9ca0c7938a0c3dc5 became candidate at term 14
> 2018-08-14 09:26:26.383022 I | raft: 9ca0c7938a0c3dc5 received MsgVoteResp from 9ca0c7938a0c3dc5 at term 14
> 2018-08-14 09:26:26.383036 I | raft: 9ca0c7938a0c3dc5 became leader at term 14
> 2018-08-14 09:26:26.383046 I | raft: raft.node: 9ca0c7938a0c3dc5 elected leader 9ca0c7938a0c3dc5 at term 14
> 2018-08-14 09:26:26.387333 I | etcdserver: published {Name:etcd1 ClientURLs:[http://127.0.0.1:8001]} to cluster d5856e2bc623615e
> 2018-08-14 09:26:26.387384 I | etcdserver: updating the cluster version from 3.1 to 3.2
> 2018-08-14 09:26:26.464768 N | etcdserver/membership: updated the cluster version from 3.1 to 3.2
> 2018-08-14 09:26:26.464846 I | etcdserver/api: enabled capabilities for version 3.2
> 2018-08-14 09:26:26.464869 I | embed: ready to serve client requests
> 2018-08-14 09:26:26.465140 N | embed: serving insecure client requests on 127.0.0.1:8001, this is strongly discouraged!

**Comment by wernergillmer** [comment]
I have the exact same problem. Spec type is also recreate and I am using trident 18.07.0

**Comment by wernergillmer** [comment]
upgrading trident to 18.10.0 does not help as well.

```
2018-11-29 08:14:23.842160 I | etcdmain: etcd Version: 3.2.19
2018-11-29 08:14:23.842219 I | etcdmain: Git SHA: 8a9b3d538
2018-11-29 08:14:23.842230 I | etcdmain: Go Version: go1.8.7
2018-11-29 08:14:23.842235 I | etcdmain: Go OS/Arch: linux/amd64
2018-11-29 08:14:23.842240 I | etcdmain: setting maximum number of CPUs to 10, total number of available CPUs is 10
2018-11-29 08:14:23.859930 N | etcdmain: the server is already initialized as member before, starting as etcd member...
2018-11-29 08:14:23.860030 I | embed: listening for peers on http://127.0.0.1:8002
2018-11-29 08:14:23.860085 I | embed: listening for client requests on 127.0.0.1:8001
2018-11-29 08:14:25.071396 W | etcdserver: another etcd process is using "/var/etcd/data/member/snap/db" and holds the file lock.
2018-11-29 08:14:25.071417 W | etcdserver: waiting for it to exit before starting...
```

after that the pod restarts, and eventually goes into a crash loop

**Comment by gnarl** [comment]
@wernergillmer this issue requires more troubleshooting. Please contact [NetApp Support](https://mysupport.netapp.com/) and open a case with support.

**Comment by mvineza** [comment]
We also experience same issue trident 18.10.0. Specifying a different volume name for etcd database (using --volume-name) doesn't help. I also tried deleting the PV and PVCs. I really don't know what's that process that keeps holding the etcd database.

> etcdserver: another etcd process is using "/var/etcd/data/member/snap/db" and holds the file lock, or loading backend file is taking >10 seconds

**Comment by kangarlou** [comment]
@wernergillmer Trident v18.10 should use etcd v3.3.9, not v3.2.19 as shown in your logs.

@mvineza I've seen this problem happening when the network latency between the k8s cluster nodes and the storage backend is high.

This might be an etcd bug, but I'm curious to see when you use the `ontap-san` driver (or any other SAN driver) for the etcd volume, you would see the same problem or not.

**Comment by clintonk** [comment]
@r0ss3  This issue is most likely to occur if connectivity between the K8S host running Trident and the ONTAP cluster is broken, either by a network disconnect or an unclean shutdown of the K8S node.

There are a couple ways to avoid this issue:
- Use NFSv4 for the Trident PV.  NFSv4 uses sessions, and any locks are released when the NFS session times out.  For an existing Trident installation, you can edit the PV and set it to use NFSv4 in the [mountOptions](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes) section.  Be sure NFSv4 is enabled on your ONTAP SVM, and then restart the Trident pod.
- When taking a node out of the K8S cluster, drain it first using `kubectl drain` or `oc adm drain`.  This will shut down the Trident pod cleanly and should release the locks.

When you encounter this issue, rather than restoring a snapshot, you can use an ONTAP CLI command to explicitly break the NFS locks on the Trident volume.

```
VICE::> vserver locks

VICE::vserver locks> show -vserver CXE -volume clinton_trident

Vserver: CXE
Volume   Object Path               LIF         Protocol  Lock Type   Client
-------- ------------------------- ----------- --------- ----------- ----------
clinton_trident 
         /clinton_trident/member/snap/db 
                                   CXE_nfs_lif1 
                                               nlm       byte-range  10.63.222.242
                Bytelock Offset(Length): 0 (18446744073709551615)
         /clinton_trident/member/wal/0000000000000000-0000000000000000.wal 
                                   CXE_nfs_lif1 
                                               nlm       byte-range  10.63.222.242
                Bytelock Offset(Length): 0 (18446744073709551615)
         /clinton_trident/member/wal/0.tmp 
                                   CXE_nfs_lif1 
                                               nlm       byte-range  10.63.222.242
                Bytelock Offset(Length): 0 (18446744073709551615)
3 entries were displayed.


VICE::vserver locks> set diag

Warning: These diagnostic commands are for use by NetApp personnel only.
Do you want to continue? {y|n}: y

VICE::vserver locks*> ?
  break                       *Break file locks based on a set of criteria
  nfsv4>                      *Display Current List Of NFSv4 Locks
  show                        Display current list of locks

VICE::vserver locks*> break -vserver CXE -volume clinton_trident -path *

Warning: Breaking file locks can cause applications to become unsynchronized and may lead to data corruption.
Do you want to continue? {y|n}: y
3 entries were acted on.

**Comment by r0ss3** [comment]
wow, interesting.

Thanks for the explanation.  We use nfsv3 over UDP (because lots of firewalls)  and we do regularly replace nodes, which are simply powered off.  I do think it is possible there is not always enough time to get trident stopped and unmounted cleanly.  This explains everything.  I will test the release of the file locks from netapp next time we encounter this.

**Comment by clintonk** [comment]
@r0ss3  Thanks for confirming the way you shutdown nodes.  That seemed the most likely explanation, since other slightly less drastic operations such as deleting the Trident pod or deleting the Docker container running Trident's etcd always appear to release the locks.  Keep in mind that this issue is not limited to Trident or even to containers; any clustered application that uses NFSv3 volumes _and_ places locks on their files is subject to stale locks in the event of dirty shutdowns.  It's best to avoid the issue across your K8S cluster by using NFSv4 (I understand why you prefer not to do that) _or_ to drain the nodes prior to powering them off.

**Comment by clintonk** [comment]
Trident 19.01 allows you to specify nfsMountOptions in the config file for any of Trident's NFS backends, including the one used for installing Trident.  That simplifies the use of NFSv4 for Trident's etcd volume, which eliminates the possibility of stale NFS locks.
