### ISSUE TITLE
Publish Trident images to Redhat Container Catalog

### ISSUE THREAD

**Issue by thomasmeeus** [NetApp/trident#146]
Hi,

we blocked Docker hub on our Openshift infrastructure because it contains too much vulnerable images. 
Because of this we noticed that the Trident setup was unable to pull images anymore. 
To be honest I was expecting that the Trident images were hosted at the Redhat Container Catalog since it's a certified way to provision storage within Openshift.

Would it be possible to upload/mirror the Trident images on the Redhat Container Catalog?

Thanks

**Comment by adkerr** [comment]
Hi @thomasmeeus,

This is a great idea and we will definitely look into it, however we might not be allowed to. Currently Trident is based off of the Alpine Linux base image as it is very small but with an easy to use package manager. However according to RedHat's site, it looks as though they only publish containers that are based on RedHat base images:

> Containers that are certified by Red Hat and based on Red Hat technology are publishable on RHCC.

https://access.redhat.com/containers/#/faq

That said, we will certainly reach out through our partner channels to see what's possible.

**Comment by clintonk** [comment]
@thomasmeeus Please note that the just-released Trident 18.07.0-beta.1 includes the ability to override the images used by the Trident installer, so you have the option of copying them from Docker Hub to a local repository and using them from there.

**Comment by kapilarora** [comment]
+1

**Comment by CalvinHartwell** [comment]
This is correct - to get images into the Red Hay catalogue they have to be built from CentOS, RHEL or maybe Fedora base images.

My suggestion would be to push the trident containers to a local registry, I.E your own instance of atomic registry, SonaType nexus or Artifactory (or another product), connect that registry to your cluster and modify then modify trident to pull its images from it.

I hope that helps, if you get stuck just reply to the thread.

Cheers

**Comment by thomasmeeus** [comment]
Ok. So Redhat Container Catalog is not possible. But a Netapp-owned registry would be nice instead of Dockerhub.
The workaround of having a local registry hosting the image is indeed the thing we're going to configure in the meantime. Unfortunately we can't go in production this way since that Trident version is still in beta.

**Comment by kangarlou** [comment]
@thomasmeeus What would be the difference between a NetApp-owned registry vs. Docker Hub for your organization? NetApp has no plans to offer its own registry service.

You don't need the latest beta to configure Trident with custom images. With v18.04, you can simply use `tridentctl install --generate-custom-yaml`, modify `setup/trident-deployment.yaml` so that it uses the images in your local registry, and install using `tridentctl install --use-custom-yaml`. You can also wait a couple of weeks for v18.07 to be released.

**Comment by thomasmeeus** [comment]
@kangarlou Security. That way we can deny Dockerhub so that no vulnerable 3rd party image from an untrusted source ends up on our environment. If Netapp offers a dedicated registry, hosting only Netapp (approved) images, we can blacklist Dockerhub & whitelist the Netapp-registry.

To be clear: this is not about Netapp offering public registry hosting. I'm asking to be able to download the Trident images from a trusted source controlled by Netapp.

Hosting a separate internal registry solely for the trident image is the thing we're going to do now. But it will be extra work for something of which only we will benefit, while I think that all Trident users can have the same benefit if the registry is managed centrally.

But thanks for mentioning the `--generate-custom-yaml`. I didn't knew that option existed.

**Comment by innergy** [comment]
@thomasmeeus Out of curiosity, is your security software sophisticated enough to make exceptions for signed images? In lieu of a NetApp registry, we could consider signing the images we push to Docker Hub:
- https://docs.docker.com/engine/security/trust/content_trust/

**Comment by thomasmeeus** [comment]
@innergy I have to verify and I'll come back to this. I don't think that verification of signed images is supported in Openshift. Perhaps the internal registry we're going to install has this functionality. 

Currently we're using this snippet in the Openshift/docker config which simply blocks dockerhub entirely:
```BLOCK_REGISTRY='--block-registry=hub.docker.com'```
