### ISSUE TITLE
Can't read secret?

### ISSUE THREAD

**Issue by stobias123** [NetApp/trident#147]
Running an install on Openshift 3.9... getting an error about the node not being able to read a secret.
Trying to connect to solidfire. 
config
```
{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": 'https://user:***@10.90.33.180/json-rpc/8.0',
    "SVIP": "10.90.33.180:3260",
    "TenantName": "openshift",
    "UseCHAP": true,
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}

```

Error
```
MountVolume.NewMounter initialization failed for volume "trident" : Couldn't get secret trident/trident-chap-solidfire-10-90-33-180-openshift error: secrets "trident-chap-solidfire-10-90-33-180-openshift" is forbidden: User "system:node:openshift-node-2.company.com" cannot get secrets in the namespace "trident": no path found to object User "system:node:openshift-node-2.company.com" cannot get secrets in project "trident"
```

Also seeing this
```
iscsi: failed to sendtargets to portal 10.90.33.180:3260 output: iscsiadm: Connection to Discovery Address 10.90.33.180 closed iscsiadm: Login I/O error, failed to receive a PDU
```

**Comment by innergy** [comment]
How are you installing Trident? Is there anything special about your installation of OpenShift 3.9?

The node authorizer is responsible for giving a node access to the secrets based on the pods scheduled to run on the node:
  https://kubernetes.io/docs/reference/access-authn-authz/node/

Trident does not do anything to configure the node authorizer, and we have never seen a failure like this before.

Just to be sure, we installed Trident 18.04 with a CHAP-enabled SolidFire backend using a brand new 2 node OpenShift 3.9 cluster and it works fine, even when the pod is scheduled on the second node.

We recommend uninstalling Trident and installing it again using tridentctl. In addition to retrying pod scheduling, that will refresh all of Trident's k8s configuration, including authorization.

**Comment by stobias123** [comment]
This is no longer an issue, Re-deployed the cluster and things were ok.
