### ISSUE TITLE
Feature request: Add support of failure domains

### ISSUE THREAD

**Issue by stang** [NetApp/trident#148]
To be able to leverage the [failure domains capabilities](https://github.com/kubernetes/kubernetes/blob/master/pkg/scheduler/algorithm/predicates/predicates.go#L560-L654), we need to be able to add the `failure-domain.beta.kubernetes.io/zone` to the persistent volumes created by trident.

It seem that the best fit for this would be to add a new setting in the [backend configuration](http://netapp-trident.readthedocs.io/en/stable-v18.04/kubernetes/operations/tasks/backends/index.html#backend-configuration), and to pass it down to the kubernete's manifest when creating the `PersistentVolume` object.

**Comment by innergy** [comment]
See my comments in #149.

**Comment by hemmop** [comment]
@innergy any progress on the subject? Since the PR both 18.07 and 18.10 are released.

**Comment by clintonk** [comment]
@hemmop Progress, yes.  This is coming, but I can't promise it for a specific release.

**Comment by gnarl** [comment]
Closing this issue as failure domains are deprecated in Kubernetes. With the Trident 20.10 release support was added for the Kubernetes Topology feature.
