### ISSUE TITLE
Trident install script should also work with OpenShift Client tool 'oc' in absence of 'kubectl' client

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#15]
When installing Trident in an OpenShift environment, it is possible that kubectl client is not present, rather 'oc' client tool from OpenShift. It will be good if install script works with 'oc' when kubectl is absent.

**Comment by adkerr** [comment]
Trackend internally by [US2359](https://rally1.rallydev.com/#/47479883219d/detail/userstory/100444722724)
