### ISSUE TITLE
Issues when trying to initalize ontap-nas driver

### ISSUE THREAD

**Issue by v0c1977** [NetApp/trident#152]
This is what is see in the logs,

time="2018-07-20T12:15:11Z" level=error msg="Kubernetes frontend couldn't add the storage class: Trident initialization failed; problem initializing storage driver 'ontap-nas': error initializing ontap-nas driver: could not create Data ONTAP API client: error reading SVM details: Post https://172.19.40.52/servlets/netapp.servlets.admin.XMLrequest_filer: EOF" storageClass=standard storageClass_parameters="map[storagePools:segotx1173_standard:segotx119_n3_aggr1,segotx119_n4_aggr1 backendType:ontap-nas]" storageClass_provisioner=netapp.io/trident

**Comment by adkerr** [comment]
It appears to be a connection issue, as we're getting a `EOF` from the zapi call. Can you verify that the zapi interface is working outside of trident? From the host where trident is installed, can you create a file called vserver-get-attributes.xml with the following contents (replacing the `vfiler` attribute with the proper svm name):

```xml
<?xml version="1.0" encoding="UTF-8"?>

<netapp xmlns="http://www.netapp.com/filer/admin" version="1.20" vfiler="XXXX">
  <vserver-get/>
</netapp>
```
Then send the curl request (with correct user/password):
```shell
curl -k -X POST -d @./vserver-get-attributes.xml https://user:password@172.19.40.52/servlets/netapp.servlets.admin.XMLrequest_filer
```

**Comment by innergy** [comment]
If you need further assistance, please open a support case: https://mysupport.netapp.com/info/web/ECMLP2619434.html

Thanks!

**Comment by v0c1977** [comment]
Hi,

I get the same error,

curl -k -u trident -X POST -d @vserver-get-attributes.xml https://172.19.40.52/servlets/netapp.servlets.admin.XMLrequest_filer
Enter host password for user 'trident':
curl: (35) Encountered end of file

Br.
Christian

**Comment by innergy** [comment]
That confirms that this isn't a Trident issue. You'll need to troubleshoot the inability to successfully call that API. The best way to do that is to contact standard NetApp support: https://mysupport.netapp.com/info/web/ECMLP2619434.html
