### ISSUE TITLE
Unable to install trident again after kubernetes node IP change

### ISSUE THREAD

**Issue by mvineza** [NetApp/trident#153]
Hello All,

We recently changed the IP address of our kubernetes nodes (master version 1.10.1) to move it to a load-balanced VLAN. The nodes are running are controlled and bootstrap via our rancher server (version 2.X). I didn't uninstall trident before moving the nodes to new IPs. After IP change, I remember installing again trident and encountered a timeout issue after starting the trident pods.

> [ansible@samplehost trident-installer]$ ./tridentctl -n trident install
> INFO Starting storage driver.                      backend=/home/ansible/trident-installer/setup/backend.json
> INFO Controller serial numbers.                    serialNumbers="ABC,XYZ"
> INFO Storage driver loaded.                        driver=ontap-nas
> INFO Starting Trident installation.                namespace=trident
> INFO Created namespace.                            namespace=trident
> INFO Created service account.                     
> INFO Created cluster role.                        
> INFO Created cluster role binding.                
> INFO Created PVC.                                 
> INFO Created PV.                                   pv=trident
> INFO Waiting for PVC to be bound.                  pvc=trident
> INFO Created Trident deployment.                  
> INFO Waiting for Trident pod to start.            
> INFO Trident pod started.                          namespace=trident pod=trident-5fd99d494d-mztrk
> INFO Waiting for Trident REST interface.          
> ERRO Trident REST interface was not available after 120.00 seconds. 
> WARN An error occurred during installation, cleaning up. 
> INFO Deleted cluster role binding.                
> INFO Deleted cluster role.                        
> INFO Deleted service account.                     
> 
While that is running, I opened another terminal to check if PV is created.

> [ansible@samplehost trident-installer]$ kubectl get pv,pvc
> NAME                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM             STORAGECLASS   REASON    AGE
> persistentvolume/trident   2Gi        RWO            Retain           Bound     trident/trident                            4m
> [ansible@samplehost trident-installer]$ 

Then going back to previous terminal, the whole installation completed. So I check the logs using _./tridentcl -n trident logs_ and I found out this on the first part.

>     time="2018-07-20T07:02:08Z" level=error msg="Trident initialization failed; the assigned aggregates for SVM SampleSVM do not include the configured aggregate SampleAggregate"

I don't know where _SampleAggregate_ came from but I'm sure I configured the backend.json correctly since the installation will fail immediately and will not proceed in creating the PV. Our storage engineer also confirmed that the settings under _backend.json_ are correct.

Anyone encountered this? Is this a caching on etcd side?

**Edit:**
Trident has been installed and working before the IP change.

Thanks in advance

**Comment by innergy** [comment]
Changing the node IPs in Kubernetes should have no impact on Trident.

What's happening here is that there's a 'SampleAggregate' aggregate specified in your backend
configuration that does not exist in the 'SampleSVM' SVM.

You should see a line in this file that includes that aggregate:
  /home/ansible/trident-installer/setup/backend.json

Trident will automatically discover all of the aggregates that are assigned to the SVM, so you can simply remove the line if you don't need to confine it to a subset of them.

**Comment by mvineza** [comment]
@innergy Yes I confirmed that backend.json contains the correct setttings.

> {
>     "version": 1,
>     "storageDriverName": "ontap-nas",
>     "managementLIF": "192.168.1.56",
>     "dataLIF": "192.168.56.45",
>     "svm": "SampleSVM",
>     "username": "Kubernetes",
>     "password": "CorrectPassword",
>     "aggregate": "CorrectAggregate",
>     "defaults": {
>         "exportPolicy": "Kubernetes"
>     }
> }
I did a _grep -r SampleSVM_ on home directory, /var and I don't see where that aggregate comes from.

**Comment by adkerr** [comment]
The aggregate needs to be delegated/assigned to the SVM on the storage array. This would be something your storage admin would need to do.

**Comment by mvineza** [comment]
@innergy Even if I remove the aggregeate settings from backend.json, the installation still encounters that error. My suspicion is during initial contact of trident to netapp API, it sends the correct settings that's why it connect successfully and create the persistent volumes.

> INFO Starting storage driver. backend=/home/ansible/trident-installer/setup/backend.json
> INFO Controller serial numbers. serialNumbers="ABC,XYZ"
> INFO Storage driver loaded. driver=ontap-nas
> INFO Starting Trident installation. namespace=trident
> INFO Created namespace. namespace=trident
> INFO Created service account.
> INFO Created cluster role.
> INFO Created cluster role binding.
> INFO Created PVC.
> INFO Created PV. pv=trident
> INFO Waiting for PVC to be bound. pvc=trident
> INFO Created Trident deployment.
> INFO Waiting for Trident pod to start.
> INFO Trident pod started. namespace=trident pod=trident-5fd99d494d-mztrk
> 

Then there might be a part inside the NetApp controller where it uses the incorrect aggregate name instead of the correct one which makes the whole initialization fail.

> time="2018-07-20T07:02:08Z" level=error msg="Trident initialization failed; the assigned aggregates for SVM SampleSVM do not include the configured aggregate SampleAggregate"

Forcing to put incorrect aggregate name in backend.json results to same error above.

> [ansible@samplehost trident-installer]$ ./tridentctl -n trident install
> INFO Starting storage driver.                      backend=/home/ansible/trident-installer/setup/backend.json
> INFO Controller serial numbers.                    serialNumbers="ABC,XYZ"
> FATA Install failed; could not start the storage backend driver; the assigned aggregates for SVM SampleSVM do not include the configured aggregate SampleAggregate 
> [ansible@samplehost trident-installer]$

**Comment by mvineza** [comment]
@adkerr That's something we haven't done. I'll ask him if he can provide a new one, delete, or create. Thanks.

**Comment by innergy** [comment]
If this aggregate isn’t referenced in the backend configuration you’re specifying during the installation, most likely what’s happening is that Trident is picking up an existing configuration from a previous installation.

Uninstalling Trident (even with the -a switch that deletes the Trident PV and PVC) does not remove Trident’s metadata volume on the backend.

If you reinstall Trident and that volume still exists, Trident will create a new PV and PVC that use it, it won’t create a new one.

If you don’t need that volume from a prior installation anymore (you have no volumes that Trident was managing), you can uninstall Trident with the -a switch, delete the Trident volume on the backend, then run the install again with your correct backend.json to start from scratch.

However, if you do want to keep that metadata around, you’ll need to edit the existing backend in place through etcd in this case.

**Comment by innergy** [comment]
If you need further assistance, please open a support case: https://mysupport.netapp.com/info/web/ECMLP2619434.html

Thanks!

**Comment by mvineza** [comment]
Hi all, just to update. We were able to solve the issue by uninstalling trident:
./tridentctl -n trident -a
Then removing the "trident_trident" volume inside Netapp. That is were the etcd is located.
Then installation finished w/o issues.
Thanks!
