### ISSUE TITLE
Installation using install_trident.sh --namespace NAMESPACE fails

### ISSUE THREAD

**Issue by dutchiechris** [NetApp/trident#16]
According to the docs and `install_trident.sh` script it is possible to pass --namespace NAMESPACE that you want to use.  I attempt this and it failed, I believe because the configmap seems to be created in the default namespace.  Even when I modified that line of `install_trident.sh` to have it created in my namespace I never got past trident-ephemeral starting.  When I started with a fresh install dir (so the yaml files are back to original) and installed without the --namespace option it worked fine. So I suspect there might be more places that need to support a custom NAMESPACE.

k8s 1.5.3

**Comment by adkerr** [comment]
Tracked internally by [DE298](https://rally1.rallydev.com/#/47479883219d/detail/defect/100448832100)

**Comment by innergy** [comment]
Fixed in 17.04.0
