### ISSUE TITLE
Unable to create a PVC on UCP Docker EE 2.0

### ISSUE THREAD

**Issue by jacobjohnanda** [NetApp/trident#161]
- DESCRIPTION:-
Unable to create a PVC on UCP Docker EE 2.0
- DETAILS:-
I was able to install Trident successfully on the UCP .
But when I try to create a PVC , it goes into the pending mode .I didn’t get  much details from the journalctl logs.
The vserver looks fine to me, I was able to create volumes from other kubernetes cluster.
I am not sure whether I am missing something or not .

SCREENSHOT:-

==========================================
[root@scspa0512191001 setup]# kubectl describe  pvc mysql-pvc-nas
Name:          mysql-pvc-nas
Namespace:     default
StorageClass:  sc-nas
Status:        Pending
Volume:
Labels:        <none>
Annotations:   volume.beta.kubernetes.io/storage-provisioner=netapp.io/trident
Capacity:
Access Modes:
Events:
  Type    Reason                Age               From                         Message
  ----    ------                ----              ----                         -------
  Normal  ExternalProvisioning  2s (x17 over 3m)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "netapp.io/trident" or manually created by system administrator

-  No relevant logs from  journalctl. 
- No  relevant logs from tridentctl.

VERSION:-
Docker Engine 17.06.2-ee-16
UCP 3.0.2
Kubernetes 1.8+

**Comment by adkerr** [comment]
I’m not sure if this is the problem or not, but you’re using the beta annotation for storage provisioner. Can you try using the top level `provisioner` attribute for the pvc instead?

Also, a copy of the logs would be helpful, even if they don’t appear to contain useful info.

**Comment by jacobjohnanda** [comment]
Hi Andrew,

Thanks for replying.
Following are the StorageClass and PersistentVolumeClaim , I am using
[root@scspa0512191001 ~]# cat sc_nas.yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-nas
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
[root@scspa0512191001 ~]# cat pvc_nas.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ucp-nas-volume1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: sc-nas
Please find the logs updated.
[log.txt](https://github.com/NetApp/trident/files/2288076/log.txt)

**Comment by clintonk** [comment]
Did you follow the [Trident installation instructions specific to Docker EE 2.0](https://netapp-trident.readthedocs.io/en/stable-v18.07/kubernetes/deploying.html#install-trident)?

**Comment by adkerr** [comment]
Trident does not have proper permissions to the API server. The log file is filled with

```
E0809 09:42:45.242713       1 reflector.go:205] github.com/netapp/trident/frontend/kubernetes/plugin.go:273: Failed to list *v1.PersistentVolumeClaim: persistentvolumeclaims is forbidden: User "system:serviceaccount:trident:trident" cannot list persistentvolumeclaims at the cluster scope: access denied
E0809 09:42:45.273111       1 reflector.go:205] github.com/netapp/trident/frontend/kubernetes/plugin.go:275: Failed to list *v1.StorageClass: storageclasses.storage.k8s.io is forbidden: User "system:serviceaccount:trident:trident" cannot list storageclasses.storage.k8s.io at the cluster scope: access denied
E0809 09:42:45.302700       1 reflector.go:205] github.com/netapp/trident/frontend/kubernetes/plugin.go:274: Failed to list *v1.PersistentVolume: persistentvolumes is forbidden: User "system:serviceaccount:trident:trident" cannot list persistentvolumes at the cluster scope: access denied
```

Did you install trident with the correct flags to set up RBAC properly (as linked to by @clintonk)?

**Comment by jacobjohnanda** [comment]
Hi Knight,
Yes , I have followed the instruction as given  in the link.I used the --ucp-host and --ucp-bearer-token.

**Comment by jacobjohnanda** [comment]
Hi Andrew,
The timestamp that you see is not correlating with the time I  created PVC.No logs are getting generated with errors at the time I create the PVC. That why had i mentioned that the logs were not relevant.

**Comment by adkerr** [comment]
@jacobjohnanda what time did you try to create the PVC? I see the RBAC errors through the entire log file, from top to bottom

**Comment by jacobjohnanda** [comment]
IF you look at the logs , its just pertaining to the time when Trident was installed.

**Comment by jacobjohnanda** [comment]
I have shared the machine details in a mail.Please do let me know if you would like any more information to debug?

**Comment by jacobjohnanda** [comment]
Hi,

Yes i was able to work around it by giving Trident  GRANT with FullControl .

**Comment by innergy** [comment]
Yes, that will work around the issue for now.

We tested with UCP 3.0.0, but it appears that some of the role requirements changed in subsequent minor versions. To fix this we'll need to make some changes to the installer to grant Trident the new set of appropriate permissions.

**Comment by chrifey** [comment]
Ok nice, thanks very much for the information!

**Comment by innergy** [comment]
This is obsolete. Docker EE 2.1 uses native k8s RBAC now.
