### ISSUE TITLE
Feature request: Create dp volumes via trident

### ISSUE THREAD

**Issue by Matthias-Beck** [NetApp/trident#162]
We would like to have the option to create dp volumes via trident to enable the possibility to move data easily from onprem to the cloud and back or from one (test/dev) to another cluster (prod) via snapmirror.

We want to automate this option for our customers. Today there are manual steps needed to recreate the volumes as dp volumes.

**Comment by cschnidr** [comment]
You could potentiallly solve this by using SVM DR. Volumes added on the primary are then automatically mirrored to the destination SVM. However, the destination SVM is stopped and the volumes cannot be accessed or cloned while the destination SVM is not started (DR activated).

**Comment by cschnidr** [comment]
If you implement this, please support also other replication policies like XDP.

**Comment by Matthias-Beck** [comment]
@cschnidr SVM DR only works if you want to move a whole Cluster or if you create a dedicated SVM for every application within you container cluster.
I would prefer to have the possibility to move single volumes to another cluster.

**Comment by innergy** [comment]
Do you see this request as any different from #72?

**Comment by Matthias-Beck** [comment]
@innergy I think, in the end it is a cross cluster / trident replication which is needed in both request

**Comment by innergy** [comment]
Dup of #72
