### ISSUE TITLE
DOC: Documentation for Backup an Recovery procedure for the Trident deployment

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#163]
A guidance on how to backup and restore/recover trident deployment would be highly appreciated.
If there is already documentation available please let me know.

**Comment by felixkrohn** [comment]
https://netapp.io/2019/03/12/backup-restore-trident-etcd-using-etcdctl-with-ontap/ looks like a link to be bookmarked in the "emergency" folder :+1:

**Comment by korenaren** [comment]
https://netapp-trident.readthedocs.io/en/stable-v19.07/dag/kubernetes/backup_disaster_recovery.html
