### ISSUE TITLE
Feature request: Support for Windows Containers on Windows Server

### ISSUE THREAD

**Issue by n1x0n** [NetApp/trident#165]
We would like to have support for Docker for Windows, preferably both for Docker EE and CE. There are a lot of Windows applications, especially .NET applications, that would benefit from containerization and require persistent storage.

The preferred solution would use CIFS with one share per volume, just like we manage NFS today. Even better would be if there was an option to access these volumes could through both CIFS and NFS to allow sharing of data between containers running on Windows and Linux hosts.

Another option would be "SMB Global Mapping" as described here: https://docs.microsoft.com/en-us/virtualization/windowscontainers/manage-containers/container-storage#smb-mounts 

The third option (required for SolidFire and E-series) would be iSCSI volumes formatted with NTFS.

**Comment by korenaren** [comment]
@n1x0n I think you mean Windows Containers on Windows Server, and not Docker for Windows (which is how you run Linux containers on Windows)... is that correct?

**Comment by n1x0n** [comment]
@korenaren Yes, Windows Containers on Windows Server. In the environments where this would be used the plan is to run Windows Containers on Windows Server and Linux containers on Linux servers, either as worker nodes in the same k8s clusters or in separate clusters.

**Comment by gprossliner** [comment]
Hello! Is there any new information on this topic? I need to setup a hybrid k8s cluster. We successfully integrated the trident as the CSI for our Linux workloads. And it would be nice to use the same Plugin for persistent storage for our Windows Workloads, running in Windows Containers.

As Windows supports NFS and iSCSI, it should be possible, I think.

**Comment by korenaren** [comment]
@gprossliner It's on our radar, but no time frame committed yet.

**Comment by gprossliner** [comment]
Thank you for the information. Is there anything I may assist you?

**Comment by korenaren** [comment]
@gprossliner not at the moment.

**Comment by gnarl** [comment]
Trident will begin supporting Windows and SMB, in the azure-netapp-files storage driver, with the Trident v22.10 release.

**Comment by travisghansen** [comment]
Does this mean not ontap? I’ve got onprem I’m looking to use…

**Comment by gnarl** [comment]
@travisghansen, for the Trident v22.10 release Windows nodes and SMB volume attachments are supported in Azure. Future Trident releases will expand this support to additional storage backends.

**Comment by travisghansen** [comment]
Is there another issue I can track for ontap?

**Comment by burkhat** [comment]
> Is there another issue I can track for ontap?

I've created one: https://github.com/NetApp/trident/issues/796
