### ISSUE TITLE
Feature Request: Support for tridentctl on macOS

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#167]
It will be great to use tridentctl directly from my macbook where i run all my kubectl commands

**Comment by okrause** [comment]
To work around this, I am using the following alias on my macOS device:
`tridentctl='kubectl exec -t -n trident $(kubectl get pods -n trident -l app=trident.netapp.io -o jsonpath="{.items[].metadata.name}") -c trident-main -- tridentctl -s 127.0.0.1:8000'
`
It uses the tridentctl running within the Trident deployment on the K8S cluster. This worked well for me. The only caveat is, that any command where you specify a yaml file with the -f option would look in the pods file system and not you local disk. So you have to work with stdin/stdout or copy the yaml file to the pods filesystem first.

**Comment by sightseeker** [comment]
I solve tridentctl (NetApp Trident CLI) use on macOS with Docker.

https://hub.docker.com/r/sightseeker/tridentctl

**Comment by stobias123** [comment]
no real resolution? why not release `tridentctl` with goreleaser? this makes the install clunky.

**Comment by ebartz** [comment]
@netapp-ci, can we please reopen this? The Docker Image does not really solve this as it just uses a virtual machine on mac os when running Docker there.

**Comment by innergy** [comment]
The close message didn’t make it clear, but in the extras directory in the release tarball there’s an alternative build of the tridentctl binary for MacOS.

extras/macos/bin/tridentctl
