### ISSUE TITLE
Feature Request: Pre/Post Script Support

### ISSUE THREAD

**Issue by cschnidr** [NetApp/trident#169]
Currently discussing a DR/backup setup of Trident volumes.
Given the vast variety of options what customers requests (DR, XDP, SVM DR...) it would be highly desired to offer a pre- and post script support for Trident.
Here some scenarios where this would solve the DR/backup problem:
-customer is using Trident to deploy volumes. Later he runs some automation to establish snapmirror of the volume. Trident can no longer delete the volume because it is in a mirror relationship. A pre-script could release the mirror relationship and Trident could delete the primary vol. The customer would be flexible to delete the destination vol after it by his automation.
-customer is using Trident to deploy volumes and desires an XDP replication relationship with a backup policy of his choice. A Trident post script could deploy the XDP relationship.

**Comment by innergy** [comment]
I'm going to track this, but I want to be clear that we don't have any immediate plans to offer it. We'd rather automate most of what your describing here, and we're working out the models for that. Once we have more of that in place, we can revisit whether we still think this is necessary.

**Comment by cschnidr** [comment]
You can dup this to if #72 will support XDP relationships (provision, deprovision (primary and secondary), deprovision (primary only) and multiple protection policies.

**Comment by cschnidr** [comment]
Again if everything would be automated - perfect. I was afraid that messing with destination pools etc. could be a bit challenging. I guessed pre-/post script would be easier to implement and would give the customer the maximum flexibility.

**Comment by sinicis** [comment]
Any news? I've just published our current workaround: https://github.com/sinicis/trident-snapmirror

**Comment by gnarl** [comment]
We've examined storage replication and have found that it is best supported outside of Trident. There isn't any coordination in Kubernetes to support replication today. Articles on how to perform replication outside of Trident are available on [NetApp.io](https://netapp.io/2019/10/08/trident-and-disaster-recovery-part-1/).
