### ISSUE TITLE
SVM-Level Account on NetApp 8.3

### ISSUE THREAD

**Issue by equinox0815** [NetApp/trident#17]
Hi,

I just tried the latest change which allows to use SVM-Level Accounts. We have a Ontap 8.3 but if i understand the docs correctly this should still work (mostly) !?

```
NetApp Release 8.3.2P9
Data ONTAP API version: 1.32
```

If i run this i get the following error from trident_ephemeral Pod:

`time="2017-03-29T15:32:47Z" level=error msg="SVM xxxxxxxx has no assigned aggregates." backend= handler=AddBackend`

When i enable debugging this is the last response i can see in the output:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE netapp SYSTEM "file:/etc/netapp_gx.dtd">
<netapp xmlns="http://www.netapp.com/filer/admin" version="1.32">
  <results status="passed">
    <attributes-list>
      <vserver-info>
        <allowed-protocols>
          <protocol>nfs</protocol>
        </allowed-protocols>
        <antivirus-on-access-policy>default</antivirus-on-access-policy>
        <comment/>
        <disallowed-protocols>
          <protocol>cifs</protocol>
          <protocol>fcp</protocol>
          <protocol>iscsi</protocol>
          <protocol>ndmp</protocol>
        </disallowed-protocols>
        <is-config-locked-for-changes>false</is-config-locked-for-changes>
        <is-repository-vserver>false</is-repository-vserver>
        <language>en_us.utf_8</language>
        <max-volumes>unlimited</max-volumes>
        <name-mapping-switch>
          <nmswitch>file</nmswitch>
        </name-mapping-switch>
        <name-server-switch>
          <nsswitch>file</nsswitch>
        </name-server-switch>
        <operational-state>running</operational-state>
        <quota-policy>default</quota-policy>
        <root-volume>xxxxxxxx_root</root-volume>
        <root-volume-aggregate>xxxxxxxxx_data_06</root-volume-aggregate>
        <root-volume-security-style>unix</root-volume-security-style>
        <snapshot-policy>SnapShot_DR</snapshot-policy>
        <state>running</state>
        <uuid>xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx</uuid>
        <volume-delete-retention-hours>12</volume-delete-retention-hours>
        <vserver-name>xxxxxxxx</vserver-name>
        <vserver-subtype>default</vserver-subtype>
        <vserver-type>data</vserver-type>
      </vserver-info>
    </attributes-list>
    <num-records>1</num-records>
  </results>
</netapp>
```

I'm not a Ontap expert so i might be wrong but doesn't this state that there is in fact an aggregate `xxxxxxxxx_data_06` assigned to the VFiler?

Is this a bug or do i do something wrong here?

Thanks in advance!

regards
 christian

**Comment by clintonk** [comment]
Hi, Christian.  Doesn't look like a bug.  Please use either System Manager or the ONTAP CLI to assign one or more aggregates to the vserver.

![image](https://cloud.githubusercontent.com/assets/1355869/24471890/9e6957d0-1491-11e7-9d01-7f482bf98369.png)

**Comment by clintonk** [comment]
Once you assign aggregates to the vserver, you should see the aggr-list attribute in the log output:

![image](https://cloud.githubusercontent.com/assets/1355869/24471935/da645e88-1491-11e7-97fc-6fd07a5faff4.png)

**Comment by equinox0815** [comment]
Thanks clintonk!
