### ISSUE TITLE
Feature Request: tridentctl get backend command should also provide available and used capacity on storage pools

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#170]
Looking for ways the k8s admin can look at his storage capacities.
Hoping this information can be fetched from the tridentctl using the following command:

tridentctl get backend -n trident -o yaml

if we could also calculate and show capacities for each storage class, that might also be useful.
But i am not sure how we will handle this when storage classes overlap.

**Comment by si-heger** [comment]
Is there any update on this ticket? Many customers would like to have the ability to monitor available/free space in a volume from within kubernetes (or at least from tridentctl)

**Comment by gtehrani** [comment]
This is not a tracked request. There are commercial (NetApp Cloud Insights), and/or open source solutions that are better suited for obtaining this type of information.

**Comment by korenaren** [comment]
Closing: Outside Trident's purview.
