### ISSUE TITLE
Trident Install Fails if GlusterFS is installed on K8s node

### ISSUE THREAD

**Issue by rileynjohnson** [NetApp/trident#177]
Installing Trident on a new server fails if GlusterFS is enabled.  

Trident Logs:
ERRO Trident REST interface was not available after 180.00 seconds. 
FATA Install failed; exit status 1; Error: Get http://127.0.0.1:8000/trident/v1/version: dial tcp 127.0.0.1:8000: connect: connection refused
command terminated with exit code 1; use 'tridentctl logs' to learn more.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again. 
root@<server>:/root/bin/NAS/trident-installer

Error Logs
2018-09-10 17:37:04.829170 W | etcdserver: another etcd process is using "/var/etcd/data/member/snap/db" and holds the file lock.
2018-09-10 17:37:04.829196 W | etcdserver: waiting for it to exit before starting...
2018-09-10 17:37:09.846095 C | mvcc/backend: cannot open database at /var/etcd/data/member/snap/db (no locks available)
panic: cannot open database at /var/etcd/data/member/snap/db (no locks available)

Workaround: disable GlusterFS before running the install.

**Comment by kangarlou** [comment]
@rileynjohnson Please share what version of GlusterFS is deployed and whether GlusterFS is deployed in a container or not.

**Comment by kangarlou** [comment]
It would also be good to know if they're running gNFS or Ganesha with GlusterFS. GlusterFS itself doesn't use the NFS lock manager, so the issue here might be that the NFS lock manager cannot start because GlusterFS is running or NFS on top of GlusterFS is causing problems.

Please share the output of `rpcinfo -p` run on the Kubernetes hosts.

Since NFSv4 locking doesn't require the lock manager, it might be worthwhile to run the flock tests (https://github.com/NetApp/trident/issues/175#issuecomment-422448765) with NFSv4 and GlusterFS. This configuration would take the lock manager out of the equation.

**Comment by rileynjohnson** [comment]
rpcinfo –p works fine on the node with GlusterFS turned OFF (see below). Whereas on other nodes (with GlusterFS turned ON) it fails

root@<server>:/root   ---(GLUSTERFS Turned OFF)
# rpcinfo -p
   program vers proto   port  service
    100000    4   tcp    111  portmapper
    100000    3   tcp    111  portmapper
    100000    2   tcp    111  portmapper
    100000    4   udp    111  portmapper
    100000    3   udp    111  portmapper
    100000    2   udp    111  portmapper
    100024    1   udp  43121  status
    100024    1   tcp  51299  status
    100021    1   udp  34376  nlockmgr
    100021    3   udp  34376  nlockmgr
    100021    4   udp  34376  nlockmgr
    100021    1   tcp  35078  nlockmgr
    100021    3   tcp  35078  nlockmgr
    100021    4   tcp  35078  nlockmgr


root@<server>:/root  ---(GLUSTERFS Turned ON)
# rpcinfo -p
No remote programs registered.

**Comment by rileynjohnson** [comment]
The GlusterFS version is 3.12.11 and it is deployed in a container

**Comment by innergy** [comment]
Thanks for the details. Please have your customer open the issue with GlusterFS. This isn't a Trident issue or even a NetApp one.
