### ISSUE TITLE
VServer DR failover causes vserver access issue in nDVP/Trident 18.07

### ISSUE THREAD

**Issue by oleimann** [NetApp/trident#180]
[Redacted] NetApp Support
on Trident/nDVP version 18.07: 

> DR failover of storage causes error in the Docker Plugin:
>        **API status: failed, Reason: Specified vserver not found, Code: 15698**
> A restart of Trident was required to make it work again.
> 
> Also, since upgrade the following was seen when volume creation was attempted:
> Docker front end method returning error:
>       **Trident initialization failed; SVM XXXX102 has no assigned aggregates**
> 
> Reverting to older version 17.06 restored older behavior.

**Comment by innergy** [comment]
If the DR event is to a different (secondary) SVM, a restart of the plugin will be required to take in the new configuration. Not sure what happened with the aggregate issue, but if you're still seeing that please contact support. (It sounds like you already did.)
