### ISSUE TITLE
Install fail with Trivent PV stuck in Pending state (18.07.1)

### ISSUE THREAD

**Issue by somejfn** [NetApp/trident#183]
I previously installed Trident on a test cluster without issues and now on another cluster (live... not a test one) I can't get the PVC to bind so install times out.  The backend config is the same (except for the tenant name, access group and SVIP since it's in another vlan):

{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://trident-user:somepass@10.74.65.188/json-rpc/8.0",
    "SVIP": "10.74.80.170:3260",
    "TenantName": "trident-k8s-clustername",
    "UseCHAP": false,
    "AccessGroups": [3],
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 4000, "maxIOPS": 6000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 6000, "maxIOPS": 8000, "burstIOPS": 10000}}]
}

Both cluster are running 1.9.6 (Coreos Tectonic)

The error:

[root@9cc320f9b4c1 trident-installer]# kubectl get events -n trident
LAST SEEN   FIRST SEEN   COUNT     NAME                       KIND                    SUBOBJECT   TYPE      REASON          SOURCE                        MESSAGE
3m          13m          42        trident.155ebb5a3c19aab8   PersistentVolumeClaim               Normal    FailedBinding   persistentvolume-controller   no persistent volumes available for this claim and no storage class is set

Any hints to troubleshoot this further ?

The install logs:

DEBU Using existing account.                       accountID=10 tenantName=trident-k8s-toolsash1
DEBU SolidFire driver initialized.                 AccountID=10 InitiatorIFace=default
INFO Please ensure all relevant hosts are added to one of the specified Volume Access Groups.  AccessGroups="[3]" SVIP="10.74.80.170:3260" UseCHAP=false driver=solidfire-san
DEBU Added pool for SolidFire backend.             attributes="map[snapshots:{Offer:  true} clones:{Offer:  true} encryption:{Offer:  false} provisioningType:{Offers: thin} backendType:{Offers: solidfire-san} media:{Offers: ssd} IOPS:{Min: 1000, Max: 2000}]" backend=solidfire_10.74.80.170 pool=Bronze
DEBU Added pool for SolidFire backend.             attributes="map[media:{Offers: ssd} IOPS:{Min: 4000, Max: 6000} snapshots:{Offer:  true} clones:{Offer:  true} encryption:{Offer:  false} provisioningType:{Offers: thin} backendType:{Offers: solidfire-san}]" backend=solidfire_10.74.80.170 pool=Silver
DEBU Added pool for SolidFire backend.             attributes="map[media:{Offers: ssd} IOPS:{Min: 6000, Max: 8000} snapshots:{Offer:  true} clones:{Offer:  true} encryption:{Offer:  false} provisioningType:{Offers: thin} backendType:{Offers: solidfire-san}]" backend=solidfire_10.74.80.170 pool=Gold
DEBU Storage driver initialized.                   driver=solidfire-san
INFO Storage driver loaded.                        driver=solidfire-san
INFO Starting Trident installation.                namespace=trident
DEBU Created Kubernetes object by file.            path=/trident-installer/setup/trident-namespace.yaml
INFO Created namespace.                            path=/trident-installer/setup/trident-namespace.yaml
DEBU Deleted Kubernetes object by YAML.
DEBU Deleted cluster role binding.
INFO Controller serial numbers.                    serialNumbers="J484XM2,J4CBCM2,J479CM2,J478CM2"
DEBU Deleted Kubernetes object by YAML.
DEBU Deleted cluster role.
DEBU Deleted Kubernetes object by YAML.
DEBU Deleted service account.
DEBU Created Kubernetes object by file.            path=/trident-installer/setup/trident-serviceaccount.yaml
INFO Created service account.                      path=/trident-installer/setup/trident-serviceaccount.yaml
DEBU Created Kubernetes object by file.            path=/trident-installer/setup/trident-clusterrole.yaml
INFO Created cluster role.                         path=/trident-installer/setup/trident-clusterrole.yaml
DEBU Created Kubernetes object by file.            path=/trident-installer/setup/trident-clusterrolebinding.yaml
INFO Created cluster role binding.                 path=/trident-installer/setup/trident-clusterrolebinding.yaml
DEBU Created Kubernetes object by file.            path=/trident-installer/setup/trident-pvc.yaml
INFO Created PVC.                                  path=/trident-installer/setup/trident-pvc.yaml
DEBU Attempting volume create.                     size=2147483648 storagePool=Gold volConfig.StorageClass=
DEBU Received Type opts in Create and set QoS: {MinIOPS:6000 MaxIOPS:8000 BurstIOPS:10000 BurstTime:0}
DEBU Parsed blocksize option.                      blocksize= enable512e=true
DEBU Filesystem format.                            fileSystemType=ext4 name=trident
DEBU Volume found.                                 volumeID=14
DEBU Found volume by attributes: {VolumeID:14 Name:trident AccountID:10 CreateTime:2018-10-18T14:48:39Z Status:active Access:readWrite Enable512e:true Iqn:iqn.2010-01.com.solidfire:trzh.trident.14 ScsiEUIDeviceID:74727a680000000ef47acc0100000000 ScsiNAADeviceID:6f47acc10000000074727a680000000e Qos:{MinIOPS:6000 MaxIOPS:8000 BurstIOPS:10000 BurstTime:0} VolumeAccessGroups:[] VolumePairs:[] DeleteTime: PurgeTime: SliceCount:1 TotalSize:2147483648 BlockSize:4096 VirtualVolumeID: Attributes:map[trident:{"version":"18.07.1","platform":"kubernetes","platformVersion":"1.9.6","plugin":"solidfire-san"} docker-name:trident fstype:ext4]}
DEBU Mapped SolidFire LUN.                         InitiatorSecret= TargetSecret= UseCHAP=false Username= VAGs="[3]" interface= lunNumber=0 targetIQN="iqn.2010-01.com.solidfire:trzh.trident.14" volume=trident volume_internal=trident
DEBU Created Kubernetes object by YAML.
INFO Created PV.                                   pv=trident
INFO Waiting for PVC to be bound.                  pvc=trident
DEBU PVC not yet bound, waiting.                   increment=596.430028ms pvc=trident
DEBU PVC not yet bound, waiting.                   increment=887.771154ms pvc=trident
DEBU PVC not yet bound, waiting.                   increment=967.261334ms pvc=trident
DEBU PVC not yet bound, waiting.                   increment=1.716908972s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=1.978626201s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=4.702936385s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=6.346618262s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=8.521755335s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=15.285499856s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=13.966604138s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=40.423025774s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=40.865045398s pvc=trident
DEBU PVC not yet bound, waiting.                   increment=1m23.055036668s pvc=trident
FATA Install failed; PVC trident was not bound after 180.00 seconds.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

**Comment by somejfn** [comment]
I destroyed all trace of the test k8s cluster in the storage unit.  All hosts are in the VAG.  The trace above was likely one I ran twice without killing the volume again

**Comment by clintonk** [comment]
You also appear to be using custom YAML (the PVC was created using setup/trident-pvc.yaml) via --use-custom-yaml switch.  Did you modify that file in some way?  Did you try running the installer without any customization beyond setup/backend.json?

**Comment by somejfn** [comment]
Yes I have to add a label on the deployment because we use calico.  Otherwise the trident pod won't be able to reach the API server

**Comment by somejfn** [comment]
Hmm ok confused....  not using the custom metadata I get the PVC to bind but then timeout on the REST API since Im missing labels

 ./tridentctl install -n trident
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Waiting for PVC to be bound.                  pvc=trident
INFO Created Trident deployment.
INFO Waiting for Trident pod to start.
INFO Trident pod started.                          namespace=trident pod=trident-67c78d8784-dqdhr
INFO Waiting for Trident REST interface.
ERRO Trident REST interface was not available after 180.00 seconds.
FATA Install failed; exit status 1; error: unable to upgrade connection: container not found ("trident-main"); use 'tridentctl logs' to learn more.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

**Comment by clintonk** [comment]
The installer creates the trident PV and PVC such that K8S will automatically bind them together.  The PV has a claimRef section that identifies the PVC by name & namespace, and the PVC has a selector that only matches the trident PV.  If you generated custom YAML, that will include the PVC YAML file, so make sure you're running the installer with a matching namespace.  Alternatively, you can delete setup/trident-pvc.yaml (but leave any other customized files, such as setup/trident-deployment.yaml, in place); that will cause the installer to generate its own PVC YAML as needed.  Don't forget to use 'tridentctl uninstall -a' between attempts.

**Comment by somejfn** [comment]
I see.  thanks for the help
