### ISSUE TITLE
Is it possible to configure soft quota or thresholds for PVCs powered by Netapp Trident in Openshift/Kubernetes?

### ISSUE THREAD

**Issue by Limit91** [NetApp/trident#189]
Is it possible to configure soft quota or thresholds for PVCs powered by Netapp Trident (as described in https://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.dot-cm-vsmg%2FGUID-42668748-5031-4250-99F1-1924D5752201.html) in Openshift/Kubernetes? 
This would allow us to identify PVCs getting too full before it is too late and it is not possible to write anything any longer.

**Comment by kangarlou** [comment]
I'm not the expert on the ONTAP quotas, but it seems quota targets apply to users, groups and qtrees (https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-vsmg/GUID-07CDD7F3-5958-478F-AE58-62AE4B8699D7.html), which may not make much sense in the context of Kubernetes PVs. If it makes sense, defining quota policies at the SVM level (outside of Trident) may be one option.

I should also note that with Trident v18.10, users can expand their NFS volumes on their own. This means when a volume gets full, admins don't necessarily have to be notified to expand volumes on behalf of the users: https://netapp-trident.readthedocs.io/en/stable-v18.10/kubernetes/operations/tasks/volumes.html#resizing-an-nfs-volume

**Comment by innergy** [comment]
Yes, we're intentionally putting this in the hands of the user by allowing them to resize their own volumes, provided the new size doesn't breach any of the limits you've defined in the k8s cluster or on the storage itself.
