### ISSUE TITLE
Is it possible for ontap-nas-economy driver to disable the duplicate storagePrefix for volume & qtree name?

### ISSUE THREAD

**Issue by mircster** [NetApp/trident#190]
Hello Trident team,

at the moment my mountpath for the Qtree created with ontap-nas-economy driver looks like this:
**xx03v10cl02.xxxxxxxxxxxxx.com:/trident_qtree_pool_xx03v10_ocpeco_000000_sq2_nas_nfs_ABCDEFGHIJ/xx03v10_ocpeco_000000_sq2_nas_nfs_projectname_postgresql_00abc**

_storagePrefix = "xx03v10_ocpeco_000000_sq2_nas_nfs"_

This is very long.
I cannot spare the storagePrefix for the volume name because of naming convention requirements. 
But i could spare the storagePrefix for the qtree name!
I don´t need the duplicate information from the storagePrefix in the volume name + qtree name.

I would like to be able to disable the storagePrefix only for the qtree name in the backend config:
**xx03v10cl02.xxxxxxxxxxxxx.com:/trident_qtree_pool_xx03v10_ocpeco_000000_sq2_nas_nfs_ABCDEFGHIJ/projectname_postgresql_00abc**

Is this possible or can it be implemented?
Thanks & Regards

**Comment by innergy** [comment]
That's a very long storage prefix indeed! There are details around how the ONTAP API works and how volumes and qtree objects are managed in ONTAP itself that require us to include a unique identifier like the storage prefix in the qtree name.

We may be able to allow you to specify a separate unique identifier for cases like this where duplicating the storage prefix results in a very long name. It would still need to be unique, but it could be short. We'll take a look.

**Comment by cgajan** [comment]
I created the pull request #238 which include this enhancement. Hope it will be integrated soon :-)

**Comment by mircster** [comment]
Hello cgajan!
This looks great! I also hope that it will be integrated soon!
We need this ASAP, as we are hitting the   **maxQtreeNameLength = 64** limit.
We already shrink the prefix, but still we need more characters for projectname and pvc.

**Comment by gandalftg** [comment]
Hi,

having a similar request (case 2007961146), ontap-nas-economy should be aware of 64 characters limit in ONTAP and shouldn't  create to long qtree names. maxQtreeNameLength = 64 looks as good option to add.
if possible also the control the naming convention so they won't get shorten in the wrong place

Thanks

**Comment by gnarl** [comment]
This issue was fixed with commit [5afa354](https://github.com/NetApp/trident/commit/5afa35469996d40a7c7edf2b3b48d732cec4d639).
