### ISSUE TITLE
What happens when we recreate the resources after rebuilding and recovering a cluster?

### ISSUE THREAD

**Issue by rendhalver** [NetApp/trident#191]
We are using Heptio Ark https://github.com/heptio/ark/ as a disaster recovery solution.

We tried a full recovery with our `RelcaimPolicy` set to `Delete` and the data in each volume was removed.

We have changes the `RelcaimPolicy` in our `StorageClass` set to `Retain`.
When would like to know what happens to the data in a volume when we restore a cluster from an Ark backup.
Will the volumes be reused and the data retained or will we need to do anything to retain that?

**Comment by innergy** [comment]
Thanks for your question. You'd be better off asking the Ark community about this. We haven't tested Trident with Ark.

**Comment by rendhalver** [comment]
It would be similar to recovering from an etcd backup.
What happens in that case?
