### ISSUE TITLE
Customize LUN name with ONTAP-SAN driver

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#193]
Hi,
when using the ONTAP-SAN driver, the flexvol's name hosting the LUN refers to the PVC name.
However, the LUN is always named "lun0".
Would it be possible to also customize the LUN name ?
thanks

**Comment by innergy** [comment]
Can you describe the use case for such an option? With that driver there's only ever one LUN in a volume, and like you said, the volume itself has identifying information.

**Comment by YvosOnTheHub** [comment]
Basically, by using ONTAP-SAN, you end up with a lot of "lun0", which makes it difficult to follow in supervision tools (commercial or home made) which display only lun names & not full path...

**Comment by innergy** [comment]
We'll look into this along with #31, which will necessarily require more LUN names, and we can consider doing something other than just incrementing.

**Comment by gnarl** [comment]
Hi @YvosOnTheHub,

There hasn't been a +1 on this request. We will also add support for storage volume labels in future releases which should also address this request.
