### ISSUE TITLE
Allow S3 tiering to be configurable within Trident.

### ISSUE THREAD

**Issue by NA-Scott** [NetApp/trident#199]
We know that that if a volume is created on an aggregate that is part of a FabricPool it'll be tiered by default when the data goes cold. But a volume in a different aggregate can have a different tiering-policy enabled.  While we have a workaround of limiting Trident to use aggregates that are not part of the FabricPool, we would like a configurable option in Trident to modify tiering.

**Comment by mrjsnook** [comment]
+1

**Comment by wesmcouch** [comment]
+1

**Comment by mrjsnook** [comment]
Hey @clintonk - Our use case is that we disable s3 tiering on the aggregate but when you enable trident something is telling it that we want the trident_trident volume set with s3 tiering enabled which then enabled tiering for the entire aggregate.  We want a way to say "dont enable s3 tiering on the trident volume".  Today the assumption is made that everyone wants tiering enabled.  Having the trident volume have s3 tiering disabled by default would be best.

**Comment by adkerr** [comment]
@mrjsnook Trident should not be explicitly setting s3 tiering options either way on the volumes at all right now. Which backend type are you using?

**Comment by adkerr** [comment]
I see. Trident isn't setting that option, but the default according to the ZAPI docs is snapshot-only

>  * @input       tiering-policy
>  * @type	string, optional
>  * @desc        The tiering policy that is to be associated with the volume.
>  *		This policy decides whether the blocks of a volume will be tiered to the capacity tier.
>  *		The possible values for this field are:
>  *		<ul>
>  *		   <li>snapshot-only - This policy allows tiering of only the volume snapshot copies not associated with the active file system.</li>
>  *		   <li> 'auto' - This policy allows tiering of both snapshot and active file system user data to the capacity tier.</li>
>  *		   <li>none - Volume blocks will not be tiered to the capacity tier.</li>
>  *		   <li>backup - On DP volumes this policy allows all transferred user data blocks to start in the capacity tier.</li>
>  *		</ul>
>  *		Default tiering policy is snapshot-only.

So as you say we need to allow users/admins to set the tiering policy used when creating volumes (in your case to `none`)
