### ISSUE TITLE
LoadSharing mirror update errors occur when creating volumes in Trident

### ISSUE THREAD

**Issue by NA-Scott** [NetApp/trident#200]
When creating a new volume in an SVM protected by a Load Sharing Mirror, the ONTAP storage system is showing meassages similar to:
Job "SnapMirror Loadshare update" [id 1001] (snapmirror update-ls-set for source "<Source Volume>") completed unsuccessfully: SnapMirror: error: Another transfer is in progress. (With Job ID 1000 in Running State.), Function acquireTransferLock
Even with this message, the volume will still create and Trident will give no warnings or errors.

This is occurring because ONTAP and Trident are both updating the LoadSharing mirror.  The one that occurs first is succeeding, but the one that is kicked off second is failing because the first one is already running.

**Comment by clintonk** [comment]
Hello, @NA-Scott.  There was a time when Trident had to kick off the LS mirror update, but it seems newer versions of ONTAP do that automatically.  As you observed, the error is harmless.  What version of ONTAP are you running, please?  It should be simple to prevent Trident's starting the update on newer ONTAP versions.

**Comment by NA-Scott** [comment]
ONTAP version is 9.1P8
