### ISSUE TITLE
Is it possible to upgrade Trident by editing or patching the Deployment instead of uninstalling and reinstalling?

### ISSUE THREAD

**Issue by rendhalver** [NetApp/trident#203]
I looked at what happens during an uninstall and reinstall of Trident using the tridentcli.
All that changed were the versions of the etcd and trident containers.
I was wondering if it's possible to upgrade by patching or editing the deployment?
Is there anything else that happens during an install that would need to happen in a cluster with an exiting install?

**Comment by kangarlou** [comment]
Updating the deployment should generally work, but you'll run into problems when some of the other artifacts of install change from one release to another. For example, we had to modify `ClusterRoles` in v18.10 to support NFS Volume resize. In this case, merely updating the deployment image, would not result in getting the resize capability working as proper `ClusterRoles` are required.

**Comment by rendhalver** [comment]
Oh OK.
We are upgrading from 18.07 to 18.10 so those resources will need to be update.
I will follow the normal upgrade process.

On a side note is adding an upgrade option to tridentctl going to happen sometime?

**Comment by rendhalver** [comment]
Awesome.
Is there an open PR to add that I can help test?

**Comment by kangarlou** [comment]
We haven't started working on this feature yet. We'll let you know once it becomes available for testing. Thanks!

**Comment by rendhalver** [comment]
Sounds great.
Feel free to tag me on the PR and I will see about testing it locally.
