### ISSUE TITLE
Trident image for Linux on ppc64le

### ISSUE THREAD

**Issue by arsenalzp** [NetApp/trident#204]
Hello,
I'm unable to use Trident on RHEL 7.5 ppc64le.
Docker image was builded well:

> $docker images
> REPOSITORY                               TAG                  IMAGE ID            CREATED             SIZE
> trident                                  18.10.0-custom       ef12a3f561db        2 hours ago         164 MB

> $file bin/tridentctl
> bin/tridentctl: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=122143f6151328a8e8fab4d93b213633e0eafa64, not stripped

> $ file bin/trident_orchestrator
> bin/trident_orchestrator: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0, BuildID[sha1]=9074f26f64a3cf3f0ffcf25e3dd21b7957ca612a, not stripped

Try to start:

> $kubectl run trident --image=trident:18.10.0-custom

> $ kubectl get pod
> NAME                       READY     STATUS              RESTARTS   AGE
> trident-4031422826-65odh   0/1       RunContainerError   1          16s

Checking logs:

> $ kubectl logs trident-4031422826-65odh
> container_linux.go:247: starting container process caused "exec: \"/usr/bin/env -i PATH='/netapp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /usr/local/bin/$BIN -port $PORT -etcd_v3 $ETCDV3 -k8s_api_server $K8S\": stat /usr/bin/env -i PATH='/netapp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /usr/local/bin/$BIN -port $PORT -etcd_v3 $ETCDV3 -k8s_api_server $K8S: no such file or directory"

Something went wrong...
Could somebody help me ?

My environment:
 

> $ docker version
> Client:
>  Version:         1.13.1
>  API version:     1.26
>  Package version: docker-1.13.1-74.git6e3bb8e.el7.ppc64le
>  Go version:      go1.9.2
>  Git commit:      6e3bb8e/1.13.1
>  Built:           Wed Aug  1 17:04:05 2018
>  OS/Arch:         linux/ppc64le
> 
> Server:
>  Version:         1.13.1
>  API version:     1.26 (minimum version 1.12)
>  Package version: docker-1.13.1-74.git6e3bb8e.el7.ppc64le
>  Go version:      go1.9.2
>  Git commit:      6e3bb8e/1.13.1
>  Built:           Wed Aug  1 17:04:05 2018
>  OS/Arch:         linux/ppc64le
>  Experimental:    false
> 

> $ kubectl version
> Client Version: version.Info{Major:"1", Minor:"4", GitVersion:"1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2017-02-07T17:25:56Z", GoVersion:"go1.7.5 ibm-1.7", Compiler:"gc", Platform:"linux/ppc64le"}
> Server Version: version.Info{Major:"1", Minor:"4", GitVersion:"1.4.7", GitCommit:"92b4f971662de9d8770f8dcd2ee01ec226a6f6c0", GitTreeState:"clean", BuildDate:"2017-02-07T17:25:56Z", GoVersion:"go1.7.5 ibm-1.7", Compiler:"gc", Platform:"linux/ppc64le"}

**Comment by ntap-rippy** [comment]
The Trident container is based on x86-64 alpine:
https://github.com/NetApp/trident/blob/0f168eef71dd978df90130fb19a83f35add54c60/Dockerfile#L1

Running **file** against the binaries inside shows x86-64
```
$ docker run --rm -it netapp/trident:18.10.0 ash -c 'apk add file; file /usr/bin/coreutils'
fetch http://dl-1.alpinelinux.org/alpine/v3.8/main/x86_64/APKINDEX.tar.gz
...
(1/2) Installing libmagic (5.32-r0)
(2/2) Installing file (5.32-r0)
Executing busybox-1.28.4-r1.trigger
OK: 27 MiB in 44 packages
/usr/bin/coreutils: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-musl-x86_64.so.1, stripped
```

**Comment by arsenalzp** [comment]
@ntap-rippy, thank for response!
Does it mean I can't build and use Trident on Linux ppc64le in no way ?

**Comment by adkerr** [comment]
@arsenalzp Since you're building a custom version anyways, you can try adjusting the Dockerfile to use a PPC based image, however that may also require changing the libraries that are installed into the image as well, but keep in mind you're venturing into unsupported and untested territory here

**Comment by adkerr** [comment]
With that said, if the x86 container will run you may not even need a PPC compiled trident since it's fully containerized. But again, we have done no testing with PPC hosts.

**Comment by kangarlou** [comment]
I don't think an x86 binary or Docker image can run on PPC. Docker doesn't provide any sort of virtualization/binary translation for you. You have to build your own Trident image on PPC. Also, you shouldn't be running Trident v18.10 with k8s 1.4. k8s 1.4 was supported by Trident v1.0, which was released more than 2 years ago.

**Comment by arsenalzp** [comment]
@kangarlou yes, I know. I tried to clone Trident repo and then build from source.

**Comment by arsenalzp** [comment]
So, I changed _Dockerfile_ and updated k8s to v1.11.1+icp ( IBM Cloud Private-ce )

> was: 
> FROM alpine:3.8

> became: 
> FROM ppc64le/alpine:3.8

Also, I add comment to the following line:

> #RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

Try to build with  _make trident_build_

Seems, everything is OK:

> Successfully built 20317c166482

In result, two binaries were created and placed into bin/ directory:

>  $file bin/*
> bin/tridentctl:           **ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0**, BuildID[sha1]=b0351a7ff7a31003c9d288ac85176e5d0445e833, not stripped
> bin/trident_orchestrator: **ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked (uses shared libs), for GNU/Linux 3.2.0**, BuildID[sha1]=33006488377a4856e39e188d92531ca6e563e8ab, not stripped

Docker image was created also:

> $ docker images|grep trident
> trident                                            18.10.0-custom      6cdbb24d162e        About a minute ago   165 MB
> 

Try to start:

> $kubectl run trident --image=trident:18.10.0-custom

And I'm getting the same error:

> $ kubectl logs trident-5b49fcff86-xgz2p
> container_linux.go:247: starting container process caused "exec: \"/usr/bin/env -i PATH='/netapp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /usr/local/bin/$BIN -port $PORT -etcd_v3 $ETCDV3 -k8s_api_server $K8S\": stat /usr/bin/env -i PATH='/netapp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /usr/local/bin/$BIN -port $PORT -etcd_v3 $ETCDV3 -k8s_api_server $K8S: no such file or directory"

Which directive I should add to Dockerfile to get success ?
P.S.
That's not obviously which file/directory does not exist...

[Dockerfile.txt](https://github.com/NetApp/trident/files/2746227/Dockerfile.txt)

**Comment by kangarlou** [comment]
You can't just do `kubectl run` to install Trident. Installing Trident entails installing a service account, ClusterRoles, ClusterRoleBindings, etc, which happen when you run `tridentctl install` (see the documentation). This means you should use the installer bundle (the .tar.gz file generated as part of the build) to install Trident.

**Comment by arsenalzp** [comment]
@kangarlou 
Yes, I read Docs and I tried to run _tridentctl install_

**Comment by kangarlou** [comment]
You either need to push your custom image to a registry and use `tridentctl install --trident-image <IMAGE>` or `docker load` your custom image on every node in your k8s cluster.

**Comment by kangarlou** [comment]
I would bring up the Trident pod with a command like `while true; do echo hi && sleep 1; done` and inspect the running pod for the Trident binary and try running the Trident command using `kubectl exec`.

**Comment by arsenalzp** [comment]
@kangarlou 
I added commet to the following line:

> #CMD ["/usr/bin/env -i PATH='/netapp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin' /usr/local/bin/$BIN -port $PORT -etcd_v3 $ETCDV3 -k8s_api_server $K8S"]
and put new one:

> ENTRYPOINT while true; do echo hi && sleep 1; done

Let's try to run:

> $kubectl run trident --image=trident:18.10.0-custom

> # kubectl get pod
> NAME                       READY     STATUS    RESTARTS   AGE
> trident-5b49fcff86-947d7   1/1       **Running**   1          5m

> $ kubectl exec trident-5b49fcff86-947d7 **/usr/local/bin/tridentctl**
> rpc error: code = 2 desc = oci runtime error: exec failed: container_linux.go:247: starting container process caused "no such file or directory"
> 
> command terminated with exit code 126

> $ kubectl exec trident-5b49fcff86-947d7 file /usr/local/bin/tridentctl
> /usr/local/bin/tridentctl: ELF 64-bit LSB executable, 64-bit PowerPC or cisco 7500, version 1 (SYSV), dynamically linked, interpreter /lib64/ld64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=64d79bd71b3db664a43a9dce8c71efa90d7d6658, with debug_info, not stripped
>

**Comment by arsenalzp** [comment]
Seems, there is a lack of some library:

>  $kubectl exec trident-5b49fcff86-947d7 ls /lib64/ld64.so.2
> ls: cannot access '/lib64/ld64.so.2': No such file or directory
> command terminated with exit code 2

**Comment by arsenalzp** [comment]
I tried the following:
mkdir /lib64
ln -s /lib/libc.musl-ppc64le.so.1 /lib64/ld64.so.2

In result I have segfault:

> $ strace /usr/local/bin/tridentctl
> execve("/usr/local/bin/tridentctl", ["/usr/local/bin/tridentctl"], 0x3fffd768be20 /* 21 vars */) = 0
> set_tid_address(0x3fff865a2880)         = 1232
> mprotect(0x11d00000, 65536, PROT_READ)  = 0
> --- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=NULL} ---
> +++ killed by SIGSEGV (core dumped) +++
> Segmentation fault

Try to exec /usr/local/bin/tridentctl without library symlink (default build):

> $ kubectl exec trident-5b49fcff86-bjln7 -it -- strace /usr/local/bin/tridentctl
> execve("/usr/local/bin/tridentctl", ["/usr/local/bin/tridentctl"], 0x3fffd2bc2f50 /* 18 vars */) = -1 ENOENT (No such file or directory)
**> writev(2, [{iov_base="strace: exec: No such file or di"..., iov_len=39}, {iov_base="\n", iov_len=1}], 2strace: exec: No such file or directory**
> ) = 40
> writev(2, [{iov_base="", iov_len=0}, {iov_base=NULL, iov_len=0}], 2) = 0
> getpid()                                = 1346
> exit_group(1)                           = ?
> +++ exited with 1 +++
> command terminated with exit code 1

I do not understand which file does not exist...

**Comment by arsenalzp** [comment]
Attempted to build Trident on ppc64le/ubuntu and, seems, it's getting better : Trident pod has started and is running!

**Comment by kangarlou** [comment]
Closed per https://github.com/NetApp/trident/issues/205.
