### ISSUE TITLE
Mounting the .snapshot volume in a k8 pod but data not visible

### ISSUE THREAD

**Issue by Quietghost** [NetApp/trident#207]
I am not sure if this is a bug or my problem but I am trying to accomplish the following but it is not working. I have a Cassandra Statefulset with two vlomune mounts defined - I am trying to mount the NetApp snapshot directory in different PVC/PV the data itself:

[...]
volumeMounts:
        - name: data
          mountPath: /var/lib/cassandra
        - name: snapshot
          mountPath: /var/lib/cassandra/.snapshot/
[...]
volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        app: {{ template "cassandra.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        trident.netapp.io/snapshotDirectory: "true"
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClass }}
    {{- if (eq "-" .Values.persistence.storageClass) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.storageClass }}"
    {{- end }}
    {{- end }}
  - metadata:
      name: snapshot
      labels:
        app: {{ template "cassandra.fullname" . }}
        chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
      annotations:
        trident.netapp.io/snapshotDirectory: "true"
    spec:
      accessModes:
        - {{ .Values.persistence.accessMode | quote }}
      resources:
        requests:
          storage: {{ .Values.persistence.size | quote }}
    {{- if .Values.persistence.storageClassSnapshot }}
    {{- if (eq "-" .Values.persistence.storageClassSnapshot) }}
      storageClassName: ""
    {{- else }}
      storageClassName: "{{ .Values.persistence.storageClassSnapshot }}"
    {{- end }}
    {{- end }}

The Storageclass I am using in the Helm install values file is defined as follows:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: 2018-12-05T16:12:42Z
  name: nas-ssd-basic
  resourceVersion: "24363126"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/nas-ssd-basic
  uid: 982698d9-f8a8-11e8-8ca6-005056b6409a
parameters:
  backendType: ontap-nas
  clones: "true"
  encryption: "false"
  media: hybrid
  provisioningType: thin
  snapshots: "true"
  storagePools: vcab0050-v-01:.*;vcab0050-v-02:.*
provisioner: netapp.io/trident
reclaimPolicy: Delete
volumeBindingMode: Immediate

Although the PVCs and PVs are created without problem and on the NetApp side everything looks normal, I cannot see the data in the container?

cassandra@cassandra-owner-cassandra-0:/var/lib/cassandra/.snapshot$ ls -a
.  ..  .snapshot
cassandra@cassandra-owner-cassandra-0:/var/lib/cassandra/.snapshot$ cd .snapshot/
cassandra@cassandra-owner-cassandra-0:/var/lib/cassandra/.snapshot/.snapshot$ ls -a
.  ..  BITdaily_1900.2019-01-12_1900  BITdaily_1900.2019-01-13_1900

I can see the snapshots of the second volume mount but they are empty (also on the NetApp side) ...

Hope somebody can bring some light here ... Thanks in advance!

**Comment by innergy** [comment]
You have two separate volumes, one that you're mounting under `/var/lib/cassandra`, and another under `/var/lib/cassandra/.snapshot`.

What you're seeing is what I would expect: two completely separate volumes, and you've lost access to the root .snapshot directory of the first.

What is the purpose of this second volume? Why wouldn't you just use the data volume, take snapshots with it, and access those using the .snapshot directory that ONTAP exposes?
