### ISSUE TITLE
Support SolidFire iSCSI Expansion

### ISSUE THREAD

**Issue by ronshuli** [NetApp/trident#208]
hi,
we are using trident 18.10 in production, using solid-fire iSCSI as a backend, OpenShift cluster version 3.9 (upgrading to 3.11 soon).

we would like to know if iSCSI resize is in the road-map.
we looked at [this commit](https://github.com/NetApp/trident/commit/38ec201081e532a9012fe833346956a0fdf4bef5) but the feature isn't available yet.

we understand that the file system resize part is missing currently, not sure how to implement it (daemon set?).
this feature very important to us, and willing to contribute for this feature, but we would love some guidance with how exactly to do this .

thank you, best regards.

**Comment by clintonk** [comment]
Hello, @ronshuli.  iSCSI resize requires changes in Kubernetes, and the community direction is CSI for such things.  iSCSI resize is definitely on the Trident roadmap, but there are other prerequisites ahead of it, so I can't promise when it will be available.  As you noticed, we have the resize code in all of Trident's backends, so all of the remaining (and not insignificant) work is in the Kubernetes-facing Trident frontend as well as Kubernetes itself.

**Comment by neufeldtech** [comment]
If this isn't natively available yet, are there any workarounds that can be executed to manually resize an iscsi PVC?

I attempted to update the `requests` field in my PVC, but it returned an error on Kubernetes 1.13

```
...
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 30Gi
...
```

```error: persistentvolumeclaims "data-elk-elasticsearch-data-0" could not be patched: persistentvolumeclaims "data-elk-elasticsearch-data-0" is forbidden: only dynamically provisioned pvc can be resized and the storageclass that provisions the pvc must support resize
You can run `kubectl replace -f /var/folders/5k/wvflv8r90551zw2798jcbh6h0000gn/T/kubectl-edit-06cpa.yaml` to try this update again.```

**Comment by neufeldtech** [comment]
This is how to do it

- Resize your ISCSI volume in solidfire
- Terminate your pod that was mounting that volume
- Allow pod to get re-created
- SSH to node that the pod is running on
- Run `lsblk` to find out the Device ID of your iscsi volume (i.e. /dev/sdc for example)
- Assuming an ext4 filesystem, run `resize2fs /dev/sdc` (the device ID that you identified previously)
- Your container should now see the larger filesystem
NOTES
- Your `pv` and `pvc` resources in Kubernetes won't know that you resized it, so they will still show the old size.
- You may be able to avoid pod deletion by rescanning the iscsi targets - YMMV.

**Comment by korenaren** [comment]
Feature added in 19.10: https://github.com/NetApp/trident/releases/tag/v19.10.0
