### ISSUE TITLE
Feature Request: NFSv4 Support

### ISSUE THREAD

**Issue by wesmcouch** [NetApp/trident#209]
Hello,

Looking for NFSv4 support. We are attempting to migrate to trident and we are using NFSv4 so we were hoping to use it here too.

Thanks!

**Comment by clintonk** [comment]
Hello, @wesmcouch.  Trident already supports NFSv4 with both Docker & Kubernetes via mount options.  With Docker, specify NFS mount options in your backend config file.  With Kubernetes, specify NFS mount options (i.e. 'nfsvers=4') in your storage classes.

**Comment by wesmcouch** [comment]
Awesome thanks!
