### ISSUE TITLE
tridentctl install failed

### ISSUE THREAD

**Issue by Chaitan007** [NetApp/trident#211]
Hello All,

Having issue trying to install Trident, any one seen this issue ?

even though Backend details are correct
chai@ubuntu01:~/trident-installer/setup$ cat backend.json 
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "192.168.0.1",
    "dataLIF": "192.168.0.6",
    "svm": "vs1",
    "username": "admin",
    "password": "password"
}

FATA Install failed; could not start the storage backend driver; unable to inspect ONTAP backend: runtime error: invalid memory address or nil pointer dereference
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack(0xc420177078, 0x150d4c0, 0x21fe590)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/netapp/trident/storage_drivers/ontap.getStorageBackendSpecsCommon.func1(0xc420178038)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_common.go:924 +0x6e
panic(0x150d4c0, 0x21fe590)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/netapp/trident/storage_drivers/ontap/api/azgo.(*VserverInfoType).VserverAggrInfoList(...)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/api/azgo/type-vserver-info.go:504
github.com/netapp/trident/storage_drivers/ontap/api.Client.VserverGetAggregateNames(0xc42042ff60, 0xc, 0xc42042ff28, 0x3, 0xc42042ff2b, 0x5, 0xc42042ff90, 0x9, 0x0, 0xc4202ad080, ...)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/api/ontap.go:1678 +0x472
github.com/netapp/trident/storage_drivers/ontap.getStorageBackendSpecsCommon(0x187d740, 0xc42012e000, 0xc4203a4280, 0xc4204572f0, 0x0, 0x0)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_common.go:929 +0x1b3
github.com/netapp/trident/storage_drivers/ontap.(*NASQtreeStorageDriver).GetStorageBackendSpecs(0xc42012e000, 0xc4203a4280, 0x0, 0x0)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_nas_qtree.go:1001 +0x89
github.com/netapp/trident/storage.NewStorageBackend(0x1897de0, 0xc42012e000, 0xa, 0xc42034ebb0, 0xa3)
	/go/src/github.com/netapp/trident/storage/backend.go:82 +0xe5
github.com/netapp/trident/storage/factory.NewStorageBackendForConfig(0xc42034ebb0, 0xa3, 0x0, 0x0, 0x0)
	/go/src/github.com/netapp/trident/storage/factory/factory.go:79 +0x5e3
github.com/netapp/trident/cli/cmd.loadStorageDriver(0xc4202ac840, 0xc420178698, 0x1)
	/go/src/github.com/netapp/trident/cli/cmd/install.go:884 +0x225
github.com/netapp/trident/cli/cmd.installTrident(0xc420179cc8, 0x0)
	/go/src/github.com/netapp/trident/cli/cmd/install.go:623 +0x3c0b
github.com/netapp/trident/cli/cmd.glob..func12(0x220ba80, 0xc4202e4ea0, 0x0, 0x12)
	/go/src/github.com/netapp/trident/cli/cmd/install.go:161 +0x210
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).execute(0x220ba80, 0xc4202e4d80, 0x12, 0x12, 0x220ba80, 0xc4202e4d80)
	/go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x220bf40, 0x0, 0xc420179f68, 0x137f8b5)
	/go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).Execute(0x220bf40, 0xc420179f78, 0xc42008e058)
	/go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/netapp/trident/cli/main.go:14 +0x3c
.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

chai@ubuntu01:~/trident-installer/setup$ kubectl get pods --all-namespaces
NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
kube-system   coredns-86c58d9df4-4q6h2           1/1     Running   1          23h
kube-system   coredns-86c58d9df4-cphmh           1/1     Running   1          23h
kube-system   etcd-ubuntu01                      1/1     Running   1          23h
kube-system   kube-apiserver-ubuntu01            1/1     Running   1          23h
kube-system   kube-controller-manager-ubuntu01   1/1     Running   2          23h
kube-system   kube-flannel-ds-amd64-ccjfl        1/1     Running   0          22h
kube-system   kube-flannel-ds-amd64-cf8qn        1/1     Running   1          22h
kube-system   kube-flannel-ds-amd64-rlx79        1/1     Running   2          23h
kube-system   kube-proxy-5wjs4                   1/1     Running   2          23h
kube-system   kube-proxy-bpkxw                   1/1     Running   1          22h
kube-system   kube-proxy-gnf5w                   1/1     Running   0          22h
kube-system   kube-scheduler-ubuntu01            1/1     Running   2          23h
trident       trident-installer                  0/1     Error     0          6m

Thanks

**Comment by Chaitan007** [comment]
Hello Yves,
Thanks for your response, yes i have tried the same with ontap-nas, still the same, just you are aware, i am using ONTAP simulator 9.4.

Thanks
Chaitan

**Comment by Chaitan007** [comment]
Hi,

here are version details :
chaitan@ubuntu01:~/trident-installer/setup$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
chaitan@ubuntu01:~/trident-installer/setup$ docker version
Client:
 Version:           18.06.1-ce
 API version:       1.38
 Go version:        go1.10.4
 Git commit:        e68fc7a
 Built:             Fri Oct 19 19:43:14 2018
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.06.1-ce
  API version:      1.38 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       e68fc7a
  Built:            Thu Sep 27 02:39:50 2018
  OS/Arch:          linux/amd64
  Experimental:     false


Backedn Json file
chaitan@ubuntu01:~/trident-installer/setup$ cat backend.json 
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "192.168.0.51",
    "dataLIF": "192.168.0.60",
    "svm": "vs1",
    "username": "admin",
    "password": "netapp123"
}

Still the same issue ;(
chaitan@ubuntu01:~/trident-installer/setup$ sudo ../tridentctl install --dry-run -n trident
INFO Created installer service account.            serviceaccount=trident-installer
INFO Waiting for object to be created.             objectName=clusterRole
INFO Created installer cluster role.               clusterrole=trident-installer
INFO Waiting for object to be created.             objectName=clusterRoleBinding
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
INFO Created installer configmap.                  configmap=trident-installer
INFO Waiting for object to be created.             objectName=installerPod
INFO Created installer pod.                        pod=trident-installer
INFO Waiting for Trident installer pod to start.  
INFO Trident installer pod started.                namespace=trident pod=trident-installer
INFO Starting storage driver.                      backend=/setup/backend.json
INFO Controller serial numbers.                    serialNumbers=4082368-50-7
FATA Install failed; could not start the storage backend driver; unable to inspect ONTAP backend: runtime error: invalid memory address or nil pointer dereference
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack(0xc420177078, 0x150d4c0, 0x21fe590)
	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/netapp/trident/storage_drivers/ontap.getStorageBackendSpecsCommon.func1(0xc420178038)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_common.go:924 +0x6e
panic(0x150d4c0, 0x21fe590)
	/usr/local/go/src/runtime/panic.go:502 +0x229
github.com/netapp/trident/storage_drivers/ontap/api/azgo.(*VserverInfoType).VserverAggrInfoList(...)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/api/azgo/type-vserver-info.go:504
github.com/netapp/trident/storage_drivers/ontap/api.Client.VserverGetAggregateNames(0xc42042df80, 0xc, 0xc42042df48, 0x3, 0xc42042df4b, 0x5, 0xc42042df90, 0x9, 0x0, 0xc4202a7080, ...)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/api/ontap.go:1678 +0x472
github.com/netapp/trident/storage_drivers/ontap.getStorageBackendSpecsCommon(0x187d780, 0xc4201fb040, 0xc4204c8880, 0xc42001c3c0, 0x0, 0x0)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_common.go:929 +0x1b3
github.com/netapp/trident/storage_drivers/ontap.(*NASStorageDriver).GetStorageBackendSpecs(0xc4201fb040, 0xc4204c8880, 0x0, 0x0)
	/go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_nas.go:354 +0x89
github.com/netapp/trident/storage.NewStorageBackend(0x1897ec0, 0xc4201fb040, 0xa, 0xc4202c6b40, 0x9b)
	/go/src/github.com/netapp/trident/storage/backend.go:82 +0xe5
github.com/netapp/trident/storage/factory.NewStorageBackendForConfig(0xc4202c6b40, 0x9b, 0x0, 0x0, 0x0)
	/go/src/github.com/netapp/trident/storage/factory/factory.go:79 +0x5e3
github.com/netapp/trident/cli/cmd.loadStorageDriver(0xc4202a6840, 0xc420178698, 0x1)
	/go/src/github.com/netapp/trident/cli/cmd/install.go:884 +0x225
github.com/netapp/trident/cli/cmd.installTrident(0xc420179cc8, 0x0)
	/go/src/github.com/netapp/trident/cli/cmd/install.go:623 +0x3c0b
github.com/netapp/trident/cli/cmd.glob..func12(0x220ba80, 0xc4202fc480, 0x0, 0x12)
	/go/src/github.com/netapp/trident/cli/cmd/install.go:161 +0x210
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).execute(0x220ba80, 0xc4202fc360, 0x12, 0x12, 0x220ba80, 0xc4202fc360)
	/go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x220bf40, 0x0, 0xc420179f68, 0x137f8b5)
	/go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).Execute(0x220bf40, 0xc420179f78, 0xc42008e058)
	/go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/go/src/github.com/netapp/trident/cli/main.go:14 +0x3c
.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again. 

Plugin it works fine.

chaitan@ubuntu01:~/trident-installer/setup$ docker plugin ls
ID                  NAME                DESCRIPTION                          ENABLED
54537f49fa88        netapp:latest       nDVP - NetApp Docker Volume Plugin   true

Thanks
Chaitan

**Comment by Chaitan007** [comment]
wow, that resolved it, silly me :).. thanks for your help adkerr.

**Comment by delfer** [comment]
Still have this issue in 19.01.0/19.04.0-beta.1. Program should correctly handle this situation instead of `invalid memory address or nil pointer dereference`.

**Comment by naveene425** [comment]
Me too i am running into the same error in 19.01.0 . ``Error: could not create backend: unable to inspect ONTAP backend: runtime error: invalid memory address or nil pointer dereference``

**Comment by innergy** [comment]
Fixed to give a proper error message by commit ecd48a175f0ff7c847b6345ad2ec35508b89603d

This commit will be in the 19.04 release. If you see this, you need to assign one or more aggregates to your SVM.

**Comment by innergy** [comment]
Note that you may receive a similar error/trace if you're attempting to use the `limitAggregateUsage` attribute in one of your backends as an SVM admin rather than a cluster admin. The calls Trident has to make to enforce that are not available to SVM admins.

**Comment by dougstaub** [comment]
I am seeing this error and per a case with NetApp ([here](https://kb.netapp.com/app/answers/answer_view/a_id/1086532)) it states to "Either change the access to use the cluster admin, or remove the option limitAggregateUsage from the backend storage definition" - where do you change the backend storage definition for this?

**Comment by adkerr** [comment]
@dougstaub This would be the `backend.json` file in the setup directory of the installer: https://netapp-trident.readthedocs.io/en/stable-v19.01/kubernetes/operations/tasks/backends/ontap.html
