### ISSUE TITLE
Migrate to a new netapp

### ISSUE THREAD

**Issue by mvineza** [NetApp/trident#214]
Hi All,

I just want to know if anyone tried to migrate the persistent volumes to a new netapp device?
If yes, can you please share the steps you did? Thank you!

Regards,
Merrell

**Comment by ToroNZ** [comment]
I did by moving the entire SVM from ClusterA to ClusterB.

That was the easiest way I could find (moving away from an EVAL license).


Sent from my phone
________________________________
De:Merrell Vineza <notifications@github.com>
Enviado:jueves, 21 de febrero de 2019 17:15
Para:NetApp/trident
Cc: Subscribed
Asunto: [NetApp/trident] Migrate to a new netapp (#214)

Hi All,

I just want to know if anyone tried to migrate the persistent volumes to a new netapp device?
If yes, can you please share the steps you did? Thank you!

Regards,
Merrell

**Comment by mvineza** [comment]
@ToroNZ Thank you for sharing! I'll discuss and sahre this with our storage team if it is possible on our end.
