### ISSUE TITLE
OpenShift 3.11 monitoring operator and trident

### ISSUE THREAD

**Issue by geoberle** [NetApp/trident#218]
The monitoring operator on OpenShift 3.11 sets up prometheus and various other things in order to monitor your openshift cluster. One can specify a storageclass for the PVs to create for the backing storage of prometheus. If we use trident for this usecase, we run into the 64 character limit of volume names, because the namespace is called openshift-monitoring and the statefule set for prometheus specifies a volumeClaimTemplate named prometheus-k8s-db. This results in PVC named prometheus-k8s-db-prometheus-k8s-0 and trident volume names like  trident_openshift_monitoring_prometheus_k8s_db_prometheus_k8s_0_a74c7, which is 67 characters long.

The bad news is, that the OpenShift operator provides no way to change the name of the namespace or the stateful sets volumeClaimTemplate. Thus as a user i have no way to shorten the PVC name to get under the 64 character limit with the trident volume name.

I read the trident documentation full of hope to find some way to tweak the volume name generation but found nothing so far. Is there a way to spare a couple of characters, like the "trident" prefix for example?

Hopefully yours
Gerd

**Comment by innergy** [comment]
Which storage driver are you using?

**Comment by geoberle** [comment]
i'm using the ontap-nas-economy driver

**Comment by clintonk** [comment]
@geoberle Yes, you can specify the storagePrefix to your backend config file.  The default prefix is 'trident', but it can be shorter.

https://netapp-trident.readthedocs.io/en/stable-v19.01/kubernetes/operations/tasks/backends/ontap.html#

**Comment by geoberle** [comment]
thank you so much. i had to go for a very short prefix but i managed to fix the issues with the "storagePrefix" option.
