### ISSUE TITLE
Feature request (small) : Add PV size to log

### ISSUE THREAD

**Issue by frank2b** [NetApp/trident#223]
To be able to calculate how much storage is/was consumed, it would be great to have the size in GB in the logs when the PV is created, should be very simple.

**Comment by innergy** [comment]
Usually data like this would be captured in an object representing the volume so that it could be more easily used programmatically rather than requiring someone to scrape log files, but it's not completely clear what you're trying to achieve. Can you elaborate on your use case?

**Comment by frank2b** [comment]
I agree that this would be the best :=)
We have some customers (service providers) which have to check which pvc/pv where provisioned at which time and how long they were used to charge the  client for the disk usage. If there would be an output or trigger with this info it would be very easy. I. e output (maybe optional) in form of csv delimited format. Or the possibility to query Trident /etcd maybe ?
Hope this makes it a little bit mor clear.
Thx in advance.

**Comment by innergy** [comment]
Oh. If you're just trying to determine when a PVC or PV was created, Kubernetes already tracks that natively. For example:

> $ kubectl get pvc -n trident trident -o json | jq '.metadata.creationTimestamp'
"2018-10-26T19:43:57Z"
> $ kubectl get pv trident -o json | jq '.metadata.creationTimestamp'
"2018-10-26T19:43:58Z"

**Comment by frank2b** [comment]
Thanks for your answer, maybe my explanation was that too bad :
I can see the creation time and size as long as a PVC exists, right ?
But how to get the information when a developer creates a pvc and deletes that again after 2 hrs ?
That is the problem. We have to know when a pvc is created , which size and when deleted.
Maybe I have a missunderstanding but I believe the info of an PVC is only available while it exists, not when it has gone.

**Comment by innergy** [comment]
That is true, but you can use the standard k8s API to handle this too, by using the List API to receive notifications when PVCs are created and deleted. This is similar to how Trident itself works.

Here's an example of kubectl calling that API. While it was waiting on the call with `watch=true`, I created and deleted a PVC, and you can see that it received multiple notifications for that.

> $ kubectl get pvc --watch-only -v=6
> I0314 14:31:19.128358    5494 round_trippers.go:405] GET https://xx.xx.xx.xx:6443/api/v1/namespaces/default/persistentvolumeclaims?limit=500 200 OK in 16 milliseconds
> I0314 14:31:19.131966    5494 round_trippers.go:405] GET https://xx.xx.xx.xx:6443/api/v1/namespaces/default/persistentvolumeclaims?resourceVersion=20091587&watch=true 200 OK in 1 milliseconds
> NAME     STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
> my-pvc   Pending                                      default        0s
> my-pvc   Pending                     default   1s
> my-pvc   Pending                     default   2s
> my-pvc   Pending   default-my-pvc-c6fb8   0           default   7s
> my-pvc   Bound   default-my-pvc-c6fb8   1Gi   RWO   default   7s
> my-pvc   Terminating   default-my-pvc-c6fb8   1Gi   RWO   default   21s
> my-pvc   Terminating   default-my-pvc-c6fb8   1Gi   RWO   default   21s
