### ISSUE TITLE
Proper way of specifying exportPolicy for a NFS backend

### ISSUE THREAD

**Issue by plz** [NetApp/trident#23]
Could be related to #22 , but according to ndvp [docs](http://netappdvp.readthedocs.io/en/latest/install/ndvp_ontap_config.html) you can specify a defaults section where, for example, you can modify the export policy for all volumes created via ndvp. 

Are these set of directives also supported by trident? If so, what's the way of specifying it in the backend configs (also via a defaults section?)

Thanks

**Comment by kangarlou** [comment]
Yes, they're supported by Trident in the same way as in nDVP.

**Comment by korenaren** [comment]
Answer posted 22 days ago, so closing this issue. If necessary, you can reopen.
