### ISSUE TITLE
Handling of storagePrefix if not part of 'aggr-list' of the svm, should be taken care off in file 'storage_drivers/ontap/ontap_common.go'

### ISSUE THREAD

**Issue by prakashkl88** [NetApp/trident#231]
INFO Created installer service account.            serviceaccount=trident-installer
INFO Waiting for object to be created.             objectName=clusterRole
INFO Created installer cluster role.               clusterrole=trident-installer
INFO Waiting for object to be created.             objectName=clusterRoleBinding
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
INFO Created installer configmap.                  configmap=trident-installer
INFO Waiting for object to be created.             objectName=installerPod
INFO Created installer pod.                        pod=trident-installer
INFO Waiting for Trident installer pod to start.
INFO Trident installer pod started.                namespace=trident pod=trident-installer
INFO Starting storage driver.                      backend=/setup/backend.json
INFO Controller serial numbers.                    serialNumbers="721825000190,721825000189"
WARN Please ensure all relevant hosts are added to the initiator group.  SVM=vs0 driver=ontap-san igroup=quark1
FATA Install failed; could not start the storage backend driver; unable to inspect ONTAP backend: runtime error: invalid memory address or nil pointer dereference
Stack trace:
goroutine 1 [running]:
runtime/debug.Stack(0xc420177078, 0x150d4c0, 0x21fe590)
        /usr/local/go/src/runtime/debug/stack.go:24 +0xa7
github.com/netapp/trident/storage_drivers/ontap.getStorageBackendSpecsCommon.func1(0xc420178038)
        /go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_common.go:924 +0x6e
panic(0x150d4c0, 0x21fe590)
        /usr/local/go/src/runtime/panic.go:502 +0x229
github.com/netapp/trident/storage_drivers/ontap/api/azgo.(*VserverInfoType).VserverAggrInfoList(...)
        /go/src/github.com/netapp/trident/storage_drivers/ontap/api/azgo/type-vserver-info.go:504
github.com/netapp/trident/storage_drivers/ontap/api.Client.VserverGetAggregateNames(0xc420427f70, 0xd, 0xc420427f88, 0x3, 0xc420427f8b, 0x5, 0xc420427f80, 0x8, 0x0, 0xc4202a5080, ...)
        /go/src/github.com/netapp/trident/storage_drivers/ontap/api/ontap.go:1678 +0x472
github.com/netapp/trident/storage_drivers/ontap.getStorageBackendSpecsCommon(0x187d7c0, 0xc42012a1c0, 0xc4203da600, 0xc4203c6780, 0x0, 0x0)
        /go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_common.go:929 +0x1b3
github.com/netapp/trident/storage_drivers/ontap.(*SANStorageDriver).GetStorageBackendSpecs(0xc42012a1c0, 0xc4203da600, 0xc420455270, 0xc4202a4cc0)
        /go/src/github.com/netapp/trident/storage_drivers/ontap/ontap_san.go:572 +0xe6
github.com/netapp/trident/storage.NewStorageBackend(0x1897fa0, 0xc42012a1c0, 0xa, 0xc4201101c0, 0xd1)
        /go/src/github.com/netapp/trident/storage/backend.go:82 +0xe5
github.com/netapp/trident/storage/factory.NewStorageBackendForConfig(0xc4201101c0, 0xd1, 0x0, 0x0, 0x0)
        /go/src/github.com/netapp/trident/storage/factory/factory.go:79 +0x5e3
github.com/netapp/trident/cli/cmd.loadStorageDriver(0xc4202a47e0, 0xc420178698, 0x1)
        /go/src/github.com/netapp/trident/cli/cmd/install.go:884 +0x225
github.com/netapp/trident/cli/cmd.installTrident(0xc420179cc8, 0x0)
        /go/src/github.com/netapp/trident/cli/cmd/install.go:623 +0x3c0b
github.com/netapp/trident/cli/cmd.glob..func12(0x220ba80, 0xc4202c9440, 0x0, 0x12)
        /go/src/github.com/netapp/trident/cli/cmd/install.go:161 +0x210
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).execute(0x220ba80, 0xc4202c9320, 0x12, 0x12, 0x220ba80, 0xc4202c9320)
        /go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:766 +0x2c1
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x220bf40, 0x0, 0xc420179f68, 0x137f8b5)
        /go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:852 +0x30a
github.com/netapp/trident/vendor/github.com/spf13/cobra.(*Command).Execute(0x220bf40, 0xc420179f78, 0xc42008e058)
        /go/src/github.com/netapp/trident/vendor/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /go/src/github.com/netapp/trident/cli/main.go:14 +0x3c
.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

We can clearly print that the user needs to add the aggregate into the aggr-list of the SVM rather than print this error which is very inconclusive and confusing:

FATA  Install failed; could not start the storage backend driver; unable to inspect ONTAP backend: runtime error: invalid memory address or nil pointer dereference

**Comment by prakashkl88** [comment]
Can this be assigned back to me, I know the fix for this issue

**Comment by thecovercover** [comment]
> Can this be assigned back to me, I know the fix for this issue

same issue, any advise？

**Comment by prakashkl88** [comment]
> > Can this be assigned back to me, I know the fix for this issue
> 
> same issue, any advise？

To overcome the issue, you need to manually add the aggregate to the svm by using a CLI or a ZAPI call to the ONTAP cluster:

"vserver modify -vserver <svm-name> -aggr-list <aggr-name>"  --> CLI
"vserver-modify" or "vserver-modify-iter" --> ZAPI

**Comment by innergy** [comment]
This issue was fixed in 19.04.
