### ISSUE TITLE
Qtree: Soft Disk Space Limit

### ISSUE THREAD

**Issue by dxlr8r** [NetApp/trident#232]
When exporting a volume the "Soft Disk Space Limit" is not set. 

```
netappXX::> quota report -vserver cust_env -volume trident_qtree_pool_cust_env_ABCD -instance

        Vserver Name: cust_env
         Volume Name: trident_qtree_pool_cust_env_ABCD
               Index: 123456789
          Qtree Name: cust_env__ns_proj_type_id
          Quota Type: tree
        Quota Target: 1
     Quota Target ID: 1
     Disk Space Used: 14.01MB
    Disk Space Limit: 25GB
          Files Used: 2
         Files Limit: -
Disk Space Threshold: -
Soft Disk Space Limit: -
    Soft Files Limit: -
     Quota Specifier: cust_env__ns_proj_type_id
```

Is it possible to set this in the future? And also support customisation of this value during installation, and expose the setting in the deploy object.

**Comment by innergy** [comment]
Are you saying that you'd like to add the ability to set a (lower) soft limit that warns the storage admin that a qtree is nearing capacity? Can you describe what it is that you would do with that warning? Normally this is used where an administrator would need to resize the volume, but in this ecosystem we allow users to resize their volumes themselves.

**Comment by dxlr8r** [comment]
> Can you describe what it is that you would do with that warning?

To get a warning so that users can: 

>  resize their volumes themselves.

**Comment by gnarl** [comment]
With the Trident 20.07 release capacity metrics are now reported. Users can use this information to resize their volumes as needed. Closing this issue since a solution now exists.
