### ISSUE TITLE
Allow more volume properties to be modified out-of-band without impacting Trident

### ISSUE THREAD

**Issue by cgajan** [NetApp/trident#233]
With ontap-nas-economy driver when Trident lookup for existing volumes it lookup with the following criteria

- Volume name prefix = storagePrefix defined in the backend 
- Snapshot-policy = snapshotPolicy defined in the backend 
- Snapshot directory access = snapshotDir defined in the backend 
- Space guarantee = spaceReserve defined in the backend 
- Encryption = encryption defined in the backend specification

If you set a backup on your Trident Volume (outside Trident with an external tool such as WFA)
you have to set a specific snapshot policy on your volume. 
This snapshot policy can be different for different volume to be able to balance the backup (snapshot) at different schedule
But with the current Trident lookup process changing the snapshot policy set by trident based on the backup snapshotPolicy parameter,
make the volume unreusable !
I should be great to allow a volume lookup only based on volume name prefix (storagePrefix)
It could be an option
- use the current lookup with all criteria
- use an new volume lookup mode only based on storagePrefix 

My current workaround is to define in the backend an snapshotPolicy compatible with my possible snapmirror policies
The backdraw is that all the snapshot for my backups are taken at the same time (not balanced over the night)

**Comment by cgajan** [comment]
I launched the pull request #238 which add a new backend parameter (qtreePoolVolSnapPolicyLookupPattern) to address this topic

**Comment by innergy** [comment]
Thanks for the PR. We do want to allow you to modify things out of band to some degree, but more and more Trident will be managing these details itself. We'll have to consider carefully which properties fall on which side of that line.

**Comment by gnarl** [comment]
Today NetApp offers an application backup solution with [Astra](https://cloud.netapp.com/astra). Astra can provide solutions for what you are requesting.
