### ISSUE TITLE
Process to change password for Trident user

### ISSUE THREAD

**Issue by nthawani** [NetApp/trident#236]
Changing password on ONTAP and updating Jason file doesn't work. Are we missing any steps? Is it documented how to change password? Thanks!

**Comment by adkerr** [comment]
After you update the json file are you also the backend to trident with `tridentctl update backend`? Trident doesn't dynamically read the json file, it loads it into its persistent store and reads from there.

**Comment by frank2b** [comment]
Hi,
same problem for me.
Defined 2 backends (drivers : ontap-nas and ontap-nas-economy) for the same svm, worked fine.
After changing the password via cli on svm, I can update the backend "ontap-nas" and it works.
But while trying to update "ontap-nas-economy", I got error 1
log (level=error msg="API invocation failed. response code 401 (Unauthorized): incorrect or missing credentials") and the backend definition is gone (tridentctl get backend). Cannot recreate it (key already exists). The whole installation incl. trident volume on Netapp has to be dropped to recreate everything.

**Comment by innergy** [comment]
This is fixed in 19.04.
