### ISSUE TITLE
SolidFire backend: 'trident' VAG 64 items limitation

### ISSUE THREAD

**Issue by sl0n** [NetApp/trident#24]
Hi,

We faced the following limitation on our SolidFire backed, while employing "trident" to provision volumes for Kubernetes:

`ERROR: Failed to Add IQN to VAG. ApiServerError(method_name="AddInitiatorsToVolumeAccessGroup", err_json={"id": 2, "error": {"message": "Exceeded max number of initiators per volumeAccessGroup. volumeAccessGroupID=1 limit=64", "code": 500, "name": "xExceededLimit"}`

The "64 limit" comes from ElementOS:

> NOTE: Volume access groups have the following system limits:
> - A maximum of 64 IQNs or WWPNs are allowed in an access group.

Since "trident" is only capable of using a pre-defined VAG called "trident", there is currently no way to introduce more than 64 IQNs.

We have a cluster of 128 servers at the moment (possible more to add later on) and need to defined all of them on SolidFire storage cluster.

Any thoughts maybe how that can be achieved?

**Comment by adkerr** [comment]
Tracked internally by [US2573](https://rally1.rallydev.com/#/47479883219d/detail/userstory/116756509452)

**Comment by kangarlou** [comment]
Hi. Thanks for bringing the issue to our attention. Here are a couple options worth exploring:

1. Using CHAP authentication instead of or in addition to VAGs.
2. Segmenting a compute cluster to multiple VAGs: Each group of 64 nodes can be assigned to a different VAG. For this to work, the SolidFire backend config file should supply the name of VAG as an argument similar to igroupName for ONTAP SAN backends (https://github.com/netapp/trident#ontap-configurations). Additionally, Trident should allow admins to define the name for a backend using the config file. Currently, Trident assigns a name to a backend using the format driverName_ipAddress. With these two changes, for each group of 64 nodes, an admin can add a separate backend instance that references a different VAG and has a unique name. The downside is that provisioned volumes will not be accessible across all hosts. However, it's possible to use container scheduling mechanisms in Kubernetes to force an app to get scheduled on one of the 64 nodes that can attach the volume.

Adding @j-griffith as he may have more insights to share.

**Comment by j-griffith** [comment]
@sl0n 
So you're correct, 64 Initiators per group; 4 groups per volume.  We could come up with some ways to try and distribute better with Trident by using multiple VAG's but I think using CHAP might be a more robust solution here.  

There's debate about which security method is preferred, but CHAP tends to make things "easier" in a large scale and dynamic setup.

**Comment by dutchiechris** [comment]
Eagerly awaiting this one I just tested in my lab with k8s 1.6.4 with success!

For the TLDR version here is how to do it:

1)	Download the 17.07.0-beta.0 release [https://github.com/NetApp/trident/releases](https://github.com/NetApp/trident/releases) to somewhere with kubectl auth'd to the cluster (I ran from my master)
2)	Untar the software and `cd trident-installer`
3)	Find the namespace of your trident pod:
```
# kubectl get po --all-namespaces | grep trident
NAMESPACE      NAME                                        READY     STATUS    RESTARTS   AGE
default        trident-102330697-ndxxb                     2/2       Running   1          6d
```
4)	Update trident:
```
# ./update_trident.sh -n default -t netapp/trident:17.07.0-beta.0
Installer assumes you have deployed Kubernetes. If this is an OpenShift deployment, make sure 'oc' is in the $PATH.
deployment "trident" image updated
```
5)	Wait a few minutes and the trident pod should be updated by the deployment:
```
# kubectl describe po
Name:           trident-3655037810-x8l65
Namespace:      default
Node:           3-docker3/10.64.28.153
Start Time:     Tue, 06 Jun 2017 20:58:02 +0200
Labels:         app=trident.netapp.io
                pod-template-hash=3655037810
Annotations:    kubernetes.io/created-by={"kind":"SerializedReference","apiVersion":"v1","reference":{"kind":"ReplicaSet","namespace":"default","name":"trident-3655037810","uid":"10e5b6
fc-4aea-11e7-bafb-525400f4fd4c"...
Status:         Running
IP:             192.168.218.20
Controllers:    ReplicaSet/trident-3655037810
Containers:
  trident-main:
    Container ID:       docker://a219454a27c7cc6556227f889cbfaf13e429bd51f6551446d6d5b0fc4dd5ff5e
    Image:              netapp/trident:17.07.0-beta.0
```
6)	Create up to 4 volume access groups (VAG) on your SolidFire cluster with whatever names you like.  Make a note of the ID (an integer) that the cluster assigns to each for use in the next step.
7)	Copy your original solidfire `backend.json` file to `backend-vag.json` and add a new line; in my case I went for 2 VAGs (the original trident one and a newly created one) and they were assigned IDs 7 and 8:
```
diff setup/backend-vag.json setup/backend.json
8d7
<     "AccessGroups": [7, 8],
```
8)	Use the new tridentctl utility to update the backend
```
[root@3-docker1 trident-17.07.0-beta.0]# ./tridentctl create backend -f setup/backend-vag.json
+-------------------------+----------------+--------+---------+
|          NAME           | STORAGE DRIVER | ONLINE | VOLUMES |
+-------------------------+----------------+--------+---------+
| solidfire_192.168.1.190 | solidfire-san  | true   |       6 |
+-------------------------+----------------+--------+---------+
```
9)	Go in the SolidFire GUI and you will see that the volumes are now assigned to both VAGs.
10)	You can now add more hosts into the VAGs you added, up to 64 per VAG. Yippie :-)
