### ISSUE TITLE
Can't install Trident

### ISSUE THREAD

**Issue by mvineza** [NetApp/trident#241]
Installing Trident 19.0.1 fails with this error.

`FATA Install failed; could not check if Trident installer pod is present; EOF.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.`

I have the correct backend.json and kubectl is pointing to correct context. I confirm that there is no existing trident installation since this is a fresh install.

**Comment by adkerr** [comment]
@mvineza There is a known issue with installing Trident 19.01 with kubectl >= 1.14.0. The fix will be available in 19.04. You could also install kubectl 1.13 or earlier.

If you are seeing this on older versions of k8s than 1.14 please let me know

**Comment by mvineza** [comment]
Thanks @adkerr . I was able to fix the issue by using kubectl v1.13.4 instead of v.1.14.0.
