### ISSUE TITLE
Various problems with volume size option with SolidFire backend 

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#244]
* CentOS 7.2 
* Trident 19.1
* Docker CE 18.06.0-ce
* Element OS 11.0.0.781 (**SF-Demo VM**, but as far as I can tell, its release notes don't indicate it should behave differently to physical clusters)

With `-o size=500M` we are told to use 1000000000 or larger.

```
Error response from daemon: create sfBronze: VolumeDriver.Create: encountered error(s) in creating the volume: [Failed to create volume sfBronze on storage pool Bronze from backend solidfire_192.168.0.130: requested volume size (524288000 bytes) is too small; the minimum volume size is 1000000000 bytes], [Failed to create volume sfBronze on storage pool Gold from backend solidfire_192.168.0.130: requested volume size (524288000 bytes) is too small; the minimum volume size is 1000000000 bytes], [Failed to create volume sfBronze on storage pool Silver from backend solidfire_192.168.0.130: requested volume size (524288000 bytes) is too small; the minimum volume size is 1000000000 bytes]
```

But that is incorrect and should be fixed - neither 1000000000 nor (1000000000 + 1) work (note the error message is now different). 

```
[root@centos72 ~]# docker volume create -d netapp --name sfBronze1 -o type=Bronze -o size=1000000001
Error response from daemon: create sfBronze1: VolumeDriver.Create: encountered error(s) in creating the volume: [Failed to create volume sfBronze1 on storage pool Bronze from backend solidfire_192.168.0.130: device API error], [Failed to create volume sfBronze1 on storage pool Gold from backend solidfire_192.168.0.130: device API error], [Failed to create volume sfBronze1 on storage pool Silver from backend solidfire_192.168.0.130: device API error]
```

While 1000000000 doesn't work, `-o size=999M` does which means "1GiB or larger" is not correct either:

```
[root@centos72 ~]# docker volume create -d netapp --name sfBronze1 -o type=Bronze -o size=999M
sfBronze1
```

1GiB = 1073741824 bytes, so 1073741825 should work, but it doesn't. 

```
[root@centos72 ~]# docker volume create -d netapp --name sfBronze15 -o type=Bronze -o size=1073741825
Error response from daemon: create sfBronze15: VolumeDriver.Create: encountered error(s) in creating the volume: [Failed to create volume sfBronze15 on storage pool Bronze from backend solidfire_192.168.0.130: device API error], [Failed to create volume sfBronze15 on storage pool Silver from backend solidfire_192.168.0.130: device API error], [Failed to create volume sfBronze15 on storage pool Gold from backend solidfire_192.168.0.130: device API error]
```

Last but not least there's an undocumented (as far as I can tell) limit of (around) 8TiB.

```
[root@centos72 ~]# docker volume create -d netapp --name sfBronze15 -o type=Bronze -o size=8700G
Error response from daemon: create sfBronze15: VolumeDriver.Create: encountered error(s) in creating the volume: [Failed to create volume sfBronze15 on storage pool Gold from backend solidfire_192.168.0.130: device API error], [Failed to create volume sfBronze15 on storage pool Bronze from backend solidfire_192.168.0.130: device API error], [Failed to create volume sfBronze15 on storage pool Silver from backend solidfire_192.168.0.130: device API error]

[root@centos72 ~]# docker volume create -d netapp --name sfBronze15 -o type=Bronze -o size=7950G
sfBronze15

```

**Comment by adkerr** [comment]
Do you have the trident debug logs with api tracing enabled for these commands? Almost all of them failed with a device api error.

**Comment by scaleoutsean** [comment]
I've seen messages like these.

```
{
  "context": {
    "ip": "192.168.0.61",
    "user": "admin"
  },
  "error": {
    "code": 500,
    "message": "Not enough free provisionable space on a single metadata drive.",
    "name": "xSliceServiceSelectionFailed"
  },
  "method": "CreateVolume",
  "params": {
    "accountID": 3,
    "attributes": {
      "docker-name": "sfBronze7",
      "fstype": "ext4",
      "trident": "{\"version\":\"19.01.0\",\"platform\":\"docker\",\"platformVersion\":\"18.06.0-ce\",\"plugin\":\"solidfire-san\"}"
    },
    "enable512e": true,
    "name": "sfBronze7",
    "qos": {
      "burstIOPS": 400,
      "maxIOPS": 200,
      "minIOPS": 100
    },
    "requestAPIVersion": "10.0",
    "totalSize": 10737418240000
  },
  "success": false
}
```
Successfully created volumes were logged like this:

```
{
  "context": {
    "ip": "192.168.0.61",
    "user": "admin"
  },
  "method": "CreateVolume",
  "params": {
    "accountID": 3,
    "attributes": {
      "docker-name": "sfBronze15",
      "fstype": "ext4",
      "trident": "{\"version\":\"19.01.0\",\"platform\":\"docker\",\"platformVersion\":\"18.06.0-ce\",\"plugin\":\"solidfire-san\"}"
    },
    "enable512e": true,
    "name": "sfBronze15",
    "qos": {
      "burstIOPS": 400,
      "maxIOPS": 200,
      "minIOPS": 100
    },
    "requestAPIVersion": "10.0",
    "totalSize": 1073741824
  },
  "success": true
}
```

Element Demo Node Release Notes do not mention any discrepancy between the max volume size on Demo VM vs. physical appliances (if that proves to be the case I'll file another bug for it): (https://mysupport.netapp.com/tools/info/ECMLP2848232I.html?productID=62139&pcfContentID=ECMLP2848232).

I just noticed `requestAPIVersion` was 10.0. This invalidates the last point from my issue (above) - I should have set it to 11.0 to be able to specify size >8T and apart from that I should duplicate other issues on a physical appliance. 

Questions: 
a) Is it acceptable to specify volume size in bytes?
b) Can actual minimum and maximum sizes for Element OS 11 API be documented, or should we refer the user to Element OS API documentation?

**Comment by scaleoutsean** [comment]
I tried to create 8TB volume on Element Demo VM  11.0.0.781 and although it should either report the same error (not enough MD capacity) or create the volume, instead it reports `CreateVolume Failed: totalSize must be less than 107374182400 cVolumeSizeMaxLimit=107374182400`. I created an Element Demo VM issue for that.

**Comment by adkerr** [comment]
@scaleoutsean I'm working on reproducing this with a real SF system. It looks like this is a issue with how Trident is interpreting ambiguous size units vs your expectation. When no unit is given, `-o size=10`, the size will be interpreted as GiB. This is why your 1000000000 and 1000000001 failed, that size is far too large as GiB. To use bytes, append `b` to end. A similar issue is happening with `M`. Trident sees that as `MiB`. The minimum size of a SolidFire volume is 1GB, not 1GiB, so 999MiB is still large enough. If you try `999MB` you will see it fail

```
root@ubuntu:~# docker volume create -d netapp --name sfBronze3 -o type=Bronze -o size=999Mb
Error response from daemon: create sfBronze3: VolumeDriver.Create: encountered error(s) in creating the volume: [Failed to create volume sfBronze3 on storage pool Bronze from backend solidfire_10.193.156.86: requested volume size (999000000 bytes) is too small; the minimum volume size is 1000000000 bytes], [Failed to create volume sfBronze3 on storage pool Gold from backend solidfire_10.193.156.86: requested volume size (999000000 bytes) is too small; the minimum volume size is 1000000000 bytes], [Failed to create volume sfBronze3 on storage pool Silver from backend solidfire_10.193.156.86: requested volume size (999000000 bytes) is too small; the minimum volume size is 1000000000 bytes]
```

**Comment by scaleoutsean** [comment]
Oh, another Tebibytes Shmebibytes situation... 

The SolidFire API specifies the size in bytes:

http://solidfire.github.io/sdk-dotnet/help/html/T_SolidFire_Element_Api_CreateVolumeRequest.htm 

Here the default is `G` but that doesn't mean GB but GiB. Maybe this is not confusing for both ONTAP and E-Series users. Personally I see this as unnecessarily ambiguous (to assume that `G` stands for GiB rather than GB)

The SolidFire UI also defaults to G, but the other G (GB), because while the volume size is expressed in bytes, it's rounded to nearest 1MB). GiB is the next choice in drop-down list.

![image](https://user-images.githubusercontent.com/16622642/56550262-bfa20e00-65b7-11e9-95c4-3c57174ea4f1.png)

The `b` appendix isn't [documented](https://netapp-trident.readthedocs.io/en/stable-v19.01/docker/use/volumes.html#create-a-volume), so maybe that could be added to the Trident docs. 

Because the minimum volume size in G(i) is well over the minimum volume size in bytes, to me it'd make sense to read any integer as the size in bytes (e.g. 10737418240), as bytes is the default (and although in some cases (ONTAP?) both byte and MiB/MB might work, I think most people would consider for storage capacity no unit = byte unit. 
(I didn't have time to check to the source code when I was submitting the bug, but I imagine most users don't). 

Do you want to add the `b` thing to Trident docs so that I can close this? 

For the remaining issue (unable to create 8TB volume in SF-Demo VM), I'd follow up on it internally.

**Comment by adkerr** [comment]
@scaleoutsean The behavior is clearly documented in the link you provided, including the `B` suffix:

> Volume sizes are expressed as strings containing an integer value with optional units (e.g. “10G”, “20GB”, “3TiB”). If no units are specified, the default is ‘G’. Size units may be expressed either as powers of 2 (B, KiB, MiB, GiB, TiB) or powers of 10 (B, KB, MB, GB, TB). Shorthand units use powers of 2 (G = GiB, T = TiB, …).

**Comment by scaleoutsean** [comment]
True. Sorry about this - I looked at the page in a case-sensitive way... 

The other issue (unable to create large volumes) turned out to be an undocumented limitation (bug in release notes) of SF-Demo 11.0 (and earlier), so now I can close this issue.
