### ISSUE TITLE
tridentctl install fails if behind a proxy

### ISSUE THREAD

**Issue by ccdgrundhoefer** [NetApp/trident#246]
Hello,
I'm trying to install trident (with Netapp CVS on AWS as backend) on OpenShift 3.11, but the installer pod fails to connect to the API endpoint (timeout), because I need to connect via a proxy. I know that I can alter the deployment config of the main pod to pass a proxy env variable, but I can't find an option to pass a proxy to the installer pod.
Does anyone have any idea how to do this?

**Comment by clintonk** [comment]
@ccdgrundhoefer  Try passing --in-cluster=false to the ``tridentctl install``.

**Comment by ccdgrundhoefer** [comment]
I tried to do this, but it still fails after:
INFO Starting storage driver.                      backend=/setup/backend.json
WARN Error communicating with AWS REST interface. Get https://cds-aws-bundles.netapp.com:8080/version: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
FATA Install failed; could not start the storage backend driver; problem initializing storage driver 'aws-cvs': error validating aws-cvs driver. failed to read version.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

However I can curl the URL from the host system, so there must be another component I'm missing?

**Comment by clintonk** [comment]
@ccdgrundhoefer   Perhaps your proxy is interfering with communication between Trident's CVS driver and the AWS CVS API service.  We haven't tested that configuration, but you could experiment with setting an environment variable as indicated [here](https://stackoverflow.com/questions/14661511/setting-up-proxy-for-http-client) before running with --in-cluster=false.  If that lets the installer succeed, then a similar tweak to the deployment YAML might get you going.

**Comment by ccdgrundhoefer** [comment]
The environment variables are set correctly. I tried to hardcode the proxy into the **cli/api/rest.go**, but it didn't work.
I'm not a go programmer, so it might be that I made a mistake, this is what I changed (the proxy IP is obviously not the real one):
func InvokeRESTAPI(method string, reqURL string, requestBody []byte, debug bool) (*http.Response, []byte, error) {

    var request *http.Request
    var err error

    if requestBody == nil {
        request, err = http.NewRequest(method, reqURL, nil)
    } else {
        request, err = http.NewRequest(method, reqURL, bytes.NewBuffer(requestBody))
    }
    if err != nil {
        return nil, nil, err
    }

    request.Header.Set("Content-Type", "application/json")

    if debug {
        LogHTTPRequest(request, requestBody)
    }

    proxyURL, err := url.Parse("https://1.2.3.4:8080")

    if err != nil {
        panic("Can't parse URL!")
    }

    client := &http.Client{Transport: &http.Transport{Proxy: http.ProxyURL(proxyURL)}, Timeout: HTTPTimeout}
    response, err := client.Do(request)

    responseBody := []byte{}
    if err == nil {

        responseBody, err = ioutil.ReadAll(response.Body)
        response.Body.Close()

        if debug {
            LogHTTPResponse(response, responseBody)
        }
    }

    return response, responseBody, err
}

**Comment by clintonk** [comment]
@ccdgrundhoefer  The file you modified is only used by **tridentctl** inside the Trident pod to communicate with Trident's REST interface, so that won't help.  The issue is the inability of Trident's AWS CVS driver to communicate with the external AWS CVS REST interface.  I would first try to do this without modifying code...you could use `tridentctl install --generate-custom-yaml`, modify the setup/trident-deployment.yaml file to add the HTTP_PROXY environment variable to the trident-main container, and install Trident using `tridentctl install --use-custom-yaml`.  If that doesn't work, you could work through NetApp support to have this added to the Trident roadmap.
