### ISSUE TITLE
Feature Request: Provide Helm Chart for Trident

### ISSUE THREAD

**Issue by si-heger** [NetApp/trident#247]
As alternative (or replacment) for the installer it would be very useful to install Trident via Helm chart.

This would have following benefits:
- Automated Deployment instead of local installer
- Can be included into the repositories of the major K8S distributions 

E. g. I have spoken with a technical consultant from Rancher who said that it would make it much more simpler to have the synergy between NetApp & Rancher if they can tell their clients to just deploy Trident from Rancher (via Helm) if there is a pre-existing NetApp Storage System

**Comment by innergy** [comment]
We’ve made multiple passes at a Helm chart, but our chicken and egg problem with running and protecting our own etcd cluster has prevented us from coming up with a solution as elegant as our installer to date.

But there are changes afoot that should make this simple and straightforward once they come about. Stay tuned!

**Comment by clintonk** [comment]
@si-heger  We agree, and we have experimented with Helm, but the biggest hurdle is Trident's etcd persistence layer which greatly complicates the installer.  The first step towards a Helm chart is switching Trident to use CRDs instead of etcd.  That work is on the roadmap and already underway.

**Comment by si-heger** [comment]
Ok, got it! You guys are really quick. Keep up the great work!

**Comment by kodo651** [comment]
Hi!
I'm VERY interested about the progress on this! I fully appreciate the complexities involved _but_ any estimates as of when this would be available for testing/evaluation?
Cheers

**Comment by korenaren** [comment]
CRDs are planned for the 19.07 release (as Clinton mentioned, this is a pre-req for Trident Helm chart). No time commitment on this one specifically, but CRDs definitely gets us one step closer.

**Comment by si-heger** [comment]
hi guys, is there any update here? With trident 19.07 and 19.10 we should have all the ground work for this?

**Comment by korenaren** [comment]
Sorry, but no update at the moment. Even though Trident now supports CRDs, we still need to figure out how to handle the etcd->CRD migration in a Helm Chart.

**Comment by si-heger** [comment]
Ok, just to be certain. For fresh installations where we do not need to migrate data from an old Trident version (19.04 or earlier) the Helm Chart would be a solution?

**Comment by clintonk** [comment]
@si-heger I suspect that by the time we have a Helm chart, we'll be past needing to include the CRD upgrade code.  The challenge is how to handle the non-trivial differences across the range of Kubernetes versions that Trident supports (currently 1.11 - 1.16).  The best option may be for a Helm chart to install a Trident operator which encapsulates all the complicated installation logic, but building an operator will take time.

**Comment by si-heger** [comment]
Got it. Just want to give you the feedback that I am getting this question for a Helm chart quite often from different customers. So people are looking forward for this feature!

**Comment by superbrothers** [comment]
I also would like to install/upgrade Trident with declarative way (even not Helm Chart). I know to be able to get Trident manifest files with `tridentctl inlstall --generate-custom-manifests`, but sometimes `tridentctl install` has special installation logic such as etcd -> CRD migration. So, I can't decide to use the way to install with generated manifests and `kubectl apply`.

**Comment by gnarl** [comment]
With the Trident v21.01 release Helm Charts v3 are supported.
