### ISSUE TITLE
install failure due to missing metrics API

### ISSUE THREAD

**Issue by travisghansen** [NetApp/trident#251]
I've got a cluster installed with `rke` from the `rancher` team and trying to install trident results in the failure below.  The metrics server is running in the cluster, I'm unclear why that resource is need and generally what's providing it.  Any insight is appreciated.  Thanks!

```
DEBU Initialized logging.                          logLevel=debug
DEBU Running outside a pod, creating CLI-based client. 



DEBU Initialized Kubernetes CLI client.            cli=kubectl flavor=k8s namespace=default version=1.13.5
DEBU Validated installation environment.           installationNamespace=trident-test kubernetesVersion=



DEBU Deleted Kubernetes configmap.                 label="app=trident-installer.netapp.io" namespace=trident-test
DEBU Namespace exists.                             namespace=trident-test
DEBU Deleted Kubernetes object by YAML.           
DEBU Deleted installer cluster role binding.      



DEBU Deleted Kubernetes object by YAML.           
DEBU Deleted installer cluster role.              
DEBU Deleted Kubernetes object by YAML.           
DEBU Deleted installer service account.           
DEBU Created Kubernetes object by YAML.           
INFO Created installer service account.            serviceaccount=trident-installer
INFO Waiting for object to be created.             objectName=clusterRole
DEBU Created Kubernetes object by YAML.           
INFO Created installer cluster role.               clusterrole=trident-installer
INFO Waiting for object to be created.             objectName=clusterRoleBinding



DEBU Created Kubernetes object by YAML.           
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
DEBU Created Kubernetes configmap from directory.  label="app=trident-installer.netapp.io" name=trident-installer namespace=trident-test path=/home/ansible/rke/trident-installer/setup
INFO Created installer configmap.                  configmap=trident-installer
INFO Waiting for object to be created.             objectName=installerPod
DEBU Created Kubernetes object by YAML.           
INFO Created installer pod.                        pod=trident-installer
INFO Waiting for Trident installer pod to start.  







DEBU Pod started.                                  phase=Failed
INFO Trident installer pod started.                namespace=trident-test pod=trident-installer
DEBU Getting logs.                                 cmd="kubectl --namespace=trident-test logs trident-installer -f"
DEBU Initialized logging.                          logLevel=debug
DEBU Running in a pod, creating API-based client.  namespace=trident-test
WARN Could not get server resources, defaulting to Kubernetes flavor.  error="unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: Unauthorized"
DEBU Initialized Kubernetes API client.            cli=kubectl flavor=k8s namespace=trident-test version=v1.13.5
DEBU Validated installation environment.           installationNamespace=trident-test kubernetesVersion=v1.13.5
DEBU Parsed requested volume size.                 quantity=2Gi
DEBU Namespace exists.                             namespace=trident-test
DEBU PVC already exists.                           namespace=trident-test phase=Bound pvc=trident
DEBU PV already exists.                            phase=Bound pv=trident
DEBU PV exists, skipping storage driver check.    
INFO Starting Trident installation.                namespace=trident-test
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRoleBinding version=v1
ERRO Could not get dynamic resource, failed to list server resources.  error="unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: Unauthorized" group=rbac.authorization.k8s.io kind=ClusterRoleBinding version=v1
WARN Could not delete cluster role binding.        error="unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: Unauthorized"
DEBU Parsed YAML into unstructured object.         group=rbac.authorization.k8s.io kind=ClusterRole version=v1
ERRO Could not get dynamic resource, failed to list server resources.  error="unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: Unauthorized" group=rbac.authorization.k8s.io kind=ClusterRole version=v1
WARN Could not delete cluster role.                error="unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: Unauthorized"
DEBU Parsed YAML into unstructured object.         group= kind=ServiceAccount version=v1
ERRO Could not get dynamic resource, failed to list server resources.  error="unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: Unauthorized" group= kind=ServiceAccount version=v1
WARN Could not delete service account.             error="unable to retrieve the complete list of server APIs: custom.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, external.metrics.k8s.io/v1beta1: the server is currently unable to handle the request, metrics.k8s.io/v1beta1: Unauthorized"
FATA Install failed; could not remove one or more previous Trident artifacts; please delete them manually and try again.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.
```

**Comment by clintonk** [comment]
Hi, @travisghansen We haven't seen this issue.  Assuming you are running the `tridentctl install` as the cluster admin, can you add `--in-cluster=false` and let us know the result?

**Comment by alarmdev** [comment]
it is going in the loop after adding --in-cluster=false option.

 ./tridentctl install -n trident-test --k8s-timeout 250m -d --in-cluster=false
DEBU Initialized logging.                          logLevel=debug
DEBU Running outside a pod, creating CLI-based client. 
DEBU Initialized Kubernetes CLI client.            cli=kubectl flavor=k8s namespace=default version=1.13.5
DEBU Validated installation environment.           installationNamespace=trident-test kubernetesVersion=
DEBU Parsed requested volume size.                 quantity=2Gi
DEBU Namespace exists.                             namespace=trident-test
DEBU PVC already exists.                           namespace=trident-test phase=Bound pvc=trident
DEBU PV already exists.                            phase=Bound pv=trident
DEBU PV exists, skipping storage driver check.    
INFO Starting Trident installation.                namespace=trident-test
DEBU Deleted Kubernetes object by YAML.           
DEBU Deleted cluster role binding.                
DEBU Deleted Kubernetes object by YAML.           
DEBU Deleted cluster role.                        
DEBU Deleted Kubernetes object by YAML.           
DEBU Deleted service account.                     
DEBU Created Kubernetes object by YAML.           
INFO Created service account.                     
DEBU Created Kubernetes object by YAML.           
INFO Created cluster role.                        
DEBU Created Kubernetes object by YAML.           
INFO Created cluster role binding.                
DEBU Created Kubernetes object by YAML.           
INFO Created Trident deployment.                  
INFO Waiting for Trident pod to start.            
DEBU Trident pod not yet running, waiting.         increment=552.330144ms
DEBU Trident pod not yet running, waiting.         increment=1.080381816s
DEBU Trident pod not yet running, waiting.         increment=1.31013006s

**Comment by alarmdev** [comment]
Here's the install command used:

> ./tridentctl install -n trident-test --k8s-timeout 250m -d --in-cluster=false

**Comment by clintonk** [comment]
OK, that's progress.  This is a permissions issue which you may be able to work around.  You should be able to use `tridentctl install --generate-custom-yaml` to populate several files in the setup directory.  Modify the file setup/trident-clusterrole.yaml to add the missing permissions, then run `tridentctl install --in-cluster=false --use-custom-yaml`.

**Comment by alarmdev** [comment]
Thanks @clintonk  will give it a try and post the result, hope this get it going as needed.

**Comment by alarmdev** [comment]
Error from server (BadRequest): a container name must be specified for pod trident-79447d6b94-9ttgv, choose one of: [trident-main etcd]

**Comment by travisghansen** [comment]
@alarmdev what's the command for that?  If you're trying to do `logs` and the pod has more than 1 container then you'll need to specify..

**Comment by alarmdev** [comment]
@clintonk  most of the issues are resolved after updating cluster roles, I can see PV and PVCs are created and bound successfully however the "Trident" pod is not coming up and there is no log.

**Comment by alarmdev** [comment]
trident       pod/trident-5dfb45466-t4x6c                0/2     ContainerCreating   0          7m
trident       pod/trident-installer                      1/1     Running             0          7m

**Comment by alarmdev** [comment]
Here's latest installer log.

./tridentctl install -n trident --k8s-timeout 250m
INFO Created installer service account.            serviceaccount=trident-installer
INFO Created installer cluster role.               clusterrole=trident-installer
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
INFO Created installer configmap.                  configmap=trident-installer
INFO Created installer pod.                        pod=trident-installer
INFO Waiting for Trident installer pod to start.  
INFO Trident installer pod started.                namespace=trident pod=trident-installer
INFO Starting storage driver.                      backend=/setup/backend.json
WARN Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005 
INFO Storage driver loaded.                        driver=ontap-nas
INFO Starting Trident installation.                namespace=trident
INFO Created service account.                     
INFO Created cluster role.                        
INFO Created cluster role binding.                
INFO Created PVC.                                 
INFO Created PV.                                   pv=trident
INFO Waiting for PVC to be bound.                  pvc=trident
INFO Created Trident deployment.                  
INFO Waiting for Trident pod to start.

**Comment by clintonk** [comment]
@alarmdev You can use `kubectl describe` on the Trident pod to see why the containers within might not be starting.  Your latest doesn't show that you are using custom YAML, so I'm not clear on which cluster role you modified (the Trident installer always replaces the RBAC objects).  By combining `--use-custom-yaml` with `--in-cluster=false`, I think you should be able to work around this permissions issue.

**Comment by alarmdev** [comment]
I created RBACs manually as i have few other stuff in there. But i can certainly use that option and send you the pod description. Thanks @clintonk

**Comment by alarmdev** [comment]
WARN Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005 

  Warning  FailedMount  39s    kubelet, 172.28.64.69  Unable to mount volumes for pod "trident-8549f65cf5-cnn79_trident(93246e31-7bdc-11e9-a698-005056a65c02)": timeout expired waiting for volumes to attach or mount for pod "trident"/"trident-8549f65cf5-cnn79". list of unmounted volumes=[etcd-vol]. list of unattached volumes=[etcd-vol trident-token-c2nrn]
  Warning  FailedMount  32s    kubelet, 172.28.64.69  MountVolume.SetUp failed for volume "trident" : mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t nfs 172.28.49.47:/HQ00Trident_trident /var/lib/kubelet/pods/93246e31-7bdc-11e9-a698-005056a65c02/volumes/kubernetes.io~nfs/trident
Output: mount.nfs: Connection timed out

**Comment by alarmdev** [comment]
I think that would something to do with NetApp mount?

**Comment by alarmdev** [comment]
Command ran to run installer:

./tridentctl install -n trident --k8s-timeout 250m --use-custom-yaml --in-cluster=false

**Comment by clintonk** [comment]
@alarmdev You're close.  The 'exit status 32' is a generic NFS error.  Did you install the NFS client (nfs-utils or nfs-common) on your host(s)?  If you can get to the point where you can manually mount the volume that Trident's installer created, then the installation should succeed.

https://netapp-trident.readthedocs.io/en/stable-v19.04/kubernetes/operations/tasks/worker.html

**Comment by alarmdev** [comment]
@clintonk  yes, I have installed all required binaries for NFS client on all of my Linux machines that are part of k8s cluster but i think we are missing something on NetApp backend side that we are working with our Cloud Ops team. 
I did try manually mounting -t nfs but it fails on connection so something blocking between nodes and nfs for sure. Thanks again for your help.

**Comment by travisghansen** [comment]
@alarmdev the node you're running the install from may not be on the allowed network(s).

**Comment by alarmdev** [comment]
nfs access does not work from any of the node including the install node, Cloud team is working on it.

**Comment by alarmdev** [comment]
@clintonk we got it working. Thanks for your help.

**Comment by clintonk** [comment]
@alarmdev  Good to hear.  Would you mind sharing what you had to do to enable NFS access, as well as the change you had to make to the cluster role?  The former might be a candidate for our FAQ, and the latter is something we could integrate into the Trident installer.

**Comment by korenaren** [comment]
@alarmdev @travisghansen @clintonk Any additional comments on this one/things we can do to Trident to prevent this situation in the future (whether that be improved docs, or improved installer)? If not, I will close this issue.

**Comment by travisghansen** [comment]
Please close. I've since updated to 19.07 using csi and not ran into this issue at all.

Thanks!

**Comment by alarmdev** [comment]
Please close the ticket


Sent from Yahoo Mail for iPhone


On Monday, August 19, 2019, 10:32 AM, Travis Glenn Hansen <notifications@github.com> wrote:


Please close. I've since updated to 19.07 using csi and not ran into this issue at all.

Thanks!

**Comment by korenaren** [comment]
Thanks for the response! Closing this issue.
