### ISSUE TITLE
support for export list creation and manipulation via tridentctl

### ISSUE THREAD

**Issue by on4tux** [NetApp/trident#252]
We have multiple dedicated k8s clusters which we setup per project on a shared ONTAP environment. As we will recycle the dedicated worker nodes on a regular base, we need on the fly automation for creating and manipulating (add/remove IPs) export lists. Can you add functionality that either create an export list with the given IPs or add/removes them from an existing one?

**Comment by rajshrivastava22** [comment]
Hi Team, We also have a very large setup and we need automated way via Trident to create export policies or add/remove IPs from existing ones. Kindly suggest when this can be added asap

**Comment by korenaren** [comment]
We don't intend to enable tridentctl as a general purpose ONTAP management tool. You should use other automation/configuration management tools, such as Ansible, for things like this.

**Comment by superbrothers** [comment]
@korenaren

We have the same request for igroup in addition to export-policy. We manage more than 400 Kubernetes clusters (total about 6000 nodes), and all of the worker nodes are frequently recreated for upgrading, fixing vulnerabilities, and so on. At that time, all nodes' IP addresses and iqn are renewed. As a result, it is impossible for humans to manage export-policy and igroup. Futhermore, cluster autoscaler increases nodes automatically. If do not update export-policy or igroup each time, volumes on a new node will fail to mount.

For these cases, it is appropriate that the Kubernetes controller, that is, Trident, handles export-policy and igroup.

Would you please reconsider this request?

**Comment by korenaren** [comment]
Yes, we will reconsider this.

**Comment by gnarl** [comment]
This enhancement was added in the [Trident 20.04](https://github.com/NetApp/trident/blob/master/CHANGELOG.md) release.
