### ISSUE TITLE
Additional empty-name backend might result in unknown backend state

### ISSUE THREAD

**Issue by ybizeul** [NetApp/trident#253]
For some reason I'm getting an additional backend, with an empty name :

```
bash-4.4# curl -s -S localhost:8000/trident/v1/backend
{"backends":["ontap-economy","cluster1",""]}
```

I'm thinking it might be causing an issue with the output of my regular backend listing with `tridentctl`, and the status of one of them (unknown) :
```
yann$ tridentctl get backend
+---------------+-------------------+---------+---------+
|     NAME      |  STORAGE DRIVER   |  STATE  | VOLUMES |
+---------------+-------------------+---------+---------+
| cluster1      | ontap-nas         | unknown |       3 |
| ontap-economy | ontap-nas-economy | online  |       1 |
+---------------+-------------------+---------+---------+
```

**Comment by korenaren** [comment]
What version are you using? Can you try it with 19.04.1 or later? We think this is fixed.

**Comment by ybizeul** [comment]
It has been a while I don’t think I have that instance anymore. Thanks !
