### ISSUE TITLE
PVC switches to read only when running out of free space

### ISSUE THREAD

**Issue by xriser** [NetApp/trident#257]
When running out of free space, pvc switches to readonly mode
How to reproduce: 
Create 4Gb PVC
Mount to pod, then try to write to mounted pvc more than 4Gb (with dd, for example)
pvc switches to R/O mode. Can't delete data from it. Can't remount.

**Comment by scaleoutsean** [comment]
Have you tried to read-only remount?

**Comment by korenaren** [comment]
@xriser is this ONTAP, Element, CVS, (which driver are you using)? NFS or iSCSI?

**Comment by nareshkumargunjalli** [comment]
@xriser  can you please answer to the question asked by @korenaren ?

**Comment by xriser** [comment]
ONTAP, iSCSI

**Comment by xriser** [comment]
> Have you tried to read-only remount?

no

**Comment by innergy** [comment]
Is space allocation enabled on the LUN? This is most likely the issue reported in #135.

**Comment by korenaren** [comment]
Closing, as this is most likely fixed (#135) in 19.07.
