### ISSUE TITLE
tridentctl broken since 19.04.0

### ISSUE THREAD

**Issue by Gregoonet** [NetApp/trident#258]
Hey guys,

After upgrading from version v18.10.0 to v19.04.1, I found out that the tridentctl is broken for me.
Each command I send (except for the help) returns 'Error: EOF'.
Server side part seems to be working as expected though.

I rolled back to see if it was my kube config that was broken or anything but it is still working.
I checked all relevant versions for me and got this breakdown (using './tridentctl version' command):
- v18.10.0 -> OK
- v19.01.0 -> OK
- v19.04.0-beta.1 -> OK
- v19.04.0 -> Error: EOF
- v19.04.1 -> Error: EOF

FYI, my Kube version is 1.13.5.

Thanks in advance for your help :)

Greg

**Comment by adkerr** [comment]
What is the output of `tridentctl version -d`?

**Comment by adkerr** [comment]
Also `tridentctl version --client`

**Comment by Gregoonet** [comment]
Here are the results:

$ ./tridentctl version --client
+----------------+
| CLIENT VERSION |
+----------------+
| 19.04.1        |
+----------------+


$ ./tridentctl version -d
Error: EOF

**Comment by adkerr** [comment]
The debug output seems unusually terse. Is that really the only thing you get returned? I would expect something more like this:

```shell
$ tridentctl version -d
Operating mode = direct, Server = localhost:9000
Trident URL: http://localhost:9000/trident/v1
--------------------------------------------------------------------------------
Request Method: GET
Request URL: http://localhost:9000/trident/v1/version
Request headers: map[Content-Type:[application/json]]
Request body: 
................................................................................
Response status: 200 OK
Response headers: map[Content-Length:[37] Content-Type:[application/json; charset=UTF-8] Date:[Thu, 20 Jun 2019 14:24:53 GMT]]
Response body: {"version":"19.04.0-custom+unknown"}

================================================================================
+------------------------+------------------------+
|     SERVER VERSION     |     CLIENT VERSION     |
+------------------------+------------------------+
| 19.04.0-custom+unknown | 19.04.0-custom+unknown |
+------------------------+------------------------+
```

**Comment by Gregoonet** [comment]
If I use the tridentctl from v19.04.0-beta.1, I get this result:

➜  trident git:(master) ✗ ./tridentctl version -d
Operating mode = tunnel, Trident pod = trident-7f78d8b6cf-xstfv, Namespace = kube-system, CLI = kubectl
Invoking tunneled command: kubectl exec trident-7f78d8b6cf-xstfv -n kube-system -c trident-main -- tridentctl -s 127.0.0.1:8000 version -o json
Version JSON: {
  "server": {
    "version": "19.04.1",
    "majorVersion": 19,
    "minorVersion": 4,
    "patchVersion": 1,
    "preRelease": "",
    "buildMetadata": "",
    "apiVersion": "1"
  },
  "client": {
    "version": "19.04.1",
    "majorVersion": 19,
    "minorVersion": 4,
    "patchVersion": 1,
    "preRelease": "",
    "buildMetadata": "",
    "apiVersion": "1"
  }
}

+----------------+---------------------------------------------------------+
| SERVER VERSION |                     CLIENT VERSION                      |
+----------------+---------------------------------------------------------+
| 19.04.1        | 19.04.0-beta.1+dfd48cac9bd2c4aac665b6275257695c22308d6a |
+----------------+---------------------------------------------------------+

**Comment by clintonk** [comment]
@Gregoonet  We haven't seen this issue.  Would you please open a support case?  The support team can help us reproduce this.

**Comment by pyves06** [comment]
support case created number : 2007936681

**Comment by Gregoonet** [comment]
Hey guys,

I actually found out that my problem was not on tridentctl, but on the version of kubectl I was using.
The version I used was 1.8.2, and after switching to a more recent version (1.13.5), tridentctl came back to life.
Now all my commands work perfectly.

I think that a warning in the documentation, with a version table for minimum kubectl version for each tridentctl release, would be great.

So thanks a lot for all your help.

Greg

**Comment by clintonk** [comment]
Hi, @Gregoonet.  Trident roughly aims to support the previous year or so of Kubernetes releases, so a kubectl mismatch with Trident is less likely.

The real issue is the kubectl mismatch with Kubernetes, which is covered in the Kubernetes [docs](https://kubernetes.io/docs/tasks/tools/install-kubectl/#before-you-begin) and probably would have led to additional problems going forward:

"You must use a kubectl version that is within one minor version difference of your cluster. For example, a v1.2 client should work with v1.1, v1.2, and v1.3 master. Using the latest version of kubectl helps avoid unforeseen issues."

Thanks for letting us know the resolution!

**Comment by ledroide** [comment]
Hello @clintonk 
I have the same issue `Error: EOF`.
```bash
$ tridentctl version --client -o json
```
```json
{
  "client": {
    "version": "23.07.1",
    "majorVersion": 23,
    "minorVersion": 7,
    "patchVersion": 1,
    "preRelease": "",
    "buildMetadata": "",
    "apiVersion": "1",
    "goVersion": "go1.20.7"
  }
}
```
```bash
$ tridentctl -n trident get backend 
Error: EOF

$ tridentctl -n trident --kubeconfig ~/.kube/config version
Error: EOF
```
My kubectl matches the cluster version - which is v1.27.4.
Any idea ?

**Comment by clintonk** [comment]
Hi, @ledroide.  Do the Trident controller logs show anything unusual?  Any clues if you add the `--debug` switch?  We haven't seen an issue like this in a long time, so you might want to open a support case.

**Comment by ledroide** [comment]
Hello @clintonk 
The trident controller and everything running in our clusters run fine. It is basically a binary or dependency / library issue on some workstations, and I cannot find what could be missing there.

Here is tridentctl installed from the trident-installer-23.07.1.tar.gz file, from this repo assets : 
```bash 
$ /usr/local/bin/tridentctl version --debug 
Error: EOF

$ file /usr/local/bin/tridentctl 
/usr/local/bin/tridentctl: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, Go BuildID=mo8oCl_b0U8zO_01IvGL/iqE8gwF2NIlwLT1mEIWX/g-Y7SWiKxN3Uk6aD-SLA/Jf1IeCn1kxBBxmDWZ4X1, stripped

$ md5sum /usr/local/bin/tridentctl
11c661ecc83023a140249051739d1326  /usr/local/bin/tridentctl
````

Here is tridentctl from inside the container docker.io/netapp/trident:23.07.1 running in a cluster :  
```bash 
$ kubectl exec -t -n trident $(kubectl get pods -n trident -l app=controller.csi.trident.netapp.io -o jsonpath="{.items[].metadata.name}") -c trident-main -- tridentctl -s 127.0.0.1:8000 version --debug 
time="2023-09-21T13:20:11Z" level=debug msg="--------------------------------------------------------------------------------\n"
time="2023-09-21T13:20:11Z" level=debug msg="Request Method: GET\n"
time="2023-09-21T13:20:11Z" level=debug msg="Request URL: http://127.0.0.1:8000/trident/v1/version\n"
time="2023-09-21T13:20:11Z" level=debug msg="Request headers: map[Content-Type:[application/json]]\n"
time="2023-09-21T13:20:11Z" level=debug msg="Request body: \n"
time="2023-09-21T13:20:11Z" level=debug msg="................................................................................\n"
Operating mode = direct, Server = 127.0.0.1:8000, Autosuport server = 127.0.0.1:8003
Trident URL: http://127.0.0.1:8000/trident/v1
time="2023-09-21T13:20:11Z" level=debug msg="Response status: 200 OK\n"
time="2023-09-21T13:20:11Z" level=debug msg="Response headers: map[Content-Length:[44] Content-Type:[application/json; charset=UTF-8] Date:[Thu, 21 Sep 2023 13:20:11 GMT]]\n"
time="2023-09-21T13:20:11Z" level=debug msg="Response body: {\"version\":\"23.07.1\",\"goVersion\":\"go1.20.7\"}\n"
time="2023-09-21T13:20:11Z" level=debug msg="================================================================================\n"
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 23.07.1        | 23.07.1        |
+----------------+----------------+
````
