### ISSUE TITLE
ONTAP NAS Volume name is limited to 64 characters #2

### ISSUE THREAD

**Issue by dxlr8r** [NetApp/trident#260]
This is a follow up to: 

https://github.com/NetApp/trident/issues/174

For E-Series and CVS you generate a random internal name. One should think it should be possible to do this for the ontap-nas-economy-driver as well? 

I've had issues with deployments using the operator and Ansible Service Broker frameworks, and the workarounds are not nice.

**Comment by korenaren** [comment]
This should not be an issue with the 19.07 CSI driver, as long as your storage prefix is not longer than 24 characters. Does that work for you?

**Comment by dxlr8r** [comment]
According to the change log: 

> Kubernetes: Implemented CSI Trident (optional for Kubernetes 1.13, exclusive for Kubernetes 1.14+).

We currently run Kubernetes 1.11 (OpenShift 3.11) on all our environments, so that will not work for us at the moment.
