### ISSUE TITLE
Resize of PV from older version of trident

### ISSUE THREAD

**Issue by madhua036** [NetApp/trident#263]
Currently on the k8s platform, we are using trident 18.07 version and in process of migrating to 19.01 . Testing the feature of resize on this. Is there a way the PVC's that are created in 18.07 version can use the resize feature after migrating to 19.01? we are on k8s 1.13 version.

**Comment by korenaren** [comment]
Hi @madhua036 - Our Slack team (#containers channel on netapppub.slack.com) would be a much better place to pose this question. Or if it gets more complicated, opening a NetApp Support case. If we/you determine this is an actual issue that needs code changes (bug or feature request), we can reopen this issue.
