### ISSUE TITLE
Proper error message required when importing(no-manage flag) a volume with no junction-path fails 

### ISSUE THREAD

**Issue by jacobjohnanda** [NetApp/trident#266]
ISSUE:-
Trident should give a  proper error message when importing a volume with no junction-path fails with the no-manage flag.
Currently it gives the following error message "command terminated with exit code 137"

SETUP:-
K8s:- 1.14
Trident:- 19.07
RHEL7.5

LOGS:-

[root@rhel3 trident-installer]# ./tridentctl import volume BackendForNAS importvolume_no_manage -f /root/k8s/pvc-import-nomanage.yaml --no-manage -n trident
**command terminated with exit code 137**

[root@rhel3 trident-installer]# kg pvc
NAME                          STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
persistent-volume-claim-nas   Bound     pvc-587281ba-50b1-485a-a3e9-a1c77d34ab7d   5Gi        RWO            storage-class-nas   7h32m
pvc-from-snap                 Bound     pvc-10f67c75-2622-44af-86b5-20b69cdfe2b7   3Gi        RWO            storage-class-nas   4h46m
pvc-nas                       Bound     pvc-347ca0d1-ed52-415c-96fc-3d8f60afde92   2Gi        RWO            storage-class-nas   4h2m
pvc-volumeimport-manage       Bound     pvc-caa0e328-c0f9-413f-9c2e-1651644d8266   2Gi        RWO            storage-class-nas   15m
pvc-volumeimport-nomanage     Pending                                                                        storage-class-nas   2m10s
[root@rhel3 trident-installer]# kd pvc pvc-volumeimport-nomanage
Name:          pvc-volumeimport-nomanage
Namespace:     default
StorageClass:  storage-class-nas
Status:        Pending
Volume:
Labels:        <none>
Annotations:   trident.netapp.io/importBackendUUID: bcd8a3d5-2953-41f8-9cf5-a47628052e32
               trident.netapp.io/importOriginalName: importvolume_no_manage
               trident.netapp.io/notManaged: true
               volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:
Access Modes:
VolumeMode:    Filesystem
Mounted By:    <none>
Events:
  Type     Reason                Age                    From                                                                                     Message
  ----     ------                ----                   ----                                                                                     -------
  Normal   Provisioning          2m34s (x5 over 2m49s)  csi.trident.netapp.io_trident-csi-5f8b854b87-d86l2_d22216f1-ba9f-11e9-b898-0271fd008906  External provisioner is provisioning volume for claim "default/pvc-volumeimport-nomanage"
  Normal   ProvisioningFailed    2m34s (x5 over 2m49s)  csi.trident.netapp.io                                                                    failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Warning  ProvisioningFailed    2m34s (x5 over 2m49s)  csi.trident.netapp.io_trident-csi-5f8b854b87-d86l2_d22216f1-ba9f-11e9-b898-0271fd008906  failed to provision volume with StorageClass "storage-class-nas": rpc error: code = Unknown desc = failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Warning  ProvisioningFailed    79s (x7 over 2m23s)    csi.trident.netapp.io_trident-csi-5f8b854b87-6szjs_fd77268d-ba9f-11e9-89e4-020cb7d22f4c  failed to provision volume with StorageClass "storage-class-nas": rpc error: code = Unknown desc = failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Normal   Provisioning          79s (x7 over 2m23s)    csi.trident.netapp.io_trident-csi-5f8b854b87-6szjs_fd77268d-ba9f-11e9-89e4-020cb7d22f4c  External provisioner is provisioning volume for claim "default/pvc-volumeimport-nomanage"
  Normal   ProvisioningFailed    79s (x7 over 2m23s)    csi.trident.netapp.io                                                                    failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Warning  ProvisioningFailed    10s (x7 over 73s)      csi.trident.netapp.io_trident-csi-5f8b854b87-fmsvj_26c9b6c8-baa0-11e9-b52d-1affc5688d82  failed to provision volume with StorageClass "storage-class-nas": rpc error: code = Unknown desc = failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Normal   Provisioning          10s (x7 over 73s)      csi.trident.netapp.io_trident-csi-5f8b854b87-fmsvj_26c9b6c8-baa0-11e9-b52d-1affc5688d82  External provisioner is provisioning volume for claim "default/pvc-volumeimport-nomanage"
  Normal   ProvisioningFailed    10s (x7 over 73s)      csi.trident.netapp.io                                                                    failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Normal   ExternalProvisioning  5s (x12 over 2m49s)    persistentvolume-controller                                                              waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator
  Normal   ProvisioningFailed    2s (x2 over 3s)        csi.trident.netapp.io                                                                    failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Warning  ProvisioningFailed    2s (x2 over 3s)        csi.trident.netapp.io_trident-csi-5f8b854b87-qcfgl_50e76294-baa0-11e9-9af0-9297337c0be8  failed to provision volume with StorageClass "storage-class-nas": rpc error: code = Unknown desc = failed to import volume importvolume_no_manage on backend bcd8a3d5-2953-41f8-9cf5-a47628052e32: driver import volume failed: junction path is not set for volume importvolume_no_manage
  Normal   Provisioning          0s (x3 over 3s)        csi.trident.netapp.io_trident-csi-5f8b854b87-qcfgl_50e76294-baa0-11e9-9af0-9297337c0be8  External provisioner is provisioning volume for claim "default/pvc-volumeimport-nomanage"

**Comment by vasum0406** [comment]
This issue has been fixed in 24.06 release
