### ISSUE TITLE
Node-CSI driver terminating

### ISSUE THREAD

**Issue by jacobjohnanda** [NetApp/trident#267]
ISSUE:-
After  doing some volume operations( importing, snapshotting etc..) the Node-CSI driver  went into terminating state.

**"Error deregistering node rhel2 with controller; could not log into the Trident CSI Controller: error communicating with Trident CSI Controller; Delete https://trident-csi:34571/trident/v1/node/rhel2: dial tcp 10.100.69.32:34571: connect: connection refused"****

[root@rhel3 ~]# kubectl get pod -n trident
NAME                           READY   STATUS        RESTARTS   AGE
trident-csi-5f8b854b87-jdmmh   4/4     Running       0          2d10h
trident-csi-hfw4d              1/2     Terminating   0          2d21h
trident-csi-nzlg4              2/2     Running       14         2d21h

LOGS:-
**[root@rhel3 ~]# kubectl logs trident-csi-hfw4d -n trident -c trident-main**
time="2019-08-09T15:16:52Z" level=debug msg=Environment PATH="/netapp:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
time="2019-08-09T15:16:52Z" level=debug msg=Environment HOSTNAME=rhel2
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBE_NODE_NAME=rhel2
time="2019-08-09T15:16:52Z" level=debug msg=Environment CSI_ENDPOINT="unix://plugin/csi.sock"
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_CSI_PORT="tcp://10.100.69.32:34571"
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_PORT_443_TCP="tcp://10.96.0.1:443"
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_PORT_443_TCP_PROTO=tcp
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_CSI_PORT_34571_TCP_PROTO=tcp
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_CSI_PORT_34571_TCP_ADDR=10.100.69.32
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_PORT="tcp://10.96.0.1:443"
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_PORT_443_TCP_PORT=443
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_CSI_SERVICE_PORT=34571
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_SERVICE_PORT_HTTPS=443
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_CSI_SERVICE_HOST=10.100.69.32
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_CSI_PORT_34571_TCP="tcp://10.100.69.32:34571"
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_CSI_PORT_34571_TCP_PORT=34571
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_SERVICE_HOST=10.96.0.1
time="2019-08-09T15:16:52Z" level=debug msg=Environment KUBERNETES_SERVICE_PORT=443
time="2019-08-09T15:16:52Z" level=debug msg=Environment PORT=8000
time="2019-08-09T15:16:52Z" level=debug msg=Environment BIN=trident_orchestrator
time="2019-08-09T15:16:52Z" level=debug msg=Environment CLI_BIN=tridentctl
time="2019-08-09T15:16:52Z" level=debug msg=Environment ETCDV3="http://localhost:8001"
time="2019-08-09T15:16:52Z" level=debug msg=Environment K8S=
time="2019-08-09T15:16:52Z" level=debug msg=Environment TRIDENT_IP=localhost
time="2019-08-09T15:16:52Z" level=debug msg=Environment HOME=/root
time="2019-08-09T15:16:52Z" level=info msg="Running Trident storage orchestrator." binary=/usr/local/bin/trident_orchestrator build_time="Wed Jul 31 14:23:00 UTC 2019" version=19.07.0
time="2019-08-09T15:16:52Z" level=debug msg=Flag name=csi_endpoint value="unix://plugin/csi.sock"
time="2019-08-09T15:16:52Z" level=debug msg=Flag name=csi_node_name value=rhel2
time="2019-08-09T15:16:52Z" level=debug msg=Flag name=csi_role value=node
time="2019-08-09T15:16:52Z" level=debug msg=Flag name=debug value=true
time="2019-08-09T15:16:52Z" level=debug msg=Flag name=no_persistence value=true
time="2019-08-09T15:16:52Z" level=debug msg=Flag name=rest value=false
time="2019-08-09T15:16:52Z" level=debug msg="Trident is configured with an in-memory store client."
time="2019-08-09T15:16:52Z" level=info msg="Initializing plain CSI helper frontend."
time="2019-08-09T15:16:52Z" level=info msg="Added frontend." name=plain_csi_helper
time="2019-08-09T15:16:52Z" level=info msg="Initializing CSI frontend." name=rhel2 version=19.07.0
time="2019-08-09T15:16:52Z" level=info msg="Enabling node service capability." capability=STAGE_UNSTAGE_VOLUME
time="2019-08-09T15:16:52Z" level=info msg="Enabling volume access mode." mode=SINGLE_NODE_WRITER
time="2019-08-09T15:16:52Z" level=info msg="Enabling volume access mode." mode=SINGLE_NODE_READER_ONLY
time="2019-08-09T15:16:52Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_READER_ONLY
time="2019-08-09T15:16:52Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_SINGLE_WRITER
time="2019-08-09T15:16:52Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_MULTI_WRITER
time="2019-08-09T15:16:52Z" level=info msg="Added frontend." name=csi
time="2019-08-09T15:16:52Z" level=warning msg="Couldn't retrieve volume transaction logs: Unable to find key"
time="2019-08-09T15:16:52Z" level=info msg="Trident bootstrapped successfully."
time="2019-08-09T15:16:52Z" level=info msg="Activating plain CSI helper frontend."
time="2019-08-09T15:16:52Z" level=info msg="Activating CSI frontend."
time="2019-08-09T15:16:52Z" level=debug msg=">>>> osutils.GetInitiatorIqns"
time="2019-08-09T15:16:52Z" level=debug msg=">>>> osutils.execCommand." args="[/etc/iscsi/initiatorname.iscsi]" command=cat
time="2019-08-09T15:16:52Z" level=info msg="Listening for GRPC connections." name=/plugin/csi.sock net=unix
time="2019-08-09T15:16:52Z" level=debug msg="Registered CSI identity server."
time="2019-08-09T15:16:52Z" level=debug msg="Registered CSI controller server."
time="2019-08-09T15:16:52Z" level=debug msg="Registered CSI node server."
time="2019-08-09T15:16:52Z" level=debug msg="<<<< osutils.execCommand." command=cat error="<nil>" output="InitiatorName=iqn.1994-05.com.redhat:rhel2.demo.netapp.com"
time="2019-08-09T15:16:52Z" level=debug msg="<<<< osutils.GetInitiatorIqns"
time="2019-08-09T15:16:52Z" level=debug msg="\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\nGET https://trident-csi:34571/trident/v1/node\nHeaders: map[Content-Type:[application/json]]\nBody: <nil>\n--------------------------------------------------------------------------------"
time="2019-08-09T15:16:52Z" level=debug msg="\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\**nStatus: 503 Service Unavailable\nHeaders: map[Content-Length:[71] Content-Type:[application/json; charset=UTF-8] Date:[Fri, 09 Aug 2019 15:16:52 GMT]]\nBody: {\n  \"nodes\": [],\n  \"error\": \"Trident is initializing, please try again later\"**\n}\n\n================================================================================"
time="2019-08-09T15:16:52Z" level=debug msg="Controller not yet ready, waiting." increment=1.085508515s
time="2019-08-09T15:16:53Z" level=debug msg="\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\nGET https://trident-csi:34571/trident/v1/node\nHeaders: map[Content-Type:[application/json]]\nBody: <nil>\n--------------------------------------------------------------------------------"
time="2019-08-09T15:17:01Z" level=debug msg="\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\nStatus: 200 OK\nHeaders: map[Content-Length:[28] Content-Type:[application/json; charset=UTF-8] Date:[Fri, 09 Aug 2019 15:17:00 GMT]]\nBody: {\n  \"nodes\": [\n    \"rhel1\",\n    \"rhel2\"\n  ]\n}\n\n================================================================================"
time="2019-08-09T15:17:01Z" level=debug msg="Communication with controller established." node=rhel2
time="2019-08-09T15:17:01Z" level=debug msg="\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\nPUT https://trident-csi:34571/trident/v1/node/rhel2\nHeaders: map[Content-Type:[application/json]]\nBody: {\n  \"name\": \"rhel2\",\n  \"iqn\": \"iqn.1994-05.com.redhat:rhel2.demo.netapp.com\"\n}\n--------------------------------------------------------------------------------"
time="2019-08-09T15:17:07Z" level=debug msg="GRPC call: /csi.v1.Identity/GetPluginInfo"
time="2019-08-09T15:17:07Z" level=debug msg="GRPC request: "
time="2019-08-09T15:17:07Z" level=debug msg=">>>> GetPluginInfo" Method=GetPluginInfo Type=CSI_Identity
time="2019-08-09T15:17:07Z" level=debug msg="<<<< GetPluginInfo" Method=GetPluginInfo Type=CSI_Identity
time="2019-08-09T15:17:07Z" level=debug msg="GRPC response: name:\"csi.trident.netapp.io\" vendor_version:\"19.07.0\" "
time="2019-08-09T15:17:08Z" level=debug msg="\n<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<\nStatus: 201 Created\nHeaders: map[Content-Type:[application/json; charset=UTF-8] Date:[Fri, 09 Aug 2019 15:17:07 GMT] Content-Length:[17]]\nBody: {\n  \"name\": \"rhel2\"\n}\n\n================================================================================"
time="2019-08-09T15:17:31Z" level=debug msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
time="2019-08-09T15:17:31Z" level=debug msg="GRPC request: "
time="2019-08-09T15:17:31Z" level=debug msg=">>>> NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:17:31Z" level=debug msg="<<<< NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:17:31Z" level=debug msg="GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > "
time="2019-08-09T15:17:33Z" level=debug msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
time="2019-08-09T15:17:33Z" level=debug msg="GRPC request: "
time="2019-08-09T15:17:33Z" level=debug msg=">>>> NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:17:33Z" level=debug msg="<<<< NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:17:33Z" level=debug msg="GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > "
time="2019-08-09T15:17:47Z" level=debug msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
time="2019-08-09T15:17:47Z" level=debug msg="GRPC request: "
time="2019-08-09T15:17:47Z" level=debug msg=">>>> NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:17:47Z" level=debug msg="<<<< NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:17:47Z" level=debug msg="GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > "
time="2019-08-09T15:18:12Z" level=debug msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
time="2019-08-09T15:18:12Z" level=debug msg="GRPC request: "
time="2019-08-09T15:18:12Z" level=debug msg=">>>> NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:18:12Z" level=debug msg="<<<< NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2019-08-09T15:18:12Z" level=debug msg="GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > "
time="2019-08-09T15:18:17Z" level=info msg="Shutting down."
time="2019-08-09T15:18:17Z" level=info msg="Deactivating plain CSI helper frontend."
time="2019-08-09T15:18:17Z" level=info msg="Deactivating CSI frontend."
time="2019-08-09T15:18:17Z" level=debug msg="\n>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>\nDELETE https://trident-csi:34571/trident/v1/node/rhel2\nHeaders: map[Content-Type:[application/json]]\nBody: <nil>\n--------------------------------------------------------------------------------"
**time="2019-08-09T15:18:17Z" level=error msg="Error deregistering node rhel2 with controller; could not log into the Trident CSI Controller: error communicating with Trident CSI Controller; Delete https://trident-csi:34571/trident/v1/node/rhel2: dial tcp 10.100.69.32:34571: connect: connection refused"**

**[root@rhel3 ~]# kubectl logs trident-csi-hfw4d -n trident -c driver-registrar**
I0809 15:17:06.629131       1 main.go:110] Version: v1.1.0-0-g80a94421
I0809 15:17:06.629235       1 main.go:120] Attempting to open a gRPC connection with: "/plugin/csi.sock"
I0809 15:17:06.629265       1 connection.go:151] Connecting to unix:///plugin/csi.sock
I0809 15:17:06.691449       1 main.go:127] Calling CSI driver to discover driver name
I0809 15:17:06.691470       1 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0809 15:17:06.691477       1 connection.go:181] GRPC request: {}
I0809 15:17:07.745743       1 connection.go:183] GRPC response: {}
I0809 15:17:07.746576       1 connection.go:184] GRPC error: rpc error: code = DeadlineExceeded desc = context deadline exceeded
E0809 15:17:07.746694       1 main.go:133] error retreiving CSI driver name: rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by adkerr** [comment]
It looks like it was shut down by the driver-registrar sidecar because it didn't get the plugin name, but our logs clearly show us responding with the requested info, so I'm not sure what happened

**Comment by korenaren** [comment]
@jacobjohnanda Any update on this one?
