### ISSUE TITLE
Trident 19.07 not assigning SolidFire Volumes created to an Access Group. 

### ISSUE THREAD

**Issue by jacobjohnanda** [NetApp/trident#271]
Trident 19.07 is not assigning SolidFire Volumes to an Access Group. Because of this,  the volume is not getting mounted on the pod.
PVC gets created without any issues.
The same works with 19.04 , I see this issue with 19.07 version.

This issue has been discussed with the team. Keeping this defect as place-holder.

**Comment by auto-store** [comment]
encountered this. any update on fix?

**Comment by adkerr** [comment]
I'm pretty sure this was fixed in 19.07.1, what version are you running?

**Comment by auto-store** [comment]
19.07.1 - was confused by the issue as PVC creation was successful - saw this and it seems consistent with my experience. In the element UI I can see no access group assigned to the volume.

**Comment by adkerr** [comment]
Is the PVC in use by a pod? I believe we do just-in-time mapping

**Comment by auto-store** [comment]
was trying to create a pod and stuck in "containercreating" - 1min let me get some output for you

**Comment by auto-store** [comment]
PVC describe:

```
root@centos1 manifests]# kubectl describe pvc nginx-vol 
Name:          nginx-vol
Namespace:     default
StorageClass:  solidfire-bronze
Status:        Bound
Volume:        pvc-2b5cb956-f673-11e9-bdd2-005056b7d088
Labels:        <none>
Annotations:   kubectl.kubernetes.io/last-applied-configuration:
                 {"apiVersion":"v1","kind":"PersistentVolumeClaim","metadata":{"annotations":{},"name":"nginx-vol","namespace":"default"},"spec":{"accessMo...
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
Finalizers:    [kubernetes.io/pvc-protection]
Capacity:      1Gi
Access Modes:  RWO
VolumeMode:    Filesystem
Mounted By:    nginx-5cfc45f8db-v69gl
Events:
  Type    Reason                Age   From                                                                                    Message
  ----    ------                ----  ----                                                                                    -------
  Normal  ExternalProvisioning  28s   persistentvolume-controller                                                             waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator
  Normal  Provisioning          27s   csi.trident.netapp.io_trident-csi-9bc96545b-nj28d_9fcd5aa2-f672-11e9-99dd-3655d9a9ab8e  External provisioner is provisioning volume for claim "default/nginx-vol"
  Normal  ProvisioningSuccess   27s   csi.trident.netapp.io                                                                   provisioned a volume 

```

**Comment by auto-store** [comment]
trident log output:

![image](https://user-images.githubusercontent.com/37550823/67501978-1a0e4b00-f67d-11e9-93c9-d86f6820dd24.png)

**Comment by adkerr** [comment]
There's nothing obvious that sticks out here from what you've provided. Would you mind opening a support case through Netapp support so we can get the proper resources looking into the issue for you? http://mysupport.netapp.com/info/web/ECMLP2619434.html

**Comment by gnarl** [comment]
Hi @auto-store,

Were you able to resolve this issue?

**Comment by balaramesh** [comment]
CSI Trident will not assign volumes to access groups. Access groups have limitations with the number of initiators that can be added, which make it unsuitable for Kubernetes workloads. CSI Trident uses CHAP to establish connections. This is what you are observing here. For Trident 19.07 and above, when installed in Kubernetes 1.14 or later, Element/SolidFire volumes will not use Volume Access Groups

**Comment by gnarl** [comment]
Closing this issue based on the information @balaramesh has provided.
