### ISSUE TITLE
Shouldn’t trident just retry forever deleting CVS provisioned volumes?

### ISSUE THREAD

**Issue by slmingol** [NetApp/trident#277]
We've been using Trident 19.04 with NetApp's CVS and have been noticing these messages from Trident:

```
time="2019-08-21T18:49:59Z" level=warning msg="Volume could not be cleaned up and must be manually deleted: API failed (500). Code: 0. Message: Error deleting file system with ID: faf94847-a875-cdab-9953-1c567821945e - File system is already transitioning between states." volume=cvs-ba93752ff8d84b63a78350db9b2b1552
```
```
time="2019-08-21T18:50:05Z" level=error msg="Kubernetes frontend failed to delete the volume for PV vol-name-0-3c758: Trident is initializing, please try again later. Will eventually retry, but volume and PV may need to be manually deleted."
```

What are the conditions where a manual delete can be required? shouldn’t trident just retry forever?

**Comment by andyfeller** [comment]
@clintonk : can you or someone else confirm if this is still an issue for trident?

**Comment by gnarl** [comment]
Hi @andyfeller,

The error you originally reported "Kubernetes frontend failed to delete the volume for PV" only occurs for non-CSI supported Trident. If you are using a modern version of Kubernetes and a recent version of Trident that supports CSI then you will not encounter this error.

**Comment by gnarl** [comment]
Closing this issue since recent releases of Trident no longer support non-CSI operations.
