### ISSUE TITLE
Volume creation is serial

### ISSUE THREAD

**Issue by akrzos** [NetApp/trident#279]
Trident creates volumes serially which can result in long delays if there is more than one volume being created and the volume creation backend is behaving slow.  Ideally volume creation could run in parallel to provision a lot of volumes quickly.

**Comment by clintonk** [comment]
We have confirmed that volume creation (and other) operations are also serialized within the CVS & ANF services at the subscription level, so enabling parallel operations in Trident would make no improvement when using those services.  And volume operations on physical systems (ONTAP, Element, E-series) are fast enough that parallel operations haven't been necessary.  It seems the focus should be on improving API performance in CVS/ANF.
