### ISSUE TITLE
import volume with solidfire-san backend shouldn't rely on volume name

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#284]
- Trident 19.07
- Element OS 11.3

The moment I saw how `import volume` works, I knew it will stumble when there are duplicate volume names (which is perfectly legal in Element OS). Having two volumes named `conf-usion`, I try to import one (both):
`import volume solidfire_10.0.0.6 conf-usion -f some.yaml`:

Of course that can't work because the name isn't unique:

```
Request Method: POST
Request URL: http://127.0.0.1:8000/trident/v1/volume/import
Request headers: map[Content-Type:[application/json]]
Request body: {"backend":"solidfire_10.0.0.6","internalName":"conf-usion","noManage":false,"pvcData":"eyJhcGlWZXJzaW9uIjoidjEiLCJraW5kIjoiUGVyc2lzdGVudFZvbHVtZUNsYWltIiwibWV0YWRhdGEiOnsibmFtZSI6ImdvbGRlbi1zaG93ZXIiLCJuYW1lc3BhY2UiOiJkZWZhdWx0In0sInNwZWMiOnsiYWNjZXNzTW9kZXMiOlsiUmVhZFdyaXRlT25jZSJdLCJyZXNvdXJjZXMiOnsicmVxdWVzdHMiOnsic3RvcmFnZSI6IjEwR2kifX0sInN0b3JhZ2VDbGFzc05hbWUiOiJnb2xkIn19"}
................................................................................
Response status: 400 Bad Request
Response headers: map[Content-Type:[application/json; charset=UTF-8] Date:[Tue, 03 Sep 2019 12:01:51 GMT] Content-Length:[160]]
Response body: {"volume":null,"error":"volume import failed to get size of volume: error requesting volume size: ambiguous volume name; 2 volumes found with name conf-usion"}

================================================================================
Error: could not import volume: volume import failed to get size of volume: error requesting volume size: ambiguous volume name; 2 volumes found with name conf-usion (400 Bad Request)
command terminated with exit code 1
```
Now you may say "import is meant for another Kubernetes volume so it won't be the same", but why shouldn't we be able to import any volume from a supported back-end, whether it's from Trident/K8S or Trident/Docker?

Element OS can't change volume name of an existing volume - we'd have to copy it to another (clone + name change). 

@ReeseLloyd

**Comment by clintonk** [comment]
@scaleoutsean  Yes, we are aware of this issue.  The fact that volume names need not be unique in ElementOS means the name is just a glorified label, so the inability to change a volume name is an indefensible limitation of ElementOS.  Please raise this concern there!

**Comment by scaleoutsean** [comment]
No problem, that's why I mentioned Reese. Actually I wouldn't have reported this as an issue if I had known it was already documented, but somehow I had missed that part in the Trident docs - my fault.
