### ISSUE TITLE
Modify imported volumes to have the properties of the specified storage class

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#285]
- Trident 19.07.0
- K8S 1.13.0

- Create a solidfire-san backend with a bronze QoS SLA
- Create a "bronze" SC with QoS same as the minimum QoS in "bronze" SLA in back-end definition
- Create a PVC that assigns "bronze" SC to a volume
- Create a random volume and import it (as Trident-managed volume)

- Result: default Element QoS settings remain 

![image](https://user-images.githubusercontent.com/16622642/64175446-e2113580-ce8d-11e9-8032-26aebf4fa867.png)

![image](https://user-images.githubusercontent.com/16622642/64175511-0836d580-ce8e-11e9-95ed-cbfdd6d56ece.png)

But:

![image](https://user-images.githubusercontent.com/16622642/64175473-f2c1ab80-ce8d-11e9-81a8-293f866d91d3.png)

- Expected result: Trident applies QoS settings for "bronze" SC

**Comment by innergy** [comment]
We are intentionally leaving imported volumes alone at the moment, we don't try to make them "look" like the storage class you specify as we pull them in. The reason why we ask you to specify a storage class is because there are policies (like delete vs. retain) that we need to understand and honor.

**Comment by scaleoutsean** [comment]
I see. I was under the impression that `manage` mode would make those changes. Maybe I'll submit a doco PR just so that folks know they may want to make manual changes to QoS properties of imported volumes if their use case could benefit from it.

**Comment by gnarl** [comment]
Closing as the previous discussion indicates that Trident never intended to make an imported volume take on characteristics of the storage class. The common customer use case for volume import is to recover (DR) or add volumes created by Trident into a Kubernetes cluster.
