### ISSUE TITLE
error validating aws-cvs driver. failed to read version

### ISSUE THREAD

**Issue by sourcedelica** [NetApp/trident#290]
trident-plugin:19.07.0
Docker 18.09.4

I have just installed the plugin and am trying to create my first volume.  When I try to create the volume I get this error:
```
$ docker volume create -d netapp --name first
Error response from daemon: create first: VolumeDriver.Create: Trident initialization failed; problem initializing storage driver 'aws-cvs': error validating aws-cvs driver. failed to read version: use 'journalctl -fu docker' to learn more
```
There is no log in `/var/log/netappdvp`.  The error from `journalctl` is:
```
Sep 11 16:31:54 usdlvfal500 dockerd[2463]: time="2019-09-11T16:31:54.986923661-04:00" level=error msg="Handler for POST /v1.39/volumes/create returned error: create first: VolumeDriver.Create: Trident initialization failed; problem initializing storage driver 'aws-cvs': error validating aws-cvs driver. failed to read version: use 'journalctl -fu docker' to learn more"
```
Here is the configuration that I got from our storage team:
```
$ cat /etc/netappdvp/config.json
{
    "version": 1,
    "storageDriverName": "aws-cvs",
    "apiRegion": "us-ch4",
    "apiURL": "https://twusgrid01.mycorp.com:8082/IDB_DEV_USCH4",
    "apiKey":    "some-api-key",
    "secretKey": "some-secret-key",
    "region": " us-ch4",
    "serviceLevel": "premium",
    "storagePrefix": "cvs-",
    "limitVolumeSize": "100Gi",
    "defaults": {
        "snapshotReserve": "5",
        "size": "100Gi"
    }
}
```
I also tried `"apiURL": "https://twusgrid01.mycorp.com:8082"`.

Thanks for your help.

**Comment by clintonk** [comment]
Hi, @sourcedelica.  The apiURL in your config.json file should be what you find in the CVS UI in the same place you find your API keys.  For example, in us-east-1, the apiURL is `https://cds-aws-bundles.netapp.com:8080/v1/`

**Comment by sourcedelica** [comment]
Hi @clintonk - It turns out that we have [Netapp Storage Grid](https://www.netapp.com/us/products/data-management-software/object-storage-grid-sds.aspx) on prem, not Netapp CVS for AWS.  Is Trident compatible with that?

**Comment by clintonk** [comment]
Hi, @sourcedelica.  Trident supports virtually all of NetApp's file & block storage portfolio, but StorageGRID is our object storage solution.  Kubernetes doesn't really have an object storage story; if and when that changes, I suspect Trident will be there with StorageGRID!
