### ISSUE TITLE
No backends currently satisfy provided storage class?

### ISSUE THREAD

**Issue by robotica72** [NetApp/trident#291]
I've been a Trident user since the early days and it has always worked well and was easy to install.  Now I have some new clusters to build and Im using the newest version on K8s 1.15 and Im running an issue in my lab testing using it with Solidfire.   The logs for Trident show:

No backends currently satisfy provided storage class for any storage class I create.

More detailed logs:
time="2019-09-04T19:11:17Z" level=info msg="Newly added backend satisfies no storage classes." backend=solidfire_x.x.x.x
time="2019-09-04T19:11:17Z" level=info msg="Added a new backend." backend=solidfire_10.2.1.81 handler=AddBackend
time="2019-09-04T19:11:19Z" level=info msg="Controller serial numbers." serialNumbers="xxxxxxxxxxxxxxxxxxxxx"
time="2019-09-04T19:12:02Z" level=info msg="No backends currently satisfy provided storage class." storageClass=basic
time="2019-09-04T19:12:02Z" level=info msg="K8S helper added a storage class." name=basic parameters="map[backendType:solidfire-san provisioningType:thin]" provisioner=csi.trident.netapp.io
time="2019-09-04T19:16:15Z" level=info msg="K8S helper deleted the storage class." name=basic
time="2019-09-04T19:16:28Z" level=info msg="No backends currently satisfy provided storage class." storageClass=basic
time="2019-09-04T19:16:28Z" level=info msg="K8S helper added a storage class." name=basic parameters="map[backendType:solidfire-san]" provisioner=csi.trident.netapp.io
time="2019-09-04T19:51:25Z" level=info msg="K8S helper deleted the storage class." name=basic
time="2019-09-04T19:51:31Z" level=info msg="No backends currently satisfy provided storage class." storageClass=basic

Checking the backend seems to be correct:
+---------------------+----------------+--------------------------------------+--------+---------+
|        NAME         | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+---------------------+----------------+--------------------------------------+--------+---------+
| solidfire_x.x.x.x | solidfire-san  | xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx | online |       0 |
+---------------------+----------------+--------------------------------------+--------+---------+

Tried a few Storageclass, but all fail to find the backend:
A desribe on the basic one:

Name:                  basic
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           csi.trident.netapp.io
Parameters:            backendType=solidfire-san
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

YAML:
apiVersion: storage.k8s.io/v1beta1
kind: StorageClass
metadata:
  name: basic
provisioner: csi.trident.netapp.io
parameters:
  backendType: "solidfire-san"

Not sure what I may be missing, but likely something little I hope???

**Comment by scaleoutsean** [comment]
`provisioner: csi.trident.netapp.io` is new - it used to be `provisioner: netapp.io/trident` and this isn't documented while samples have been updated. 
If you Kubernetes is older (v1.13) you can reinstall Trident w/o CSI, otherwise you look into the provisioner thing.

**Comment by jacobjohnanda** [comment]
With Trident 19.07.1 , VAGs dont work anymore, by default it will use CHAP. But the error message "No backends currently satisfy provided storage class" doesn't point to any issues on the authentication side. This looks trident cannot find the requested storage pool. Could  you make sure that QoS are all set up properly on the storage and backend.

**Comment by robotica72** [comment]
@jacobjohnanda -  Thanks - On the provisioner - I did use the original netapp.io/trident and I had the same results, and the Trident watcher changes it to the new provisioner when you create that SC, at least from what I recall (and what the logs said).

@jacobjohnanda - I did check the QOS a few weeks ago, as this has been an issue for some time now - but Ill verify that again just in case... Playing with so many things, I may have missed something after other changes.

**Comment by korenaren** [comment]
Hi @robotica72 - is this still an issue?

**Comment by gnarl** [comment]
Closing this issue as a response hasn't been made.
