### ISSUE TITLE
Upgrading from Trident 19.04 to 19.07.1 fails on OpenShift 3.10

### ISSUE THREAD

**Issue by bigl0af** [NetApp/trident#292]
I am trying to upgrade Trident to resolve an issue with CVS volume provisioning. However, upgrading from 19.04 to 19.07.1 seems to not work on OpenShift 3.10:

[ec2-user@dwfostst3 trident-installer]$ ./tridentctl version -n trident
+---------------------------------------------------------+----------------+
|                     SERVER VERSION                      | CLIENT VERSION |
+---------------------------------------------------------+----------------+
| **19.04.0-beta.1+dfd48cac9bd2c4aac665b6275257695c22308d6a** | 19.07.1        |
+---------------------------------------------------------+----------------+

[ec2-user@dwfostst3 trident-installer]$ ./tridentctl uninstall -n trident
**FATA Uninstall pre-checks failed; could not initialize Kubernetes client; Trident 19.07.1 supports Kubernetes versions in the range [1.11, 1.15]**

**Comment by adkerr** [comment]
Can you try using the 19.04 version of tridentctl to perform the uninstall, then switch to 19.07 tridentctl to perform the install?

**Comment by bigl0af** [comment]
This did not work:
[ec2-user@dwfostst3 trident-installer]$ ./tridentctl version -n trident
+---------------------------------------------------------+---------------------------------------------------------+
|                     SERVER VERSION                      |                     CLIENT VERSION                      |
+---------------------------------------------------------+---------------------------------------------------------+
| 19.04.0-beta.1+dfd48cac9bd2c4aac665b6275257695c22308d6a | 19.04.0-beta.1+dfd48cac9bd2c4aac665b6275257695c22308d6a |
+---------------------------------------------------------+---------------------------------------------------------+
[ec2-user@dwfostst3 trident-installer]$ ./tridentctl uninstall -n trident
INFO Created installer service account.            serviceaccount=trident-installer
INFO Waiting for object to be created.             objectName=clusterRole
INFO Created installer cluster role.               clusterrole=trident-installer
INFO Waiting for object to be created.             objectName=clusterRoleBinding
INFO Created installer cluster role binding.       clusterrolebinding=trident-installer
INFO Added security context constraint user.       scc=privileged user=trident-installer
INFO Created uninstaller pod.                      pod=trident-installer
INFO Waiting for Trident installer pod to start.
INFO Trident installer pod started.                namespace=trident pod=trident-installer
INFO Deleted Trident deployment.
INFO Deleted cluster role binding.
INFO Deleted cluster role.
INFO Deleted service account.
INFO Removed security context constraint user.     scc=anyuid user=trident
INFO The uninstaller did not delete the Trident's namespace, PVC, and PV in case they are going to be reused. Please use the --all option if you need the PVC and PV deleted.
INFO Trident uninstallation succeeded.
INFO Waiting for Trident installer pod to finish.
INFO Trident installer pod finished.               namespace=trident pod=trident-installer
INFO Deleted uninstaller pod.                      pod=trident-installer
INFO Deleted installer cluster role binding.
INFO Deleted installer cluster role.
INFO Deleted installer service account.
INFO Removed security context constraint user.     scc=privileged user=trident-installer

[ec2-user@dwfostst3 trident-installer]$ ./tridentctl install -n trident
FATA Install pre-checks failed; could not initialize Kubernetes client; Trident 19.07.1 supports Kubernetes versions in the range [1.11, 1.15]

**Comment by clintonk** [comment]
Hi, @bigl0af.  Sorry, but this seems to be a doc bug.  Trident 19.07's minimum Kubernetes version is 1.11, corresponding to OpenShift 3.11.

**Comment by bigl0af** [comment]
Any chance this CVS bug fix will be backported to 19.04??

**Comment by bigl0af** [comment]
To be clear, the CVS bug found at https://github.com/NetApp/trident/issues/288

**Comment by korenaren** [comment]
Hi @bigl0af - It is correct that Trident 19.07 does not support OCP 3.10. And at this point, we have no plans to backport that fix to 19.04. OCP 3.10 runs out of Support in Oct 2019 (per RH Support website). If you upgrade to OCP 3.11, all versions would be compatible (and work properly).
