### ISSUE TITLE
Bad Slack Invite Link

### ISSUE THREAD

**Issue by synth3tk** [NetApp/trident#294]
The link to join the Slack on your main website and from the Trident [support doc](https://github.com/NetApp/trident/blob/5f4e88e382ab2e7dd25de59f75576a1f8707402b/docs/support/support.rst) point to https://netapp.io/slack/, which says that the "link is no longer active".
![image](https://user-images.githubusercontent.com/2099988/65615142-e14c5a80-df86-11e9-8e51-8dd2486679db.png)

**Comment by gtehrani** [comment]
@synth3tk yes, we're aware and are working on it with the service provider. Thanks for your patience.

**Comment by korenaren** [comment]
Fixed.
