### ISSUE TITLE
Support for kubernetes on arm64/aarch64 

### ISSUE THREAD

**Issue by braudel** [NetApp/trident#298]
Please add support for using trident on arm64-based kubernetes clusters/nodes.

**Comment by gnomeAware** [comment]
+1
I'd like to be able to run Trident on my Raspberry Pi k8s cluster.

**Comment by gnarl** [comment]
@braudel and @gnomeAware we provide [build instructions](https://github.com/NetApp-openstack-dev/trident/blob/master/BUILD.md) that enable you to build Trident. Just edit the Makefile to set GOARCH variable.
