### ISSUE TITLE
Azure NetApp Files volume provisioning breaks in Trident v19.07

### ISSUE THREAD

**Issue by LarsMilland** [NetApp/trident#300]
Hi

After most recent update to the recently launched Azure based service "Azure NetApp Files" provisioning of volumes from Trident v19.07 fails.

According to Azure support it is apparently because the Azure NetApp Files service is not now capable of handling the volume provisioning request to the REST api with both NFS3 and NFS4 in the volume type options. Would it be possible to resolve this in the Trident client, with a configuration to the backend configuration or a software change to get the provisioning to work again?

Best regards
Lars Milland

**Comment by bnaylor** [comment]
We have a fix for this pending in the next release.  Thanks for reporting it.

**Comment by korenaren** [comment]
Fixed in 19.10.
