### ISSUE TITLE
Trident through a Firewall

### ISSUE THREAD

**Issue by jakewarren81** [NetApp/trident#301]
We are attempting to setup a Trident backend on a NetApp SVM that is behind a firewall, with NATed addresses for the managementLIF and the dataLIF.  Is this a supported setup?

Here are some of the error messages we are getting from Trident:
"Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005"

"Could not initialize storage driver." error="error validating ontap-nas driver: driver validation failed: data LIF validation failed: could not find Data LIF for 172.28.2.24"

"problem initializing storage driver 'ontap-nas': error validating ontap-nas driver: driver validation failed: data LIF validation failed: could not find Data LIF for 172.28.2.24" backend= handler=AddBackend

We are seeing this on the NetApp side for each attempt:
Unable to find API: system-node-get-iter :: ONTAPI :: Error

**Comment by gnarl** [comment]
@jakewarren81 This isn't a supported configuration. Kubernetes, Trident, the management LIF, and data LIFs should not be separated by NAT.

**Comment by gnarl** [comment]
Hi @cesarandreslopez,

The ports that Trident uses is included in the [Trident documentation](https://docs.netapp.com/us-en/trident/trident-reference/trident-ports.html).
