### ISSUE TITLE
Deploy trident in Kubernetes 1.16

### ISSUE THREAD

**Issue by zakkg3** [NetApp/trident#303]
Hi, 
I build trident with the actual code, that includes the commit from @clintonk https://github.com/NetApp/trident/commit/82cdabbe0d05b38251b3793bf86952b3b3b44628
I did some hacks to make the build go through ... glide and then docker stages were failing. finally built but now, `Error: ErrImagePull` as the image "netapp/trident:19.10.0-custom" is not available. :/

Do we have a release date for the new Kubernetes 1.16 compatible version? 
If someone is able to build and push the images I will give you feedback :D

thanks.

**Comment by adkerr** [comment]
19.10 will be 1.16 compatible and is due by the end of October

**Comment by zakkg3** [comment]
guess you can close this one as [19.10](https://github.com/NetApp/trident/releases/tag/v19.10.0) supports k8s 1.16
Thanks!
