### ISSUE TITLE
Trident 19.07.1 fails pre-check on Openshift 4,2.0

### ISSUE THREAD

**Issue by fmj3fmj3** [NetApp/trident#304]
Trident 19.07.1 (and 19.07.0) fails the install pre check on Openshift 4.2.  It works fine on 4.1 and 3.11.  Looks like it's probably just some error in syntax in the checking logic?

FATA Install pre-checks failed; could not initialize Kubernetes client; Trident 19.07.1 supports Kubernetes versions in the range [1.11, 1.15]

**Comment by clintonk** [comment]
Hi, @fmj3fmj3.  The ```oc``` tool's version command works differently in 3.11, 4.1 and 4.2!

We're targeting a fix in the forthcoming Trident 19.10, due this month.  In the meantime, you might try placing ```oc``` 4.1 in your path ahead of 4.2, and then running the Trident installer.

**Comment by fmj3fmj3** [comment]
That worked, thanks.  I thought I had tried using the oc 4.1 before, but I guess I didn't.

I also had to do the workaround in this issue as well.
https://github.com/NetApp/trident/issues/296

Hopefully all of this will get hashed out in Trident 19.10

Thanks for the help

**Comment by clintonk** [comment]
@fmj3fmj3  Yes, we have 19.10 builds installing on 4.2.  We've switched back to using the out-of-cluster installer by default, which circumvents the permissions issue.
