### ISSUE TITLE
Change in volume size display in Trident >=19.04

### ISSUE THREAD

**Issue by megabreit** [NetApp/trident#305]
When a volume is created with 10Gi, the displayed size is "10737418240", not "10 Gi".
This happens in >=19.04, but was not the case in <=19.1.

This is quite confusing, not userfriendly at all and should be changed back to the original behavior.

**Comment by gnarl** [comment]
"10737418240" is the number of bytes for 10 Gibibytes. The reported byte size is correct as Kubernetes actually stores the number of bytes instead of the "human-readable" version. We will look into why bytes are being reported in 19.04 instead of the userfriendly version.

**Comment by gnarl** [comment]
This was fixed in the [Trident 20.04](https://github.com/NetApp/trident/blob/master/CHANGELOG.md) release.
