### ISSUE TITLE
trident install steps on openshift 4.2

### ISSUE THREAD

**Issue by go2sekhar** [NetApp/trident#308]
Hi,

am looking how to install trident on openshift 4.2 and in openshift 4.2 how we can set to use dynamic storage to use trident other than any storage class config.

I know how to do it on 3.11, but i didn't find proper document for 4.2.

**Comment by korenaren** [comment]
Trident releases 19.07 and earlier do not support OpenShift 4.2. OpenShift 4.2 will be supported in Trident 19.10, which will be out very soon.
