### ISSUE TITLE
Create Multiple iSCSI LUNs in a Single Volume

### ISSUE THREAD

**Issue by rileynjohnson** [NetApp/trident#31]
Similar to the qtree request for enhancement, this is required for customers to scale OSE.  Trident currently creates one iSCSI lun and one volume per request.  With only 1,000 volumes per controller (12,000 per cluster), this quickly becomes impractical.  If trident created multiple luns per volume we could achieve 98,304 LUNs per cluster.

**Comment by kapilarora** [comment]
Do we have any update on this issue? Is this being worked on?

**Comment by innergy** [comment]
We don't have this in our near-term plans at the moment, but we are tracking demand.

**Comment by redbaron** [comment]
Register my interest in this then :)

**Comment by scaleoutsean** [comment]
>  If trident created multiple luns per volume we could achieve 98,304 LUNs per cluster.

You'd still have the same number of LUNs (volumes) and up to 98K partitions per Element OS cluster, no?

What happens with volume QoS settings in this case? It would seem they'd become "per project" QoS settings, similar to VMware datastores but without QoSSIOC.

**Comment by adkerr** [comment]
@scaleoutsean this request is directed at ONTAP SAN where you can have multiple LUNs per flexvol.

**Comment by per-steinar** [comment]
I am interested in this. We cannot implement ONTAP-SAN backends as long as each LUN needs its own volume.

**Comment by acsulli** [comment]
+1 for this on behalf of a customer.  They are under additional volume count pressure as a result of MetroCluster.

Andrew

**Comment by YvosOnTheHub** [comment]
+1 
another customer in UK who is interested in hosted several LUN per flexVol

**Comment by promiseowolabi** [comment]
+1
I have customer who need this feature ASAP, going into production with openshift
