### ISSUE TITLE
Feature Request: ONTAP iSCSI Volume Import

### ISSUE THREAD

**Issue by psingh59** [NetApp/trident#310]
HI,

Can you please update roadmap to include iSCSI and FC import of volumes by trident? At present NFS is supported but we have usecase for FC and iSCSI as well however cannot do this as trident is not supporting importing of managed FC and iSCSI volumes.

Thanks.

**Comment by anungw** [comment]
Hi,

We would like to have this feature, especially for ISCSI and for DR use cases.

Thanks

**Comment by pablogarciaarevalo** [comment]
Agree. We would need this feature also for iSCSI for disaster recovery use case. Please, consider at least to allow importing LUNs when a volume only has a single LUN.

**Comment by anungw** [comment]
Is there any plan to add this feature on the next release?

**Comment by korenaren** [comment]
This feature is not in the 20.01 release. We have not confirmed our plans for the 20.04 release.

**Comment by anungw** [comment]
Hi, 

May I know whether this feature will be added in the next release (20.04)?

**Comment by gnarl** [comment]
This feature will be in the Trident 20.07 release.

**Comment by gnarl** [comment]
This issue is fixed in the Trident 20.07 release.
