### ISSUE TITLE
No options of CSI images location in the "tridentctl install"

### ISSUE THREAD

**Issue by ysakashita** [NetApp/trident#311]
I would like to install Trident v19.10.0 using our private container repository.
So tridentctl already has a nice option called `--trident-image` .
But I can't specify the location for CSI images(csi-provisioner, csi-attacher etc).

Do you have a plan to support the options?

**Comment by clintonk** [comment]
Hello, @ysakashita.  You can use the --generate-custom-yaml switch to generate all the YAML that the installer needs, modify that accordingly, and then specify the --use-custom-yaml switch for the actual installation.

**Comment by synth3tk** [comment]
I'm curious why an option wasn't provided for CSI images. Would you accept a PR to add the flag?

**Comment by clintonk** [comment]
@synth3tk There are multiple CSI sidecars (and their versions differ somewhat between K8S versions) and we're not inclined to add that many flags to the installer.  The custom YAML mechanism provides all the control needed (maybe too much!).

**Comment by wonderland** [comment]
What about a generic flag that just specifies the custom repo to use for all images? In cases like this, you'd typically have all images in the same private repo so we wouldn't require individual installer flags for each image. And would still make this easier than going through the whole YAML just for the (pretty much standard) use case of a private repo...

**Comment by clintonk** [comment]
@wonderland That may be a reasonable compromise, although it could be a while.  We're currently monitoring the trend toward K8S operators, so the Trident install method may change down the road anyway, and this is good feedback.  In the meantime, using a caching image proxy like Nexus or Artifactory might be an option.

**Comment by ysakashita** [comment]
@wonderland 
+1 a generic flag
At least in my environment, I get all images from the same private repository.
