### ISSUE TITLE
Dead Alpine Linux links in Dockerfile 

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#315]
```
fetch http://dl-1.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
fetch http://dl-2.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz
ERROR: http://dl-1.alpinelinux.org/alpine/v3.10/main: No such file or directory
WARNING: Ignoring APKINDEX.8002c5a8.tar.gz: No such file or directory
```
Source:
https://github.com/NetApp/trident/blob/f819aa0a01e1b84288a46f6c953a503fca211ff3/Dockerfile#L8

It seems they have a functioning alias (for example http://dl-cdn.alpinelinux.org/alpine/v3.10/main/x86_64/APKINDEX.tar.gz).

**Comment by gnarl** [comment]
This was fixed in the 20.01 release.
