### ISSUE TITLE
Volumes creation fails in 19.10 because of flashpool default set to none

### ISSUE THREAD

**Issue by mickeysh** [NetApp/trident#318]
After installing trident 19.10 we’re getting this error when trying to create iSCSI PV with the san driver. It worked before with Trident 19.07 (and works again after reverting the version)

`encountered error(s) in creating the volume: [Failed to create volume pvc-6dd59c87-2f51-4044-ac3e-437299fbebd4 on storage pool n3_aggr3800_adpv2_0 from backend ontapsan_: error creating volume: API status: failed, Reason: Only the 'snapshot-only' tiering policy is supported when the Vserver is in a DR relationship., Code: 13001]`

The system is AFF with ONTAP 9.3 that has no fabricpool implemented on it 
I saw that Trident 19.10 has a fix regarding FB when we change the default to none, but in our case since this is a system that has DR relationships ONTAP demands snapshot-only to create the volume
https://github.com/NetApp/trident/issues/199

**Comment by korenaren** [comment]
Thanks for reporting this. Sorry our fix for #199 doesn't work with your use case. We will take a look at this as soon as we can.
