### ISSUE TITLE
Trident does not work with ONTAP SLM and iSCSI

### ISSUE THREAD

**Issue by kincl** [NetApp/trident#321]
We are running Trident with ontap-san connecting to a ONTAP cluster with 12 iscsi data lifs (one per node as required)

When Trident creates a PV, it populates `.spec.iscsi.portals` with all of these interfaces but the Selective LUN Map reduces the number of paths from the host to the LUN. This means that when the kubelet tries to mount the iSCSI volume, it tries to connect to all of the portals. Two succeed (the HA node pair that SLM set) but the rest time out which means that it takes the kubelet ~20min to mount one iSCSI volume on a pod. 

I could set the IP address in the backend config but then I wouldn't have HA failover between nodes at all. I can turn off SLM for an individual volume but cannot turn it off for new volumes.

Trident should probably be configuring SLM for each volume or only adding the portal IPs that SLM has restricted the paths from the host to the volume on.

**Comment by gnarl** [comment]
@kincl Thanks for bringing this issue to our attention. We'll work on a fix as soon as we can.

**Comment by kincl** [comment]
Hey @gnarl is there an ETA on this or a workaround we can do? It limits our ability to offer iSCSI since there is this manual intervention of disabling SLM for a volume after it has been created

**Comment by korenaren** [comment]
We are hoping to include a fix for this in the 20.01 release. Not sure we can get in done in time (it's not an easy fix), but we are actively working on it. I'll let @gnarl respond to if there is a workaround.

**Comment by kincl** [comment]
@korenaren Did this fix make it into 20.01? I don't see anything in the changelog

**Comment by korenaren** [comment]
It did not make it. We are now targeting the 20.01.1 patch release. Please stay tuned.

**Comment by gnarl** [comment]
This issue was fixed with the [Trident 20.01.1 ](https://github.com/NetApp/trident/releases/tag/v20.01.1)release.
