### ISSUE TITLE
FailedAttachVolume

### ISSUE THREAD

**Issue by Jubayer1228** [NetApp/trident#323]
I am having this issue "node trident-clnt3 was not found". Even though kubernetes cluster has three worker nodes. pods are showing "ContainerCreating" status as It could not find the worker nodes. worker nodes has storage access. In my case, I am using ISCSI.
someone also reported quite similar issues before. Even though his solution did not work for me.
https://github.com/NetApp/trident/issues/283
Is there anyone having same issues?
See Below for Details:
---------------------------------------------------------------------
root@trident-master:~/trident-installer# kubectl get pods
NAME          READY   STATUS              RESTARTS   AGE
task-pv-pod   0/1     ContainerCreating   0          12m
root@trident-master:~/trident-installer# kubectl describe pod task-pv-pod 
Name:         task-pv-pod
Namespace:    default
Priority:     0
Node:         trident-clnt3/172.16.1.57
Start Time:   Mon, 16 Dec 2019 12:12:37 -0700
Labels:       <none>
Annotations:  <none>
Status:       Pending
IP:           
IPs:          <none>
Containers:
  task-pv-container:
    Container ID:   
    Image:          nginx
    Image ID:       
    Port:           80/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /usr/share/nginx/html from task-pv-storage (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-t5rr7 (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  task-pv-storage:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  basic
    ReadOnly:   false
  default-token-t5rr7:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-t5rr7
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age                 From                     Message
  ----     ------              ----                ----                     -------
  Normal   Scheduled           12m                 default-scheduler        Successfully assigned default/task-pv-pod to trident-clnt3
  Warning  FailedMount         97s (x5 over 10m)   kubelet, trident-clnt3   Unable to attach or mount volumes: unmounted volumes=[task-pv-storage], unattached volumes=[task-pv-storage default-token-t5rr7]: timed out waiting for the condition
  Warning  FailedAttachVolume  26s (x14 over 12m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-fd2aa57d-e282-4b5c-ad4d-42ef36cf0f5d" : rpc error: code = NotFound desc = node trident-clnt3 was not found
root@trident-master:~/trident-installer# 

root@trident-master:~/trident-installer# kubectl logs trident-csi-64464dfb6-xxgpf -n trident trident-main
time="2019-12-16T19:16:14Z" level=info msg="Running Trident storage orchestrator." binary=/usr/local/bin/trident_orchestrator build_time="Wed Oct 30 13:17:04 EDT 2019" version=19.10.0
time="2019-12-16T19:16:14Z" level=info msg="Initializing HTTP REST frontend." address="127.0.0.1:8000"
time="2019-12-16T19:16:14Z" level=info msg="Added frontend." name="HTTP REST"
time="2019-12-16T19:16:14Z" level=info msg="Initializing HTTPS REST frontend." address=":8443"
time="2019-12-16T19:16:14Z" level=info msg="Added frontend." name="HTTPS REST"
time="2019-12-16T19:16:14Z" level=info msg="Initializing K8S helper frontend." namespace=trident
time="2019-12-16T19:16:14Z" level=info msg="K8S helper determined the container orchestrator version." gitVersion=v1.16.4 version=1.16
time="2019-12-16T19:16:14Z" level=info msg="Added frontend." name=k8s_csi_helper
time="2019-12-16T19:16:14Z" level=info msg="Initializing CSI frontend." name=trident-clnt1 version=19.10.0
time="2019-12-16T19:16:14Z" level=info msg="Enabling controller service capability." capability=CREATE_DELETE_VOLUME
time="2019-12-16T19:16:14Z" level=info msg="Enabling controller service capability." capability=PUBLISH_UNPUBLISH_VOLUME
time="2019-12-16T19:16:14Z" level=info msg="Enabling controller service capability." capability=LIST_VOLUMES
time="2019-12-16T19:16:14Z" level=info msg="Enabling controller service capability." capability=CREATE_DELETE_SNAPSHOT
time="2019-12-16T19:16:14Z" level=info msg="Enabling controller service capability." capability=EXPAND_VOLUME
time="2019-12-16T19:16:14Z" level=info msg="Enabling controller service capability." capability=CLONE_VOLUME
time="2019-12-16T19:16:14Z" level=info msg="Enabling volume access mode." mode=SINGLE_NODE_WRITER
time="2019-12-16T19:16:14Z" level=info msg="Enabling volume access mode." mode=SINGLE_NODE_READER_ONLY
time="2019-12-16T19:16:14Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_READER_ONLY
time="2019-12-16T19:16:14Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_SINGLE_WRITER
time="2019-12-16T19:16:14Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_MULTI_WRITER
time="2019-12-16T19:16:14Z" level=info msg="Added frontend." name=csi
time="2019-12-16T19:16:14Z" level=info msg="Initializing Trident CRD controller frontend." namespace=trident
time="2019-12-16T19:16:14Z" level=info msg="Creating event broadcaster."
time="2019-12-16T19:16:14Z" level=info msg="Setting up CRD event handlers."
time="2019-12-16T19:16:14Z" level=info msg="Added frontend." name=crd
time="2019-12-16T19:16:14Z" level=info msg="Activating HTTP REST frontend." address="127.0.0.1:8000"
time="2019-12-16T19:16:14Z" level=info msg="Activating HTTPS REST frontend." address=":8443"
time="2019-12-16T19:16:14Z" level=info msg="Controller serial numbers." serialNumbers=99887766554433221193
time="2019-12-16T19:16:14Z" level=info msg="Storage driver initialized." driver=ontap-san
time="2019-12-16T19:16:14Z" level=info msg="Created new storage backend." backend="&{0xc00000c5a0 ontapsan_172.16.20.51  true online map[ontap_vsan1_01_VM_DISK_1:0xc0005d2700] map[]}"
time="2019-12-16T19:16:14Z" level=info msg="Newly added backend satisfies no storage classes." backend=ontapsan_172.16.20.51
time="2019-12-16T19:16:14Z" level=info msg="Added an existing backend." backend=ontapsan_172.16.20.51 backendUUID=8a0eb022-fc09-4b18-b55a-4853de93ef59 handler=Bootstrap online=true persistentBackends.BackendUUID=8a0eb022-fc09-4b18-b55a-4853de93ef59 state=online
time="2019-12-16T19:16:14Z" level=info msg="Added an existing storage class." handler=Bootstrap storageClass=basic-csi
time="2019-12-16T19:16:14Z" level=info msg="Added 1 existing volume(s)"
time="2019-12-16T19:16:14Z" level=info msg="Trident bootstrapped successfully."
time="2019-12-16T19:16:14Z" level=info msg="Activating K8S helper frontend."
time="2019-12-16T19:16:14Z" level=info msg="Activating CRD frontend."
time="2019-12-16T19:16:14Z" level=info msg="Activating CSI frontend."
time="2019-12-16T19:16:14Z" level=info msg="Starting Trident CRD controller."
time="2019-12-16T19:16:14Z" level=info msg="Waiting for informer caches to sync."
time="2019-12-16T19:16:14Z" level=info msg="Listening for GRPC connections." name=/plugin/csi.sock net=unix
time="2019-12-16T19:16:14Z" level=warning msg="K8S helper could not add a storage class: storage class basic-csi already exists" name=basic-csi parameters="map[backendType:ontap-san]" provisioner=csi.trident.netapp.io
time="2019-12-16T19:16:14Z" level=info msg="Starting workers."
time="2019-12-16T19:16:14Z" level=info msg="Started workers."
time="2019-12-16T19:16:21Z" level=error msg="Node info not found." node=trident-clnt3
time="2019-12-16T19:16:21Z" level=error msg="GRPC error: rpc error: code = NotFound desc = node trident-clnt3 was not found"
time="2019-12-16T19:16:31Z" level=error msg="Node info not found." node=trident-clnt3
time="2019-12-16T19:16:31Z" level=error msg="GRPC error: rpc error: code = NotFound desc = node trident-clnt3 was not found"
time="2019-12-16T19:16:51Z" level=error msg="Node info not found." node=trident-clnt3
time="2019-12-16T19:16:51Z" level=error msg="GRPC error: rpc error: code = NotFound desc = node trident-clnt3 was not found"

**Comment by gnarl** [comment]
@Jubayer1228 your issue may be related to this closed issue https://github.com/NetApp/trident/issues/314. If this doesn't solve your issue then please contact NetApp support.

**Comment by Jubayer1228** [comment]
Thanks @gnarl. I have looked at the issue #314. My kubelet installation directory is /var/lib/kubelet. Even though I tried to do the custom installation, that did not help. 

It seems like trident CSI controller is trying to make communication with ISCSI initiator. here is that error message.
root@trident-master:~/trident-installer# kubectl logs trident-csi-jvqvn -n trident trident-main

Body: {\n  \"name\": \"trident-clnt3\",\n  \"iqn\": \"iqn.1993-08.org.debian:01:76b7ef90d819\"\n}\n--------------------------------------------------------------------------------"
time="2019-12-16T22:35:07Z" level=debug msg="Controller not yet ready, waiting." error="could not log into the Trident CSI Controller: error communicating with Trident CSI Controller; Put https://trident-csi:34571/trident/v1/node/trident-clnt3: dial tcp: lookup trident-csi on 10.96.0.10:53: write udp 172.16.1.57:38215->10.96.0.10:53: write: operation not permitted" increment=5.400194246s

**Comment by glenndekhayser** [comment]
I am having same issue, my kubelet dir is where it should be at /var/lib/kubelet. I'm getting "AttachVolume.Attach failed for volume "pvc-a69d5820-e88a-4ff2-8a1e-0456a094e0c4" : rpc error: code = NotFound desc = node k8s-worker1 was not found" 

k8s-worker1 is pingable, cni0 is up on that node and verified. 

Trident is installed in separate namespace, 'trident'.  Trying to create this pod in default namespace.

**Comment by Jubayer1228** [comment]
Just an update on that issues. I was using ubuntu 16.04 as OS with trident version 19.10. Once I installed everything on ubuntu 18.04 with docker version 18.09. I don't see any more issues. Everything is working now.
