### ISSUE TITLE
CHAP authentication for e-series backend

### ISSUE THREAD

**Issue by L4rS6** [NetApp/trident#324]
I'm unable to configure docker volume plugin for e-series which uses CHAP as authentication (two-way, mutual). Is this currently not supported, or did I misconfigure something?

I always get errors during path discovery:
`Dec 19 14:47:30.635 myhost dockerd[1166]: time="2019-12-19T14:47:30+01:00" level=error msg="time=\"2019-12-19T13:47:30Z\" level=error msg=\"Problem adding backend.\" backendErr=\"problem initializing storage driver 'eseries-iscsi': could not establish iSCSI session: could not run iSCSI discovery: exit status 19\" handler=Bootstrap newBackendExternal=\"&{  block {0xc0001ba000 localhost 8443 false false   10.0.0.4 10.0.0.5  .+  10.0.4.4 netappdvp linux_dm_mp {map[]   {{1G}}} []} map[] failed false []}\"" plugin=4f2663c771c4c18f53a27319xxxxef95fae4bd189e0186c85e12becdac7d8ebf
`

**Comment by gtehrani** [comment]
Tracking...please provide details on your CO when available.

**Comment by gnarl** [comment]
Closing this issue as the last Trident release that includes E-Series as a supported storage backend is Trident v21.04.
