### ISSUE TITLE
512e/4K Block Size for SolidFire Volumes

### ISSUE THREAD

**Issue by BrianVanEtten** [NetApp/trident#33]
All of my Trident provisioned volumes have a block size of 4K and I'm not able to specify 512e. The only way to set this is upon volume creation. Is the ability to choose this block size on the roadmap in the future?

**Comment by j-griffith** [comment]
This is a bug IMO, we should be setting 512e to true by default.  So, now it's on the roadmap.  I'll work on making this default to 512e with an option to override to 4K.
