### ISSUE TITLE
Support Fedora CoreOS

### ISSUE THREAD

**Issue by ysakashita** [NetApp/trident#330]
We would like to use Fedora CoreOS in our Kubernetes's node.
Do you have support plan in a roadmap of NetApp/Trident ?
Could you support it if you don't have?

**Comment by gnarl** [comment]
@ysakashita, we don't have plans to support Fedora CoreOS on Trident's roadmap. Fedora CoreOS was just deemed production-ready and doesn't have a lot of demand at this time.

**Comment by ysakashita** [comment]
@gnarl Sure. I hope Fedora CoreOS users increase.

**Comment by ysakashita** [comment]
As you may know, CoreOS announced that On May 26, 2020, CoreOS Container Linux will reach its end of life and will no longer receive updates. 
https://coreos.com/os/eol/

The EOL is faster than I expected...

Current Trident supports CoreOS Container Linux.
https://netapp-trident.readthedocs.io/en/latest/support/requirements.html#supported-host-operating-systems

If Trident don't support Fedora CoreOS until end of CoreOS Container Linux, we must migrate to other OS.
Could you have a migration plan of support OS from CoreOS Container Linux to other OS?
Also please let me know the end of support the CoreOS in Trident.

**Comment by ysakashita** [comment]
We don’t need it now. so I close it. 
Please re-open if you need.
