### ISSUE TITLE
Cannot delete trident namespace

### ISSUE THREAD

**Issue by superbrothers** [NetApp/trident#331]
**Describe the bug**
After running `tridentctl uninstall -n trident`, I tried to delete trident namespace, but it failed due to finalizers of Trident custom resources.

```
$ tridentctl uninstall -n trident
$ kubectl delete ns trident --wait=false
$ kubectl get ns trident
NAME      STATUS        AGE
trident   Terminating   25m
$ kubectl get trident -n trident
NAME                                       VERSION
tridentversion.trident.netapp.io/trident   19.10.0

NAME                                     AGE
tridentnode.trident.netapp.io/minikube   25m
$ kubectl get -n trident tridentversions.trident.netapp.io -o yaml  -o jsonpath='{.items[*].metadata.finalizers}'
[trident.netapp.io]
```

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [e.g. 19.10] 19.10.0
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml] `tridentctl install -n trident`
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: [e.g. 1.15.1] 1.16.5
- Kubernetes orchestrator: [e.g. OpenShift v3.11, Rancher v2.3.3] minikube version: v1.6.1
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: [e.g. RHEL 7.6, Ubuntu 16.04]
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7]
- Other:

**To Reproduce**

```
$ minikube start --kubernetes-version=v1.16.5
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:47:40Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.4", GitCommit:"224be7bdce5a9dd0c2fd0d46b83865648e2fe0ba", GitTreeState:"clean", BuildDate:"2019-12-11T12:37:43Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
$ tridentctl version --client
+----------------+
| CLIENT VERSION |
+----------------+
| 19.10.0        |
+----------------+
$ tridentctl install -n trident
$ tridentctl version -n trident
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 19.10.0        | 19.10.0        |
+----------------+----------------+
$ tridentctl uninstall -n trident
$ kubectl delete ns trident --wait=false
namespace "trident" deleted
$ kubectl get ns trident
NAME      STATUS        AGE
trident   Terminating   2m9s
$ kubectl get trident -n trident
NAME                                       VERSION
tridentversion.trident.netapp.io/trident   19.10.0
```

**Expected behavior**
Just running `kubectl delete ns trident`, `trident` namespace is deleted.

**Additional context**

**Comment by superbrothers** [comment]
The workaround for this issue is the below:
```bash
# Remove finalizers from all Trident custom resources
for obj in $(kubectl get trident -n trident -o name); do kubectl get -n trident "$obj" -o json | jq -r '.metadata.finalizers = null' | kubectl apply -f-; done
# Then, delete trident namespace
kubectl delete ns trident
```

**Comment by zakkg3** [comment]
I did something similar before finding this issue. Basically deleting the api-resoruces:

`kubectl delete -n trident $(kubectl api-resources --verbs=list --namespaced -o name | xargs -n 1 kubectl get --show-kind --ignore-not-found  -n trident -o name)`

**Comment by abelk-bw** [comment]
I ran into a similar scenario. Have you tried using the `tridentctl obliviate crd` command? This will clean up all of the CRD and should clear the finalizers holding onto the namespace.

Ref:
https://netapp-trident.readthedocs.io/en/stable-v19.10/kubernetes/troubleshooting.html

**Comment by gnarl** [comment]
From the Trident [documentation](https://netapp-trident.readthedocs.io/en/stable-v20.01/kubernetes/troubleshooting.html#troubleshooting), "To completely remove Trident, execute the tridentctl obliviate crd command. This will remove all CRD objects and undefine the CRDs. Trident will no longer manage any PVs it had already provisioned. Remember that Trident will need to be reconfigured from scratch after this."

Will using the tridentctl obliviate crd command solve the issue you are reporting?

**Comment by kodo651** [comment]
Hi!

That solved the problem. I needed to issue the command twice because first
time it got stuck. Nevertheless many thanks for your help!

Cheers

**Comment by gnarl** [comment]
Closing this issue as resolved as a solution was provided.
