### ISSUE TITLE
tridentctl oblivate alpha-snapshot-crd faild

### ISSUE THREAD

**Issue by inajob** [NetApp/trident#337]
**Describe the bug**

```
$ tridentctl oblivate alpha-snapshot-crd
Error: no Auth Provider found for name "oidc"
```

We set kube-apiserver Authentication method to OIDC.(https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)

**Environment**

- Trident version: 20.01.0
- Trident installation flags used: `trident install -n trident`
- Container runtime: 
- Kubernetes version: 1.17.2
- Kubernetes orchestrator: original
- Kubernetes enabled feature gates: -
- OS: ContainerLinux
- NetApp backend types: none

**To Reproduce**

exec `tridentctl oblivate alpha-snapshot-crd` to the kube-apiserver which use OIDC.

**Expected behavior**

Pass `tridentctl oblivate alpha-snapshot-crd` without errors.

**Comment by gnarl** [comment]
HI @inajob,

Did you review the [upgrade notice](https://netapp-trident.readthedocs.io/en/stable-v20.01/kubernetes/upgrading.html#upgrading-trident)and [blog post](https://netapp.io/2020/01/30/alpha-to-beta-snapshots/) regarding Alpha Snapshots prior to running the obliviate command?

**Comment by inajob** [comment]
@gnarl 

Yes I read these posts.

We haven't use Alpha Snapshots feature.
But trident v19.10.0 deploied alpha snapshot crd, so I want to delete these CRDs by `tridentctl obilvate alpha-snapshot-crd`.

**Comment by gnarl** [comment]
To get past this issue you can delete the alpha CRDs manually. This looks like an auth provider issue in your environment. Contact [NetApp Support](https://mysupport.netapp.com/) if you still need assistance.
