### ISSUE TITLE
Generate custom yaml without a Kubernetes cluster

### ISSUE THREAD

**Issue by superbrothers** [NetApp/trident#339]
**Describe the solution you'd like**

I'd like to generate custom manifest files without using a cluster.

**Describe alternatives you've considered**

To generate custom yaml with `tridentctl install --generate-custom-yaml` needs a Kubernetes cluster which can connect. If there is no cluster, the command will fail, but the Kubernetes cluster should not be necessary to do that.

**Additional context**

```
$ tridentctl version --client
+----------------+
| CLIENT VERSION |
+----------------+
| 20.01.0        |
+----------------+
$ tridentctl install --generate-custom-yaml
FATA Install pre-checks failed; could not initialize Kubernetes client; could not find the Kubernetes CLI; Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-18T23:30:10Z", GoVersion:"go1.13.5", Compiler:"gc", Platform:"linux/amd64"}
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```

**Comment by ysakashita** [comment]
https://github.com/NetApp/trident/issues/247
にてHelm Chartがサポートとなりました。
本Issueの目的は達成されたかと思うので、Closeします。

**Comment by gnarl** [comment]
`tridentctl install --generate-custom-yaml` requires access to the Kubernetes cluster to determine the Kubernetes version and the version of some Kubernetes CRDs. This information is used to generate the YAML to install Trident in that environment.
