### ISSUE TITLE
PVC create fails during ONTAP upgrade

### ISSUE THREAD

**Issue by forgosh** [NetApp/trident#340]
**Describe the bug**
During an ONTAP cluster upgrade a PVC is submitted which is scheduled on an aggregate of a failed over node. The PVC remains in a pending state and Trident logs show:

time="2020-02-06T22:37:51Z" level=debug msg="Volume event." eventType=Normal message="encountered error(s) in creating the volume: [Failed to create volume pvc-522156b9-dc3f-432d-af06-e9c032e7356b on storage pool aggr_cl01_06_SSD from backend ontap-nas: backend cannot satisfy create request for volume FS_pvc_522156b9_dc3f_432d_af06_e9c032e7356b: (ONTAP-NAS pool aggr_cl01_06_SSD/aggr_cl01_06_SSD; error creating volume FS_pvc_522156b9_dc3f_432d_af06_e9c032e7356b: API status: failed, Reason: Failed to create the volume on node \"rtp-sa-cl01-05\". Reason: Operation is disallowed on an aggregate which is not home. , Code: 13130)]" name=pvc-522156b9-dc3f-432d-af06-e9c032e7356b reason=ProvisioningFailed

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.01
- Trident installation flags used: -n
- Container runtime: on-prem NKS
- Kubernetes version: 1.15.0
- Kubernetes orchestrator: Kubernetes (NKS)
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: Debian
- NetApp backend types: ONTAP-NAS, 4 node 8020 cluster, ONTAP 9.6P2 upgrading to ONTAP 9.7
- Other:

**To Reproduce**
Perform ONTAP upgrade and when one node is taken over, submit a PVC

**Expected behavior**
The PVC will remain in a pending state

**Additional context**

**Comment by adkerr** [comment]
I'm not sure I understand the problem. You state that the PVC remains pending but then say that is what you expect to happen. ONTAP does not allow us to create volumes on aggrs that are not "home." So the volume create request will fail and the PVC will remain pending. Every minute or so k8s will retry the create and we will continue to fail until the aggr is back "home." Is this not the behavior you are seeing?

**Comment by forgosh** [comment]
I meant that on recreating the problem I’d expect that to happen. My expectation was that an ONTAP upgrade would be nondisruptive to Trident operations.

Seth Forgosh
Solution Architect - Open Ecosystem, Virtualization & Flash

________________________________

**Comment by clintonk** [comment]
Likewise, I fail to see the problem.  If the only aggregate that can satisfy a provisioning request happens to be owned by a failed-over node, and ONTAP disallows new volumes on aggrs in that state, then we're kinda stuck.  OTOH, if the ONTAP cluster has multiple aggrs that can satisfy a provisioning request, and one or more of those aggrs are on a node that isn't failed over (or even a different cluster), Trident will try them in turn until one succeeds.  Failing that, Kubernetes will keep trying and the provisioning will eventually succeed when the upgrade is done.  Are you seeing something different?

**Comment by forgosh** [comment]
Agreed. If ONTAP disallows creating volumes then there isn’t an issue. I was not aware that this was the case.

Seth Forgosh
Solution Architect - Open Ecosystem, Virtualization & Flash

________________________________

**Comment by forgosh** [comment]
Confirmed that is the case. We can close the issue.

Seth Forgosh
Solution Architect - Open Ecosystem, Virtualization & Flash

________________________________
