### ISSUE TITLE
Deprecated extensions/v1beta1 API on 20.01.0 on Openshift 4.3 and 4.3.1

### ISSUE THREAD

**Issue by dbarreda** [NetApp/trident#346]
I'm getting constant warnings for "A client in the cluster is using deprecated extensions/v1beta1 API that will be removed soon." This is planned to be upgraded in future versions?

**Comment by gnarl** [comment]
@dbarreda The apiVersion is planned to be upgraded in Trident 20.04. We believe that we have some work to do to support v1 CRDs.

**Comment by gnarl** [comment]
This was fixed in the [Trident 20.04](https://github.com/NetApp/trident/blob/master/CHANGELOG.md) release.
