### ISSUE TITLE
tridentctl install faild with auth provider

### ISSUE THREAD

**Issue by inajob** [NetApp/trident#348]
**Describe the bug**

Install failed.

```
$ tridentctl install -n trident
INFO Starting Trident installation.                namespace=trident
INFO Created namespace.                            namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Created custom resource definitions.          namespace=trident
ERRO Could not create CRD client; no Auth Provider found for name "oidc"
ERRO Could not delete CRDs; no Auth Provider found for name "oidc"
FATA Install failed; no Auth Provider found for name "oidc".  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.
```

We set kube-apiserver Authentication method to OIDC.(https://kubernetes.io/docs/reference/access-authn-authz/authentication/#configuring-the-api-server)

**Environment**

- Trident version: 20.01.0
- Trident installation flags used: `trident install -n trident`
- Container runtime: 
- Kubernetes version: 1.17.2
- Kubernetes orchestrator: original
- Kubernetes enabled feature gates: -
- OS: ContainerLinux
- NetApp backend types: none

**To Reproduce**

Exec `trident install -n trident` to the kube-apiserver which use OIDC.

**Expected behavior**

Install trident successflly.

**Additional context**

The workaround of this issue is "install twice".
I can install trident successfully in second time `trident install -n trident`.

```
# 2nd try!
$ tridentctl install -n trident
INFO Starting Trident installation.                namespace=trident
INFO Created service account.
INFO Created cluster role.
INFO Created cluster role binding.
INFO Added finalizers to custom resource definitions.
INFO Created Trident pod security policy.
INFO Created Trident service.
INFO Created Trident secret.
INFO Created Trident deployment.
INFO Created Trident daemonset.
INFO Waiting for Trident pod to start.
```

**Comment by gnarl** [comment]
The enhancement to provide additional auth providers was added in the [Trident 20.04](https://github.com/NetApp/trident/blob/master/CHANGELOG.md) release.
