### ISSUE TITLE
doesn't delete old node's IQN initiator

### ISSUE THREAD

**Issue by inajob** [NetApp/trident#352]
**Describe the bug**

I rolling updated my kubernetes cluster. My updatig way is createing new Node and joining the cluster and deleteing old Node again and again.

I also use trident and volume backed by ontap-san.
I noticed that my igroup has old node's IQN initiators yet.

**Environment**

- Trident version: 20.01.1
- Trident installation flags used: `trident install -n trident`
- Container runtime: -
- Kubernetes version: 1.17.2
- Kubernetes orchestrator: original
- Kubernetes enabled feature gates: -
- OS: ContainerLinux
- NetApp backend types: -
- Other:

**To Reproduce**

As I mentioned, add new Node and drain and delete old Node.

**Expected behavior**

igroup has only IQN initiators which is a member of the cluster.

**Additional context**

We automate this rolling update method, so we have to delete old IQN initiator manually.
I want trident to delete old ones.

**Comment by adkerr** [comment]
This is actually working as designed, as when the code was implemented we didn't have a great way to reliably detect if/when it was safe to remove the iqn. That said, we do plan to implement the auto-removal of inactive iqns in a future update.

**Comment by inajob** [comment]
@adkerr 
OK! I'm looking forward to implement the auto-removal feature!

**Comment by inajob** [comment]
@adkerr 
When will you implement this feature?
I would like to use this feature in next release(20.04.0).

**Comment by gnarl** [comment]
This enhancement is included in the Trident 20.07 release.
