### ISSUE TITLE
Max NetApp Volume information

### ISSUE THREAD

**Issue by Si-Constable** [NetApp/trident#354]
The Current documentation refers to out of date information in regards to the maximum volume count. the Volume count per HA should be referenced to the net app HWU, as depending on the platform and the ONTAP version there are a different amount of online volumes supported on the netapp.
Ontap 9.7 supports 5000 volumes per HA pair but still maxes out at 12K per cluster.
it should be noted that a single node can handle 5000 online volumes in the event of a HA Takeover.
This information is very useful in planning a K8/openshift ecosystem when using netapp and trident.

**Comment by gnarl** [comment]
This will be fixed in the Trident 20.04 release.
