### ISSUE TITLE
Unable to install trident 19.07.2 on a kube cluster running v1.14

### ISSUE THREAD

**Issue by hsimran13** [NetApp/trident#357]
Hello,

We have a small test cluster running kubernetes v1.14 and are working on testing trident with a older Ontap 8.3.x netapp filer to provide persistent storage for our containers.  I am running into a issue with installing trident v19.07.2 and it seems to not like my k8 version even though is seems to support anything above v1.14:

# ./tridentctl install -n trident
FATA Install pre-checks failed; could not initialize Kubernetes client; Trident 19.07.2 supports Kubernetes versions in the range [1.11, 1.15]

# kubectl version
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0+724e12f93f", GitCommit:"420c3d6212a959907360fb0b6545f2f0ab173271", GitTreeState:"clean", BuildDate:"2019-11-05T08:03:47Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"14+", GitVersion:"v1.14.6+dc8862c", GitCommit:"dc8862c", GitTreeState:"clean", BuildDate:"2019-11-07T17:15:37Z", GoVersion:"go1.12.12", Compiler:"gc", Platform:"linux/amd64"}

# kubectl get nodes
NAME      STATUS   ROLES    AGE   VERSION
node10   Ready    worker   27d   v1.14.6+c7d2111b9
node1   Ready    worker   27d   v1.14.6+c7d2111b9
node12   Ready    worker   27d   v1.14.6+c7d2111b9
node13   Ready    worker   27d   v1.14.6+c7d2111b9
node16   Ready    master   27d   v1.14.6+c7d2111b9
node30   Ready    master   27d   v1.14.6+c7d2111b9
node31   Ready    master   27d   v1.14.6+c7d2111b9

Any help/guidance with this issue would be greatly appreciated!

Thanks,
-Simran

**Comment by gnarl** [comment]
Try installing Trident with the debug flag to see if another error is reported in the logs. If you need faster assistance then please contact [NetApp support](https://mysupport.netapp.com/info/web/findsupport.html).

**Comment by hsimran13** [comment]
I was able to download a older openshift client binary 4.1 and that seems to have worked.  However, I am now seeing the following error message:

FATA Install failed; could not create the Kubernetes CSI Driver object; could not delete csidriver custom resource; csidrivers.storage.k8s.io "csi.trident.netapp.io" is forbidden: User "system:serviceaccount:trident:trident-installer" cannot delete resource "csidrivers" in API group "storage.k8s.io" at the cluster scope.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

I am logged in as kubeadmin in the oc environment using oc login.

-Simran

**Comment by gnarl** [comment]
Can you try uninstalling Trident v19.02 and installing Trident 20.01.1? There was a fix in Trident for how oc reports versions and a fix for PodSecurityPolicies. Also, are you doing a custom install and if so what is in the custom yaml?

**Comment by balaramesh** [comment]
@hsimran13 the OpenShift client reports its versions in different formats, from the 3.11 client to the 4.2 and 4.3 clients. This was addressed with Trident 19.10 (https://github.com/NetApp/trident/commit/fc1e32735675ec161d39b94b68b07d2be185de2d)

**Comment by hsimran13** [comment]
Unfortunately, I am unable to use trident v20.x or 19.10 since my netapp is stuck at 8.3.x and cannot be upgraded to 9.x due to hardware limitations.  This was meant to be a test to see how trident could fit into our long term kubernetes platforms.  The documentation says that v19.07.x support Ontap 8.3.

**Comment by clintonk** [comment]
@hsimran13 As a workaround in a test environment, you could move oc 3.11 to the front of your path before running the Trident installer.

**Comment by hsimran13** [comment]
I got around that using the 4.1 openshift tools version but now I am getting a different error that I can open another issue for after searching the issue db:

FATA Install failed; could not create the Kubernetes CSI Driver object; could not delete csidriver custom resource; csidrivers.storage.k8s.io "csi.trident.netapp.io" is forbidden: User "system:serviceaccount:trident:trident-installer" cannot delete resource "csidrivers" in API group "storage.k8s.io" at the cluster scope.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

Thanks,
-Simran

**Comment by clintonk** [comment]
@hsimran13 You may be able to use the --generate-custom-yaml option to tweak the cluster role to grant that permission.

**Comment by gnarl** [comment]
@hsimran13 Were you able to install Trident?

**Comment by gnarl** [comment]
Closing this as we haven't heard back on the reported issue.
