### ISSUE TITLE
Add PVC labels to PV

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#359]
**Describe the solution you'd like**
A PVC definition file can include a bunch of labels.
However, Trident does not use them when it creates the PV corresponding to the PVC.
It would be great if Trident could retrieve these labels & add them to the PV definition.

**Describe alternatives you've considered**
The sole alternative is to manually edit the PV & add labels

**Additional context**
WIthout these labels, it can be challenging to get the PV associated to an application.

**Comment by gnarl** [comment]
Hi @YvosOnTheHub,

Trident isn't directly in the path to be able to perform this function. This is a feature that the CSI community would need to implement in the [external-provisioner sidecar](https://kubernetes-csi.github.io/docs/external-provisioner.html).
