### ISSUE TITLE
tridentctl not loading the kube context

### ISSUE THREAD

**Issue by gfvirga** [NetApp/trident#360]
**Describe the bug**

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.01.1
- Trident installation flags used: -d -n trident
- Container runtime: gitlab-runner on openshift
- Kubernetes version: v1.16.2
- Kubernetes orchestrator: [e.g. OpenShift v4.3.5
- Kubernetes enabled feature gates: none
- OS: RHEL 8.1
- NetApp backend types: ONTAP
- Other:

**To Reproduce**
Run tridentctl in a gitlab-runner

**Expected behavior**
Installation to use the context from oc or kubectl

**Additional context**
Output from gitlab-runner
```
 $ oc project trident
 Now using project "trident" on server "https://api.openshift.company.com:6443".
 $ kubectl config get-contexts
 CURRENT   NAME                                         CLUSTER                   AUTHINFO                             NAMESPACE
           default/api-openshift-company-com:6443/kube:admin   api-openshift-company-com:6443   kube:admin/api-openshift-company-com:6443   default
 *         trident/api-openshift-company-com:6443/kube:admin   api-openshift-company-com:6443   kube:admin/api-openshift-company-com:6443   trident
 $ oc config get-contexts
 CURRENT   NAME                                         CLUSTER                   AUTHINFO                             NAMESPACE
           default/api-openshift-company-com:6443/kube:admin   api-openshift-company-com:6443   kube:admin/api-openshift-company-com:6443   default
 *         trident/api-openshift-company-com:6443/kube:admin   api-openshift-company-com:6443   kube:admin/api-openshift-company-com:6443   trident

 $ tridentctl install -d -n trident
 level=debug msg="Initialized logging." logLevel=debug
 level=debug msg="Trident image: netapp/trident:20.01.1"
 level=fatal msg="Install pre-checks failed; could not initialize Kubernetes client; unable to load in-cluster configuration, KUBERNETES_SERVICE_HOST and KUBERNETES_SERVICE_PORT must be defined"
```

**Comment by gfvirga** [comment]
It seems that this has happened before: https://github.com/NetApp/trident/issues/202 
--use-cluster=false isn't working either.

**Comment by gnarl** [comment]
Prior to invoking the Trident installer the KUBECONFIG env variable needs to be set. If you can do this it should resolve your issue.

FYI, we are moving to using an Operator to handle Trident installs and upgrades in future Trident releases.

**Comment by gnarl** [comment]
Closing this issue as a response wasn't received after providing a solution to the OP.
