### ISSUE TITLE
Make the storagePrefix parameter available for Virtual Storage Pools

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#362]
**Describe the solution you'd like**
The _storagePrefix_ parameter should be part of the options you can set when using Virtual Pools.

**Describe alternatives you've considered**
The alternative is to create multiple _backend_ files, each one having its own _storagePrefix_ parameter set.

**Additional context**
If someone wants to explicitly isolate Qtree PVC (ONTAP-NAS-ECONOMY driver) or group a project under one explicit volume, a good idea would be to use the _storagePrefix_ parameter.
As the volume hosting the Qtrees will also have the prefix in its name, you could then build entire projects with several PVC under one volume. This could be later used for B&R procedure...
The alternative is to create several _backend_ files, but that quickly can become heavy in terms of management...

**Comment by gnarl** [comment]
Hi @YvosOnTheHub,

Your enhancement request is appreciated but the change would add a number of complexities to maintain. This includes modifying the virtual pool prefix for existing volumes, being able to track volumes, and defining a volume level attribute that is normally done accomplished in the backend file. Currently, once the volume is created there is not a way to tie that volume to the virtual pool used to filter it to a particular backend. This was done to provide the user the ability to modify existing virtual pools which may change the backend selection. 

Please keep the requests coming but we are not able to fulfill this one at this time.
