### ISSUE TITLE
trident-azure netapp files

### ISSUE THREAD

**Issue by rushins** [NetApp/trident#363]
Hello Support, 
we have Azure NetApp files in Azure US EAST and we have Kubernetes Distribution Rancher 2.3.5 .

 I have configured Trident 20.0.1 latest and getting the following errors while creating the PVC. 

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [e.g. 19.10] 20.0.01
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml] tridentctl 
- Container runtime: [e.g. Docker 19.03.1-CE] 17.03.2,
- Kubernetes version: [e.g. 1.15.1] 1.17
- Kubernetes orchestrator: [e.g. OpenShift v3.11, Rancher v2.3.3] Rancher 2.3.5
- Kubernetes enabled feature gates: [e.g. CSINodeInfo] Yes
- OS: [e.g. RHEL 7.6, Ubuntu 16.04]: RHEL 7 /SUSE 12
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7] CVS
- Other:

Here is the error.
---------------
time="2020-03-21T17:49:57Z" level=info msg="Running Trident storage orchestrator." binary=/usr/local/bin/trident_orchestrator build_time="Fri Feb 28 15:08:01 UTC 2020" version=20.01.1
time="2020-03-21T17:50:11Z" level=warning msg="Could not get server resources, defaulting to Kubernetes flavor." error="unable to retrieve the complete list of server APIs: 
metrics.k8s.io/v1beta1: the server is currently unable to handle the request"
time="2020-03-24T19:05:35Z" level=warning msg="Requested size is too small. Setting volume size to the minimum allowable (100 GB)." name=anf-b566270b6d484edfbfcf71631ef7fe00 size=1073741824
time="2020-03-24T19:07:48Z" level=warning msg="Failed to create the volume on this backend." backend=azurenetappfiles_54614 backendUUID=9c339874-b29b-4347-a719-6f8a9b3b381d error="new volume requested with location different from capacity pool location" pool=azurenetappfiles_54614_pool volume=pvc-4e3cef6c-6029-4dda-a885-9a2bf263bb9b
time="2020-03-24T19:07:48Z" level=error msg="GRPC error: rpc error: code = Unknown desc = encountered error(s) in creating the volume: [Failed to create volume pvc-4e3cef6c-6029-4dda-a885-9a2bf263bb9b on storage pool azurenetappfiles_54614_pool from backend azurenetappfiles_54614: new volume requested with location different from capacity pool location]"
time="2020-03-24T19:07:49Z" level=info msg="Found PVC for requested volume pvc-4e3cef6c-6029-4dda-a885-9a2bf263bb9b." UID=4e3cef6c-6029-4dda-a885-9a2bf263bb9b name=akg-test-anf namespace=default size="{{1073741824 0} {<nil>} 1Gi BinarySI}" storageClass=azure-netapp-files
time="2020-03-24T19:07:49Z" level=info msg="Found storage class for requested volume pvc-4e3cef6c-6029-4dda-a885-9a2bf263bb9b." name=azure-netapp-files

---------

BR,
Rushi.

**Comment by gnarl** [comment]
It is difficult to determine what is exactly wrong with the provided information. You should look at resolving the "new volume requested with location different from capacity pool location" error first though.

**Comment by gnarl** [comment]
This issue was resolved by NetApp Support.

**Comment by rushins** [comment]
no ..the underline issue was kubernetes PODs first that i resolved with our team and after installation was good, 

We still having one  issue that the Volume deletion is not happening in AZure NetApp files but in K8S the PV/PVC is deleted but the volume is still in AzureNetApp files when checked Azure portal. ? so we need support on that.
