### ISSUE TITLE
Exposing the Trident information metric

### ISSUE THREAD

**Issue by superbrothers** [NetApp/trident#364]
**Describe the solution you'd like**
We want to use the Trident information metric like the below:

```
# HELP trident_info Information about the Trident.
# TYPE trident_info gauge
trident_info{version="20.01.1"} 1
```

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by gnarl** [comment]
This was added in the expanded Prometheus metrics in the Trident 20.07.0 release.
