### ISSUE TITLE
tridentctl install options enhancement for automated installs

### ISSUE THREAD

**Issue by nbs-richardphillips** [NetApp/trident#367]
In order to script unattended installs it would be useful if tridentctl could use either the --config option similar to the OpenShift "oc" binary, or perhaps accept a account/token which could be generated for the purpose of the install, using for example, ansible.

It's not clear whether I could use the KUBECONFIG to point to an alternative .kube/config file

**Comment by gnarl** [comment]
@nbs-richardphillips using KUBECONFIG to point to an alternative .kube/config file will work.

**Comment by gnarl** [comment]
@nbs-richardphillips Setting the KUBECONFIG environment variable is also included in the [Trident documentation](https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/tridentctl-install.html?highlight=kubeconfig#before-you-begin).
