### ISSUE TITLE
PVC pending on new 20.01.1 install

### ISSUE THREAD

**Issue by roycec** [NetApp/trident#368]
**Describe the bug**
After the install of Trident 20.01.1 and creating a (NAS-)Backend and a basic storage class, I tried to create a test pv/pvc to check if everything works. But the pvc is pending. Tridentctl and the pvc shows me the errors

`time="2020-04-02T15:32:19Z" level=info msg="Found PVC for requested volume pvc-63e8998f-df1f-404c-b242-fc0a7cc0675b." UID=63e8998f-df1f-404c-b242-fc0a7cc0675b name=basic namespace=default size="{{1073741824 0} {<nil>} 1Gi BinarySI}" storageClass=basic-netapp
time="2020-04-02T15:32:19Z" level=info msg="Found storage class for requested volume pvc-63e8998f-df1f-404c-b242-fc0a7cc0675b." name=basic-netapp
time="2020-04-02T15:32:19Z" level=error msg="ONTAP-NAS pool serv0914_aggr_daten02/serv0914_aggr_daten02; error creating volume prod_pvc_63e8998f_df1f_404c_b242_fc0a7cc0675b: API status: failed, Reason: Ruleset default not found. Reason: entry doesn't exist. , Code: 13001"
time="2020-04-02T15:32:19Z" level=warning msg="Failed to create the volume on this backend." backend=NetappNAS backendUUID=fecff922-117f-47ba-a9ad-7f1232e6e4d6 error="backend cannot satisfy create request for volume prod_pvc_63e8998f_df1f_404c_b242_fc0a7cc0675b: (ONTAP-NAS pool serv0914_aggr_daten02/serv0914_aggr_daten02; error creating volume prod_pvc_63e8998f_df1f_404c_b242_fc0a7cc0675b: API status: failed, Reason: Ruleset default not found. Reason: entry doesn't exist. , Code: 13001)" pool=serv0914_aggr_daten02 volume=pvc-63e8998f-df1f-404c-b242-fc0a7cc0675b                                     
time="2020-04-02T15:32:19Z" level=error msg="GRPC error: rpc error: code = Unknown desc = encountered error(s) in creating the volume: [Failed to create volume pvc-63e8998f-df1f-404c-b242-fc0a7cc0675b on storage pool serv0914_aggr_daten02 from backend NetappNAS: backend cannot satisfy create request for volume prod_pvc_63e8998f_df1f_404c_b242_fc0a7cc0675b: (ONTAP-NAS pool serv0914_aggr_daten02/serv0914_aggr_daten02; error creating volume prod_pvc_63e8998f_df1f_404c_b242_fc0a7cc0675b: API status: failed, Reason: Ruleset default not found. Reason: entry doesn't exist. , Code: 13001)]"`

For this environment we created a new SVM with its own set of credentials. 

**Environment**

- Trident version: 20.01.1
- Trident installation flags used: -n trident --use-custom-yaml
- Container runtime: Docker 1.13.1 (RHEL 7)
- Kubernetes version: 1.16.3
- Kubernetes orchestrator: Rancher v2.3.3
- Kubernetes enabled feature gates: 
- OS: RHEL 7.7
- NetApp backend types: [ONTAP 9.3 P11]
- Other:

**To Reproduce**
- Install Trident 20.01.1 with custom config (internal registry)
- Create backend
```
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "backendName": "NetappNAS",
    "managementLIF": "x.x.x.x",
    "dataLIF": "x.x.x.x",
    "svm": "xxx",
    "username": "vsadmin",
    "password": "xxxxxxxxxxxxxx",
    "storagePrefix": "prod_",
}
```

- Create storage class
```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: basic-netapp
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-nas"
```
The provisioner gets changed to the new CSI provisioner.

- Create PVC
```
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: basic
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: basic-netapp
```

**Expected behavior**
PV gets provisioned immediately

**Additional context**
Maybe this could be an issue with the new SVM we created?

**Comment by adkerr** [comment]
The provisioner in your storage class should be `csi.trident.netapp.io`

**Comment by roycec** [comment]
Yes, if I apply this I get this result

```
$ k describe sc basic-netapp                                                         
Name:                  basic-netapp
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           csi.trident.netapp.io
Parameters:            backendType=ontap-nas
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

In the logs I can seen the provisioner gets "updated".

```
time="2020-04-02T15:25:45Z" level=info msg="Replaced storage class so it works with CSI Trident." name=basic-netapp newPr
ovisioner=csi.trident.netapp.io oldProvisioner=netapp.io/trident 
```

**Comment by adkerr** [comment]
`Ruleset default not found. Reason: entry doesn't exist.` sounds like there may not be a default export policy in your SVM?

**Comment by roycec** [comment]
I'll have to check with my collegue

**Comment by roycec** [comment]
Ok, that was it. The default export policy has been renamed. We reverted it, and now the pv gets created without problems. Thanks!
