### ISSUE TITLE
PKS integration 20.01 (CSI driver)

### ISSUE THREAD

**Issue by Busesz** [NetApp/trident#371]
**Describe the Issue**

In a PKS created Kubernetes cluster with NSX-T, cannot integrate with Trident, the pods with shorter generated-id will tell: Error failed to start container "trident-main": Error response from daemon: linux mounts: path / is mounted on / but it is not a shared mount.

**Environment**

- Trident version: stable/v20.01
- Trident installation flags used: -n trident --use-custom-yaml --kubelet-dir=/var/vcap/data/kubelet
- Container runtime: Docker 18.09.9
- Kubernetes version: 1.16.7
- Kubernetes orchestrator: Enterprise PKS
- OS: Ubuntu 16.04
- NetApp backend types: ONTAP 9
- Other: PKS version: 1.7.0-build-26, enabled Allow Privileged

**To Reproduce**
Download and install the PKS, Kubectl, Tridentctl. 
Needed a PKS created Kubernetes with Allow Privileged mode checked plan.
pks get-credentials <kubernetescluster>
kubectl get nodes/ kubectl get pods --all-namespaces (make sure you can access to the kubernetes cluster)
run the "tridentctl install -n trident --use-custom-yaml --kubelet-dir=/var/vcap/data/kubelet"

**Expected behavior**
The pods wont start, and will tell the same error message.

**Comment by gnarl** [comment]
Hi @Busesz, we don't have a PKS environment with NSX-T to try and reproduce this error. Trident has been successfully installed in other PKS environments though. Please contact [NetApp Support](https://mysupport.netapp.com/site/) for assistance on this issue.

**Comment by Busesz** [comment]
Hi @gnarl, thanks a lot!
So the Enterprise PKS should be compatible with the Trident.

**Comment by gnarl** [comment]
@Busesz were you able to solve your issue?

**Comment by Busesz** [comment]
Nope, it is not working.

**Comment by gnarl** [comment]
@Busesz This appears to be a known issue with the Docker service on Ubuntu. Please check the following links.
[https://success.docker.com/article/not-a-shared-mount-error](https://success.docker.com/article/not-a-shared-mount-error)
[https://github.com/kubernetes/kubernetes/issues/61058](https://github.com/kubernetes/kubernetes/issues/61058)
