### ISSUE TITLE
Support on k8s 1.18

### ISSUE THREAD

**Issue by sfkwan** [NetApp/trident#377]
What's the plan to support k8s 1.18 because our company is starting to adopt k8s?

**Comment by balaramesh** [comment]
@sfkwan the upcoming 20.04 release is targeted to support k8s 1.18.

**Comment by an-sy** [comment]
@balaramesh is there any timeline for the release 20.04 ?

**Comment by clintonk** [comment]
@an-sy  20.04 == April 2020.  So, this month!

**Comment by sfkwan** [comment]
Thanks for the fast response.  Looking forward for it.
