### ISSUE TITLE
Year and copyright owner missing in LICENSE

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#381]
See https://github.com/NetApp/trident/blob/master/LICENSE#L189

**Comment by gnarl** [comment]
Hi @scaleoutsean,

Other projects, like [Kubernetes](https://github.com/kubernetes/kubernetes/blob/master/LICENSES/LICENSE), don't set the copyright in this file. When I read the appendix section it appears that this line is just an example in the License itself.

**Comment by scaleoutsean** [comment]
Ok, no problem - feel free to close it, I thought to highlight that in the case that was an oversight.
