### ISSUE TITLE
Grafana dashboard for netapp trident monitor

### ISSUE THREAD

**Issue by sfkwan** [NetApp/trident#382]
Our company would like to use Grafana for netapp trident metric monitor.  This is to ensure the healthiness of the production platform.  

Do you have any pre-built dashboard that we can use?

**Comment by YvosOnTheHub** [comment]
take a look at the following
https://github.com/YvosOnTheHub/LabNetApp/blob/master/Kubernetes_v2/Scenarios/Scenario03/Trident_Dashboard_Std.json
it could maybe be useful if you are looking at monitoring Trident

there is a screenshot on
https://github.com/YvosOnTheHub/LabNetApp/tree/master/Kubernetes_v2/Scenarios/Scenario03

**Comment by sfkwan** [comment]
@YvosOnTheHub thanks for the sharing.  This dashboard shows the statistics.  Are there any performance figure that we should pay attention?

**Comment by YvosOnTheHub** [comment]
@sfkwan I believe most Trident metrics are statistics.
However, the 2 following ones may be interesting to look at:
- trident_core_operation_duration_xyz
- trident_ontap_operation_duration_in_milliseconds_by_svm_xyz  

You will have latency numbers measured at the Trident level.

Keep in mind Trident is not on the data path, so it wont show performance data from the storage backend...

**Comment by sfkwan** [comment]
@YvosOnTheHub in that case can we monitor performance on netapp level using Grafana?

**Comment by ybizeul** [comment]
Hi @sfkwan you have a couple options, all based on NetApp Harvest. You can use your own Graphite and Grafana, and point NetApp Harvest (http://mysupport.netapp.com/tools/info/ECMLP2314554I.html?productID=61924) to it. Or you can use the NAbox Virtual Appliance that has everything pre-configured (https://nabox.org/)

That will give you a lot of dashboards and performance metrics regarding your ONTAP systems

**Comment by SeungYong-Baek** [comment]
Hello~

One of my customer has asked about the same issue.
Does NetApp has standard or official(?) grafana dashboard for trident?
I have checked "Trident_Dashboard_Std.json" at YvosOnTheHub's github links.
So, I am going to delivere the json sample to the customer. 
But, what I want to know more exactly is official dashboard which can be found at Grafana Dashboard web site.

Thank You,
SeungYong

**Comment by gnarl** [comment]
@SeungYong-Baek, @sfkwan, As @ybizeul points out you can provide your own Grafana or Graphite dashboard. These are highly customizable per an individual's requirements and not something we can support at this time. @YvosOnTheHub has provided a reference dashboard for Trident that can help you get started.
