### ISSUE TITLE
Customizable prefix for FlexVol

### ISSUE THREAD

**Issue by WTFKr0** [NetApp/trident#383]
Hi

We install trident on an Openshift 4.3 cluster recently, with a nas-economy backend (qtrees)
We specify a storagePrefix when creating the backend, like "MY_COMP_PREFIX_"
Then name are generated like these for the volume : 
`trident_qtree_pool_MY_COMP_PREFIX_XXXXXXXXXXXXXXX`

We have strong naming convention in volume names, and we want to customize the `trident_qtree_pool_` part or simply remove it.

I found that these values are hardcoded in:
https://github.com/NetApp/trident/blob/b9fbfe870a9f41461c445072214d812ba2e19020/storage_drivers/ontap/ontap_common.go#L61-L65
and
https://github.com/NetApp/trident/blob/b9fbfe870a9f41461c445072214d812ba2e19020/storage_drivers/ontap/ontap_nas_qtree.go#L126-L127

Is it possible to make these values customizable in the backend json file when we first create it ?

Thanx for reading

**Comment by WTFKr0** [comment]
After checking source code, I think something as simple as this can solve our problem
https://github.com/NetApp/trident/compare/master...WTFKr0:custom-prefix

**Comment by gnarl** [comment]
Hi @WTFKr0,

While we can appreciate your request we are unable to fulfill it in the near future. The change isn't as simple as you have suggested as both the Kubernetes and NDVP modes of operation must be supported. Trident uses the hardcoded prefix to accurately manage the correct FlexVols on a backend where many other FlexVols may exist.

**Comment by WTFKr0** [comment]
Hi and thanx for this answer

I understand that in many cases this hardcoded prefix is a good thing to separate volumes manages by trident from others volumes.
In our case, we wan't to manage this hardcoded prefix manually to match our naming conventions.

I'll check with the storage team if we can continue with the `trident_qtree_pool_` prefix but if they tell me no, we can't use trident so we can't use NetApp as our storage backend for our Openshift kubernetes cluster

Feel free to close this issue

**Comment by adkerr** [comment]
In the case of the NAS economy driver, as presently written, it could be dangerous for the prefix to match with your other flexvols. Trident uses this prefix to know which of the flexvols it has created to hold the qtrees and so it will start provisioning qtrees all over your cluster if all your flexvols have that same prefix.
