### ISSUE TITLE
Cannot expand PVC created by ontap-san-economy driver.

### ISSUE THREAD

**Issue by yh152** [NetApp/trident#384]
**Describe the bug**

Cannot expand PVC created by ontap-san-economy driver.

**Environment**

- OpenShift Container Platform 4.3.5
- Trident v20.01.1

**To Reproduce**
Steps to reproduce the behavior:Please see the attached files.

**Expected behavior**
Succeed to expand PVC when creating ontap-san-economy driver.

**Additional context**

Attaching the following files:
result.txt: Confirmation
　pvc-and-pod-economy2.yaml: yaml file used to create the first PV and pod
　pvc-and-pod-economy3.yaml: yaml file used to create the second PV and pod
[202004_trident.zip](https://github.com/NetApp/trident/files/4514414/202004_trident.zip)

**Comment by gnarl** [comment]
@yh152 are you still experiencing this issue? If you are please contact NetApp support for assistance in resolving your issue.

**Comment by yh152** [comment]
Hi, Chuck,

This is Yoshitaka Hamada.

>@yh152<https://github.com/yh152> are you still experiencing this issue? If you are please contact NetApp support for assistance in resolving your issue.

Thank you for your kind reply.Yes, still experiencing this.

*Unfortunatey, we cannot open your NetApp support case. Have no way. Is there any other way to solve this?


All the Best,
HAMADA, Yoshitaka


---------------------------------------------------------
  NEC: 8-50-67529 (050-3757-3018) mobile:+81-80-1038-0701
        ＼Orchestrating a brighter world
　　　　　　世界の想いを、未来へつなげる。
    http://jpn.nec.com/profile/solutionsforsociety/
------- Forwarded Message

**Comment by yasuoo-netapp** [comment]
Hi, I hit the same issue with 20.04.0.
I think this issue will be fixed in this commit. Is it correct?

https://github.com/NetApp/trident/commit/536aadc686df91e7a3a884e7c221c9237fe5f309

If yes, is this going to be included in the 20.07 release?

**Comment by gnarl** [comment]
This issue was resolved with commit [536aadc](https://github.com/NetApp/trident/commit/536aadc686df91e7a3a884e7c221c9237fe5f309) and is included in the Trident 20.07 release.
