### ISSUE TITLE
ontap-nas-economy driver validation failed

### ISSUE THREAD

**Issue by techie11** [NetApp/trident#385]
o	https://kb.netapp.com/app/answers/answer_view/a_id/1096347

Here’s the config I updated the backend with.  The logs from the trident pod said it successfully updated the backend, but the validation check in your CVE article does not pass  - the new backend json doesn’t mention qtree prunes (attached).

After applying the fix to the driver file, validation fails.  Is there another way to validate that the backend has the qtreePruneFlexvolsPeriod value set?

{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.83.108.107",
    "svm": "vs_BFCDVT2VSCONA01",
    "dataLIF": "10.232.142.24",
    "username": "openshift",
    "password": "<pw>",
    "storagePrefix": "vf",
    "qtreePruneFlexvolsPeriod": "157788000",
    "defaults": {
      "spaceReserve": "none",
      "exportPolicy": "ep_openshift_bdv01",
      "snapshotPolicy": "openshift",
      "snapshotReserve": "20",
      "snapshotDir" : "true"
    }
}

**Comment by clintonk** [comment]
Hello, @techie11.  I tried your backend definition file with just enough changes for my SVM, and it worked fine.  Assuming you have Trident 19.10 or later, you should be able to use ```tridentctl get backend -o yaml``` to see the value of ```qtreePruneFlexvolsPeriod```.  Alternatively, you can install Trident with the --debug switch and watch the logs in the Trident controller pod (trident-main container) to ensure there is no mention of FlexVol pruning when you update the backend.  The ```qtreePruneFlexvolsPeriod``` workaround is really for Trident 19.07 or earlier; later versions of Trident do no Flexvol pruning at all.

**Comment by techie11** [comment]
I'm running v18.10

**Comment by clintonk** [comment]
@techie11  OK, then until you upgrade, I think you will have to inspect the debug logs to be comfortable that the quota resize housekeeping task is running periodically, but the flexvol pruning task is not.

**Comment by gnarl** [comment]
@techie11 we're closing this issue with the recommendation to upgrade to a newer version of Trident.
