### ISSUE TITLE
trident installer using -n trident-custom does not work correctly if namespace does not yet exist

### ISSUE THREAD

**Issue by dutchiechris** [NetApp/trident#39]
Using `trident_installer.sh -n trident-custom` when  `trident-custom` namespace does not  yet exist causes a partial installation.

It looks like this snippet is to blame:
```
# Check if the namespace exists already
TMP=$($CMD get namespace $NAMESPACE 2>&1)
if [ "$?" -ne "0" ]; then
	TMP=$($CMD create -f $DIR/trident-namespace.yaml 2>&1)
	if [ "$?" -ne "0" ]; then
		echo >&2 "Installer failed to create namespace ${NAMESPACE}: ${TMP}"; exit 1
	fi
fi
```

The `trident-namespace.yaml` file has a hardcoded namespace name of `trident` in it.  To fix there should be a search/replace of that file with the user specified namespace prior to the create.

**Comment by kangarlou** [comment]
Thanks Chris! Very timely as we're working to get the 17.07.0 release out the door. :)
