### ISSUE TITLE
basic / basic-csi used interchangably in Creating a Storage Class docs

### ISSUE THREAD

**Issue by dericcrago** [NetApp/trident#390]
The docs suggest `cp sample-input/storage-class-csi.yaml.templ sample-input/storage-class-basic.yaml` (should the destination file be called `sample-input/storage-class-basic-csi.yaml` instead?) which results in a storage class named `basic-csi` (unless the user changes it). However, the docs, as well as the `pvc-basic.yaml`, continue to reference the storage class name `basic`. Perhaps this could get called out a bit more?

**Comment by gnarl** [comment]
@dericcrago we will look at making the examples in the sample-input directory more consistent.

**Comment by gnarl** [comment]
This issue will be fixed with the Trident 20.07 release.
