### ISSUE TITLE
tridentctl -n trident obliviate crd times out

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#394]
**Describe the bug**
Deleting Trident's CRD with tridentctl times out.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [e.g. 19.10] Tridentctl 20.04 / CRD created with Trident 19.07.1
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml] standard
- Container runtime: [e.g. Docker 19.03.1-CE] Docker 18.09.1
- Kubernetes version: [e.g. 1.15.1] 1.15.3
- Kubernetes orchestrator: [e.g. OpenShift v3.11, Rancher v2.3.3] N/A
- Kubernetes enabled feature gates: [e.g. CSINodeInfo] N/A
- OS: [e.g. RHEL 7.6, Ubuntu 16.04] RHEL 7.5
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7] ONTAP 9.6
- Other: tested with the LabOnDemand "Using Trident with Kubernetes and ONTAP v3.1"

**To Reproduce**
run the command _tridentctl -n trident obliviate crd -d_

tridentctl -n trident obliviate crd
Are you sure you want to wipe out all of Trident's custom resources and CRDs??? [y/n]: y
INFO Resources not present.                        CRD=tridentversions.trident.netapp.io
INFO Resources not present.                        CRD=tridentbackends.trident.netapp.io
INFO Resources not present.                        CRD=tridentstorageclasses.trident.netapp.io
INFO Resources not present.                        CRD=tridentvolumes.trident.netapp.io
INFO Resources not present.                        CRD=tridentnodes.trident.netapp.io
INFO Resources not present.                        CRD=tridenttransactions.trident.netapp.io
INFO Resources not present.                        CRD=tridentsnapshots.trident.netapp.io
INFO CRD deleted.                                  CRD=tridentversions.trident.netapp.io
ERRO CRD tridentbackends.trident.netapp.io was not deleted after 180.00 seconds  CRD=tridentbackends.trident.netapp.io
Error: CRD tridentbackends.trident.netapp.io was not deleted after 180.00 seconds

After having run this command 5 times, you should finally get to 
INFO CRD deleted.                                  CRD=tridentsnapshots.trident.netapp.io
INFO Reset Trident's CRD state.

**Expected behavior**
All Trident CRD to be deleted & the process to end succesfully.

**Additional context**
in order to delete all CRD, one needs to cancel the obliviate process (CTRL+C), & restart it until is succeeds (4 or 5 restarts are required)

**Comment by YvosOnTheHub** [comment]
maybe I used the wrong process.
If you uninstall Trident & then remove the CRD with the tridentctl obliviate option, it times out.
If you first 'obliviate' the CRD, & then uninstall Trident, it works.
I guess since this command is not documented, it is open to confusion?

**Comment by gnarl** [comment]
@YvosOnTheHub We have found a bug with the obliviate command where it sometimes fails the first time it is run. It appears to always work the second time the obliviate command is run. We are currently working on fixing this bug.

**Comment by gnarl** [comment]
This was fixed with [commit 4e2408](https://github.com/NetApp-openstack-dev/trident/commit/4e2408427c64d7113d9450a510c7d20c6b30fb9e)

**Comment by jrhunger** [comment]
Just wanted to provide a working link to the [commit 4e2408](https://github.com/NetApp/trident/commit/4e2408427c64d7113d9450a510c7d20c6b30fb9e)
