### ISSUE TITLE
Monitor PV utilization

### ISSUE THREAD

**Issue by sfkwan** [NetApp/trident#400]
Monitor PV current utilization and predict the utilization trend 

For a production platform, it is important for us to be able to see the current utilization effectively and take active action based on trend.

It will make our monitoring effective if NetApp expose the metrics needed by following dashboard.

https://grafana.com/grafana/dashboards/11454

To take an example,
kubelet_volume_stats_available_bytes 
kubelet_volume_stats_used_bytes 
kubelet_volume_stats_capacity_bytes

**Comment by gnarl** [comment]
Hi @sfkwan,

We are already working on exposing additional metrics for the Trident 20.07 release.

**Comment by gnarl** [comment]
Multiple commits were made to add this feature with the final commit being [fbc91b7](https://github.com/NetApp-openstack-dev/trident/commit/fbc91b769b9d6a2bd90cf19f35244b8d8fb2e468).
