### ISSUE TITLE
Check the "storagePrefix" parameter at the backend creation

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#401]
**Describe the solution you'd like**
Trident does not seem to verify the validity of the _storagePrefix_ parameter.
Adding an extra check would avoid errors at PVC creation.

**Describe alternatives you've considered**
An alternative would be to add caveats in the documentation with regards to this parameter.

**Additional context**
In my test, here is the parameter I used:
`    "storagePrefix": "test/nas1_",`
Trident did not complain during the backend creation.

However, an ONTAP error was raised when creating a PVC:

`failed to provision volume with StorageClass "storage-class-nas": rpc error: code = Unknown desc = encountered error(s) in creating the volume: [Failed to create volume pvc-46a0cded-a847-4b85-b10a-ca7a968e8717 on storage pool aggr1 from backend NAS_Vol-default: error checking for existing volume: API status: failed, Reason: Invalid character '/' in volume name. It can have '_' and alphanumeric characters., Code: 13001], [Failed to create volume pvc-46a0cded-a847-4b85-b10a-ca7a968e8717 on storage pool aggr2 from backend NAS_Vol-default: error checking for existing volume: API status: failed, Reason: Invalid character '/' in volume name. It can have '_' and alphanumeric characters., Code: 13001]`

**Comment by gnarl** [comment]
We are planning to fix this in the Trident 20.07 release.

**Comment by gnarl** [comment]
Fixed in commit [c262e4c](https://github.com/NetApp-openstack-dev/trident/commit/c262e4ca7966700dfc48276c86a26ee7c82c71c9).

**Comment by travisghansen** [comment]
This removed the ability to use `-` which seemed to be perfectly fine previously...
