### ISSUE TITLE
Feature Request: Support "storagePrefix" for CVS & ANF backends

### ISSUE THREAD

**Issue by g-ogden** [NetApp/trident#406]
Customer would like to use "storagePrefix", which is available for ontap backends, on their CVS and ANF backends also. They have multiple Kubernetes clusters using the same CVS/ANF subscription and region, and need a way to quick identify which PV belongs to which cluster from the CVS UI and their reporting tools such as Cloud Insights. Setting Storage Prefix to the K8S cluster name gives them that visibility for ontap backends.

Currently if trying to specify a prefix, Trident fails with this error

Could not initialize storage driver." error="error validating aws-cvs driver. storage prefix may only contain letters and hyphens"

Even when prefix does only contain letters and hyphens.

**Comment by innergy** [comment]
In general we would prefer to allow you to configure Trident to apply custom labels to the volumes it provisions, which should satisfy this use case, and is already on the roadmap. Let us know if for some reason that does not.

**Comment by g-ogden** [comment]
Yes that would work for our use case. I'll close this request and look forward to the labelling feature being available!

**Comment by gnarl** [comment]
[Trident v20.10.0](https://netapp.io/2020/10/30/trident-2010/) now applies labels defined in the storage pool to the volumes created by CVS drivers.
