### ISSUE TITLE
Dynamically provisioned volumes not properly mounted

### ISSUE THREAD

**Issue by hujogrom** [NetApp/trident#408]
After a successfully provisioning the volume, PVC is not mounted properly inside the pod, 

following error is visible:

  Normal   SuccessfulAttachVolume  2m17s      attachdetach-controller                   AttachVolume.Attach succeeded for volume "pvc-c01d67e2-7018-49a2-ac2d-b42321666f71"
  Normal   SuccessfulAttachVolume  2m17s      attachdetach-controller                   AttachVolume.Attach succeeded for volume "pvc-78e0a1ff-edcc-4386-a133-4de50c2ec942"
  Warning  FailedMount             15s        kubelet, node1  Unable to attach or mount volumes: unmounted volumes=[data data1], unattached volumes=[domain-service-account-secret control-agent-secrett var-run ]: timed out waiting for the condition
  Warning  FailedMount             9s         kubelet, node1  MountVolume.MountDevice failed for volume "pvc-78e0a1ff-edcc-4386-a133-4de50c2ec942" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
  Warning  FailedMount             8s         kubelet, node1  MountVolume.MountDevice failed for volume "pvc-c01d67e2-7018-49a2-ac2d-b42321666f71" : rpc error: code = DeadlineExceeded desc = context deadline exceeded

Volumes provisioned using ontap-san driver (iscsi)

**Environment**

- Trident version: 20.01.1
- Trident installation flags used:   -d -n trident-storage --csi --use-custom-yaml]
- Container runtime: 19.03.8
-  Kubernetes version: v1.17.4
- Kubernetes enabled feature gates: 
- OS: RHEL 7.7
- NetApp backend types: ontap-san

**To Reproduce**

Appears randomly during creating a deployment

**Expected behavior**

Volume mounts every time

**Additional context**

**Comment by hujogrom** [comment]
May 27 13:09:14 node1 kubelet: I0527 13:09:14.990977    2985 reconciler.go:209] operationExecutor.VerifyControllerAttachedVolume started for volume "pvc-c01d67e2-7018-49a2-ac2d-b42321666f71" (UniqueName: "kubernetes.io/csi/csi.trident.netapp.io^pvc-c01d67e2-7018-49a2-ac2d-b42321666f71") pod "control-p4tdq" (UID: "5db708ba-e3e5-4aab-85ea-919c61a9117e")
May 27 13:09:14 node1 kubelet: E0527 13:09:14.991086    2985 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/csi/csi.trident.netapp.io^pvc-c01d67e2-7018-49a2-ac2d-b42321666f71\"" failed. No retries permitted until 2020-05-27 13:09:15.491057427 +0200 CEST m=+732787.128930660 (durationBeforeRetry 500ms). Error: "Volume has not been added to the list of VolumesInUse in the node's volume status for volume \"pvc-c01d67e2-7018-49a2-ac2d-b42321666f71\" (UniqueName: \"kubernetes.io/csi/csi.trident.netapp.io^pvc-c01d67e2-7018-49a2-ac2d-b42321666f71\") pod \"control-p4tdq\" (UID: \"5db708ba-e3e5-4aab-85ea-919c61a9117e\") "

**Comment by gnarl** [comment]
@hujogrom determine if this is occurring on a specific set of nodes. You can attempt to manually mount from the Node where the deployment fails to mounts. Also, check your export policy for the backend where you are trying to mount.

If none of these options work then you should contact NetApp support to help you with problem determination.

**Comment by wonderland** [comment]
exportPolicy is not relevant for iSCSI (only for NFS). In the case of iSCSI, access control is via the so-called iGroup, which you have configured in your backend config. And if the failure is not on specific nodes, it appears that the igroup is correct (it should contain the IQN of every k8s node). My guess would be a timeout issue in the iSCSI attach operation, though that should show up in the logs of the Linux host. Maybe worth a try to review the timeout values in /etc/iscsi/iscsid.conf as well as the multipath config if you use that.

**Comment by hujogrom** [comment]
Hi @wonderland, thanks a lot for your advice! I checked the settings you mentioned and see nothing suspicious, but maybe I'm missing something. Here are mine multipath.conf and iscsid.conf:

iscsid.conf:

iscsid.startup = /bin/systemctl start iscsid.socket iscsiuio.socket
iscsid.safe_logout = Yes
node.startup = automatic
node.leading_login = No
node.session.timeo.replacement_timeout = 120
node.conn[0].timeo.login_timeout = 15
node.conn[0].timeo.logout_timeout = 15
node.conn[0].timeo.noop_out_interval = 5
node.conn[0].timeo.noop_out_timeout = 5
node.session.err_timeo.abort_timeout = 15
node.session.err_timeo.lu_reset_timeout = 30
node.session.err_timeo.tgt_reset_timeout = 30
node.session.initial_login_retry_max = 8
node.session.cmds_max = 128
node.session.queue_depth = 32
node.session.xmit_thread_priority = -20
node.session.iscsi.InitialR2T = No
node.session.iscsi.ImmediateData = Yes
node.session.iscsi.FirstBurstLength = 262144
node.session.iscsi.MaxBurstLength = 16776192
node.conn[0].iscsi.MaxRecvDataSegmentLength = 262144
node.conn[0].iscsi.MaxXmitDataSegmentLength = 0
discovery.sendtargets.iscsi.MaxRecvDataSegmentLength = 32768
node.conn[0].iscsi.HeaderDigest = None
node.session.nr_sessions = 1
node.session.iscsi.FastAbort = Yes
node.session.scan = auto

multipath.conf:

defaults {
        user_friendly_names  no
        max_fds              max
        queue_without_daemon no
        flush_on_last_del    yes
        find_multipaths yes
        disable_changed_wwids yes
#        verbosity 4
}

blacklist {
        devnode "^(ram|raw|loop|fd|md|dm-|sr|scd|st)[0-9]*"
        devnode "^(hd|xvd|vd)[a-z]*"
        devnode "^cciss!c[0-9]d[0-9]*[p[0-9]*]"
}

# Make sure our multipath devices are enabled.
blacklist_exceptions {
        device {
           vendor "NETAPP"
           product "LUN"
        }
}

devices {
      device {
         vendor                 "NETAPP"
         product                "LUN"
         features               "3 queue_if_no_path pg_init_retries 50"
         hardware_handler       "1 alua"
         prio                 "alua"
         path_grouping_policy   group_by_prio
         path_selector         "round-robin 0"
         failback               immediate
         rr_weight              uniform
         rr_min_io              128
         path_checker           tur
       }
}

**Comment by gnarl** [comment]
@hujogrom, we're not able to determine the likely cause of the problem from what you have reported so far. Please contact NetApp support so that we can collect some additional data.

**Comment by crossond** [comment]
Here are some suggestions to try:

1. The iscsi-initiator-utils package version must be 6.2.0.874-2.el7 or newer
2.  Set `node.session.timeo.replacement_timeout = 5` per 'NetApp ONTAP Documentation: 
     **Setting the iSCSI replacement timeout value'**
     http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.exp-iscsi-rhel-cg%2FGUID-F9935B47-A709-4CAA-945B-64C03E338E79.html
3.   Include the following line in /etc/iscsi/iscsid.conf:
              node.session.scan = manual

**Comment by gnarl** [comment]
@hujogrom, please review this [GitHub issue](https://github.com/NetApp/trident/issues/410) as it may be relevant to the issue you are seeing. Let us know if you've resolved the issue.

**Comment by gnarl** [comment]
Closing this issue as the OP hasn't responded since 05/29/20.
