### ISSUE TITLE
update_trident.sh failure "unable to resolve image" with Openshift

### ISSUE THREAD

**Issue by dutchiechris** [NetApp/trident#41]
Updating Trident with OpenShift failed:

```
# ./update_trident.sh -n trident -t netapp/trident:17.07.0
Installer assumes you have deployed OpenShift.
error: unable to resolve image "netapp/trident:17.07.0" for container "trident-main": failed to get
image stream tag "trident": imagestreams "trident" not found

# oc version
oc v3.5.5.8
kubernetes v1.5.2+43a9be4
```

After having a look at the update_trident.sh script the problem was in the `oc set image` command. Googling a bit I discovered a couple of interesting stuff in the openshift project:
* https://github.com/openshift/origin/issues/12468
* https://github.com/openshift/origin/pull/10995

>> This PR will add new flag --source for oc set image. This flag will default to istag in OpenShift (where as in kube it default to  docker).

So it looks like to use the docker registry (instead of the imagestreams) you have to pass a `--source docker` flag. 

I tried and it worked successfully:

```
# oc --namespace trident --source docker set image deployment/trident trident-main=netapp/trident:17.07.0
deployment "trident" image updated
```

Looks like the update script needs to add this `--source=docker` flag when running in an OpenShift environment, or at least in one where this PR is merged.

**Comment by dutchiechris** [comment]
@kangarlou I don't have a lab anymore to test a fix.  Please assign to someone else.  Thanks!

**Comment by kangarlou** [comment]
Closing the issue as the update script was deprecated in 9287dc850979b00d39c6f4772fbe105f488a76a8.
