### ISSUE TITLE
PV and volume size are different

### ISSUE THREAD

**Issue by ysakashita** [NetApp/trident#410]
**Describe the bug**

We are using StatefulSet to create 100 Pods that mount 10G PV.
However, the size of the PV and the size of the volume mounted on the Pod are rarely different.

(e.g.) 
The request size is 10G in StatefulSet(volumeclaimtemplate). 
PV's size is 10G too. 
But volume's size in Pod(also kubelet) is 5G.

We found the error message in dmesg. 
When Trident try to format the device, it's occured the error.

```
[163212.056306] sd 2:0:0:12: [sdm] tag#67 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[163212.058689] sd 2:0:0:12: [sdm] tag#67 Sense Key : Illegal Request [current] 
[163212.060404] sd 2:0:0:12: [sdm] tag#67 Add. Sense: Logical block address out of range
[163212.062635] sd 2:0:0:12: [sdm] tag#67 CDB: Write(10) 2a 00 00 c0 00 00 00 00 08 00
[163212.064832] print_req_error: critical target error, dev sdm, sector 12582912
[163212.066566] Buffer I/O error on dev sdm, logical block 1572864, lost async page write
[163212.068831] Buffer I/O error on dev sdm, logical block 2097152, lost async page write
[163212.071076] Buffer I/O error on dev sdm, logical block 2097167, lost async page write
[163212.073321] Buffer I/O error on dev sdm, logical block 2621424, lost async page write
[163212.075557] Buffer I/O error on dev sdm, logical block 2621425, lost async page write
[163212.094402] sd 2:0:0:12: [sdm] 10485760 512-byte logical blocks: (5.37 GB/5.00 GiB)
[163212.096663] sd 2:0:0:12: [sdm] 4096-byte physical blocks
[163212.099449] sdm: detected capacity change from 10737418240 to 5368709120
```

I guess it's the error in Ontap.
Also I understood the changing size of FileSystem in the code.
https://github.com/torvalds/linux/blob/v4.19/fs/block_dev.c#L1334
 
So we would like to know the root cause in the error.

**Environment**
This issue is occurring in two different environments.

(1)

- Trident version: [20.04]
- Trident installation flags used: [-n trident]
- Container runtime: [Docker 19.03.11-CE]
- Kubernetes version: [1.17.4]
- Kubernetes orchestrator: [none]
- Kubernetes enabled feature gates: [none]
- OS: [Ubuntu18.04]
- NetApp backend types: [ONTAP AFF 9.5]

(2)

- Trident version: [19.10]
- Trident installation flags used: [-n trident]
- Container runtime: [Docker 18.06.3-CE]
- Kubernetes version: [1.16.1]
- Kubernetes orchestrator: [none]
- Kubernetes enabled feature gates: [none]
- OS: [Container Linux 2303.3.0]
- NetApp backend types: [ONTAP FAS 9.1]

**To Reproduce**

Create more than 100 PVs using StatefulSet.
However, the recall is less than 1%.

**Expected behavior**

Depending on the cause,　Trident may be able to avoid this error.
(e.g.)
1. Trident check the size after formatting
2. If PV and volume size are different, Trident would delete the PV.
3. Then Trident re-create the PV.

**Comment by wonderland** [comment]
So the k8s node reports the device size as 5G as well? (e.g. output of fdisk -l /dev/sdm)?

Do you have access to the storage array or can you ask the storage team to take a look? Curious what the affected LUNs look like on the backend system, e.g. does it report it as 5GB as well?

**Comment by ysakashita** [comment]
@wonderland The device size in K8S node and LUN/Volume size in Ontap are same 10G.
I think Ontap sent sense code to K8S node at mkfs.ext4 time. Then, FileSystem is created 5G (shrinking size).

**Comment by ysakashita** [comment]
I think I was addicted to the unlucky timing.

Depending on the SSD device,
I know that an error may be returned to the Storage Controller when the GC(etc..) runs on the SSD Controller and it is unable to allocate addresses temporarily. 
I doubt that case.

 IMO, I think that saving the issue is to retry with Storage Controller (Ontap) or Trident.

**Comment by ysakashita** [comment]
@wonderland We already sent all log data(K8S and Ontap) to NetApp(Japan) members. Could you contact to NetApp(Japan) if you want to look it?

**Comment by wonderland** [comment]
OK, great. You are already in good hands then. Maybe you can share the root cause here as well, once it is found?

**Comment by ysakashita** [comment]
@wonderland Maybe yes.  It depend on NetApp members.
I would like to fix the issue ASAP. Also I hope it will be helpful to others.

**Comment by gnarl** [comment]
@ysakashita Do you have an update on this issue?

**Comment by ysakashita** [comment]
@gnarl No. I'm waiting for NetApp(Japan) to analyze the log.

**Comment by ysakashita** [comment]
We would like to resolve the issue ASAP.
So, I try to change from analyze of problem to solution based approach.

A K8S node is received SCSI error from under layer's device (include external Storage).
So, it rarely happens that the size of File System shrink at format.
https://github.com/torvalds/linux/blob/v4.19/fs/block_dev.c#L1334

I believe that it so difficult to work around all SCSI errors.
If we will re-create the shrink volume,  it is fixed.

Therefore, I think it's a better solution to put a retry processing(re-create the volume) somewhere.
There are three points to implement the retry process.

1. NetApp/Ontap
2. OS (e.g, Ubuntu)
3. NetApp/Trident

I think better points is NetApp/Trident.
Because, NetApp/Ontap don't know File System size and it is difficult to re-create the shrink volume.
2nd option is a OS. However the OS can't re-create volume. Unfortunately, the OS don't know user request's size of volume.
Last option is Trident. Trident know user request's size of volume(size of PVC) and is able to check the size of a formatted volume.
Of course, it needs to consider about margin size. As you know, this is because the size of raw volume and file system are different.

In addition, (IMO) I think it is enough to retry once or twice.
Because SCSI error is a rare case.

What do you think of the idea about re-crate shrink volume in Trident?

**Comment by gnarl** [comment]
@ysakashita we haven't seen this issue reported previously. I will talk to the team about it although this does sound like an Ontap bug.

**Comment by ysakashita** [comment]
@gnarl Thank you.  I am very reassuring.
Our customer, who develop web service in our kubernetes&trident , have already encountered about over 5 times.
We try to find a way of reproduce the issue too.

**Comment by gnarl** [comment]
@ysakashita, there is a [bug fix](https://bugs.launchpad.net/ubuntu/+source/open-iscsi/+bug/1877617) that was recently fixed for Ubuntu 18.04 that you will want to verify you are running in your worker node instances. Also, if there is anything else that is performing iSCSI scans on the worker node that can also cause an issue with Trident SAN storage drivers.

**Comment by crossond** [comment]
- Follow the general NetApp Best Practices for SAN multipathing:  '[Best Practices for Modern SAN and ONTAP 9 | TR-4080']:
     https://www.netapp.com/us/media/tr-4080.pdf

    and

- ONTAP Documentation page for Managing iSCSI:
     https://docs.netapp.com/ontap-9/topic/com.netapp.doc.dot-cm-sanag/GUID-BE4CBED9-DEFC-4073-A5EA-E9E96EDE8A99.html
   
- The iscsi-initiator-utils package version must be 6.2.0.874-2.el7 or newer

- Set the following line in /etc/iscsi/iscsid.conf:
                              **node.session.scan = manual**
- Set **node.session.timeo.replacement_timeout = 5**
   per 'NetApp ONTAP Documentation: Setting the iSCSI replacement timeout value'
   http://docs.netapp.com/ontap-9/index.jsp?topic=%2Fcom.netapp.doc.exp-iscsi-rhel-cg%2FGUID-F9935B47-A709-4CAA-945B-64C03E338E79.html

Note: After making changes to the iscsi.conf file it requires restarting the iscsi service.

**Comment by ysakashita** [comment]
@crossond Thank you for information. I have one question.

> Set the following line in /etc/iscsi/iscsid.conf:
node.session.scan = manual

Why do I set from auto to manual?
We use open-iscsi in K8S Node's OS. So we don't operate OS by human and manual.
Because we provide kubernetes services to customer.
Therefore, I think that it is better 'node.session scan = auto' .

Please let me know about issue if it is 'auto' .

I think the [open-iscsi bug](https://bugs.launchpad.net/ubuntu/+source/open-iscsi/+bug/1877617) is more likely to occur with `auto`.
However, if we will update open-iscsi package (2.0.874-5ubuntu2.10 or later), we don't need to change to `manual`, right?

**Comment by ysakashita** [comment]
@gnarl Thank you for information about open-iscsi bug.
We try to update it. Then we will check the issue.

> Also, if there is anything else that is performing iSCSI scans on the worker node that can also cause an issue with Trident SAN storage drivers.

On our K8S nodes, just open-iscsi scans the session. Users are not allowed to login to K8S Node.　Does the environment still have a negative effect on trident?

I think the question will also influence [above question](https://github.com/NetApp/trident/issues/410#issuecomment-649170406).

**Comment by wonderland** [comment]
"manual" does not imply that you'd have to do it manually (e.g. with human interaction), it just indicates that it happens outside the OS layer. You want those actions to be coordinated by k8s/Trident, without any interference from automated activities at the lower levels.

**Comment by ysakashita** [comment]
@wonderland Sure. We try to set 'manual' in node.session.scan .

**Comment by ysakashita** [comment]
We have found the following code and documentation fixes.
It's great work for this issue !

https://github.com/NetApp/trident/commit/329044c9079fcd516ba177617495ffc46c84d7c6
https://github.com/NetApp/trident/commit/6ddc07d6b7e8a5d12d12de8b725b050456a168f8

I still continue test of 'node.session.scan' in our customer environment.

**Comment by gnarl** [comment]
@ysakashita, thanks for the feedback! I will leave this issue open for now.

**Comment by ysakashita** [comment]
We made the following settings on our customer's Kubernetes node and confirmed that the issue was resolved.
Thank you for great comments.

- open-iscsi:  2.0.874-5ubuntu2.10  (in Ubuntu 18.04)
- configuration in /etc/iscsi/iscsid.conf :  update `node.session.scan = manual ` and `node.session.timeo.replacement_timeout = 5 `

**Comment by gnarl** [comment]
@ysakashita, thanks for confirming that your issue is resolved!
