### ISSUE TITLE
Trident Operator:  No option for custom CSI image repository

### ISSUE THREAD

**Issue by somejfn** [NetApp/trident#412]
**Describe the solution you'd like**
Similarly to the "image-registry" option with Tridentctl,  we need to specify the repository of all images used in a trident instance deployment.  Internal clusters do not have internet access... not something I can work around.

The tridentImage paramerter in the CR is a start,  but we need the same for:  

quay.io/k8scsi/csi-provisioner:v1.6.0
quay.io/k8scsi/csi-attacher:v2.2.0
quay.io/k8scsi/csi-node-driver-registrar:v1.3.0

**Describe alternatives you've considered**
This is blocking us from using the operator... falling back to tridenctl install

**Additional context**

**Comment by gnarl** [comment]
@somejfn The Trident Operator [supports imageRegistry](https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operator-install.html#customizing-your-deployment).
