### ISSUE TITLE
Documentation / feature req: restore trident (not tridentctl import)

### ISSUE THREAD

**Issue by zakkg3** [NetApp/trident#413]
In case of a problem on trident. After reinstalling it, I want to map existing volumes on netapp SVM to an existing already running netapp pvc.

If i reinstall trident and re-add the backend I see "0" volumes. I need to delete the running pvc and then recreate it with [tridentctl import](https://netapp-trident.readthedocs.io/en/stable-v20.01/kubernetes/operations/tasks/volumes.html#importing-a-volume). But ofc this implies a downtime in my application. Its manual and it does not scale.

How can make the new trident installation to recognise the existing volumes in the SVM and the existing PVC ?
Is the operator listening to the crds creation? can I just backup my CRDS in case of a failure and after reinstall trident, apply the crds so the backend, volumes and so on , can be restored all back and tracked by trident?
should we keep a copy of the crds on the SVM so in case of a total lost of the k8s cluster i can just install trident and do "tridentctl restore" ?

**Comment by gnarl** [comment]
Hi @zakkg3,

If you uninstall Trident 19.07 or newer and then install Trident again all of the Trident CRDs should still exist. Did you use the same namespace when you reinstalled Trident?

**Comment by gnarl** [comment]
Closing this issue as an update with additional information wasn't received.
