### ISSUE TITLE
Backend CRD?

### ISSUE THREAD

**Issue by stobias123** [NetApp/trident#424]
**Describe the solution you'd like**
Native backend setup via trident operator

I just set up the new trident operator in hopes that I could set up trident natively in k8s. I was disappointed to find I still have to use `tridentctl` to finish trident setup. This is outside the workflow of all other k8s operations. 

Please create/provide a `tridentbackend` crd, and let the operator manage `tridentctl` operations related to backend initialization.

**Describe alternatives you've considered**
None available.

**Additional context**

**Comment by sgryczan** [comment]
I agree, exposing some option to configure Backends/StorageClasses through the operator would be nice to have. 

Here's an example of another operator that 'wraps' the trident-operator to do this currently: https://github.com/sgryczan/TridentInstaller

**Comment by gnarl** [comment]
@stobias123, this is being tracked in issue #358 and we are currently working on solving this. Closing #424 as a duplicate.
