### ISSUE TITLE
Failed to take snapshot

### ISSUE THREAD

**Issue by BostjanBozic** [NetApp/trident#427]
**Describe the bug**
Snapshots can not be created. When `volumeSnapshot` is created (and dynamically with it `volumeSnapshotContent`), it never finishes.
`csi-snapshotter` container provides following error output:
```
I0804 13:54:16.842445       1 request.go:1017] Response Body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io \"snapcontent-9046fc53-c316-41cb-b088-6ee2da4088c3\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"snapcontent-9046fc53-c316-41cb-b088-6ee2da4088c3","group":"snapshot.storage.k8s.io","kind":"volumesnapshotcontents"},"code":409}
I0804 13:54:16.842552       1 snapshot_controller.go:200] updating VolumeSnapshotContent[snapcontent-9046fc53-c316-41cb-b088-6ee2da4088c3] error status failed Operation cannot be fulfilled on volumesnapshotcontents.snapshot.storage.k8s.io "snapcontent-9046fc53-c316-41cb-b088-6ee2da4088c3": the object has been modified; please apply your changes to the latest version and try again
E0804 13:54:16.842573       1 snapshot_controller.go:139] createSnapshot [create-snapcontent-9046fc53-c316-41cb-b088-6ee2da4088c3]: error occurred in createSnapshotWrapper: failed to take snapshot of the volume, pvc-27da380d-caa8-4d2d-ae9b-06b152bd8815: %!q(<nil>)
E0804 13:54:16.842610       1 goroutinemap.go:150] Operation for "create-snapcontent-9046fc53-c316-41cb-b088-6ee2da4088c3" failed. No retries permitted until 2020-08-04 13:54:17.842584822 +0000 UTC m=+3721.127509318 (durationBeforeRetry 1s). Error: "failed to take snapshot of the volume, pvc-27da380d-caa8-4d2d-ae9b-06b152bd8815: %!q(<nil>)"
```
I am not sure if this in the end is issue with csi-snapshotter or actual underlying platform (OpenShift).

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.07.0
- Trident installation flags used: installed by operator (`deploy/bundle.yaml`) and custom resource (`deploy/crds/tridentprovisioner_cr.yaml`)
- Container runtime: CRI-O (1.17.4-20.rhaos4.4.git7c01831.el8)
- Kubernetes version: v1.17.1+3288478
- Kubernetes orchestrator: OpenShift v4.4.14
- OS: Red Hat Enterprise Linux CoreOS release 4.4
- NetApp backend types: ONTAP

**To Reproduce**
* deploy Trident Operator (v20.07.0)
* deploy `TridentProvisioner` custom resource
* create `VolumeSnapshotClass` with `csi.trident.netapp.io` as driver
* create `VolumeSnapshot`, which dynamically creates `VolumeSnapshotContent`
* check csi-snapshotter container logs

**Expected behavior**
I would expect snapshots to be completed, as `VolumeSnapshotContent` has been prepared.

**Additional context**
What I also noticed is that PVC, from which snapshot should have been created, receives snapshot finalizer, which causes issue with deleting PVC (you have to edit PVC and delete that particular finalizer).

**Comment by gnarl** [comment]
Hi @BostjanBozic,

We have successfully tested snapshots with Trident 20.07 against OCP 4.4 in our CI. We have seen one other reported issue like this and OpenShift support was contacted regarding the issue. We haven't received an update on what the issue is yet. I recommend that you open a NetApp support case and also contact OpenShift support.

**Comment by BostjanBozic** [comment]
Hello,

sounds good, thank you for information. I will open support cases, though I am not sure how support regarding this topic is handled from OpenShift aide, as snapshotting is still in Texh Preview there.
I will keep you updated if I learn anything new.

**Comment by BostjanBozic** [comment]
It seems the issue is that we are using `ontap-nas-economy` driver for backend, which does not support csi snapshots (as it does not use volumes like `ontap-nas`, but qtrees).
Interestingly enough we also have same issue with ceph-csi, so there is most likely something on our OpenShift installation.

I will close the issue as apparently this has nothing to do directly with Trident.
