### ISSUE TITLE
federated storage class

### ISSUE THREAD

**Issue by rushins** [NetApp/trident#428]
Hi

I am using kubernetes federation (federated control plane ) on 2 clusters with trident as a storage class on-prem. both are working with storage class, persistency volumes. 

So, i  would like to test with  Federated storage class and federaeted. persistence volume to make sure the replication of volume get replicated on federation master to slave . Does this feature tested with TRident .

here is the link below , from Trident i dont see any documentation  using federated storage class, federated persistence volumes. can guys check and help.

https://github.com/kubernetes-sigs/kubefed/issues/1165

BR
Rushi

**Comment by gnarl** [comment]
Hi @rushins,

We haven't tested this with Trident yet. We will track your request but it may be a while before we are able to get to this.

**Comment by rushins** [comment]
thanks .Let me know if you can. Also if you could get a chance make sure this is also tested on AzureNetAppFiles because my use case is for 2 Federation, 1)  for on-prem using NetApp CDOT and  2) azure  with Azurenetappfiles. my current production without federation using netapp trident on-prem and azureneappfiles with azure is all working.

**Comment by rushins** [comment]
@gnarl : thanks .Let me know if you can. Also if you could get a chance make sure this is also tested on AzureNetAppFiles because my use case is for 2 Federation, 1) for on-prem using NetApp CDOT and 2) azure with Azurenetappfiles. my current production without federation using netapp trident on-prem and azureneappfiles with azure is all working.

**Comment by gnarl** [comment]
Hi @rushins,

We've looked into Kubernetes Federation and it isn't a feature that is on the Trident roadmap.
