### ISSUE TITLE
Invalid initiator error when attaching volumes to K8S pods

### ISSUE THREAD

**Issue by canberkkoc** [NetApp/trident#433]
**Describe the bug**
Hello,
We are trying to use ontap-san driver and thinking done every step as described at docs also pvcs are attached and take volumes from storage. But we have an error log like this when K8S try to attach the volumes, what we might missed.

Here is log:

```
Warning  FailedAttachVolume  1s (x5 over 8s)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-3737bca1-064d-494f-ad42-54ee4eb69363" : rpc error: code = Internal desc = error publishing ontap-san driver: error adding IQN  to igroup trident: API status: failed, Reason: Invalid initiator "". An example of a valid WWN is "01:02:03:04:0a:0b:0c:0d". Examples of valid iSCSI names are "iqn.1995-08.com.example:string" and "eui.0123456789abcdef"., Code: 13001
```

Here is my backend and storageclass config:

```json
{
    "version": 1,
    "storageDriverName": "ontap-san",
    "managementLIF": XXXXXX,
    "dataLIF": XXXXXX,
    "svm": XXXXXXX,
    "useCHAP": false,
    "username": "vsadmin",
    "password":  XXXXX,
    "igroupName": "trident"          
}
```

```yaml
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: iscsi-storage-class
provisioner: netapp.io/trident
parameters:
  backendType: "ontap-san"
  provisioningType: "thin"
  snapshots: "false"
reclaimPolicy: Retain
allowVolumeExpansion: true
```

Here is volumes, pv and pvcs:

```
| pvc-5a7d1939-0079-4273-a500-b47dee5bcd9d | 100 GiB | iscsi-storage-class | block    | d6b1f45f-1f2b-4c51-9e0a-13fdf11e49a7 | online | true    |

| pvc-2f29c94b-39b0-4079-90f2-9b0a523d69c4 | 100 GiB | iscsi-storage-class | block    | d6b1f45f-1f2b-4c51-9e0a-13fdf11e49a7 | online | true    |
```
```
alertmanager-prometheus-operator-alertmanager-db-alertmanager-prometheus-operator-alertmanager-0   Bound    pvc-5a7d1939-0079-4273-a500-b47dee5bcd9d   100Gi      RWO            iscsi-storage-class   86m
prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0           Bound    pvc-2f29c94b-39b0-4079-90f2-9b0a523d69c4   100Gi      RWO            iscsi-storage-class   85m

```

```
pvc-5a7d1939-0079-4273-a500-b47dee5bcd9d   100Gi      RWO            Retain           Bound      monitoring/alertmanager-prometheus-operator-alertmanager-db-alertmanager-prometheus-operator-alertmanager-0   iscsi-storage-class             87m
pvc-2f29c94b-39b0-4079-90f2-9b0a523d69c4   100Gi      RWO            Retain           Bound      monitoring/prometheus-prometheus-operator-prometheus-db-prometheus-prometheus-operator-prometheus-0           iscsi-storage-class             86m

```

**Environment**

- Trident version: 20.01
- Trident installation flags used: tridentctl install -n trident
- Container runtime: 19.03.6 -CE
- Kubernetes version: 1.15.3
- Kubernetes orchestrator: Vanilla
- OS: Centos 7
- NetApp backend types: ONTAP
-Other: We done steps desribed here https://netapp-trident.readthedocs.io/en/stable-v20.01/kubernetes/operations/tasks/worker.html#iscsi

**Comment by gnarl** [comment]
@canberkkoc, I recommend reviewing the [Worker Node](https://netapp-trident.readthedocs.io/en/stable-v20.07/kubernetes/operations/tasks/worker.html) section of the documentation verifying that iscsid is actually running on all of your worker nodes. If iscsid isn't running properly then the node pods will need to be restarted once this is fixed.

Also, the initiator may not have been configured when the node pod first came up. If this is the case then bouncing the pod should fix the issue.

**Comment by canberkkoc** [comment]
Hello,

I restarted all node pods and it worked. I think trident doesn't understand iscsci attached when it installed before.
