### ISSUE TITLE
ISCSI LUN Expansion issue - csi.trident.netapp.io  can't resize a non-NFS PV

### ISSUE THREAD

**Issue by Chaitan123** [NetApp/trident#434]
Hello All, 

Currently having isssue expanding the ISCSI LUN.

Trident Version : 20.04.0 
K8s Version : v1.16.14
Ontap : 9.7

I have edited the PVC to new LUN size, this is what i have been getting:
Events:
  Type     Reason             Age                       From                   Message
  ----     ------             ----                      ----                   -------
  Warning  ExternalExpanding  33m                       volume_expand          Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Warning  ExternalExpanding  19m (x2 over 20m)         volume_expand          Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Warning  ExternalExpanding  9m11s                     volume_expand          Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.
  Warning  ResizeFailed       <invalid> (x13 over 31m)  csi.trident.netapp.io  can't resize a non-NFS PV.

Also tried editing : manifests/kube-apiserver.
    - --feature-gates=ExpandCSIVolumes=true
    - --feature-gates=ExpandInUsePersistentVolumes=true

also tried this:
kube-apiserver --disable-admission-plugins=PersistentVolumeClaimResize

Thanks
Chaitan

**Comment by balaramesh** [comment]
@Chaitan123 based on our earlier conversations it looks like this was a k8s upgrade (from `1.15` to `1.16`). Can you try bouncing your Trident Controller pod? If you have installed Trident with `tridentctl` the k8s version change won't be picked up unless the Trident Controller pod inits again. You can get around this by using the [Trident operator](https://netapp-trident.readthedocs.io/en/stable-v20.07/kubernetes/deploying/deploying.html#why-should-i-use-the-trident-operator)

**Comment by Chaitan123** [comment]
Hello Thanks Balaramesh for your response, i have bounced the trident pods, still getting the error:

  Type     Reason             Age                 From           Message
  ----     ------             ----                ----           -------
  Warning  ExternalExpanding  2m20s (x2 over 2d)  volume_expand  Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC.

Also edited: - kube-apiserver --disable-admission-plugins=PersistentVolumeClaimResize

Thanks
Chaitan

**Comment by adkerr** [comment]
That "error" is a normal message from Kubernetes stating that k8s has no built-in plugin that can handle it. The external controller is says it's waiting for is Trident. LUNs cannot resize until the pod(s) mounting them are started (or restarted if they're currently in use) because the filesystem must be resized as well and that requires data access to the LUN while nothing is using it, so k8s will not inform trident of the resize until the re/start of the pod.

**Comment by Chaitan123** [comment]
Thanks for the responses, i have re-installed trident and it worked as expected.

Thanks

**Comment by Chaitan123** [comment]
Thanks for the responses, i have re-installed trident and it worked as expected.
