### ISSUE TITLE
Add livenessProbe to trident-csi DaemonSet 

### ISSUE THREAD

**Issue by ysakashita** [NetApp/trident#436]
**Describe the solution you'd like**

I want to add checking logic of trident-csi pod of daemonset after installing.
I rarely come across the below error after installing Trident.

```
$ kubectl describe pod test-pod
Events:
  Type     Reason                  Age                       From                                                   Message
  ----     ------                  ----                      ----                                                   -------
  ...
  Warning  FailedMount             2m21s (x1492 over 7m21s)  kubelet, test-03-worker-default-8982ccb9-bb4jn  MountVolume.MountDevice failed for volume "pvc-6f1bcde8-5820-4373-9d3c-047af02e1253" : rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/csi.trident.netapp.io/csi.sock: connect: no such file or directory"
```

I know that the error can recover by re-creating the pod.
Therefore, I would like to recover it automatically.
A one idea is the adding livenessProbe  in a trident-csi daemonset.
So the livenessProbe try to check csi.sock.
Also the daemonset has `initialDelaySeconds` and `periodSeconds` for livenessProbe too.

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by gnarl** [comment]
This was addressed in [commit 503e040](https://github.com/NetApp/trident/commit/503e04000e6be4878cb2237aff35dec79a6e9b7f) and will be included in the Trident 21.04 release.
