### ISSUE TITLE
ontap-nas: enable support for volume-state propagation to netapp mirror servers from trident

### ISSUE THREAD

**Issue by HardikDR** [NetApp/trident#44]
Provisioner creates the PV corresponding to the PVC immediately , but the actual application takes quite a time to get mounted to the Netapp NFS share. 

It looks like this issue is mainly from the Netapp vservers which are configured to propagate the current-state of the volumes to all the Netapp mirror-servers every 5 minutes.(configurable though) 
Would it be possible to make a call from trident-provisioner to propagate the volume-creation state to all the backend vservers , everytime PVC-PV is created ?
eg .
```
snapmirror update-ls-set -source-path xyz://abc_vol
```

This would allow applications over kubernetes to get mounted immediately to the new PV, irrespective of the configuration made at backend Netapp Vservers.

**Comment by dutchiechris** [comment]
Note, there is also a related request for the NetApp Docker Volume Plugin: 
https://github.com/NetApp/netappdvp/issues/84

**Comment by HardikDR** [comment]
Thanks for hint !!
