### ISSUE TITLE
Kubernetes 1.19 support

### ISSUE THREAD

**Issue by SuperBaobab** [NetApp/trident#440]
**Describe the solution you'd like**
I currently have an OpenShift 4.5 cluster and I'm preparing for the next update on 4.6 (unreleased yet).
OpenShift 4.5 is based on Kubernetes 1.18 which is supported by Trident but OpenShift 4.6 is based on Kubernetes 1.19 which is not yet supported.
I would like to have the support for Kubernetes 1.19 in the next Trident release.

**Describe alternatives you've considered**
Just not update my OpenShift cluster, but it's not a real alternative.

**Comment by gnarl** [comment]
Hi @SuperBaobab,

As the Kubernetes 1.19 release was just announced we are waiting for the release to be available in multiple repositories for operating systems that we support. We will then be able to qualify Trident by using K8S 1.19 in our CI. We are also planning to include bug fixes along with K8S 1.19 support in a 20.07.1 patch release. You can follow our Slack channel or look for a release notice on the [Trident section of thePub](https://netapp.io/persistent-storage-provisioner-for-kubernetes/).

**Comment by SuperBaobab** [comment]
Hello @gnarl 
Thank you for this quick response. Yes I know I'm in a bit of a hurry because Kubernetes 1.19 was just announced.
I will wait patiently for the next Trident release. Thanks for your great work.

**Comment by gnarl** [comment]
Kubernetes v1.19 is supported in the [Trident 20.07.1 ](https://github.com/NetApp/trident/releases/tag/v20.07.1)release.
