### ISSUE TITLE
Trident is trying to unmount not existing volumes

### ISSUE THREAD

**Issue by hujogrom** [NetApp/trident#443]
A lot of errors regarding missing PV's on one of Trident sidecar pods and csi-attacher pod. PV's are not present in Kubernetes, not visible on Trident volume list, LUN's for volumes not exported. Only leftovers remained in /var/lib/kubelet/plugins/kubernetes.io/csi/pv/ directory on node. It looks like Trident is trying to unmount the volumes that in fact does not exist anymore. 

**Environment**

- Trident version: 20.07
- Trident installation flags used:  -d -n trident-system --use-custom-yaml
- Container runtime: 19.03.12
- Kubernetes version: v1.18.4
- OS: RHEL 7.7
- NetApp backend types: ontap-san
- Other:

**To Reproduce**
We noticed it when checking logs to debug delays in attaching PV's. I'm wondering if it can cause any delay in attaching/deteaching PV's

**Expected behavior**
Any information about PV will be deleted from node/trident  after PV's deletion. 

below some logs from sidecar trident container:

`time="2020-09-02T11:53:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-da95a22f-ef9a-4390-8b10-57fcb134de39/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-da95a22f-ef9a-4390-8b10-57fcb134de39/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:53:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-35613c97-7498-4174-a574-ea5b9ea15498/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-35613c97-7498-4174-a574-ea5b9ea15498/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:53:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e54997c8-008d-4110-b120-5c77e8d6e5a5/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e54997c8-008d-4110-b120-5c77e8d6e5a5/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:53:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41bfe1cc-4fb1-4d4d-a432-2a6ced1a3cf3/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41bfe1cc-4fb1-4d4d-a432-2a6ced1a3cf3/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:48Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-c162323e-020e-43bb-b677-7397713ee917/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-c162323e-020e-43bb-b677-7397713ee917/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:48Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-aebb61d0-914b-4d81-9553-4023b453e246/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-aebb61d0-914b-4d81-9553-4023b453e246/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:48Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-887233bd-aea9-4f91-80d2-45bade7f1a2c/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-887233bd-aea9-4f91-80d2-45bade7f1a2c/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:48Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4651daf2-d65e-47e4-b05d-461987a25ed1/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4651daf2-d65e-47e4-b05d-461987a25ed1/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:48Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:49Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-286b4396-f3df-4108-8a59-cb0310dde5b0/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-286b4396-f3df-4108-8a59-cb0310dde5b0/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4d186a9b-3efe-42fa-b24e-d68f11ca0c11/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4d186a9b-3efe-42fa-b24e-d68f11ca0c11/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6dfe8de3-b710-406c-8605-d6bf5efdac62/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6dfe8de3-b710-406c-8605-d6bf5efdac62/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0d8d2212-bcb1-4824-bb92-efafe73df587/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-0d8d2212-bcb1-4824-bb92-efafe73df587/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-14be0714-f92c-4f37-86f0-9b86d6cf2744/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-14be0714-f92c-4f37-86f0-9b86d6cf2744/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:53Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e4853f98-f005-4ff8-b910-8325512ec2ce/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e4853f98-f005-4ff8-b910-8325512ec2ce/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:55Z" level=error msg="GRPC error: rpc error: code = NotFound desc = target path (/var/lib/kubelet/pods/0dcbf453-4057-463b-8e57-22950631329e/volumes/kubernetes.io~csi/pvc-fe3565a2-a546-441b-ac01-d2eb11125111/mount) not found; could not check if the target path is a directory."
time="2020-09-02T11:55:55Z" level=error msg="GRPC error: rpc error: code = NotFound desc = target path (/var/lib/kubelet/pods/0dcbf453-4057-463b-8e57-22950631329e/volumes/kubernetes.io~csi/pvc-1ff13b03-b743-4ac7-ae37-2894c875c51c/mount) not found; could not check if the target path is a directory."
time="2020-09-02T11:55:56Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41bfe1cc-4fb1-4d4d-a432-2a6ced1a3cf3/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-41bfe1cc-4fb1-4d4d-a432-2a6ced1a3cf3/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:56Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-35613c97-7498-4174-a574-ea5b9ea15498/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-35613c97-7498-4174-a574-ea5b9ea15498/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:56Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e54997c8-008d-4110-b120-5c77e8d6e5a5/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-e54997c8-008d-4110-b120-5c77e8d6e5a5/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T11:55:56Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-da95a22f-ef9a-4390-8b10-57fcb134de39/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-da95a22f-ef9a-4390-8b10-57fcb134de39/globalmount/volumePublishInfo.json: no such file or directory"
`

from csi-attacher:

`I0902 12:12:23.429514       1 csi_handler.go:267] Detaching "csi-beafff542dc3617455a19627273fc9da705f980539db94e37fbddff41274c2dc"
I0902 12:12:23.629537       1 csi_handler.go:219] Error processing "csi-845dd762f3e7b7ed92cb7c30760b05ea51a62bffa491b808e3f5b77cd4269f05": failed to detach: persistentvolume "pvc-89a5579b-5374-4bd4-bdd7-813a259f0aa7" not found
I0902 12:12:23.629734       1 csi_handler.go:267] Detaching "csi-d7c7fc95104b156e6386ce12c942d7b73fd05965ec6d9c78fb5053876e122cbe"
I0902 12:12:23.830511       1 csi_handler.go:219] Error processing "csi-0c97eec6ea939e16de48b2cc5d009a5fe29233bb47e54e78e33bf5c8b43f1781": failed to detach: persistentvolume "pvc-3ee2d55b-edaa-4029-ad43-c843cbb8911b" not found
I0902 12:12:23.830589       1 csi_handler.go:267] Detaching "csi-71934b29a3f70a324fc0106345abc551b8df98b32081e25317c0d961f1cf4369"
I0902 12:12:24.029347       1 csi_handler.go:219] Error processing "csi-180c6640581376335d936d503c041d942de29af84f596c3834847f4beccc91ae": failed to detach: persistentvolume "pvc-a8156fa7-64c4-4b8d-9703-fb03d0704635" not found
I0902 12:12:24.029520       1 csi_handler.go:267] Detaching "csi-f17280914ad071a326a6101ad49fa1e86c89105e39e25e12fd362801940b2725"
I0902 12:12:24.231806       1 csi_handler.go:219] Error processing "csi-e7b5e3361fac205b17040f7b25e29b78b436e7f0a50b9f43221a77d5289ab6a8": failed to detach: persistentvolume "pvc-2b73397a-8f05-41cc-90f6-07ffd7cc7bf0" not found
I0902 12:12:24.231892       1 csi_handler.go:267] Detaching "csi-0e86b9836912e4347c635aec1ae4bcb25e848bf65a334c3b1e810f7a5ff2c6fc"
I0902 12:12:24.428920       1 csi_handler.go:219] Error processing "csi-e62f72aa35928c15e5e56b3f7a6b5147f610f7509bdaffe143ce273c811b1473": failed to detach: persistentvolume "pvc-c455bbef-c976-4fd5-9f67-b532e5bef4a0" not found
I0902 12:12:24.428998       1 csi_handler.go:267] Detaching "csi-dd51bacc1cfbd0435a92d1ea8e05f9fb027ce4bd8cd3b7015dbfcc8d040ea158"
I0902 12:12:24.630160       1 csi_handler.go:219] Error processing "csi-65166aee0d924f63a7ca7017f0d7c4250bd1c5811880b38983f698b65e4b4027": failed to detach: persistentvolume "pvc-01f29661-d400-46b3-93c9-a58b53b6f300" not found
I0902 12:12:24.630273       1 csi_handler.go:267] Detaching "csi-af28f2cf9468f24e8392eebb56eee9cb794362410702b9455452a393d8d579f4"
I0902 12:12:24.829035       1 csi_handler.go:219] Error processing "csi-8b2f5a00d831d4e460636716eab24fbea3d03931ad6fbf5d6af848bb6a6e0256": failed to detach: persistentvolume "pvc-6dfe8de3-b710-406c-8605-d6bf5efdac62" not found
I0902 12:12:24.829119       1 csi_handler.go:267] Detaching "csi-9ddb7c305d4a3b6b2fc516c9e528a17d8be1a4660b24480f149ad57a4f292384"
I0902 12:12:25.029797       1 csi_handler.go:219] Error processing "csi-454b489606a09a31102c79d7bef04210c29fe6982abb3453cea3ab2425c2973e": failed to detach: persistentvolume "pvc-45752f8a-7e43-421f-9633-1b435469ada3" not found
I0902 12:12:25.029881       1 csi_handler.go:267] Detaching "csi-e4ef0f978ff63810cef37ef2a3ffa034622f529b0b70f564a637e22c8de2de41"
I0902 12:12:25.229041       1 csi_handler.go:219] Error processing "csi-1fa39a0df001bbe261b8b2eef66e6a6a715073b7e96f4f1a795ade387a3a2920": failed to detach: persistentvolume "pvc-0cbc0ce0-3197-4820-a87e-80179d565def" not found
I0902 12:12:25.229116       1 csi_handler.go:267] Detaching "csi-059b0db92e76e18b71ecc95c96abefe32fa7767682ac0337d92d5445939861d1"
I0902 12:12:25.429072       1 csi_handler.go:219] Error processing "csi-beafff542dc3617455a19627273fc9da705f980539db94e37fbddff41274c2dc": failed to detach: persistentvolume "pvc-33ac8ac6-d2a0-4cc1-812c-70501397d456" not found
I0902 12:12:25.429253       1 csi_handler.go:267] Detaching "csi-aeb9414b9d8415e4093eb2beff8d1bd696be7bdd0068a0366ca3764bbff6c296"
I0902 12:12:25.628575       1 csi_handler.go:219] Error processing "csi-d7c7fc95104b156e6386ce12c942d7b73fd05965ec6d9c78fb5053876e122cbe": failed to detach: persistentvolume "pvc-edf8bb98-7210-4377-8360-b677ce9830bc" not found
I0902 12:12:25.628653       1 csi_handler.go:267] Detaching "csi-22d827840d95cd7e2d5da71c2444565cee90357a064e86b4b6cc24249c5986e1"
I0902 12:12:25.828719       1 csi_handler.go:219] Error processing "csi-71934b29a3f70a324fc0106345abc551b8df98b32081e25317c0d961f1cf4369": failed to detach: persistentvolume "pvc-54b2bfcd-6032-4077-9067-280a0135f46b" not found
I0902 12:12:25.828804       1 csi_handler.go:267] Detaching "csi-7ca26713363581f44bea7fe1fc4a7ac580e17973cdbea3912d0b82854189f9cd"
I0902 12:12:26.029916       1 csi_handler.go:219] Error processing "csi-f17280914ad071a326a6101ad49fa1e86c89105e39e25e12fd362801940b2725": failed to detach: persistentvolume "pvc-01d1c988-f9b2-44e5-a82a-216aab8f2a0d" not found
I0902 12:12:26.029992       1 csi_handler.go:267] Detaching "csi-6e1ce04fc21d3ddd16a0bed3f4f560acbbc9a1ab7cbdd1093379974dbb37aa01"
I0902 12:12:26.229385       1 csi_handler.go:219] Error processing "csi-0e86b9836912e4347c635aec1ae4bcb25e848bf65a334c3b1e810f7a5ff2c6fc": failed to detach: persistentvolume "pvc-55af6aad-c2eb-473f-8eec-0867f6640b25" not found
I0902 12:12:26.229462       1 csi_handler.go:267] Detaching "csi-7330348f97aa35ff9a3bf1a12bf34c84331c96bef822bed1c86b2d4d8f5c09bd"
I0902 12:12:26.430966       1 csi_handler.go:219] Error processing "csi-dd51bacc1cfbd0435a92d1ea8e05f9fb027ce4bd8cd3b7015dbfcc8d040ea158": failed to detach: persistentvolume "pvc-d7634e4d-8d8c-45fd-b6a1-a2388a999d92" not found
I0902 12:12:26.431050       1 csi_handler.go:267] Detaching "csi-11334737db1c762091fb7c3596204a5f3a2df5e12509dabe3d72ba3219302b0c"
I0902 12:12:26.629587       1 csi_handler.go:219] Error processing "csi-af28f2cf9468f24e8392eebb56eee9cb794362410702b9455452a393d8d579f4": failed to detach: persistentvolume "pvc-b1e5f214-4e16-4efd-88d1-c71e110d461f" not found
I0902 12:12:26.629668       1 csi_handler.go:267] Detaching "csi-73a5247d6e46e817f4a029d13c1ca5c3c13b0f08aca95288bd483ad9b9b59c8b"
`

with debug mode enabled:

`time="2020-09-02T12:14:07Z" level=debug msg="GRPC call: /csi.v1.Node/NodeUnstageVolume"
time="2020-09-02T12:14:07Z" level=debug msg="GRPC call: /csi.v1.Node/NodeUnstageVolume"
time="2020-09-02T12:14:07Z" level=debug msg="GRPC request: volume_id:\"pvc-4651daf2-d65e-47e4-b05d-461987a25ed1\" staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4651daf2-d65e-47e4-b05d-461987a25ed1/globalmount\" "
time="2020-09-02T12:14:07Z" level=debug msg="Attempting to acquire shared lock (NodeUnstageVolume-pvc-4651daf2-d65e-47e4-b05d-461987a25ed1)." lock=csi_node_server
time="2020-09-02T12:14:07Z" level=debug msg="Acquired shared lock (NodeUnstageVolume-pvc-4651daf2-d65e-47e4-b05d-461987a25ed1)." lock=csi_node_server
time="2020-09-02T12:14:07Z" level=debug msg="GRPC request: volume_id:\"pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f\" staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f/globalmount\" "
time="2020-09-02T12:14:07Z" level=debug msg="Attempting to acquire shared lock (NodeUnstageVolume-pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f)." lock=csi_node_server
time="2020-09-02T12:14:07Z" level=debug msg=">>>> NodeUnstageVolume" Method=NodeUnstageVolume Type=CSI_Node
time="2020-09-02T12:14:07Z" level=debug msg="<<<< NodeUnstageVolume" Method=NodeUnstageVolume Type=CSI_Node
time="2020-09-02T12:14:07Z" level=debug msg="Released shared lock (NodeUnstageVolume-pvc-4651daf2-d65e-47e4-b05d-461987a25ed1)." lock=csi_node_server
time="2020-09-02T12:14:07Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4651daf2-d65e-47e4-b05d-461987a25ed1/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-4651daf2-d65e-47e4-b05d-461987a25ed1/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T12:14:07Z" level=debug msg="Acquired shared lock (NodeUnstageVolume-pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f)." lock=csi_node_server
time="2020-09-02T12:14:07Z" level=debug msg=">>>> NodeUnstageVolume" Method=NodeUnstageVolume Type=CSI_Node
time="2020-09-02T12:14:07Z" level=debug msg="<<<< NodeUnstageVolume" Method=NodeUnstageVolume Type=CSI_Node
time="2020-09-02T12:14:07Z" level=debug msg="Released shared lock (NodeUnstageVolume-pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f)." lock=csi_node_server
time="2020-09-02T12:14:07Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-6ff5a5b7-217d-44b2-a82e-436c3f4cdc0f/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T12:14:08Z" level=debug msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
time="2020-09-02T12:14:08Z" level=debug msg="GRPC request: "
time="2020-09-02T12:14:08Z" level=debug msg=">>>> NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2020-09-02T12:14:08Z" level=debug msg="<<<< NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2020-09-02T12:14:08Z" level=debug msg="GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > capabilities:<rpc:<type:EXPAND_VOLUME > > capabilities:<rpc:<type:GET_VOLUME_STATS > > "
time="2020-09-02T12:14:08Z" level=debug msg="GRPC call: /csi.v1.Node/NodeUnstageVolume"
time="2020-09-02T12:14:08Z" level=debug msg="GRPC request: volume_id:\"pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b\" staging_target_path:\"/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b/globalmount\" "
time="2020-09-02T12:14:08Z" level=debug msg="Attempting to acquire shared lock (NodeUnstageVolume-pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b)." lock=csi_node_server
time="2020-09-02T12:14:08Z" level=debug msg="Acquired shared lock (NodeUnstageVolume-pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b)." lock=csi_node_server
time="2020-09-02T12:14:08Z" level=debug msg=">>>> NodeUnstageVolume" Method=NodeUnstageVolume Type=CSI_Node
time="2020-09-02T12:14:08Z" level=debug msg="<<<< NodeUnstageVolume" Method=NodeUnstageVolume Type=CSI_Node
time="2020-09-02T12:14:08Z" level=debug msg="Released shared lock (NodeUnstageVolume-pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b)." lock=csi_node_server
time="2020-09-02T12:14:08Z" level=error msg="GRPC error: rpc error: code = FailedPrecondition desc = unable to read the staging target /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b/globalmount; open /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-34af6d3a-2555-4e23-bbfb-fa97de474c8b/globalmount/volumePublishInfo.json: no such file or directory"
time="2020-09-02T12:14:10Z" level=debug msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
time="2020-09-02T12:14:10Z" level=debug msg="GRPC request: "
time="2020-09-02T12:14:10Z" level=debug msg=">>>> NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2020-09-02T12:14:10Z" level=debug msg="<<<< NodeGetCapabilities" Method=NodeGetCapabilities Type=CSI_Node
time="2020-09-02T12:14:10Z" level=debug msg="GRPC response: capabilities:<rpc:<type:STAGE_UNSTAGE_VOLUME > > capabilities:<rpc:<type:EXPAND_VOLUME > > capabilities:<rpc:<type:GET_VOLUME_STATS > > "
`
Please let me know if you need any additional info.

BR,

**Comment by gnarl** [comment]
Hi @hujogrom,

This issue was fixed with [commit f59a30b](https://github.com/NetApp/trident/commit/f59a30b63d80057b5ccdeaa4e22c3009d2ed6241) and will be included in Trident 20.07.1.

**Comment by YuxiJin-tobeyjin** [comment]
@gnarl face same issue，any plan to release 20.07.1？

**Comment by gnarl** [comment]
Hi @YuxiJin-tobeyjin,

We are working on code completion for Trident 20.07.1. We plan on this release being available by the end month.
