### ISSUE TITLE
Improve snapshot-related documentation page

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#445]
**Describe the solution you'd like**

- This leaves the impression that snaps should work as long as one's K8s is new enough:

> "Before creating a Volume Snapshot, a VolumeSnapshotClass must be set up."

- Official [blog post on snapshots](https://kubernetes.io/blog/2019/12/09/kubernetes-1-17-feature-cis-volume-snapshot-beta/#how-do-i-deploy-support-for-volume-snapshots-on-my-kubernetes-cluster) says "it is strongly recommended that Kubernetes distributors bundle and deploy the controller and CRDs as part of their Kubernetes cluster management process (independent of any CSI Driver)" but *not all do*.

**Describe alternatives you've considered**

- Clarify requirements by adding the missing piece. 

Before creating a Volume Snapshot, [External Snapshotter](https://github.com/kubernetes-csi/external-snapshotter#usage) must be installed and a VolumeSnapshotClass must be set up.

**Comment by balaramesh** [comment]
Fixed with [619be02](https://github.com/NetApp/trident/commit/619be024f43671d2abb2ce8c7adbd5da80eb273e)
