### ISSUE TITLE
Unable to upgrade to 20.07 on a cluster without internet access: unable to set the correct image for trident-autosupport

### ISSUE THREAD

**Issue by heikocane** [NetApp/trident#447]
**Describe the bug**
I'm trying to update trident on our kubernetes cluster without internet access. We can pull images from our artifactory (artifactory.mycompany.com), there are two remote repositories, one for dockerhub (called docker-dockerhub-release-remote) and one for quay.io (docker-quay-official-remote).

I tried this command:
`
./tridentctl install -n trident --image-registry artifactory.mycompany.com/docker-quay-official-remote --trident-image artifactory.mycompany.com/dockerhub-release-remote/netapp/trident:20.07.0 --autosupport-image artifactory.mycompany.com/docker-dockerhub-release-remote/netapp/trident-autosupport:20.07.0
`

Using the --trident-image works fine (we have set-up the 20.04 with this parameter). 

The first upgrade to 20.07 failed because of
`Failed to pull image "artifactory.mycompany.com/docker-quay-official-remote/netapp/trident-autosupport:20.07.0": rpc error: code = Unknown desc = Error response from daemon: manifest for artifactory.mycompany.com/docker-quay-official-remote/netapp/trident-autosupport:20.07.0 not found` 

(seems like netapp/trident-autosupport is not available on quay) so I added 

` --autosupport-image artifactory.mycompany.com/docker-dockerhub-release-remote/netapp/trident-autosupport:20.07.0`

to the command and it still failes:

` Failed to pull image "artifactory.mycompany.com/docker-quay-official-remote/dockerhub-release-remote/netapp/trident-autosupport:20.07.0": rpc error: code = Unknown desc = Error response from daemon: manifest for artifactory.mycompany.com/docker-quay-official-remote/dockerhub-release-remote/netapp/trident-autosupport:20.07.0 not found`

I don't know why the image url is a strange mix of the given image-registry and the autosupport-image and not working as the trident-image parameter.

**Environment**
Kubernetes 1.17.9 Cluster without internet access

Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.07
- Trident installation flags used: see description
- Container runtime: Docker 19.03.12
- Kubernetes version: 1.17.9
- Kubernetes orchestrator: Kubespray
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: Ubuntu 18.04
- NetApp backend types: ontap
- Other:

**To Reproduce**
see description

**Expected behavior**
trident can be installed in an offline environment

**Additional context**

**Comment by hujogrom** [comment]
Hello ,

you can always use './tridentctl install  --generate-custom-yaml' option, which creates configuration yaml's in 'setup' directory (best invoke from trident-installer directory). Image info is stored in trident-deployment.yaml and trident-daemonset.yaml. After editing the repository there, you can install Trident using './tridentctl install -n trident --use-custom-yaml'.

BR,

**Comment by scaleoutsean** [comment]
https://netapp-trident.readthedocs.io/en/stable-v20.07/dag/kubernetes/deploying_trident.html#trident-installation-modes explains offline installation.

Trident Autosupport image:

https://hub.docker.com/r/netapp/trident-autosupport/

**Comment by gnarl** [comment]
Closing this issue since the ability to install Trident in an air gapped network is supported.
