### ISSUE TITLE
Mention the new autosupport image in offline install section

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#448]
in the docs for v20.07.0:

> This registry must contain the Trident image (obtained here) and the CSI sidecar images as required by your Kubernetes version.

(Source: https://netapp-trident.readthedocs.io/en/stable-v20.07/dag/kubernetes/deploying_trident.html#trident-installation-modes)

That link leads to https://hub.docker.com/r/netapp/trident/. Since v20.07.0 we have another image so we should probably add a link to https://hub.docker.com/r/netapp/trident-autosupport/. The first link is referred to as mandatory (*must contain") so I'm not going to submit a PR as I'm not sure about the wording (whether the autosupport image is optional (when `--silence-autosupport` is applied) or also mandatory.)

**Comment by gnarl** [comment]
Thanks, @scaleoutsean!

**Comment by balaramesh** [comment]
Fixed with [619be02](https://github.com/NetApp/trident/commit/619be024f43671d2abb2ce8c7adbd5da80eb273e)
