### ISSUE TITLE
Request for Enhancement - production setup documentation

### ISSUE THREAD

**Issue by Filirom1** [NetApp/trident#45]
Hello,

You did a very great job with Trident, I really appreciate.
However, I am not confident in running Trident in production.

I would appreciate a documentation explaining how to setup an Highly Available Trident, how to secure the communication between Trident and Etcd, how to monitor it and how to backup it.

When using k8s or OpenShift, an Etcd cluster is already running with every production aspects already in place. It would be awesome if Trident could use the k8s Etcd instance instead of creating it's own one. IMHO it would ease the production setup, if I do not have to care about a new Etcd. Do you think it would work with Trident ?

Thank you very much for your work and I am grateful that you did it in OpenSource.
Romain

**Comment by andiMenge** [comment]
I also would like support for:

- external ETCD Clusters
- external ETCD Clusters with encryption (self signed certs)
- ETCD `v3`APIs
- A single static binary Trident artefact-release for installing in own containers (preferably based on alpine-linux)
- `solidfire-backend-config.json` injectable via k8s configMaps

**Comment by kangarlou** [comment]
Hi. Thanks for the feedback! Adding support for an external etcd cluster and etcdv3 API is definitely on our roadmap. However, I would like to comment on a couple of things. First, Kubernetes documentation doesn't recommend using the etcd cluster used internally by Kubernetes for other applications and services. Giving Kubernetes apps access to the Kubernetes etcd cluster is equivalent to giving these apps root access to the Kubernetes cluster. Also, performance has improved considerably in etcdv3, but for small etcd clusters, it's not desirable to have many apps compete with Kubernetes in using the etcd resources (this shouldn't be a concern for Trident as it's not an I/O intensive app). Second, the current etcd setup, where Trident launcher provisions the storage for the etcd container in the Trident pod, is as reliable as the underlying NetApp storage. In other words, in absence of any out-of-band volume replication and snapshot, Trident is as reliable as the production workloads that it supports. This setup may in fact be more reliable than an in-memory, 3-node etcd cluster where losing two nodes brings down the whole cluster. Having said that, I understand the need for a highly available setup and I'm in favor of it.

My suggestion is that for now you rely on the existing etcd setup. You have options to make it more reliable/available by following some of the instructions outlined below:
https://kubernetes.io/docs/tasks/administer-cluster/configure-upgrade-etcd/
https://kubernetes.io/docs/admin/high-availability/

Once we add support for an external etcd cluster, you can migrate your etcd data from the volume managed by Trident to your production etcd cluster. Thanks!

**Comment by Filirom1** [comment]
Hi @kangarlou

Good to know that supporting external Etcd is on the roadmap. Please do not forget to allow client certificates authentication as well, because it's a often used with Etcd, and I personnaly use it this way 😄 

I agree with your recommendation about not sharing Etcd with application because of the privilege elevation it implies. However, I do not consider Trident like a user application, but more like an infrastructure component. I will not host it side by side with user applications because I don't want user app to have Firewall access to the Filer administration IP.

Thanks to you, I know that Trident is not IO intensive for Etcd, and I still consider sharing the k8s Etcd 😄 . OpenShift already do it, and is more intensive than Trident could be.

Could you confirm me that Trident is stateless and that it would be possible to scale the Trident application once the Etcd will be externalized ? Could you confirm me as well that the only component to backup is Etcd ?

Currently, I can't really improve the Etcd setup available in the Trident pod because client certification authentication is not supported, as well as [Etcd cluster](https://github.com/NetApp/trident/blob/44272ba2acf369838fc9f473ed3f206fdd18d183/persistent_store/etcd.go#L27)

I thank you for your time and for your great answer that provides me such details and suggestions.

**Comment by andiMenge** [comment]
@kangarlou thank you for the detailed explanation. With my cluster engineer perspective I see some things a little bit different. For example the **`ETCDv3` API**:

We use it as the k8s brain and therefore handle the backup mechanism of it very carefully. Using the v3 API for Trident gives us the benefit of having synced backups with the k8s brain. If we use a additional `ETCDv2` API for Trindent then we have to build an additional backup mechanism and sync it with the k8s brain.

Regarding the **Trident Deployment**: 

The install script with the launcher feels a little bit complicated for me. My _personal_ principal is to build simple mechanisms that lead to faster mean time to recovery in case of a failure. I appreciate the one click abstraction that you have build with `install_trident.sh` but it has a lot of moving parts and is not easy to maintain for me. 

For example, I would have to clone your repo, switch to stable branch and have to inject my `backend.json` config. For updates I assume I have to `pull` from github. This way I have to version control my `backend.json` in a another repo in my version control system and have to inject it into my clone of the Trident repo.

For me it would be simpler to just have a binary that lives inside my repo along with the additional k8s resources like service account, rolebindings etc. Doing it that way I have full control over the deployment and can use my existing CI/CD automation to package Trident in a container and deploy it to the cluster. Another benefit is that this is the same deployment mechanism as all other deployments that I have in the cluster.

Using the `install_trident.sh` leads to a deployment dependency to the NetApp Team. For example if I want to update Trident and the update script fails somehow, my update task is blocked until the script is fixed. If I use my own deployment mechanism (CI/CD automation) I can handle deployment issues myself.

**Comment by kangarlou** [comment]
@Filirom1 Yes, Trident container is stateless and all the state is managed by etcd, so you just need to back up the state managed by etcd. However, I would caution against deploying more than one instance of Trident as Trident doesn't handle concurrent updates and it caches some of the etcd state. Supporting etcd client certificates is definitely part of supporting external etcd clusters.

@andiMenge I understand that it's not ideal to have separate workflows for etcdv2 and etcdv3, so supporting the etcdv3 API is definitely on our roadmap. A lot of complications associated with the install script is due to Trident provisioning storage for itself. These complications would go away with support for external etcd clusters where Trident doesn't have to provision storage for itself. As I indicated to you in an earlier [comment](https://github.com/NetApp/trident/issues/34#issuecomment-310678388), you never need to clone the GitHub repo or build Trident yourself. All you need to do is to download the Trident installer bundle for the version you're interested in. See step 3 in the [Getting Started](https://github.com/NetApp/trident#getting-started) section. You can write your own custom `install_trident.sh` script and rely on the Trident images that we host in DockerHub.

**Comment by kangarlou** [comment]
@Filirom1 @andiMenge Trident supports etcdv3 with TLS in release [v18.01.0-beta.0](https://github.com/NetApp/trident/releases/tag/v18.01.0-beta.0). Please see the [docs](https://github.com/NetApp/trident/tree/master/extras/external-etcd) for more information.

Also, in case you want to build your own custom images, Trident installer bundle now includes binaries for Trident and Trident launcher under `trident-installer/extras/bin/`.
