### ISSUE TITLE
Allow users to specify tolerations/nodeSelectors in the operators provisioner object

### ISSUE THREAD

**Issue by JosephGJ** [NetApp/trident#450]
I'd like to be able to add nodeSelectors/tolerations to the operators provisioner object to determine where the trident provisioners deployment is run, as this currently is not an option in the provisioner objects spec.

**Comment by julian3xl** [comment]
Hi, I've added a PR to fix this https://github.com/NetApp/trident/pull/565. Hope you like it

**Comment by gnarl** [comment]
This issue is resolved with commits [e167c7](https://github.com/NetApp/trident/commit/e167c7e92e143e4bb4a8373ff0dc9f41c374cd42) and [c7c167d](https://github.com/NetApp/trident/commit/c7c167da22657559ae2c330e3aa8ef7150300214). This change will be included with the Trident 22.01 release.
