### ISSUE TITLE
Fix the documentation about the ontap-san drivers

### ISSUE THREAD

**Issue by pablogarciaarevalo** [NetApp/trident#451]
There is a mistake with the supported access mode for ontap-san & ontap-san-economy drivers in the Trident documentation, in the section [drivers for ONTAP](https://github.com/NetApp/trident/blob/stable/v20.07/docs/kubernetes/operations/tasks/backends/ontap/drivers.rst).
The mount type for the ontap-san drivers is block, not file, and iSCSI only supports ReadWriteOnce and ReadOnlyMany access mode based on the [Kubernetes documentation](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes).

**Comment by ntap-arorar** [comment]
Hello @pablogarciaarevalo 

iSCSI can be used in two different modes (see [Volume modes](https://kubernetes.io/docs/concepts/storage/persistent-volumes/#volume-mode)), one is using iSCSI volume with a filesystem that you can mount on a pod and the other is iSCSI volume as a raw block device that can be attached to the block. This is what `mount` and `block` refers to that is what mount type column of the Trident documentation.

Also, iSCSI raw block device unlike iSCSI volume with a filesystem supports ReadWriteMany.

I hope this helps in clearing the confusion.

**Comment by pablogarciaarevalo** [comment]
Understood, I didn't know about the volume mode. Thanks a lot
