### ISSUE TITLE
persistentvolume-controller sends waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator

### ISSUE THREAD

**Issue by willemstevens** [NetApp/trident#457]
**Describe the bug**

We've deployed an AKS cluster connecting to Azure NetApp Files using the trident driver (20.04). Since last Friday evening the creation of new persistent volumens is stuck on a message from the persistentvolume-controller:  

Type    Reason                Age                   From                         Message
  ----    ------                ----                  ----                         -------
  Normal  ExternalProvisioning  82s (x9503 over 39h)  persistentvolume-controller  waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator

This used to work well before. I can't find anything in the logs that can tell me more about the cause of the issue. I've opened a support case in Azure but both the Azure AKS guys as the Azure NetApp guys asked me to open a case at NetApp/Trident because they don't see what could be wrong.

The storage class is configured this way:

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azure-netapp-files-bronze
provisioner: csi.trident.netapp.io
reclaimPolicy: Retain
allowVolumeExpansion: true
parameters:
  selector: "performance=bronze"
  backendType: "azure-netapp-files"

And the backend:

{
    "version": 1,
    "storageDriverName": "azure-netapp-files",
    "subscriptionID": "removedId",
    "tenantID": "removedId",
    "clientID": "removedId",
    "clientSecret": "removedSecret",
    "nfsMountOptions": "vers=3,proto=tcp,timeo=600",
    "labels": {
        "cloud": "azure"
    },
    "location": "westeurope",
    "storage": [
        {
            "labels": {
                "performance": "bronze"
            },
            "serviceLevel": "Standard"
        }
    ],
    "virtualNetwork": "<vnetName>",
    "subnet": "<subnetName>"
}

The backend is online:

+------------------------+--------------------+--------------------------------------+--------+---------+
|          NAME          |   STORAGE DRIVER   |                 UUID                 | STATE  | VOLUMES |
+------------------------+--------------------+--------------------------------------+--------+---------+
| azurenetappfiles_8a213 | azure-netapp-files | cb376368-a295-49a4-8619-80bd1bea6a39 | online |       17 |
+------------------------+--------------------+--------------------------------------+--------+---------+

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.04
- Trident installation flags used: ./tridentctl install -n trident2
- Container runtime: [e.g. Docker 19.03.1-CE] 
- Kubernetes version: [e.g. 1.15.1] AKS 1.17.7
- Kubernetes orchestrator: [e.g. OpenShift v3.11, Rancher v2.3.3]
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: [e.g. RHEL 7.6, Ubuntu 16.04] Ubuntu 16.04
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7] Azure NetApp Files
- Other:

**To Reproduce**

We cannot reproduce this issue

**Expected behavior**

We expected a persistent volume to be created and the persistent volume claim to be bound

**Additional context**

**Comment by gnarl** [comment]
Hi @willemstevens,

This isn't the right forum to provide you with the level of support you require to resolve this issue. Please contact NetApp Support.

To open a case with NetApp, please go to https://mysupport.netapp.com/site/.

- Bottom left, Click on 'Contact Support'
- Find the appropriate number from your region to call in, or login.
- Note: Trident is not listed on the page, but is a supported product by NetApp based on a supported Netapp storage SN.
- Open the case on the NetApp storage SN, and provide the description of the problem.
- Be sure to mention the product is Trident on Kubernetes, and provide the details. Mention this GitHub.
- The case will be directed to Trident support engineers for response.
