### ISSUE TITLE
autosupportImage image is not populated correctly

### ISSUE THREAD

**Issue by vnandha** [NetApp/trident#459]
**Describe the bug**
The --autosupport-image populated by the tridentctl always prepends with --image-registry value specified.

I am trying to install 20.07.1, I used the tridentctl to generate the yaml files to see what are the images being used, We have restrictions to pull images directly from external so we have to mirror the images. In 20.04.0 i used 
```
./tridentctl install --image-registry docker.internal.com:4443/someorg/quay.io --trident-image docker.internal.com:4443/someorg/docker.io/netapp/trident:20.04.0 --etcd-image docker.internal.com:4443/someorg/etcd3:3.3.15 -n kube-trident

that worked perfectly, the tridentctl used the trident image i passed. but in 20.07.1 the autosupport image is populated with its default value 

./tridentctl install --image-registry docker.internal.com:4443/someorg/quay.io --trident-image docker.internal.com:4443/someorg/docker.io/netapp/trident:20.07.1 -n kube-trident --generate-custom-yaml

```
/etc/k8s/trident/20.07.1/trident-installer/setup $ cat trident-deployment.yaml |grep image
        image: docker.internal.com:4443/someorg/docker.io/netapp/trident:20.07.1
        image: docker.internal.com:4443/someorg/quay.io/netapp/trident-autosupport:20.07.0
        image: docker.internal.com:4443/someorg/quay.io/k8scsi/csi-provisioner:v1.6.0
        image: docker.internal.com:4443/someorg/quay.io/k8scsi/csi-attacher:v2.2.0
```

Notice that trident image used as it is supplied from the command line, but the default autosupport image was prepended with image-registry.

When supplied custom image to --autosupport-image, then also the same as the code does not check for the provided value it just prepends with image-registry

```
/etc/k8s/trident/20.07.1/trident-installer/setup $ ./tridentctl install --image-registry docker.internal.com:4443/someorg/quay.io  --autosupport-image docker.internal.com:4443/someorg/docker.io/netapp/trident-autosupport:20.07.0 --trident-image docker.internal.com:4443/someorg/docker.io/netapp/trident:20.07.1  -n kube-trident --generate-custom-yaml

/etc/k8s/trident/20.07.1/trident-installer/setup $ cat trident-deployment.yaml |grep image
        image: docker.internal.com:4443/someorg/docker.io/netapp/trident:20.07.1
        image: docker.internal.com:4443/someorg/quay.io/someorg/docker.io/netapp/trident-autosupport:20.07.0
        image: docker.internal.com:4443/someorg/quay.io/k8scsi/csi-provisioner:v1.6.0
        image: docker.internal.com:4443/someorg/quay.io/k8scsi/csi-attacher:v2.2.0
**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.07
- Trident installation flags used: see above
- Container runtime: Redhat Docker 1.13
- Kubernetes version: 1.15.9
- Kubernetes orchestrator: Upstream
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: RHEL 7.8
- NetApp backend types: ONTAP
- Other:

**To Reproduce**
Try the installation command mentioned above

**Expected behavior**
The --autosupport-image populated as given in the input or without pretending the --image-registry

**Additional context**

**Comment by gnarl** [comment]
This issue is fixed in the Trident 21.01 release with [commit c7570c2](https://github.com/NetApp/trident/commit/c7570c2c1a83126631085a7da18af32ed63f54a0).
