### ISSUE TITLE
Reinstall of Trident after cDot crash

### ISSUE THREAD

**Issue by robotica72** [NetApp/trident#46]
So the short version - my cDot for my my lab crashed and I rebuilt it - I added the mount points back for legacy pods and they all function - but I needed to redeploy my trident appliance and no matter what I try now, it refuses to create anything new.   When I create a storage class, just basic, I keep getting errors like this in the log: (Obviously the big error is : (Kubernetes frontend couldn't provision a volume: No available backends for storage class basic! (will retry upon resync)" volume=default-basic-f7357)

Did I miss a permission on cDot somewhere?  as a lab its pretty much swiss cheese for any security...

time="2017-08-01T19:19:34Z" level=info msg="Running Trident storage orchestrator." build_time="Wed Jul 26 20:51:19 EDT 2017" version=17.07.1
time="2017-08-01T19:19:34Z" level=info msg="Kubernetes frontend determined the container orchestrator version." gitVersion=v1.7.1 version=1.7
time="2017-08-01T19:19:34Z" level=info msg="Added frontend." name=kubernetes
time="2017-08-01T19:19:34Z" level=info msg="Starting REST interface on localhost:8000"
time="2017-08-01T19:19:34Z" level=info msg="Unable to find key /trident/v1/backend"
time="2017-08-01T19:19:34Z" level=warning msg="Unable to find key /trident/v1/backend.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-08-01T19:19:34Z" level=info msg="Added an existing storage class." handler=Bootstrap storageClass=ssd
time="2017-08-01T19:19:34Z" level=info msg="Unable to find key /trident/v1/volume"
time="2017-08-01T19:19:34Z" level=warning msg="Unable to find key /trident/v1/volume.  Continuing bootstrap, but consider checking integrity if Trident installation is not new."
time="2017-08-01T19:19:34Z" level=info msg="Unable to find key /trident/v1/txn"
time="2017-08-01T19:19:34Z" level=warning msg="Couldn't retrieve volume transaction logs: Unable to find key"
time="2017-08-01T19:19:34Z" level=info msg="trident bootstrapped successfully."
time="2017-08-01T19:19:34Z" level=warning msg="Kubernetes frontend couldn't provision a volume: No available backends for storage class ssd! (will retry upon resync)" volume=default-basic-72338
time="2017-08-01T19:20:34Z" level=warning msg="Kubernetes frontend couldn't provision a volume: No available backends for storage class ssd! (will retry upon resync)" volume=default-basic-72338
time="2017-08-01T19:21:15Z" level=warning msg="Kubernetes frontend couldn't provision a volume: No available backends for storage class ssd! (will retry upon resync)" volume=default-basic-72338
time="2017-08-01T19:22:18Z" level=info msg="No backends currently satisfy provided storage class." storageClass=basic
time="2017-08-01T19:22:18Z" level=info msg="Kubernetes frontend successfully added the storage class." default_storageClasses= storageClass=basic storageClass_parameters=map[backendType:ontap-nas] storageClass_provisioner="netapp.io/trident"
time="2017-08-01T19:23:58Z" level=warning msg="Kubernetes frontend couldn't provision a volume: No available backends for storage class basic! (will retry upon resync)" volume=default-basic-f7357
time="2017-08-01T19:24:34Z" level=warning msg="Kubernetes frontend couldn't provision a volume: No available backends for storage class basic! (will retry upon resync)" volume=default-basic-f7357

Hoping to fix this quickly for a quick demo of Trident Friday :)

Any ideas?

**Comment by kangarlou** [comment]
When you say "my cDot for my my lab crashed and I rebuilt it", does it mean you lost the volume that was internally used by Trident's etcd component? If the volume is still present, Trident should recover all the information about backends, volumes, and storage classes that it managed before the crash. If you lost the volume, then you should use `tridentctl` to add the backends again. That's why you see messages like `"Kubernetes frontend couldn't provision a volume: No available backends for storage class basic! (will retry upon resync)"`. Losing the etcd volume also means that Trident wouldn't automatically unprovision the volumes it created before the crash as it no longer has any records of them.

**Comment by robotica72** [comment]
Thanks for the quick reply - I was just coming back to mention I forgot that step - Its been killing :)   Thanks again....
