### ISSUE TITLE
Trident Installer not working on macOS

### ISSUE THREAD

**Issue by andiMenge** [NetApp/trident#47]
Hi,
I am unable to deploy Trident to my Kubernetes cluster

Specs:
- macOS `10.12.5`
- Kubernetes `v1.6.4`
- `trident-installer-17.07.1`

I see the following **issues** with the install command:

- namespace argument is ignored
- `sed` not working correctly
- errors don't get handled
- no pod gets deployed
- grep not working correctly (uninstall)

install output:
```
./install_trident.sh -n kube-system
Installer assumes you have deployed Kubernetes. If this is an OpenShift deployment, make sure 'oc' is in the $PATH.
You are running in namespace default.
Trident will be deployed in namespace default.
For maximum security, we recommend running Trident in its own namespace: ./install_trident.sh -n trident
serviceaccount "trident" created
serviceaccount "trident-launcher" created
clusterrole "trident" created
clusterrole "trident-launcher" created
clusterrolebinding "trident" created
clusterrolebinding "trident-launcher" created
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
sed: 1: "/Users/andi/1_repositor ...": command a expects \ followed by text
configmap "trident-launcher-config" created
pod "trident-launcher" created
Trident deployment definition is available in /Users/andi/1_repository/psp/trident-installer/setup/trident-deployment.yaml.
Started launcher in namespace "default".
```

uninstall output:
```
./uninstall_trident.sh
Installer assumes you have deployed Kubernetes. If this is an OpenShift deployment, make sure 'oc' is in the $PATH.
You are running in namespace default.
Cleanup will take place in namespace default.
usage: grep [-abcDEFGHhIiJLlmnOoqRSsUVvwxZ] [-A num] [-B num] [-C[num]]
	[-e pattern] [-f file] [--binary-files=value] [--color=when]
	[--context[=num]] [--directories=action] [--label] [--line-buffered]
	[--null] [pattern] [file ...]
pod "trident-launcher" deleted
clusterrolebinding "trident" deleted
clusterrolebinding "trident-launcher" deleted
clusterrole "trident" deleted
clusterrole "trident-launcher" deleted
serviceaccount "trident" deleted
serviceaccount "trident-launcher" deleted
configmap "trident-launcher-config" deleted
This script didn't delete namespace "default" and PVC and PV "trident" in case they're going to be reused. Please use the -a option if you need PVC and PV "trident" deleted.
Successfully deleted Trident deployment, service accounts, and cluster roles and role bindings.
Successfully deleted Trident launcher pod and configuration.
```

**Comment by dutchiechris** [comment]
I believe the user utilities in MacOS are BSD based while the ones in Linux are GNU based.  Likely the utilities called by the installer use options that only exist in the GNU ones.  I run (gasp!) Windows 10 on my desktop and use kubectl from it for some tasks, but to run the Trident installer I jump on a k8s cluster node that has kubectl installed.

Since Trident users must have a linux box (k8s requirement) I'd suggest a doc update to specify the installer must be run from linux.  If MacOS (or windows) support for the installer is needed then it needs some updates.  If you're up for it I know the team welcomes PRs :-)

**Comment by andiMenge** [comment]
@dutchiechris I agree with you. A simple entry in the requirements could be a quick fix. At least for me because I prefer a custom deployment without the installer.

On the other hand, not every admin/engineer has a dedicated linux box with `kubectl` installed or wants to change the state of a production server while pulling some scripts on it.

**Comment by rushins** [comment]
Hello

i get error unable to recognize . i have K8S 1.7 release and trident 17.07.1 "/Users/i811144/rushi/devops/kubernetes/sapinternalprojects/saplama-lvm/virtual-colo-cluster/storageclass/trident-installer/trident-clusterrolebindings-openshift.yaml": no matches for /, Kind=ClusterRoleBinding

here is my install step.


./install_trident.sh -n trident
Installer assumes you have deployed OpenShift.
You are running in namespace default.
Trident will be deployed in namespace default.
For maximum security, we recommend running Trident in its own namespace: ./install_trident.sh -n trident
unable to recognize "/Users/i811144/rushi/devops/kubernetes/sapinternalprojects/saplama-lvm/virtual-colo-cluster/storageclass/trident-installer/trident-clusterrolebindings-openshift.yaml": no matches for /, Kind=ClusterRoleBinding
