### ISSUE TITLE
Trident fails with K8s 1.19 despite being listed as a supported version in the docs

### ISSUE THREAD

**Issue by cjreyn** [NetApp/trident#472]
**Describe the bug**
The docs at https://netapp-trident.readthedocs.io/en/stable-v20.07/support/requirements.html#supported-frontends-orchestrators state that v20.07 supports the latest kubernetes version 1.19

When running on a cluster with 1.19.3 I get the following:

`time="2020-10-21T12:58:01Z" level=fatal msg="Could not create Kubernetes k8sclient." error="unsupported Kubernetes version; Trident-Operator 20.07.0 supports Kubernetes versions in the range [1.14, 1.18]"`

I can't see anything in the change log for v20.07.0 or v20.07.01 that suggests v1.19 is supported. Are the docs just wrong?

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.07.0
- Trident installation flags used: operator installed using default bundle (kubectl create -f deploy/bundle.yaml)
- Container runtime: Docker 19.03.8-CE
- Kubernetes version: 1.19.3
- Kubernetes orchestrator: kubeadm
- Kubernetes enabled feature gates: none
- OS: RHEL 7.8
- NetApp backend types: Not yet hooked up to a backend

**To Reproduce**
Kubeadm deployed cluster at 1.19.x with the trident operator.

**Expected behavior**
Trident to work

**Comment by balaramesh** [comment]
@cjreyn support for k8s 1.19 is available with Trident [20.07.1](https://github.com/NetApp/trident/releases/tag/v20.07.1)

**Comment by cjreyn** [comment]
Thanks @balaramesh I missed that in the changelog. I will update.
