### ISSUE TITLE
csi-attacher logs curl command including Bearer Token

### ISSUE THREAD

**Issue by jrhunger** [NetApp/trident#479]
**Describe the bug**

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.04 and 20.07
- Trident installation flags used: --image-registry $DOCKER_REGISTRY_FQDN -n trident -d
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: 1.18.5 and 1.19.0
- Kubernetes orchestrator: PKS Esential (basically upstream)
- Kubernetes enabled feature gates: VolumeSnapshotDataSource: true
- OS: RHEL 7.8 and 7.9
- NetApp backend types: ONTAP AFF v??
- Other:

**To Reproduce**
1. install trident and use it
2. kubectl -n trident logs -l app=controller.csi.trident.netapp.io --container=csi-attacher | grep curl

Observe lines like this:
I1030 20:06:07.481822       1 round_trippers.go:423] curl -k -v -XGET  -H "User-Agent: csi-attacher/v0.0.0 (linux/amd64) kubernetes/$Format" -H "Accept: application/json, */*" -H "Authorization: Bearer eyJhb..8vKXNA" 'https://172.16.128.1:443/apis/storage.k8s.io/v1beta1/csinodes?allowWatchBookmarks=true&resourceVersion=92584026&timeout=7m3s&timeoutSeconds=423&watch=true'

**Expected behavior**
A clear and concise description of what you expected to happen:
I expect the log should not include any authorization tokens

**Additional context**
In our log aggregator we are seeing this across all of our trident-enabled clusters.

**Comment by ysakashita** [comment]
@gnarl Please let me know when it will be fixed if you know.

**Comment by bswartz** [comment]
This is an issue in the CSI sidecar. The appropriate place to file this bug is:
https://github.com/kubernetes-csi/external-attacher

If you want us to help you file a bug against that project we're more than happy to.

**Comment by bswartz** [comment]
Also because it's a security issue, you should follow the process for reporting a security issue:
https://kubernetes.io/docs/reference/issues-security/security/

Make sure the mention that the affected component is the CSI external-attacher

**Comment by bswartz** [comment]
I actually started to look into why the external attacher sidecar is doing this and it seems that somehow the log level for the sidecar is turned up to 9. This is under the control of Trident and may not be a bug in the sidecar at all.

**Comment by clintonk** [comment]
Trident uses 9 for the log level if installed with --debug, otherwise it uses 2.  What's the log level of the offending message?

**Comment by bswartz** [comment]
Yes, it's because you specified the "-d" flag at install time. That causes the sidecars to run with a log verbosity of 9, which is not secure. Don't enable debug if you don't want secrets to get logged by sidecars.

We might want to consider a middle level of verbosity that's lower than this but higher than the default for some cases.

**Comment by bswartz** [comment]
@clintonk The log level of the offending message is 9

**Comment by jrhunger** [comment]
OK, i see the -d in our install command above.  Thanks for digging into this.  I see sometime in November we updated our install command from:
tridentctl install  --image-registry $DOCKER_REGISTRY_FQDN -n trident -d
to:
tridentctl install  --image-registry $DOCKER_REGISTRY_FQDN --silence-autosupport -n trident 

and that seems to have resolved it on our side.
