### ISSUE TITLE
Documentation update: CSI Sidecars versions

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#480]
**Describe the solution you'd like**
As some customers run Kubernetes clusters in closed environments, they need to know in advance the **list** & **version** of images they have to download before moving to the Trident installation.
It would be beneficial to add a table in the Trident requirement page that lists these images alongside their version.

**Describe alternatives you've considered**
manually parse the file: https://github.com/NetApp/trident/blob/master/cli/k8s_client/yaml_factory.go

**Additional context**

**Comment by mzamot** [comment]
We have experienced this first hand with our customers. We need to know the CSI images, so far the only way is digging into the code.

**Comment by gnarl** [comment]
The documentation for the Trident v21.01 release will include a CSI sidecar table. This is included in [commit 66414c1](https://github.com/NetApp/trident/commit/66414c19d3a5960a141094584a88b05a5d9cd817).
