### ISSUE TITLE
Restrict storageclass to certain backends after creation

### ISSUE THREAD

**Issue by geoberle** [NetApp/trident#482]
We are using Trident 20.04 on Openshift 3.11 (without CSI) right now and have one StorageClass and one tridentbackend defined. Since it is just this one backend, the storageclass picks this one to provision persistent volumes. Lets call them storageclass1 and backend1

Now we would like to introduce a second storageclass and a second backend. Lets call them storageclass2 and backend2. We would like to configure it in a way, that storageclass1 only uses backend1 and storageclass2 uses only backend2. Storageclass1 has currently no restrictions in what backend to use so it will most likely start using backend2 as well - something i want to prevent.

From the blog article (https://netapp.io/2019/03/26/tenant-data-isolation-with-trident/) i learned that i would need to set the storagePool setting in storageclass1 like this

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: storageclass1
parameters:
  backendType: ontap-nas-economy
  storagePools: backend1:.*
provisioner: netapp.io/trident
...                                

But since storageclass parameters can not be updated and storageclass1 already exists and has already provisioned many PVs, i'm unsure how to do this change. I tried to find documentation regarding this but could not find anything related to this. I'm aware that this is most likely a very special situation.

Thanks
Gerd

**Comment by clintonk** [comment]
Hi, @geoberle.  This situation isn't that special!  Once a PV is created, it doesn't remain "connected" to its storage class, so you can delete and recreate the storage class at will.

**Comment by geoberle** [comment]
Hi Clinton 
Thank you for your answer. I was not aware of this disconnected nature of the storageclass :)

I will give it a try on our testcluster. 

👍

**Comment by geoberle** [comment]
Recreating the storageclass worked out quite well. Everything's works as expected. Thank you for your guidance!
