### ISSUE TITLE
backend password details appearing in debug mode

### ISSUE THREAD

**Issue by vijaymailb** [NetApp/trident#485]
**Describe the bug**
backend password details appearing in debug mode

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [e.g. 20.07]
- Trident installation flags used: [-d]
- Container runtime: [Docker 19.03.1-CE]
- Kubernetes version: [e.g. 1.18]
- Kubernetes orchestrator: [OCP 4.5]
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: [CoreOS]
- NetApp backend types: [ONTAP FAS8200]
- Other:

**To Reproduce**

**Expected behavior**
Password should be hashed in the debug log.

**Additional context**
bastion@hbupiuatbjs trident-installer]$ ./tridentctl -n otrident create backend -f /home/bastion/netapptrident/manifests/backend-ontap-nas_node1.json -d
Operating mode = tunnel, Trident pod = trident-csi-7bb4bfb84-tt9gh, Namespace = otrident, CLI = oc
Invoking tunneled command: oc exec trident-csi-7bb4bfb84-tt9gh -n otrident -c trident-main -- tridentctl --debug create backend --base64 eyJiYWNrZW5kTmFtZSI6Ik5BU19UcmlkZW50X05vZGUxIiwiZGF0YUxJRiI6IjEwLjIyNi4xODAuMzIiLCJtYW5hZ2VtZW50TElGIjoiMTAuMjI2LjE4MC4zMiIsInBhc3N3b3JkIjoiJHVzZXJAaW5kaWExMjMiLCJzdG9yYWdlRHJpdmVyTmFtZSI6Im9udGFwLW5hcyIsInN2bSI6IlVQSV9JU0NTSV9EQVRBIiwidXNlcm5hbWUiOiJ2c2FkbWluIiwidmVyc2lvbiI6MX0=
Operating mode = direct, Server = 127.0.0.1:8000, Autosuport server = 127.0.0.1:8003
Trident URL: http://127.0.0.1:8000/trident/v1
--------------------------------------------------------------------------------
Request Method: POST
Request URL: http://127.0.0.1:8000/trident/v1/backend
Request headers: map[Content-Type:[application/json]]
Request body: {"backendName":"Backend_name","dataLIF":"10.226.180.32","managementLIF":"10.226.180.32","password":"svm_password","storageDriverName":"ontap-nas","svm":"SVM_name","username":"vsadmin","version":1}
................................................................................
Response status: 201 Created
Response headers: map[Content-Length:[32] Content-Type:[application/json; charset=UTF-8] Date:[Thu, 19 Nov 2020 06:27:45 GMT]]

**Comment by gnarl** [comment]
This fix will be included in the Trident v21.01 release.

**Comment by gnarl** [comment]
This issue was fixed I the Trident v21.01.0 release.
