### ISSUE TITLE
Trident v20.10 supports installation between 1.14 to 1.19 not above (like 1.20)

### ISSUE THREAD

**Issue by sakaia** [NetApp/trident#494]
**Describe the solution you'd like**
The Trident 20.10 supports K8s 1.14 to 1.19 not 1.20

**Describe alternatives you've considered**
Or do not limit the K8s 1.19 

**Additional context**
I try to install K8s 1.20 and failed. I check the log and found it.

**Comment by gnarl** [comment]
Hi @sakaia,

This is expected as K8S v1.20 was not available when Trident v20.10.0 was released. Support for K8S v1.20 will be included in the next Trident release.

**Comment by sakaia** [comment]
The document writes `1.14 and above` at this moment.

https://github.com/NetApp/trident/blob/stable/v20.10/docs/kubernetes/deploying/operator-deploy.rst

**Comment by gnarl** [comment]
Hi @sakaia,

The Trident [requirements](https://netapp-trident.readthedocs.io/en/stable-v20.10/support/requirements.html) provides detailed support information. The ref link in operator-deploy.rst takes you to this document.
