### ISSUE TITLE
Question about connecting backend to ONTAP Simulator

### ISSUE THREAD

**Issue by sakaia** [NetApp/trident#495]
**Describe the solution you'd like**
I want to know the port number list to connect ONTAP Simulator,
because I am running ONTAP Simulator on VM. (VMware Player vmnet8 (NAT))

**Describe alternatives you've considered**
How to connect Trident Backend to Storage(ontap  etc)?
Or Other mode (not vmnet8) should be use? 
 (Currently K8s cluster and ONTAP Simulator is running on physically separated machine)

**Additional context**

**Comment by sakaia** [comment]
Is the port number of dataLIF and managementLIF documented?

**Comment by NA-Scott** [comment]
Connecting to the ONTAP simulator is just the same as connecting to ONTAP.  You connect to the IP address of either a cluster management LIF or a SVM management LIF over HTTPS, port 443.

**Comment by balaramesh** [comment]
@sakaia Trident communicates over HTTPS by default (443). Your ONTAP login being used in your Trident backend definition must support making ontapi calls. In your setup, you must make sure you are able to reach the managementLIF and dataLIF from your k8s cluster node.

**Comment by gnarl** [comment]
@sakaia,

Can this issue be closed?

**Comment by sakaia** [comment]
Thanks for your information it is helpful

For my case, ONTAP simulator running on other physical host.  Is there any way to connect ONTAP Simulator  from other physical host? only one https port forwarding is minimum requirement?

**Comment by sakaia** [comment]
Thanks, my primary issue is solved (I run the simulator on the same physical machine). I close this issue.
