### ISSUE TITLE
Document installation of external-snapshotter v4 or v3

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#497]
**Describe the solution you'd like**

Update [this](https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/operations/tasks/volumes/snapshots.html?highlight=external%20snapshotter#on-demand-volume-snapshots) section of the docs for external snapshotter from the existing v2.1 to v4 (or v3 first).

**Describe alternatives you've considered**

The current  links related to CRDs and other external snapshotter refer to v2, which was deprecated in v1.16.
Meanwhile, while external-snapshotter v3 is newer, there's a new requirement ([validating Webhook](https://github.com/kubernetes-csi/external-snapshotter#validating-webhook)) which v3 doesn't enforce, but version 4 does. Delays in implementing validating Webhooks doen't seem like a good idea for folks who rely on snapshots.

**Additional context**

As K8s [tightens](https://github.com/kubernetes/enhancements/tree/master/keps/sig-storage/1900-volume-snapshot-validation-webhook) volume snapshot object validation, validating Webhooks become a thing. Snapshots created based on v2 and v3 will not be restorable once people upgrade to K8s v1.20.

While that section of our documentation already indicates  that these CRDs and the rest is the responsibility of the Kubernetes orchestrator, not all include them, and validating Webhook details have CSI Provider-specific details, so having a minimally viable integration details is important.

**Comment by gnarl** [comment]
This is included in the documentation for the Trident 21.01 release with [commit 952358a](https://github.com/NetApp-openstack-dev/trident/commit/952358a5993ae167710d7d3efd6e0b6397af6cb0#diff-dc3d97351367be8d1db96072e46c0000f8b5e009de48d2fce28d85df79d878f7).

**Comment by scaleoutsean** [comment]
Thanks! Those who want to see the commit, use this  [link](https://github.com/NetApp/trident/commit/952358a5993ae167710d7d3efd6e0b6397af6cb0#diff-dc3d97351367be8d1db96072e46c0000f8b5e009de48d2fce28d85df79d878f7)
