### ISSUE TITLE
Question about nas_blog meaning.

### ISSUE THREAD

**Issue by sakaia** [NetApp/trident#498]
**Describe the solution you'd like**
I want to know the meaning of `nas_blog` in https://github.com/NetApp/trident/blob/stable/v20.10/docs/kubernetes/operations/tasks/volumes/import.rst

**Describe alternatives you've considered**

**Additional context**

**Comment by sakaia** [comment]
Please ignore my patch. It takes long time for taking CCLA.

**Comment by gnarl** [comment]
Hi @sakaia,

This was just an example where the example volume name is "nas_blog".
