### ISSUE TITLE
[Question] Topology feature does not exist in kubernetes-csi other feature

### ISSUE THREAD

**Issue by sakaia** [NetApp/trident#499]
**Describe the solution you'd like**
Topology feature does not exist in kubernetes-csi features.
https://github.com/kubernetes-csi/docs/blob/master/book/src/drivers.md

There are any reason which is not listed in?
Some other driver listed topology.

**Describe alternatives you've considered**

**Additional context**

**Comment by gnarl** [comment]
Hi @sakaia,

We have a PR up (https://github.com/kubernetes-csi/docs/pull/400) and are awaiting approval.
