### ISSUE TITLE
Where is sample-input?

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#5]
> Edit either sample-input/backend-ontap-nas.json, sample-input/backend-ontap-san.json, or sample-input/backend-solidfire.json to refer to an actual ONTAP or SolidFire deployment (use backend-ontap-nas.json to provision NFS volumes from ONTAP and backend-ontap-san.json for iSCSI volumes).

Where can we find these files? 
Tried to search with Google and Github, no luck.

**Comment by kangarlou** [comment]
You can find them under https://github.com/NetApp/trident/tree/master/trident-installer/sample-input.
Also, these files are part of the installer bundle: https://github.com/NetApp/trident/releases/download/v1.0/trident-installer-1.0.tar.gz
