### ISSUE TITLE
Issue when running with docker-compose

### ISSUE THREAD

**Issue by kkzinger** [NetApp/trident#50]
Currently I am running trident with docker and I am using `make docker_run`. 
For this to run as intended I had to change docker_compose.yaml.

The change is in the etcd container command.

`command: /usr/local/bin/etcd -name etcd1 -advertise-client-urls http://etcd:2379,http://localhost:2379 -listen-client-urls http://etcd:2379,http://localhost:2379 -data-dir /var/etcd/data  `

------------------------
System Info:

docker version: 17.06.0-ce
Kernel Version: 4.11.9-1-ARCH
Operating System: Arch Linux
OSType: linux
Architecture: x86_64

docker-compose version 1.14.0, build unknown
docker-py version: 2.4.2
CPython version: 3.6.2
OpenSSL version: OpenSSL 1.1.0f  25 May 2017

**Comment by kangarlou** [comment]
Thanks for the note! etcdv3 takes a different set of arguments than etcdv2. We have updated the [deployment definition](https://github.com/NetApp/trident/blob/master/kubernetes-yaml/trident-deployment.yaml.templ#L32:L47) to use the correct set of arguments but have forgotten to update the Docker Compose file. Just curious, are you using Trident with a non-Kubernetes deployment? Any reason you're not using the Kubernetes deployment definition?

**Comment by kkzinger** [comment]
I needed it for testing. I was configuring a Netapp Cluster for usage with Trident and tried to do an end to end test before usage in the kubernetes lab environment.
