### ISSUE TITLE
Volume shows online status when backend isn't available

### ISSUE THREAD

**Issue by vijaymailb** [NetApp/trident#500]
Volume shows online status when backend isn't available

**Describe the bug**
Client accidentally removes storage backend during maintenance activity. When we check PVC and volume status in OCP trident it shows online status.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.07
- Trident installation flags used: -d -n trident
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: 1.18
- Kubernetes orchestrator: Openshift 4.5
- Kubernetes enabled feature gates: CSI
- OS: CoreOS
- NetApp backend types: AFF
- Other:

**To Reproduce**
Steps to reproduce the behavior: NA

**Expected behavior**
volume status should have moved from online status to error/unbound or not available

**Additional context**
Logs:

[bastion@hbupiprdbjs trident-installer]$ ./tridentctl get volume -n otrident
+------------------------------------------+----------+---------------+----------+--------------------------------------+--------+---------+
|                   NAME                   |   SIZE   | STORAGE CLASS | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+------------------------------------------+----------+---------------+----------+--------------------------------------+--------+---------+
| pvc-0efac5a6-b6ae-48ef-ab4c-df1dc1b76901 | 500 GiB  | nfs-node1     | file     | bb7c91ef-951a-41b4-8781-ed898f056ce3 | online | true    |
| pvc-370ba483-7fc4-4354-8c96-0060e2cc3a16 | 5.0 GiB  | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-391d63df-5a65-478b-bd69-d8b2d0d1c539 | 1.0 GiB  | nfs-node1     | file     | bb7c91ef-951a-41b4-8781-ed898f056ce3 | online | true    |
| pvc-3ac23a15-7a4a-42e9-b9e8-abb7dbede7a9 | 1000 GiB | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-3d4cf6cf-e9ef-49c2-8d99-f1efed1f5c76 | 5.0 GiB  | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-5fe4eb6e-4902-4103-a1c3-1a8efb84a025 | 1000 GiB | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-7964f56d-5a5a-4768-93af-deb211cf88cf | 3.0 GiB  | san-node2     | block    | 96185c65-b4d8-4bf4-9b92-9dff1a28bb43 | online | true    |
| pvc-8c418eb8-604d-4ee3-901f-580629f1207b | 5.0 GiB  | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-a58ead91-99ec-47e0-9041-ac85a7de3911 | 2.9 TiB  | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-a5b9d1d8-c4b7-45bc-9cf8-17187b92b4f5 | 1.0 GiB  | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-a7f5c118-c2f7-4f5b-9ea4-6d57d63110b8 | 2.9 TiB  | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
| pvc-bbfdaa37-33ac-4ec2-a1b2-e11c93b9b5e4 | 3.0 GiB  | nfs-node2     | file     | 73947fd8-fe73-4d17-b038-bb992a65244e | online | true    |
| pvc-f767d955-4a69-4520-a843-8a248700d04f | 2.9 TiB  | san-node1     | block    | d07123ed-ca30-48a9-ace7-32cac77d09e5 | online | true    |
+------------------------------------------+----------+---------------+----------+--------------------------------------+--------+---------+
[bastion@hbupiprdbjs trident-installer]$ ./tridentctl get backend -n otrident
+-------------------+----------------+--------------------------------------+----------+---------+
|       NAME        | STORAGE DRIVER |                 UUID                 |  STATE   | VOLUMES |
+-------------------+----------------+--------------------------------------+----------+---------+
| SAN_Trident_Node1 | ontap-san      | d07123ed-ca30-48a9-ace7-32cac77d09e5 | deleting |       9 |
| NAS_Trident_Node1 | ontap-nas      | bb7c91ef-951a-41b4-8781-ed898f056ce3 | deleting |       2 |
| NAS_Trident_Node2 | ontap-nas      | 73947fd8-fe73-4d17-b038-bb992a65244e | deleting |       1 |
| SAN_Trident_Node2 | ontap-san      | 96185c65-b4d8-4bf4-9b92-9dff1a28bb43 | deleting |       1 |
+-------------------+----------------+--------------------------------------+----------+---------+
[bastion@hbupiprdbjs trident-installer]$ oc get pv
No resources found
[bastion@hbupiprdbjs trident-installer]$ oc get pvc -A
NAMESPACE           NAME                                         STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS   AGE
openshift-logging   elasticsearch-elasticsearch-cdm-sq1ukjf4-1   Pending                                      san-node1      36m
openshift-logging   elasticsearch-elasticsearch-cdm-sq1ukjf4-2   Pending                                      san-node1      35m
openshift-logging   elasticsearch-elasticsearch-cdm-sq1ukjf4-3   Pending                                      san-node1      18m

**Comment by mravi-na** [comment]
Backend is not reachable and if data paths are up and running which makes volume is available for IO. However, marking it offline for the reason of not reaching to backend gives confusing signal. And the same way, backend is reachable but data paths are down for some reason, showing it online is conflicting as data paths are down and NO i/o to volume. Hence, to mitigate the confusion, masked the display of volume state if it is online. It still shows the state if it is in `deleting`, or `missing_backend` during bootstrap, or `subordinate`. Similarly for snapshot volume, display is null if it is online, else displays other states as applicable.
The code changes are with https://github.com/NetApp/trident/commit/75dd05ca3d780f9456f339af4f1c2452b62b73a3 and included in Trident 23.07 release.
