### ISSUE TITLE
How to connect trident from ONTAP Simulator

### ISSUE THREAD

**Issue by sakaia** [NetApp/trident#501]
**Describe the bug**
At this moment, I met trouble on connecting from trident to ONTAP simulator. 

- ONTAP WebUI/System Manager seems working.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.10
- Trident installation flags used: just follows Trident Operator deployment procedure.
- Container runtime: doker ce 19.03
- Kubernetes version: 1.18.5
- Kubernetes orchestrator: None
- Kubernetes enabled feature gates: default
- OS: Ubuntu 18.04]
- NetApp backend types: ONTAP Simulator 9.7
- Other:

**To Reproduce**
Just occured on configuration procedure.

**Expected behavior**
Connection works successfully.

**Additional context**
I am trying to connect Trident to ONTAP Simulator but still have connection problem.
The `./tridentctl version -n trident` works fine.
but `./tridentctl -n create backend` failed with following message.
Any suggestions for connecting trident?

The error message is follows.

```
$ ./tridentctl -n trident create backend -f backend-ontap-nas-economy.json  -d
Operating mode = tunnel, Trident pod = trident-csi-5b5b74f78b-8rf6c, Namespace = trident, CLI = kubectl
Invoking tunneled command: kubectl exec trident-csi-5b5b74f78b-8rf6c -n trident -c trident-main -- tridentctl --debug create backend --base64 eyJkYXRhTElGIjoiIiwibWFuYWdlbWVudExJRiI6IjE3Mi4xNi4yOC4xMzEiLCJwYXNzd29yZCI6Im9udGFwc2ltMCIsInN0b3JhZ2VEcml2ZXJOYW1lIjoib250YXAtbmFzLWVjb25vbXkiLCJzdm0iOiJ0cmlkZW50X3N2bSIsInVzZXJuYW1lIjoiYWRtaW4iLCJ2ZXJzaW9uIjoxfQ==
Operating mode = direct, Server = 127.0.0.1:8000, Autosuport server = 127.0.0.1:8003
Trident URL: http://127.0.0.1:8000/trident/v1
--------------------------------------------------------------------------------
Request Method: POST
Request URL: http://127.0.0.1:8000/trident/v1/backend
Request headers: map[Content-Type:[application/json]]
Request body: {"dataLIF":"","managementLIF":"172.16.28.131","password":"ontapsim0","storageDriverName":"ontap-nas-economy","svm":"trident_svm","username":"admin","version":1}
................................................................................
Error: could not create backend: problem initializing storage driver 'ontap-nas-economy': error initializing ontap-nas-economy driver: could not create Data ONTAP API client: error reading SVM details: API status: failed, Reason: Specified vserver not found, Code: 15698 (400 Bad Request)
Response status: 400 Bad Request
Response headers: map[Content-Length:[263] Content-Type:[application/json; charset=UTF-8] Date:[Tue, 05 Jan 2021 09:10:19 GMT]]
Response body: {"backend":"","error":"problem initializing storage driver 'ontap-nas-economy': error initializing ontap-nas-economy driver: could not create Data ONTAP API client: error reading SVM details: API status: failed, Reason: Specified vserver not found, Code: 15698"}

================================================================================
command terminated with exit code 1
```

The storage IP's of the simulator is follows.

```
WebUI      172.16.28.128
Cluster IP 172.16.28.131
Node IP    172.16.28.132
```

And backend configuration file is follows.

```json
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "172.16.28.131",
    "dataLIF": "",
    "svm": "trident_svm",
    "username": "admin",
    "password": "ontapsim0"
}
```

Following command (`./tridentctl version -n trident`) works fine.

```
$ ./tridentctl -n trident version -d
Operating mode = tunnel, Trident pod = trident-csi-5b5b74f78b-8rf6c, Namespace = trident, CLI = kubectl
Invoking tunneled command: kubectl exec trident-csi-5b5b74f78b-8rf6c -n trident -c trident-main -- tridentctl version -o json
Version JSON: {
  "server": {
    "version": "20.10.0",
    "majorVersion": 20,
    "minorVersion": 10,
    "patchVersion": 0,
    "preRelease": "",
    "buildMetadata": "",
    "apiVersion": "1",
    "goVersion": "go1.14.10"
  },
  "client": {
    "version": "20.10.0",
    "majorVersion": 20,
    "minorVersion": 10,
    "patchVersion": 0,
    "preRelease": "",
    "buildMetadata": "",
    "apiVersion": "1",
    "goVersion": "go1.14.10"
  }
}

+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 20.10.0        | 20.10.0        |
+----------------+----------------+
```

**Comment by sakaia** [comment]
If my understanding correct, a following document link  should switch.

- Original Document

Following document writes `backend configuration guide` with link.

https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/deploying/operator-deploy.html#creating-a-trident-backend


- Linked Document (Current)

https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/operations/tasks/backends/ontap/ontap-san/configuration.html#backend-configuration


- Linked Document (should be linked)

https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/operations/tasks/backends/ontap/index.html

**Comment by NA-Scott** [comment]
The error seen is "Specified vserver not found".  The vserver, which is also called an SVM, that is specified in the backend is "trident_svm".  This SVM, or vserver if you prefer, needs to be created before the Trident backend can be created.  Does this SVM already exist?

**Comment by sakaia** [comment]
Thank you. Currently SVM is not exist.  I am plan to create SVM.

Creating SVM is described in  `preparing` which is under following link (which is not link directry from instruction)
https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/operations/tasks/backends/ontap/index.html

**Comment by sakaia** [comment]
I create SVM by Simulate ONTAP. Then this error is passed.

- Hopefully  document link should be changed.
    - https://github.com/NetApp/trident/issues/501#issuecomment-754527943

-  Also, the Simulate ONTAP covers adding the license key in Set up procedure
