### ISSUE TITLE
[Doc] Question about Trident requirements for aggregate

### ISSUE THREAD

**Issue by sakaia** [NetApp/trident#502]
**Describe the bug**
I am presently setting up trident backend environment. (of following page)
 https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/operations/tasks/backends/ontap/index.html

It get stacked in Sec.6. Digging into the log. it says root aggregate is not supported.

Trident requirements for aggregate is not clear. (not documented)
Is non-root aggregation  enough for Trident?

> For all ONTAP backends, Trident requires at least one aggregate assigned to the SVM.

https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/operations/tasks/backends/ontap/ontap-nas/preparing.html

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 20.10
- Trident installation flags used: default
- Container runtime: Docker 19.03
- Kubernetes version: 1.18.5
- Kubernetes orchestrator: Not used
- Kubernetes enabled feature gates: default
- OS: Ubuntu 18.04
- NetApp backend types: Simulate ONTAP 9.7
- Other:

**To Reproduce**
Follow the following page and Stopped at Section 6 (`kubectl get pods --wait`)
  https://netapp-trident.readthedocs.io/en/stable-v20.10/kubernetes/deploying/operator-deploy.html#provision-your-first-volume

**Expected behavior**
Persistent Volume Created successfully.

**Additional context**
Looking into the event, it says 

```
  Type    Reason                Age                     From                                                                                     Message
  ----    ------                ----                    ----                                                                                     -------
  Normal  Provisioning          3m47s (x39 over 157m)   csi.trident.netapp.io_trident-csi-5b5b74f78b-8rf6c_2d964978-5bb7-465a-b77d-cd0f2c0172fb  External provisioner is provisioning volume for claim "default/basic"
  Normal  ProvisioningFailed    3m47s (x30 over 148m)   csi.trident.netapp.io                                                                    (combined from similar events): encountered error(s) in creating the volume: [Failed to create volume pvc-bdd1507b-ec11-46a9-bc8b-252a0bc06210 on storage pool aggr0_ontapsim_01 from backend ontapnaseco_172.16.28.134: backend cannot satisfy create request for volume trident_pvc_bdd1507b_ec11_46a9_bc8b_252a0bc06210: (ONTAP-NAS-QTREE pool aggr0_ontapsim_01/aggr0_ontapsim_01; Flexvol location/creation failed trident_pvc_bdd1507b_ec11_46a9_bc8b_252a0bc06210: error creating Flexvol for qtree: error creating Flexvol: API status: failed, Reason: Cannot provision volume "trident_qtree_pool_trident_PQMDUXOECR" on root aggregate "aggr0_ontapsim_01". Provisioning a volume on a root aggregate is not supported., Code: 15675)]
  Normal  ExternalProvisioning  2m10s (x622 over 157m)  persistentvolume-controller                                                              waiting for a volume to be created, either by external provisioner "csi.trident.netapp.io" or manually created by system administrator
```

**Comment by wonderland** [comment]
The root aggregate is really only for system-internal use. You'd need at least one data aggregate and assign that to the SVM you intend to use.

Noticed that you run the simulator. You might want to look into Ontap Select as an alternative. Less limitations than the simulator (capacity etc.), easier to deploy if you have access to a VMware environment and has an evaluation mode built in.
