### ISSUE TITLE
DOC Issue: ONTAP and SolidFire user minimum permissions requirements

### ISSUE THREAD

**Issue by kaparora** [NetApp/trident#51]
Document instructions to create a user for ONTAP and SolidFire with minimum rights /permissions.
(Probably also E-Series, I guess)

I see this is documented for ONTAP in nDVP documentation. Probably we can just point to it?!
For SolidFire we don't have any such documentation available.

A SolidFire user must have "Volume" and "Cluster Admin" permissions and also "Account" permission  if we would like Trident to setup new accounts.

**Comment by gnarl** [comment]
We currently recommend using vsadmin for ONTAP as a user with a level of minimum permissions. Minimum permission support can break with ONTAP upgrades when using an SVM user with custom roles and permissions.
