### ISSUE TITLE
"Backend is not Online or Deleting" on K8S rolling restart

### ISSUE THREAD

**Issue by lce-financal-com** [NetApp/trident#512]
**Describe the bug**
When performing rolling restarts of the K8S cluster (e.g. for a Kubernetes update), Trident often fails to recover, keeping pods that need persistant storage attached down:
```
Normal   Scheduled               99s                default-scheduler        Successfully assigned default/nextcloud-production-58c58d5bf7-2txns to k8s-worker-2

Warning  FailedAttachVolume      67s (x7 over 99s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-6bea9728-3ee8-4751-b95c-b1796be895af" : rpc error: code = Internal desc = backend k8s-filer-nfs is not Online or Deleting
```
To recover from this situation, all deployments and daemonsets in the trident namespace have to be restarted, followed by the actual production workloads.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 19.10.0
- Trident installation flags used: -n trident
- Container runtime: Docker 19.03.12
- Kubernetes version: 1.19.6
- Kubernetes orchestrator: Rancher v2.5.5
- OS: CentOS Linux release 7.8
- NetApp backend types: ONTAP

**To Reproduce**
- Have a cluster with some generic pod, trident installed and the generic pod using a pvc from trident.
- Perform a rolling restart on the cluster
- When the new pod is created, observe the error 

**Expected behavior**
All the pods should be running after the rolling restart is complete.

**Comment by gnarl** [comment]
Hi @lce-financal-com,

We have a number of customers that are able to successfully upgrade Kubernetes without running into this issue. According to your original post the installed Trident version is 19.10.0 which is in [limited support](https://mysupport.netapp.com/site/info/trident-support). It is recommended that you upgrade to a newer version of Trident.

**Comment by lce-financal-com** [comment]
Hi @gnarl,

Thanks for the feedback and I guessed it is probably caused by something else as I could not find any similar report about this throughout. We upgraded Trident to v20.10.1 at the moment and there will be an upgrade of K8S in the next days. I will check how it behaves and report back and close this in case the problem is not observed anymore. Otherwise, I will try to add more information/logs to help us.

Thanks a lot once again!

**Comment by gnarl** [comment]
@Ice-financal-com,

Thanks for updating this issue with your plan. Looking forward to hearing about the results of the upgrade.

**Comment by lce-financal-com** [comment]
Hi @gnarl,

We update to the latest stable version of Trident and could not reproduce the issue anymore. I guess it was either something that was fixed or provenient from another source in K8S.

I am closing this for now and thanks for the short support! :)
