### ISSUE TITLE
iSCSI-PVC snaphots share the same filesystem uuid and therefore cannot be mounted on the same pod or node

### ISSUE THREAD

**Issue by megabreit** [NetApp/trident#514]
**Describe the solution you'd like**
Snapshots created from iSCSI-PVCs cannot be mounted on the same pod or node because of a duplicate filesystem uuid.
This behaviour has been seen with Openshift 4.6 and Kubernetes 1.18 with ontap-nas-economy (20.07.1 and 20.10.1) drivers. Probably other iSCSI backends show the same behaviour. All filesystems are affected, but only XFS filesystems produce an error because Linux prevents XFS filesystems with duplicate fs uuids to be mounted simultaneously by default.
The error message inside Kubernetes is ambigous: `"unable to mount device; exit status 32"`.
The kernel messages show errors like:
`[104402.666841] XFS (dm-1): Filesystem has duplicate UUID 37ac2c5d-1671-43e8-8eee-59a123797324 - can't mount`

Trident should have an option or a way to change the filesystem uuid after a PVC clone was created... by default or on demand.

If it is not considered to create such functionality, this behaviour should be documented including ways to work around the issue.

**Describe alternatives you've considered**
A workaround for XFS filesystems is to add the "nouuid" option to mountOptions. There might be side effects which have not been deeply investigated.

**Comment by gnarl** [comment]
This issue is fixed with [commit 4fc00be](https://github.com/NetApp/trident/commit/4fc00be728af13653dfb9fa4d915589e19a9f5e5) and will be included in the Trident v21.10 release.
