### ISSUE TITLE
Privileged Trident Pod (Pod Security Policy)

### ISSUE THREAD

**Issue by kesso1** [NetApp/trident#516]
I was wondering why trident pod needs a pod security policy with privileged permissions? Could the persistent volumes mounted with NFS without these privileged permissions for the trident pod? Is trident explicit attaching a volume to the the Worker VM?

**Comment by clintonk** [comment]
@kesso1  As a CSI-compliant storage provisioner, Trident is responsible for mounting NFS volumes on the nodes where they are attached to containers.  Similarly, for iSCSI volumes, Trident must rescan for new iSCSI devices and format & mount them.  All of those operations require elevated privileges.  Please note that CSI Trident consists of two servers, controller and node.  The controller server is a non-privileged single-replica Deployment; that is the component that interacts with storage system APIs and the Kubernetes API server.  The node server is a privileged Daemonset, so it runs on each node and is only tasked with node-local operations while attaching/detaching volumes to containers.

**Comment by kesso1** [comment]
Thanks for the quick response.
