### ISSUE TITLE
no backend pools support the requisite protocol

### ISSUE THREAD

**Issue by megabreit** [NetApp/trident#518]
**Describe the bug**
In the trident log this message is seen when a volume is provisioned:
`time="2021-01-26T15:13:01Z" level=info msg="*no backend pools support the requisite protocol*" requestID=513fc178-a56b-49b3-9df9-51aa9a169c16 requestSource=CSI`
The volume is provisioned, the pvc is usable. The cause and meaning of the message is unclear.

**Environment**
- Trident version: 20.10.0
- Trident installation flags used: operator, callhome disabled
- Container runtime: CRI-O 1.19
- Kubernetes version: 1.19
- Kubernetes orchestrator: OpenShift v4.6
- Kubernetes enabled feature gates: 
- OS: RHCOS
- NetApp backend types: Ontap-nas-economy

**To Reproduce**
Simply provision a pvc

**Expected behavior**
The content of the message is unclear. I was told in the Netapp Slack that it's harmless, so more context should be added or the message removed completely.

**Comment by gnarl** [comment]
This was fixed with commit [1c59c80](https://github.com/NetApp/trident/commit/1c59c80cc948e48e55f6f374005bda46d905701b) and is included in the Trident 21.04 release.
