### ISSUE TITLE
Updating from 20.10.1 to 21.01.0 fails if there is no aesKey included in the certificates secret

### ISSUE THREAD

**Issue by ffilippopoulos** [NetApp/trident#519]
**Describe the bug**
Upgrading trident from 20.10.1 to 21.01.0 failed due to: 
`level=fatal msg="Unable to start the CSI frontend. open /certs/aesKey: no such file or directory"` 

I believe this is due to commit: https://github.com/NetApp/trident/commit/821d26b9f02e260d82acd215e2e45e9fb2193d59#diff-cda973fdf597337abb85b685dc654207c1c95b6b322f6cabded2f2a5555701dbR151 because of the default `/certs/aesKey` location that is not present for me as my secret doesn't contain an aes key.

I also tried setting 
`--aes_key=""` but was unsuccessful:
```
time="2021-02-01T14:18:40Z" level=fatal msg="Unable to start the CSI frontend. open \"\": no such file or directory"
```

The only workaround that did the trick was to add an empty `aesKey: ""` data field on my secret, and with that I was able to successfully deploy the new version.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 21.01.0
- Trident installation flags used: tridentctl install -n sys-trident --generate-custom-yaml
- Container runtime: containerd://1.4.3
- Kubernetes version: v1.19.2
- Kubernetes orchestrator: self managed cluster on-prem
- Kubernetes enabled feature gates: defaults
- OS: Flatcar Container Linux by Kinvolk 2605.11.0
- NetApp backend types: ONTAP SAN 9.7

**To Reproduce**
Update from a 20.10.1 deployment that does not already contain an aesKey

**Expected behavior**
I believe that since chap is not enabled by default nor the aesKey should be required in the secret. I appreciate that for people using tridentctl install to deploy trident the key would be generated, but the code could handle the missing aek key path in cases that this is not actually used anywhere.

**Comment by adkerr** [comment]
How are you installing? Tridentctl installs and operator installs should both be generating the key.

**Comment by ffilippopoulos** [comment]
I am using `tridentctl install -n sys-trident --generate-custom-yaml` to get the latest manifests and update, since none of those 2 ways fit our ci nicely. Also, as far as I understand, I do not need that key in my manifests/kube resources, so why have it in the first place (even if I use a way that would generate it for me)?

**Comment by adkerr** [comment]
Trident has no way to know if you'll need it or not as backends are added dynamically. Therefore it is required.

**Comment by torirevilla** [comment]
The error was reproduced with the following steps:
Install 20.10.01:
1. tridentctl -n trident install -d --generate-custom-yaml
2. tridentctl -n trident install -d --use-custom-yaml
Upgrade to 21.01.0:
3. tridentctl -n trident install -d --generate-custom-yaml
4. Change trident-daemonset.yaml and trident-deployment.yaml to use image: NetApp/trident:21.01.0
5. Kubectl -n trident apply -f trident-daemonset.yaml
6. Kubectl -n trident apply -f trident-deployment.yaml
The controller and node pods never come up and the logs produce the error above: 
`level=fatal msg="Unable to start the CSI frontend. open /certs/aesKey: no such file or directory"`

Trident encourages users to follow the [upgrade documentation](https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/upgrades/tridentctl-upgrade.html) and use the `tridentctl install --use-custom-yaml` command when installing with a custom yaml.

**Comment by gnarl** [comment]
Closing this issue as the Trident documentation should be followed when upgrading Trident.
