### ISSUE TITLE
Feature request: Allow Backend Config Json injectable via k8s configMaps

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#52]
Explore the possibilities to allow use of K8S ConfigMap instead of Backend Json file to provide Backend Configrations for Trident.

**Comment by mickeysh** [comment]
I second that plus using secrets for the username and password

**Comment by kangarlou** [comment]
ConfigMaps and Secrets work just like volumes. For them to be consumed by the Trident pod, they should exist before the creation of the pod. As you see, this is not very useful when storage backends are dynamically added, removed, and updated. Exploring the use of [Custom Resource Definitions](https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/) is on our roadmap.
