### ISSUE TITLE
Fix "latest" pointer in Trident docs

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#520]
**Describe the solution you'd like**

Searching `latest` docs for `helm` gives 0 results.

![image](https://user-images.githubusercontent.com/16622642/106490120-73a42d00-64f0-11eb-873f-b2ae108a8497.png)

**Describe alternatives you've considered**

Search stable-v21.01.01 version (works fine)

**Comment by adkerr** [comment]
The "latest" tag has already been updated. Could this be a browser cache issue?

![image](https://user-images.githubusercontent.com/6106766/106494476-7834fb00-6488-11eb-8e96-99030f016a3e.png)

**Comment by adkerr** [comment]
Nevermind, seems to have been a RTD issue. I forced a rebuild of the latest tag and it's working now.
