### ISSUE TITLE
RHEL OpenShift ACM

### ISSUE THREAD

**Issue by valt-boop** [NetApp/trident#525]
Hi, 

Does Trident require special support for " Red Hat Advanced Cluster Management for Kubernetes"

**Comment by balaramesh** [comment]
@valt-boop Trident's scope is that of a single k8s/OpenShift cluster. Trident is installed and managed at a per-Kubernetes cluster level. Red Hat Advanced Cluster Management is an encompassing service that looks like it allows you to manage multiple k8s environments and workloads. Are you looking for Trident support with "Red Hat Advanced Cluster Management?" As mentioned above, Trident is meant to be run per-cluster

**Comment by gnarl** [comment]
Closing this issue as @valt-boop hasn't responded. Please take a look at [Astra](https://cloud.netapp.com/astra) as a possible NetApp provided solution.
