### ISSUE TITLE
Trident 20.07.1 doesn't clean out tracking json files when cleaning up PVs for Solidfire

### ISSUE THREAD

**Issue by oleimann** [NetApp/trident#526]
**Describe the bug**
Trident 20.07.1 as well as 20.10.0 (likely up to current version 21.01 - not tested by customer) 
doesn't clean out tracking json files when cleaning up PVs for Solidfire.

Note that with 20.07.0 base, it was also unable to unmount the PVs, but that got fixed in 20.07.1

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [20.07.1, 20.10.0]
- Trident installation flags used: [-d -n trident]
- Container runtime: [Docker - independent of issue]
- Kubernetes version: [1.18.9]
- Kubernetes orchestrator: [Kubernetes]
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: [presumably independent of issue]
- NetApp backend types: [Solidfire, Element OS 11.7.0.76]
- Other: NetApp Case #2008618514, Jira Ticket CDS-2261

**To Reproduce**
Created Solidfire backend PV's of type Delete instead of Retain,  creating and destroying pods with these regularly.

**Expected behavior**
Only deployed PV's should have json tracking files on the node in question (under /var/lib/trident/tracking )
These files are not in the way, but they "multiply" over time.

Note that the finalizer is not a trident reference (like with ONTAP) - could be normal...

**Additional context**
Example PVC before removal:
[root@ansible02c ~]# kubectl get pvc -n storage-verification stateful-storage-stateful-storage-2 -o yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  creationTimestamp: "2020-08-27T08:46:31Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: stateful-storage
  name: stateful-storage-stateful-storage-2
  namespace: storage-verification
  resourceVersion: "36192262"
  selfLink: /api/v1/namespaces/storage-verification/persistentvolumeclaims/stateful-storage-stateful-storage-2
  uid: cb986e5b-fe35-47db-8893-f38aafb5e3c3
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: bronze
  volumeMode: Filesystem
  volumeName: pvc-cb986e5b-fe35-47db-8893-f38aafb5e3c3
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound

[root@ansible02c ~]# kubectl get pvc -n hzc-swissid-epd-release-epd-04-00 hzc-swissid-epd-release-epd-04-00-mancenter -o yaml 
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  creationTimestamp: "2020-07-09T15:17:24Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/instance: hzc-swissid-epd-release-epd-04-00
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: hazelcast
    helm.sh/chart: hazelcast-3.0.5
    io.cattle.field/appId: hzc-swissid-epd-release-epd-04-00
  name: hzc-swissid-epd-release-epd-04-00-mancenter
  namespace: hzc-swissid-epd-release-epd-04-00
  resourceVersion: "17062450"
  selfLink: /api/v1/namespaces/hzc-swissid-epd-release-epd-04-00/persistentvolumeclaims/hzc-swissid-epd-release-epd-04-00-mancenter
  uid: 4490fa65-3b9d-411e-9d0f-3cb027782911
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: bronze
  volumeMode: Filesystem
  volumeName: pvc-4490fa65-3b9d-411e-9d0f-3cb027782911
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 2Gi
  phase: Bound

**Comment by balaramesh** [comment]
@oleimann can you add some additional details? What do you mean by "they multiply over time"? The json files are only present if the PVC exists, and on the node the PVC is being used in. If the PVC is no longer in use by an app pod, the json is removed from the host

**Comment by oleimann** [comment]
It dosn't happen under normal conditions. 
In retrospect it appears that the Trident database was deleted for a fresh reinstall, causing these to remain behind.
I believe that the obliviate CRD option does not clean up the json files on the nodes as well.

**Comment by gnarl** [comment]
@oleimann, I'm going to close this as Trident is working as expected. Trident needs to be running in order to comply with the [CSI specification](https://github.com/container-storage-interface/spec/blob/master/spec.md) when a volume is unpublished.
