### ISSUE TITLE
DOC: tridentctl and namespace name in Quick start guide

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#53]
As per the quick start  documentation
I install trident with 

>./install_trident.sh -n trident
and then add backend  with 
>tridentctl create backend -f setup/backend.json 
and get error

Error: could not find a Trident pod.

It works if I use -n trident

tridentctl create backend -f setup/backend.json -n trident

1) Update command to have -n trident option

2) When tridentctl cannot find trident pod..it should say in which namespace/project..and ask the user to verify their namespace/project

**Comment by korenaren** [comment]
Tracked internally as DE400
