### ISSUE TITLE
Control Snapshots from K8s/Openshift

### ISSUE THREAD

**Issue by suhasagasthya** [NetApp/trident#536]
With OKD4.6+ and K8s 1.19 onwards, we are able to manage and control snapshots and view snapshot classes, PV clones taken from OKD or K8s. 
The problem is not able to view the existing vol snapshots configured via the snapshot policy set on trident or via the snapshots taken from with ontap on the OKD/K8s console or commands. 
If we were to view or manage the Vol snapshots taken from the ontapp via the K8s will provide more control and easier to manage day2 operations such as restore in case of failure.

**Comment by YvosOnTheHub** [comment]
are PVC mounted with NFSv3 or NFSv4?
I think that with NFSv3, the .snapshot directory can be made visible (option snapshotDir=True in Trident backend).
However, with NFSv4, the .snapshot directory exists, but you need to explicitly enter it to see its content. It will not appear in the PVC with "ls -la"

**Comment by scaleoutsean** [comment]
@YvosOnTheHub - yes, as documented in the FAQs [here](https://netapp-trident.readthedocs.io/en/stable-v21.01/frequently_asked_questions.html#can-we-directly-access-the-volume-snapshot-directory-and-copy-files).

Snapshot management is available (`kubectl ... volumesnapshots`). As far as I know CSI doesn't offer a method to directly restore snapshots over existing or other volumes. Certain [apps](https://cloud.netapp.com/astra) have workflows that connect manual steps into a restore feature.

**Comment by YvosOnTheHub** [comment]
@scaleoutsean , I think documentation should be updated as not seeing the .snapshot directory (NFSv4 use case) can be puzzling for some, especially those who used to mount with NFSv3.

if the following parameters are set in the Trident backend, the .snapshot directory will be visible

- "nfsMountOptions": "nfsvers=3"
- "snapshotDir": "true"

```
# kubectl exec pod-7f858f897d-kk6bp -- mount | grep /data
192.168.0.135:/snap_pvc_be7e024e_b50c_4721_bd61_86d682b3d19d on /data type nfs (rw,relatime,vers=3,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,mountaddr=192.168.0.135,mountvers=3,mountport=635,mountproto=udp,local_lock=none,addr=192.168.0.135)

# kubectl exec pod-7f858f897d-kk6bp -- ls -la /data
total 8
drwxrwxrwx    2 root     root          4096 Feb 23 17:49 .
drwxr-xr-x    1 root     root            29 Feb 23 17:49 ..
drwxrwxrwx    3 root     root          4096 Feb 23 17:50 .snapshot

# kubectl exec  pod-7f858f897d-kk6bp -- ls -la /data/.snapshot
total 16
drwxrwxrwx    4 root     root          4096 Feb 23 17:55 .
drwxrwxrwx    2 root     root          4096 Feb 23 17:49 ..
drwxrwxrwx    2 root     root          4096 Feb 23 17:49 5min.2021-02-23_1750
drwxrwxrwx    2 root     root          4096 Feb 23 17:49 5min.2021-02-23_1755
```

However, if the mount defaults to NFSv4, you wont see it, even though it is accessible
```
#kubectl exec -pod-5bf868f4dd-xdhx4 -- mount | grep /data
192.168.0.135:/snap_pvc_e7449455_2825_46bd_8a58_1e2986ac2812 on /data type nfs4 (rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,port=0,timeo=600,retrans=2,sec=sys,clientaddr=192.168.0.61,local_lock=none,addr=192.168.0.135)

# kubectl exec pod-7f858f897d-vxklq -- ls -la /data
total 4
drwxrwxrwx    2 99       99            4096 Feb 23 16:46 .
drwxr-xr-x    1 root     root            41 Feb 23 16:45 ..
-rw-r--r--    1 99       99               0 Feb 23 16:46 test.txt

# kubectll exec pod-7f858f897d-vxklq -- ls -la /data/.snapshot
total 32
drwxrwxrwx    8 99       99            4096 Feb 23 17:05 .
drwxrwxrwx    2 99       99            4096 Feb 23 16:46 ..
drwxrwxrwx    2 99       99            4096 Feb 23 16:46 5min.2021-02-23_1700
drwxrwxrwx    2 99       99            4096 Feb 23 16:46 5min.2021-02-23_1705
drwxrwxrwx    2 99       99            4096 Feb 23 16:46 snapshot-d1df9918-ff66-49d6-b894-4721bf4a230b
```

more details can be found here:
https://kb.netapp.com/Advice_and_Troubleshooting/Data_Storage_Software/ONTAP_OS/Why_isn%27t_the_.snapshot_directory_visible_in_an_%27ls_-al%27_output_on_an_NFS_client%3F

**Comment by balaramesh** [comment]
@suhasagasthya there are now two ways to create and manage snapshots:

1. Through the Kubernetes interface, using VolumeSnapshots. Trident supports this from the 19.10 release
2. Through ONTAP snapshot policies. Trident has been supporting this for a long time, since 18.07 IIRC

Both are distinct ways of handling snapshots. Option (1) is controlled through the Kubernetes plane and is orchestrated by a K8s user. (2) is handled at the infrastructure layer and handled directly by the storage admin with a pre-configured snapshot policy, or triggered snapshots. A consequence of this -> the snapshots are taken through ONTAP and are visible at the ONTAP layer alone.

As @YvosOnTheHub suggested, you can view pre-existing ONTAP snapshots if the `.snapshot` dir is visible.

**Comment by gnarl** [comment]
Closing this issue based on the information provided by @balaramesh.
