### ISSUE TITLE
Possibility to create a backend with a custom resource instead tridentctl.

### ISSUE THREAD

**Issue by ykoer** [NetApp/trident#538]
We are managing our Kubernetes clusters with ArgoCD. It is currently installing the Trident Operator, but backends can be managed only with tridentctl. I would like to have the possibility to create backends with a custom resource. 
Is that feature already on your radar?

Thanks
Yusuf

**Comment by clintonk** [comment]
@ykoer Yes.  @gnarl may be able to provide more insight on when you might see that.

**Comment by gnarl** [comment]
Hi @ykoer,

Closing this issue as a duplicate of GitHub Issue #358. We are working on providing this support in a future Trident release.

**Comment by c4m4** [comment]
This is an example about how to create the backend, using the crd:

apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-btc-solidfire
  namespace: trident
type: Opaque
spec:
  version: 1
  storageDriverName: solidfire-san
  credentials:
    name: backend-btc-solidfire
  SVIP: x.x.x.x:3260
  TenantName: K8S-LAB
  Types:
    - Type: btc
      Qos:
        minIOPS: 1000
        maxIOPS: 2000
        burstIOPS: 4000
    - Type: ada
      Qos:
        minIOPS: 1000
        maxIOPS: 3000
        burstIOPS: 5000
  storage:
  storage:
    - labels:
        performance: btc
      type: btc
    - labels:
        performance: ada
      type: ada
