### ISSUE TITLE
Apply #523 to Trident v20.10.2

### ISSUE THREAD

**Issue by ysakashita** [NetApp/trident#539]
Could you apply #523 to v20.10?
We would like to release v20.10.2 ASAP.

Because, NetApp/Trident v21.01 change to Trident orchestrator.
So our customer can't use NetApp/Trident v21.01.1 yet.
Also it's related #508. 
When upgrade NetApp/Trident, our customer doesn't operate kubectl command.
It's like GitOps (#358 ）
I know the NetApp/Trident don't support #358 and #508 yet. 
Therefore, it's difficult that we can't update NetApp/Trident v21.01 or later yet.

**Comment by gnarl** [comment]
Issues #358 and #508 were addressed in the Trident 21.04 release. This issue can be reopened if it is not fully resolved.
