### ISSUE TITLE
Volume mount not visible when creating multiple volumes

### ISSUE THREAD

**Issue by carlcantprogram** [NetApp/trident#54]
Data ontapp version: 9.1P2

Description: When creating multiple PVCs at the same time, the first volume mounts ok on the NAS. Subsequent volumes are create and mounted on the NAS, but the volume is not able to be accessed at it's mount point.

Steps to recreate: 
1. Make an openshift template with multiple PVCs (at least three) all using the same storage class. 
2. Add a pod to the template that mounts the PVCs into a container.
3. Run the template from command line (oc process -f )
 PVCs PVs and NAS volumes will be created
4. Check pod status from openshift console. Should see an error "Exit status 32"
5. Do "ls -l /net/vserver/trident_vol" or similar and confirm volume is not accessable

Workaround:
1. Log into the vserver and re-run "mount trident_vol  /trident_vol"
2. Do "ls -l /net/vserver/trident_vol" or similar and confirm volume is now available

**Comment by dutchiechris** [comment]
Volumes are mounted by the corresponding k8s volume plugin (NFS in your case?) but it could still be related to Trident.  

Are you using load-sharing mirrors on the SVM root volume?  If yes, it might be that the read replicas are not updated prior to your mount; see https://github.com/NetApp/trident/issues/44.  To test this theory unconfigure any LSM and see if the problem persists.

**Comment by adkerr** [comment]
@dutchiechris It sounds from his description that it's ONTAP that isn't exposing a mount; which really odd as I think that's all automatic on a NFS enabled vserver.  We will need to investigate and attempt to reproduce

**Comment by kangarlou** [comment]
@carlcantprogram We pushed a fix for Issue #44. Please check if [v17.10.0-beta.0](https://github.com/NetApp/trident/releases/tag/v17.10.0-beta.0) addresses the problem you were experiencing.

As @dutchiechris said, Trident delegates mounting/unmounting volumes to Kubernetes/OpenShift. In your case, it seems Trident has correctly provisioned the volume.
