### ISSUE TITLE
Trident backends remain "online" even when not available

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#543]
**Describe the bug**
When a SVM is not available, I would expect backend status in trident not to be _online_, but rather _offline_ or _non available_.
However, statues do not change (even after 8hours ... so not a timeout issue)

**Environment**
LoD Kubernetes v4 with the following upgrades
- ONTAP 9.8P1
- Trident 21.01.1

**To Reproduce**
- Modify all LIF of a SVM to status_admin = down
- Create a PVC against this SVM (will fail) or run a tridentctl update backend (will also fail)
- Check the status of the backend with tridentctl get backend: still _online_

**Expected behavior**
Backend status to reflect the correct status

**Additional context**
Some customers rely on Trident metrics to monitor backend statuses.
if Trident always report "online", they will not know that something happened on the backend

**Comment by mravi-na** [comment]
The issue is fixed with https://github.com/NetApp/trident/commit/458db05e6475ab095351848a849d4a5a8de3f937 and is included in Trident 23.07 release.
