### ISSUE TITLE
Provide consistent instructions for nfsMountOptions

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#544]
Cloud-based ONTAP back-ends:

`"nfsMountOptions": "vers=3"`

Example: [here](https://netapp-trident.readthedocs.io/en/stable-v21.01/docker/install/ndvp_cvs_gcp_config.html?highlight=vers%3D3#cloud-volumes-service-cvs-on-gcp-configuration)

On-prem ONTAP back-ends:

`"nfsMountOptions": "nfsvers=3"`

Example: [here](https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/operations/tasks/backends/ontap/ontap-nas/examples.html?highlight=nfsvers%3D3#ontap-nas-driver-with-auto-export-policy)

If both work, can the docs be standarized to use one of them?

**Describe alternatives you've considered**

I don't have access to cloud based ONTAP back-ends so I don't know if nfsvers can or cannot work. I'd like to have one way of doing things documented and used throughout, but if they must be two, then I'd like that noted to lessen the confusion.

**Comment by wonderland** [comment]
Both are identical, but I agree that it would be nice to have the Trident docs standardized on one of them.

`nfsvers=n
The NFS protocol version number used to contact the server's NFS service. If the server does not support the requested version, the mount request fails. If this option is not specified, the client negotiates a suitable version with the server, trying version 4 first, version 3 second, and version 2 last.

vers=n

This option is an alternative to the nfsvers option. It is included for compatibility with other operating systems.` 

(From: https://linux.die.net/man/5/nfs)

**Comment by balaramesh** [comment]
@wonderland @scaleoutsean I was able to confirm both work fine for CVS and ONTAP. The docs shall be updated to use one format

**Comment by gnarl** [comment]
This was fixed with [commit 7b15247](https://github.com/NetApp/trident/commit/7b15247327ee75f136dfc9bd2b22c9547efb63d7).
