### ISSUE TITLE
[Doc][Helm Chart]Question about Trident Operator Deployment documentation status?

### ISSUE THREAD

**Issue by sakaia** [NetApp/trident#545]
**Describe the solution you'd like**
Helm Chart Deployment operation seems not equivalent to manually deployment.
The current document state of helm and manuall is different?

**Describe alternatives you've considered**
I want to install trident by helm chart. But it seems not equivalent to manually deployment.

**Additional context**
Deploying with the Trident Operator
- [Deploying with the Trident Operator](https://netapp-trident.readthedocs.io/en/latest/kubernetes/deploying/operator-deploy.html)
   - [Deploy Trident Operator by using Helm](https://netapp-trident.readthedocs.io/en/latest/kubernetes/deploying/operator-deploy.html#deploy-trident-operator-by-using-helm)
   - [Deploy Trident Operator manually](https://netapp-trident.readthedocs.io/en/latest/kubernetes/deploying/operator-deploy.html#deploy-trident-operator-manually)

**Comment by scaleoutsean** [comment]
You've linked to `latest`,  not `v21.0.1`, so the content can be different.

> But it seems not equivalent to manually deployment.

Which part is not the same?

**Comment by gnarl** [comment]
Hi @sakaia,

Is this a request to update the documentation? There are certain operations in tridentctl that can not be implemented in Helm. If you can provide more information that would help determine what you are requesting.

**Comment by sakaia** [comment]
@gnarl Thank you for your suggestion. I want to install via helm chart. but it seems beta (?) release. I want to know the helm chart status and its pros and cons compared to manual installation.

**Comment by balaramesh** [comment]
Hello @sakaia the Helm Chart is a fully supported, GA solution to install Trident with. The Helm chart uses the Trident operator underneath.

To understand the option that is best for you, please read the breakdown provided here: https://netapp-trident.readthedocs.io/en/latest/kubernetes/deploying/deploying.html#choosing-the-right-option

**Comment by balaramesh** [comment]
@sakaia circling back. Did this answer your question? Please reach out!
