### ISSUE TITLE
Move SVM to new cluster

### ISSUE THREAD

**Issue by roycec** [NetApp/trident#549]
Hello,

we are about to move our data to a new Netapp cluster. For Kubernetes/Trident we have set up dedicated SVMs.  So I have some questions regarding this migration

- Do we have to "prepare" Trident in advance?
- Will the IO be interrupted during the move?
- What happens to the NFS mounts when we move the SVM? Do we have to unmount/remount the volumes?

Kind regards
Roycec

**Comment by balaramesh** [comment]
Hello @roycec 

Are you planning to move your data to a new NetApp cluster and then serve the data from the new cluster? Scrap the old one?

For all volumes that have been created by Trident on the old storage cluster (let's call this cluster A):
1. They are identified by the SVM credentials (dataLIF, managementLIF, username, password) and associated to a Trident backend (which would have been created for cluster A).

If you are going to use both cluster A and the new cluster (let's call this cluster B) side by side, then all you will need to do is:
1. Create another backend for cluster B. The data present on cluster A will be accessible as always. Storage Classes may be defined to map to cluster A/cluster B/both. Volumes will be accordingly provisioned.

If you would like to move all data from A to B and have future volumes provisioned on B:
1. Copy the data from A to B (SnapMirror or vol move, depending on the desired granularity). At the end of this step the data is available on B, but Trident still sees the volumes being served from A.
2. Import each volume (that was originally created on A) to be served from B. This will be done using `tridentctl import`. See [here](https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/operations/tasks/volumes/import.html)
3. Use volumes from step 2 in respective application deployments.

In addition, I would recommend going through the disaster and recovery guide in the Trident [documentation](https://netapp-trident.readthedocs.io/en/stable-v21.01/dag/kubernetes/backup_disaster_recovery.html#data-replication-using-ontap)

**Comment by wonderland** [comment]
No chance to add the new nodes to the existing Ontap cluster? In that case your SVM would stay in place (regular tech refresh). 

If moving to a new cluster, it would be best if you manage to move the IP addresses for the SVM as well. In that case it would be mostly transparent to Trident. You could use SVM-DR for that (and just update the Trident backend once switched over to the new cluster to reflect the new SVM name). There would still be an I/O interruption but it can be short.

If IP addresses change then this will be a lot more disruptive and you need to follow the volume import steps outlined above by Bala.

**Comment by roycec** [comment]
Thanks for the answers, but to my understanding moving the SVM to new hardware is like live-migrating a virtual machine to another hypervisor in the cluster - or in a separate cluster. So there's only an interruption when the SVM needs to be reconfigured on the new hardware?

**Comment by wonderland** [comment]
It all depends on what you plan to do. You can add new hardware to the existing Ontap cluster non-disruptively and without any impact and move data over to the new hardware transparent to Trident & your apps. 

You can also create an entirely new Ontap cluster (different data center, ...). At that point you can still move the data over to the new cluster, but there will be some disruption. In that case one of the key questions is if you can move IP addresses of the SVM over to the new cluster.

**Comment by roycec** [comment]
@wonderland We will go for the second option and will reusing the existing IP addresses for the SVM on the new cluster. So it is obvious, that there will be a short interruption. But my initial question was, if there are other caveats which we didn't think off before.

**Comment by wonderland** [comment]
In that case the SVM-DR feature on the Ontap side is probably your best option. It will not only replicate the data (volumes) but also all configuration of the SVM. You can pre-copy the data and then only have a brie final sync and failover. 

The only caveat is that the SVM name changes. you either revert that one you failover over to the new cluster (as this is migration, not a DR use case) or you need to update the Trident backend config. This is described in more detail here: https://netapp.io/2019/10/21/trident-and-disaster-recovery-part-3/

As always, test and validate in your environment before doing this on your production instance. You can just set up a test SVM and add that as an additional Trident backend (+ storage class in k8s).

**Comment by wonderland** [comment]
NFS will never timeout, so from that perspective things would just continue to work once everything becomes available again on the new cluster. However, your apps might not exactly like that and have timeouts of their own if the data access hangs for a longer period of time. That is really app specific, so I cannot comment on that. 

The safe way to do it is shutting down the apps. In reality, not doing it will likely just work for the majority of your apps. 

All operations within the storage cluster are non-disruptive, including full tech refresh of hardware and other maintenance activities. So unless you physically move your data center across longer distances there really shouldn't be many future storage migrations.

**Comment by balaramesh** [comment]
@roycec did you get the answer to your question? Any open questions that still need answering?

**Comment by roycec** [comment]
We did the migration scaling down some deployments and did the final sync after unmounting some still mounted volumes. Then we switched to the new NetApp Cluster and brought the NFS server online again. We still have an issue because the new aggegate names we not discovered automatically. After changing the name manually, we get an error that the aggregate in question cannot be found, so new volumes can't be created at the moment.

**Comment by balaramesh** [comment]
@roycec can you check and confirm if the aggregate is assigned to the SVM on the ONTAP cluster? If the new aggregates are assigned to the SVM, then running `tridentctl backend update` will have Trident fetch all newly assigned aggregates automatically

**Comment by roycec** [comment]
Everything is configured correctly on the hardware side, I ran into this issue https://kb.netapp.com/Advice_and_Troubleshooting/Cloud_Services/Trident_Kubernetes/New_Trident_installation_create_volume_fails_with_error%3A_could_not_find_aggregate
