### ISSUE TITLE
Improve error message & documentation wrt GKE & CVS configured in different regions

### ISSUE THREAD

**Issue by YvosOnTheHub** [NetApp/trident#551]
**Describe the solution you'd like**
When creating a GKE cluster in a region & Trident backends pointing to CVS created in an other region, one will get the following error when trying to create a PVC:
`configured region does not match topology region`
This message is quite confusing, especially since we support the CSI Topology feature, & will lead to debugging the wrong problem.

**Describe alternatives you've considered**
Trident does not allow to create PVC in such configuration because of the additional network traffic charges the customer will receive if trying to use compute in one region and storage in another region.
The error message should definitely be more explicit.
Also, documentation should add a warning about this.

**Comment by gnarl** [comment]
This issue was fixed with [commit 7b15247](https://github.com/NetApp/trident/commit/7b15247327ee75f136dfc9bd2b22c9547efb63d7).
