### ISSUE TITLE
debugTraceFlags documented but no longer valid

### ISSUE THREAD

**Issue by wonderland** [NetApp/trident#552]
The troubleshooting section of the documentation mentions to set debugTraceFlags in the backend JSON:

https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/troubleshooting.html

However, this setting is no longer honoured by Trident. The logs give a warning:

level=warning msg="The debug setting in the configuration file is now ignored; use the command line --debug switch instead."

Documentation should be updated to provide the correct steps for enabling debug logging when troubleshooting issues with a backend.

**Comment by balaramesh** [comment]
@wonderland `debugTraceFlags` is a supported config option. The warning message is for the `debug` backend config option. To distinguish:

```
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "dataLIF": "10.0.0.2",
    "debugTraceFlags": {"method": true, "api" :true},
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
```
This is supported. The logs will display all method calls as well as API calls made to the ONTAP system.

```
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "10.0.0.1",
    "debug": true,
    "dataLIF": "10.0.0.2",
    "svm": "trident_svm",
    "username": "cluster-admin",
    "password": "password"
}
```
The `debug` config option does nothing here.

**Comment by wonderland** [comment]
Sorry, my bad. I had indeed both, the debug and debugTraceFlags in the JSON. Thanks for the swift reply!

**Comment by balaramesh** [comment]
Glad to help! If this answered your question, please go ahead and close this issue
