### ISSUE TITLE
Fix part about the reclaim policy Delete in DAG section

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#557]
**Describe the solution you'd like**

Correct the explanation about the reclaim policy Delete.

**Additional context**

For [Delete](https://netapp-trident.readthedocs.io/en/stable-v21.01/dag/kubernetes/concepts_and_definitions.html) it is said:

> However, Kubernetes does not delete the storage which was referenced by the PV. A storage administrator will need to delete the volume on the backend.

**Comment by balaramesh** [comment]
This was fixed with commit [7b1524](https://github.com/NetApp/trident/commit/7b15247327ee75f136dfc9bd2b22c9547efb63d7)
