### ISSUE TITLE
Request for Enhancement: add timestamp for trident's metadata, like volumes, backends. 

### ISSUE THREAD

**Issue by sl0n** [NetApp/trident#56]
Hello,

I was debugging an issue recently where a volume, provisioned by trident, couldn't get mounted. I quickly came to realized that doing something like:

`$ tridentctl get volume -o json
`
doesn't provide me with volume creation date / time, and I had to do `tridentctl logs` and scroll through it, however this is of limited capacity.

Generally speaking, I'd say timestamps would be great to have for the following:

backend
storageclass
volume

Thanks,
Vladimir

**Comment by gnarl** [comment]
Closing this issue as `kubectl get PVC <pvc-name> -o json` includes the creationTimestamp which is set by Kubernetes.
