### ISSUE TITLE
FIle Permission squashing to NOBODY 

### ISSUE THREAD

**Issue by anvpetrov** [NetApp/trident#561]
Files created on NFS PV downgrade permissions to NOBODY

**Environment**
- Trident version: 21.01.1
- Trident installation flags used: [trident  -n trident install]
- Container runtime:  crio 1.19
- Kubernetes version: 1.19
- Kubernetes orchestrator: Openshift 4.6.20
- Kubernetes enabled feature gates: 
- OS: CoreOS 4.6
- NetApp backend types: ONTAP
- Other:

1. create pvc
2. map it to deployment
3. open container console
4. create file on PV mount point
5. File owner 99(nobody)

**Expected behavior**
Owner of file user with openshift range UID

On node I see that share mounted with sec=null
On enother cluster, when all working fine sec=sys

**Comment by balaramesh** [comment]
@anvpetrov you can enforce file ownership in Kubernetes using `fsGroups` as follows:

1. Make sure the StorageClass used to create PVCs has `parameter.fsType` defined. Example manifest is [here](https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-basic.yaml.templ)
2. Provide `securityContext.fsGroup` for RWO PVCs, and `supplementalGroups` for RWX PVCs. Example manifest is [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)

**Comment by balaramesh** [comment]
In addition, you should also take a look at https://github.com/NetApp/trident/issues/269.

Moreover, the share is likely being mounted as `sec=null` because of the idmapper config on your RHCOS nodes (/etc/idmapd.conf). You will need to set the realm to be the same as configured on ONTAP.

**Comment by anvpetrov** [comment]
Thank you for response.

I will add that my user in container is not root. His uid is for example 101234100

I have several clusters with same storage class and backend.json , but only on this cluster I have a problem with squashing

**Comment by anvpetrov** [comment]
> In addition, you should also take a look at #269.
> 
> Moreover, the share is likely being mounted as `sec=null` because of the idmapper config on your RHCOS nodes (/etc/idmapd.conf). You will need to set the realm to be the same as configured on ONTAP.

idmaper is disabled by default
$ cat /sys/module/nfs/parameters/nfs4_disable_idmapping 
Y

On netapp option superuser = any

**Comment by megabreit** [comment]
@anvpetrov Why do you disable the idmapper? It's probably the reason for your problems. It's simple to configure. Just think about a realm, just a simple text string, and configure it on RHCOS and on the SVM.

**Comment by paraenggu** [comment]
@balaramesh although it's a rather oldish issue/comment, I would be interested in some background on your following statement (the second part regarding the RWX PVCs):

>  you can enforce file ownership in Kubernetes using `fsGroups` as follows:
> 
>     1. Make sure the StorageClass used to create PVCs has `parameter.fsType` defined. Example manifest is [here](https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/storage-class-basic.yaml.templ)
> 
>     2. Provide `securityContext.fsGroup` for RWO PVCs, **and `supplementalGroups` for RWX PVCs.** Example manifest is [here](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod)

For ontap-nas backed RWX PVCs: How will the group specified in the `supplementalGroups` be reflected on the NFS root directory? i.e what ensures that the directory group ownership matches with the group specified in `supplementalGroups`? 

Thanks a lot!

**Comment by sjpeeris** [comment]
@paraenggu Please let us know if this issue still exists with the newer versions of Trident.

**Comment by sjpeeris** [comment]
Closing. Please re-open if you notice this issue with newer versions of Trident.
