### ISSUE TITLE
Trident 21.01.2 upgrade  Error ( upgrade from 20.07.1 to 21.x.x)

### ISSUE THREAD

**Issue by arunbpt7** [NetApp/trident#566]
Hello All,
I am trying to upgrade Trident 21.07.2 on Kubernetes 1.17.4. But The operator pod ( trident-operator-xxxx-xxxx )is failing due to below errorn and unable to proceeds with futher steps

"Error: Container has runAsRoot and image will run as root".  I added securityContext "runAsUser" in deploy.yaml as a trail and run  and that completed succefully with the deployment of operator , torc , CSI controller and CSI daemon set.

let me know the fix for these errors.

Is there any potential issues that would occure when operator runAsUser ie, PV operation, Trident functionality etc?

**Comment by clintonk** [comment]
Hello, @arunbpt7.  The ```trident-operator``` and ```trident-csi``` deployments do not require elevated privileges, nor do they request that.  However, the ```trident-csi``` daemonset does require root privileges, since it must be able to discover and attach storage resources to the cluster nodes.  Even if Trident installs without elevated privileges on the daemonset, I suspect it would fail to attach PVs to pods.

**Comment by arunbpt7** [comment]
> Hello, @arunbpt7. The `trident-operator` and `trident-csi` deployments do not require elevated privileges, nor do they request that. However, the `trident-csi` daemonset does require root privileges, since it must be able to discover and attach storage resources to the cluster nodes. Even if Trident installs without elevated privileges on the daemonset, I suspect it would fail to attach PVs to pods.

@clintonk 
Thanks for the response. I was able to fix the privilage issue by adding a emptyDir volume and mount  as /tmp in operator deployment spec.  not sure that the right fix for it.

Long story short ,
I am trying to upgrade trident from upgrade from 20.07.1 to 21.01.2. The operator issues was fixed by adding the /tmp as mentioned above. I am follwoing the trident offcial documentation for the upgrade process.
 The operator was able to bought up and installed the required CRD, and the CSI daemon sets with out having any issues. But trident instalation is still not completing due to resource quota issues. Attaching the screen shot for your reference.

![Untitled](https://user-images.githubusercontent.com/18433900/116010151-5bbde000-a5eb-11eb-8ad7-f1b010708b3f.jpg)
![Image 3](https://user-images.githubusercontent.com/18433900/116010169-6bd5bf80-a5eb-11eb-9c03-d16bb7b52798.jpeg)

**Comment by balaramesh** [comment]
@arunbpt7 do you have any updates on this? As Clinton mentioned, `runAsRoot` is a requirement for the `trident-csi` daemonset that Trident creates. The deploy.yaml file is used to spin up the Trident operator, which in turn will install Trident (create the `trident-csi` deployment, `trident-csi` daemonset)

**Comment by arunbpt7** [comment]
@balaramesh , Yes trying to upgrade from 20.07.1 to 21.07.2 however the operator fails with "Error: Container has runAsRoot and image will run as root".

**Comment by sjpeeris** [comment]
Closing. Please re-open if you notice this issue with newer versions of Trident.
