### ISSUE TITLE
trident-autosupport:21.04 does not push in a container repository

### ISSUE THREAD

**Issue by ysakashita** [NetApp/trident#574]
**Describe the bug**
The container image `netapp/trident-autosupport:21.04` does not push in Docker Hub.

**Environment**

Provide accurate information about the environment to help us reproduce the issue.

Trident version: v21.04.0
Trident installation flags used: -n trident
Container runtime: Docker 20.10.6
Kubernetes version: 1.20.6
Kubernetes orchestrator: none
Kubernetes enabled feature gates: none
OS: Ubuntu 20.04.1
NetApp backend types: ONTAP AFF 9.5

**To Reproduce**
non

**Expected behavior**

The flowing code is specified `netapp//trident-autosupport:21.04` .
https://github.com/NetApp/trident/blob/master/deploy/crds/tridentorchestrator_cr_autosupport.yaml#L9

Could you change the image tag from 21.04 to 21.01 if it does not update in 21.04 ?

**Additional context**
none

**Comment by yasuoohno** [comment]
This may have to be submitted separately as a documentation issue.

https://netapp-trident.readthedocs.io/en/stable-v21.04/support/requirements.html
https://github.com/NetApp/trident/blob/stable/v21.04/docs/support/requirements.rst

'netapp/trident-autosupport:21.04' is listed on v1.14.0~v1.20.0.
It is inconsistent with the output of `tridentctl images`.

https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/deploying/operator-deploy.html
https://github.com/NetApp/trident/blob/stable/v21.04/docs/kubernetes/deploying/operator-deploy.rst

The default value of autosupportImage in the TridentOperator spec is 'netapp/trident-autosupport:21.04'.

**Comment by gnarl** [comment]
This issue was fixed with [commit fe5910a](https://github.com/NetApp/trident/commit/fe5910a0b0d2f3056ad2a5843c2597b8ddfa07ac) and will be included in Trident v21.07 release.
