### ISSUE TITLE
Trident is mounting a non-existent volume from a unknown netapp nfs server

### ISSUE THREAD

**Issue by suhasagasthya** [NetApp/trident#575]
**Bug Description**
 Trident is trying to mount a volume that is not present on the svm nor a pv is present with that name. It is also trying to mount this non existent volume from a different Data LIF other than the ones mentioned in the trident backend config. Below are more details,
 
1. There is only a single volume present on the trident backend
```
$ tridentctl get volume -o yaml
items:
- Config:
    accessInformation:
      mountOptions: nfsvers=4.0
      nfsPath: /mb_drdeploy_pvc_9e956666_8783_4f79_9bc9_0f2e5014a1f7
      nfsServerIp: 10.25.104.34
    accessMode: ReadWriteMany
    internalName: mb_drdeploy_pvc_9e956666_8783_4f79_9bc9_0f2e5014a1f7
    name: pvc-9e956666-8783-4f79-9bc9-0f2e5014a1f7
```

2. PVC details
`$ oc get pvc
NAME                   STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
volume-test   Bound    pvc-9e956666-8783-4f79-9bc9-0f2e5014a1f7   20Gi       RWX            test   51m`

3. The trident is trying to mount a non existent volume onto the OKD worker node, here this volume does not exist and the nfs server address is also incorrect. Data taken from the worker node where pod was being created
`sh-4.4# mount -l | grep nfs
10.25.104.32:/ssites_austin_pvc_5c2ba8d2_1d76_4b2d_ab6c_e31aa102dff1 on /host/var/lib/kubelet/pods/db7f3738-f2ac-4374-b191-086fb0b98598/volumes/kubernetes.io~csi/pvc-886e8224-e41d-4fd1-8f66-ad403d2e7aff/mount type nfs4 (rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=sys,clientaddr=10.25.33.42,local_lock=none,addr=10.25.104.32)`

4. trident backend options specified, 
`    "version": 1,
    "storageDriverName": "ontap-nas",
    "storagePrefix": "mb_drdeploy_",
    "managementLIF": "10.25.104.36",
    "dataLIF": "10.25.104.34", "10.25.104.35",
    "labels": {"backend": "mbdeploy"},
    "nfsMountOptions": "nfsvers=4.0",`

5. Error thrown by OKD during the volume mount on the pod 
`Unable to attach or mount volumes: unmounted volumes=[pv-storage-ssites-mount-test-test], unattached volumes=[default-token-jv4xt pv-storage-ssites-mount-test-test]: timed out waiting for the condition
MountVolume.MountDevice failed for volume "pvc-9e956666-8783-4f79-9bc9-0f2e5014a1f7" : rpc error: code = DeadlineExceeded desc = context deadline exceeded
`

6. trident logs - https://pastebin.pl/view/f77e97c4
 
Note:- Creation of a PVC is working  fine. 

**Environment**

- Trident version: 20.10.0
- Trident installation flags used:  -d -n trident 
- Kubernetes version: v1.19.2-1049+f173eb4a83e557-dirty
- Kubernetes orchestrator: OKD 4.6 - 4.6.0-0.okd-2021-02-14-205305
- OS: Fedora CoreOS
- NetApp backend types: Ontap NAS

**To Reproduce**
1. Create a PVC and mount it to a pod, the pod fails to start up throwing the error

**Expected behavior**
The pod should start up having the volume mounted without any issues

**Additional context**

**Comment by balaramesh** [comment]
@suhasagasthya there is nothing in the logs that you had shared that indicates Trident was behind the mounting of `10.25.104.32:/ssites_austin_pvc_5c2ba8d2_1d76_4b2d_ab6c_e31aa102dff1`. Can you confirm if Trident was behind that volume being mounted? It could be a volume that was mounted outside of Trident

**Comment by suhasagasthya** [comment]
Issue got resolved after the worker nodes got rebooted, looks like an old cache

**Comment by gnarl** [comment]
Thanks for the update @suhasagasthya.

**Comment by suhasagasthya** [comment]
Found a similar issue here, 

Environment

Trident version: 20.10.0
Trident installation flags used: -d -n trident
Kubernetes version: v1.19.2-1049+f173eb4a83e557-dirty
Kubernetes orchestrator: OKD 4.6 - 4.6.0-0.okd-2021-02-14-205305
OS: Fedora CoreOS
NetApp backend types: Ontap NAS

The trident daemonset node running on the worker node has deregistered and could see stale volumes being mounted. 
`I0507 05:35:35.042687 2402029 main.go:112] Version: v2.0.1-0-g1aaa13ae
I0507 05:35:35.042801 2402029 main.go:122] Attempting to open a gRPC connection with: "/plugin/csi.sock"
I0507 05:35:35.042817 2402029 connection.go:151] Connecting to unix:///plugin/csi.sock
I0507 05:35:35.043704 2402029 main.go:129] Calling CSI driver to discover driver name
I0507 05:35:35.043764 2402029 connection.go:180] GRPC call: /csi.v1.Identity/GetPluginInfo
I0507 05:35:35.043781 2402029 connection.go:181] GRPC request: {}
I0507 05:35:35.048754 2402029 connection.go:183] GRPC response: {"name":"csi.trident.netapp.io","vendor_version":"20.10.0"}
I0507 05:35:35.048852 2402029 connection.go:184] GRPC error: <nil>
I0507 05:35:35.048862 2402029 main.go:139] CSI driver name: "csi.trident.netapp.io"
I0507 05:35:35.048962 2402029 node_register.go:55] Starting Registration Server at: /registration/csi.trident.netapp.io-reg.sock
I0507 05:35:35.049197 2402029 node_register.go:64] Registration Server started at: /registration/csi.trident.netapp.io-reg.sock
I0507 05:35:35.049285 2402029 node_register.go:86] Skipping healthz server because port set to: 0
I0507 05:35:37.032376 2402029 main.go:79] Received GetInfo call: &InfoRequest{}
I0507 05:35:37.060700 2402029 main.go:89] Received NotifyRegistrationStatus call: &RegistrationStatus{PluginRegistered:true,Error:,}
E0605 19:55:07.530067 2402029 connection.go:129] Lost connection to unix:///plugin/csi.sock.
E0608 05:59:18.716063 2402029 connection.go:129] Lost connection to unix:///plugin/csi.sock.
E0610 15:57:34.237829 2402029 connection.go:129] Lost connection to unix:///plugin/csi.sock.
E0613 02:34:00.286825 2402029 connection.go:129] Lost connection to unix:///plugin/csi.sock.
E0615 12:37:56.423345 2402029 connection.go:129] Lost connection to unix:///plugin/csi.sock.`

Logs says trident is trying to mount the non existent volume - `
time="2021-06-16T15:12:02Z" level=debug msg="GRPC call: /csi.v1.Node/NodeUnpublishVolume" requestID=1c703883-1d47-4c4e-8943-741eefb2832e requestSource=CSItime="2021-06-16T15:12:02Z" level=debug msg="GRPC request: volume_id:\"pvc-39d7958a-0c49-422f-a9f6-56c16037262b\" target_path:\"/var/lib/kubelet/pods/ce51ac0e-2dbd-44c4-8328-72c844656587/volumes/kubernetes.io~csi/pvc-39d7958a-0c49-422f-a9f6-56c16037262b/mount\" " requestID=1c703883-1d47-4c4e-8943-741eefb2832e requestSource=CSItime="2021-06-16T15:12:02Z" level=debug msg="Attempting to acquire shared lock (NodeUnpublishVolume-pvc-39d7958a-0c49-422f-a9f6-56c16037262b)." lock=csi_node_server requestID=1c703883-1d47-4c4e-8943-741eefb2832e requestSource=CSI`

These PVC are not existent and these are the mounts seen on the worker node -  `sh-5.0# mount -l | grep nfs | grep 10.25.*
10.25.104.34:/oshpci_austin_pvc_39d7958a_0c49_422f_a9f6_56c16037262b on /var/lib/kubelet/pods/ce51ac0e-2dbd-44c4-8328-72c844656587/volumes/kubernetes.io~csi/pvc-39d7958a-0c49-422f-a9f6-56c16037262b/mount type nfs4 (rw,relatime,vers=4.0,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=null,clientaddr=10.86.193.78,local_lock=none,addr=10.25.104.34)
10.25.104.34:/oshpci_austin_pvc_ea3f7b2a_257e_4915_99b3_981979b535ac on /var/lib/kubelet/pods/adef85ee-58bb-468d-bba3-32407b554465/volumes/kubernetes.io~csi/pvc-ea3f7b2a-257e-4915-99b3-981979b535ac/mount type nfs4 (rw,relatime,vers=4.1,rsize=65536,wsize=65536,namlen=255,hard,proto=tcp,timeo=600,retrans=2,sec=null,clientaddr=10.86.193.78,local_lock=none,addr=10.25.104.34)`

**Comment by suhasagasthya** [comment]
Attaching the list of all volumes in the cluster, the volume under discussion was deleted few weeks ago, but still exists in trident and tries to mount stale volumes on the node - 
1. 10.25.104.34:/oshpci_austin_pvc_39d7958a_0c49_422f_a9f6_56c16037262b 
2. 10.25.104.34:/oshpci_austin_pvc_ea3f7b2a_257e_4915_99b3_981979b535ac
<img width="962" alt="Screenshot 2021-06-18 at 11 57 24 AM" src="https://user-images.githubusercontent.com/38955501/122516591-93199d80-d02c-11eb-99e5-a5906e820f86.png">

**Comment by suhasagasthya** [comment]
The worker node reboot solved this, looks like a stale cache again. Post reboot, trident is not trying to mount that volume back. Please have a look , we were able to reproduce this twice.
