### ISSUE TITLE
is this NAS compatible with trident ?

### ISSUE THREAD

**Issue by dimthe** [NetApp/trident#58]
hello 

i would like to know if the nas listed below can work with trident. 
I have a kube cluster and i am looking for storage
https://www.hetzner.de/storage-box/bx60

**Comment by adkerr** [comment]
Hi @dimthe,

Trident is currently only compatible with NetApp storage devices. For NAS this is limited to the NetApp ONTAP platform.

**Comment by dimthe** [comment]
ok i understand @adkerr , no trident for me :(

**Comment by kangarlou** [comment]
@dimthe You may be able to use https://github.com/kubernetes-incubator/external-storage. I believe the NAS provisioner creates directories/shares as "volumes" under an existing NFS share.
