### ISSUE TITLE
Can' t create volume snapshots

### ISSUE THREAD

**Issue by roycec** [NetApp/trident#580]
In an test environment using Trident 21.01.1 on k8s 1.18.14, we want to create volume snapshots on the k8s level. I followed the instructions [here](https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/operations/tasks/volumes/snapshots.html). Everything worked fine until I tried to create an actual snapshot from an existing PVC. Then the creation of the snapshot hangs indefinitely, the "ready to use" status is "false".
Depending on if I add a namespace at snapshot creation or not, I get the errors/events

`Failed to create snapshot content with error snapshot controller failed to update data-bitbucket-0-snapshot on API server: cannot get claim from snapshot`

or

`Waiting for a snapshot bitbucket/data-bitbucket-0-snapshot to be created by the CSI driver.`

I do also not find any other errors, except these messages mentioned above. Also the logs of the snapshot-controller pod don't tell me anything useful.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 21.01.1
- Trident installation flags used: -n trident 
- Container runtime: RHEL Docker 1.13
- Kubernetes version: 1.18.14
- Kubernetes orchestrator: Rancher 2.5.5
- Kubernetes enabled feature gates: 
- OS: RHEL 7.9
- NetApp backend types: ONTAP 9.7P11
- Other:

**To Reproduce**
- Install everything needed to create Kubernetes volume snapshots (see https://netapp-trident.readthedocs.io/en/stable-v21.01/kubernetes/operations/tasks/volumes/snapshots.html)
- Create snapshot class
- Create snapshot from existing pvc

**Expected behavior**
Snapshot gets created and is in "ready to use" state.

**Comment by clintonk** [comment]
Hi, @roycec.  The only time I've seen ```cannot get claim from snapshot``` is when the VolumeSnapshot was in a different namespace from the PVC.

**Comment by roycec** [comment]
> Hi, @roycec. The only time I've seen `cannot get claim from snapshot` is when the VolumeSnapshot was in a different namespace from the PVC.

How can I influence this? Afaik the pvcs are namespaced, the examples regarding snapshots in the documentation are without any reference to namespaces. Now the case is, that both pvc and the possible snapshot are within the same namespace, so I get the second message.

**Comment by clintonk** [comment]
@roycec  Yes, all PVCs are namespaced, as are VolumeSnapshot objects.  New namespaced objects such as snapshots may specify their namespace, otherwise they wind up in the namespace from your current context.  Specify the namespace like this, where the snapshot namespace must match that of the PVC.
```
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: pvc1-snapshot
  namespace: default
spec:
  volumeSnapshotClassName: trident-csi
  source:
    persistentVolumeClaimName: pvc1

```

**Comment by roycec** [comment]
@clintonk yes, this makes this a lot more clear, the docs could be a little more precise on this. But if I apply the YAML like this, I'm still stuck in the creation process of the snapshot itself

```
Events:
  Type    Reason            Age   From                 Message
  ----    ------            ----  ----                 -------
  Normal  CreatingSnapshot  37s   snapshot-controller  Waiting for a snapshot bitbucket/data-bitbucket-0-snapshot to be created by the CSI driver.
```

**Comment by clintonk** [comment]
Ensure that your VolumeSnapshotClass includes ```driver: csi.trident.netapp.io```.  Then check the logs for the csi-snapshotter & trident-main containers in the Trident deployment pod to see what might be happening.

**Comment by roycec** [comment]
yes, it does

```
apiVersion: snapshot.storage.k8s.io/v1beta1
kind: VolumeSnapshotClass
metadata:
  name: csi-snapclass-test                                                                                                                                                              
driver: csi.trident.netapp.io
deletionPolicy: Delete
```

**Comment by roycec** [comment]
In my case it turned out, that the backend was offline. Since it is back online again, the snapshots can be created successfully.
