### ISSUE TITLE
Publish container images list in to a file on the release page

### ISSUE THREAD

**Issue by mrlindblom** [NetApp/trident#582]
For air-gapped installations it would be beneficial to have a file that contains all container images used in the release. 

I know they are listed in https://netapp-trident.readthedocs.io/en/stable-v21.04/support/requirements.html#container-images-and-corresponding-kubernetes-versions.

However if its included in the release its easier to automate the preparation of the images in our internal registry. 
Similar to rancher-images.txt file in a Rancher release. 
https://github.com/rancher/rancher/releases/tag/v2.5.8-patch1

**Comment by wonderland** [comment]
Did you see the "tridentctl images" features that was recently added?

https://netapp-trident.readthedocs.io/en/stable-v21.04/reference/tridentctl.html#images

**Comment by gnarl** [comment]
Closing this issue as the required container image information is available via the tridentctl binary and also in the Trident documentation.
