### ISSUE TITLE
ontab-nas-economy dont provied "Used" Metrics

### ISSUE THREAD

**Issue by dn30000** [NetApp/trident#583]
**Describe the bug**
Openshift 3.11
I try to collect "Used" Metrics from the ontab-nas-economy metrics but unlike ontap-nas it does not provide "used" by PV.

**Comment by balaramesh** [comment]
Hi @dn30000 can you provide additional context here? Can you clarify what "used" by PV means? Are you referring to the PV/PVC binding?
