### ISSUE TITLE
autoExportPolicy: true not recognized by back-end, but back-end uses auto export policy if it already exists

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#586]
**Describe the bug**

autoExportPolicy works unpredictably in the following ways:

- autoExportPolicy and autoExportCIDRs are provided in back-end JSON file, but only the latter gets recognized. autoExportPolicy does not get recognized (`false`).
- if `trident_qtree_pool_export_policy` exists and the back-end is deleted and then created with (any different) autoExportCIDRs, the export policy's CIDR does not get updated (i.e. it remains accessible as per the original CIDR the first time the Qtree export policy was created by Trident, `0.0.0.0/0`). I know this is not "unexpected" to those who know about it, but I think it is *unpredictable* for those who haven't encountered this (so I may create a documentation enhancement request to improve this depending on comments to this issue) .
- when autoExportPolicy is set to `true`, back-end JSON is loaded without issues but the end result (`tridentctl get backend`) shows `autoExportPolicy: false` and yet autoExportPolicy appears to partially work in the sense that the FlexVol uses `trident_qtree_pool_export_policy` and not `default` or some other
- [edit] after submitting this bug I deleted `trident_qtree_pool_export_policy` and recreated NAS economy back-end, and even though `autoExportCIDRs` were recognized and shown in back-end definition (as at the top of this list), export CIDRs in `trident_qtree_pool_export_policy` are still `0.0.0.0/0` and `::/0`

**Environment**

- Trident version: 21.04.1
- Trident installation flags used: default
- Container runtime: version 1.13.1, build 0be3e21/1.13.1
- Kubernetes version: v1.11.0
- Kubernetes orchestrator: OpenShift (OKD) v3.11
- Kubernetes enabled feature gates: (none)
- OS: CentOS 7.9
- NetApp backend types: ONTAP 9.8P1

**To Reproduce**

Steps to reproduce the behavior: at some point the default `trident_qtree_pool_export_policy` was created, so it was in place on vserver3 already. I deleted all PVCs, SCs, and NAS back-ends, while SVMs and Export Policies were left as-is. Then I did the following.

1. Create back-end with autoExportPolicy set to `true`  
```json
{
    "version": 1,
    "backendName": "ontap-nas_192.168.1.55-auto-ep",
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "192.168.1.50",
    "dataLIF": "192.168.1.55",
    "svm": "vserver3",
    "username": "admin",
    "password": "NetApp123$",
    "autoExportCIDRs": ["192.168.1.108/32"],
    "autoExportPolicy": true
}
```
2. Examine the new back-end (notice how autoExportCIDRs got loaded (although this doesn't really affect new exports), but autoExportPolicy did not and shows `false`):  
```raw
$ tridentctl get backends -n trident ontap-nas_192.168.1.55-auto-ep -o yaml
items:
- backendUUID: 7cc89e36-d388-418b-b39c-be280e5909fc
  config:
    aggregate: ""
    autoExportCIDRs:
    - 192.168.1.108/32
    autoExportPolicy: false
    backendName: ontap-nas_192.168.1.55-auto-ep

```
3. Create SC and a PVC/PV to use it:  
```sh
$ oc describe pv default-qtreeguy-ccc78
Name:            default-qtreeguy-ccc78
Labels:          <none>
Annotations:     pv.kubernetes.io/provisioned-by=netapp.io/trident
                 volume.beta.kubernetes.io/storage-class=autoqtree
Finalizers:      [kubernetes.io/pv-protection]
StorageClass:    autoqtree
Status:          Bound
Claim:           default/qtreeguy
Reclaim Policy:  Delete
Access Modes:    RWO
Capacity:        2Gi
Node Affinity:   <none>
Message:         
Source:
    Type:      NFS (an NFS mount that lasts the lifetime of a pod)
    Server:    192.168.1.55
    Path:      /trident_qtree_pool_trident_DJIUOEJTQN/trident_default_qtreeguy_ccc78
    ReadOnly:  false
Events:        <none>
```

**Expected behavior**

- `autoExportPolicy: true`, if accepted on back-end create, should not show as `autoExportPolicy: false` in `get backend` output
- if `autoExportPolicy: false` is truly in effect, Trident would try to use the export policy `default` rather than default to an export policy that may not be the one called and considered `default`. That is, `default` seems like the logical default policy name and `trident_qtree_pool_export_policy` does not, when `autoExportPolicy: false`.

**Additional context**

- Environment:

```sh
$ tridentctl version -n trident
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.04.0        | 21.04.0        |
+----------------+----------------+

$ oc get nodes
NAME      STATUS    ROLES                  AGE       VERSION
m         Ready     compute,infra,master   103d      v1.11.0+d4cacc0

$ cat /etc/redhat-release 
CentOS Linux release 7.9.2009 (Core)

```

- FlexVol `trident_qtree_pool_trident_DJIUOEJTQN` uses `trident_qtree_pool_export_policy` although back-end description shows `autoExportPolicy: false`

![image](https://user-images.githubusercontent.com/16622642/122035946-967f1000-ce05-11eb-95a1-a3d7b330f5d1.png)

![image](https://user-images.githubusercontent.com/16622642/122041239-4f941900-ce0b-11eb-8c4c-c8328a678569.png)

- ONTAP export rules for vserver3 (as mentioned above, `trident_qtree_pool_export_policy` had existed before and was not deleted prior to new back-end creation, so it's "stale" in the sense that it doesn't reflect the autoExportCIDRs set in latest iteration)

```raw
otsc::> export-policy rule show -vserver vserver3 -policyname default 
             Policy          Rule    Access   Client                RO
Vserver      Name            Index   Protocol Match                 Rule
------------ --------------- ------  -------- --------------------- ---------
vserver3     default         2       nfs3,    192.168.1.0/24        any
                                     nfs4,
                                     nfs

otsc::> export-policy rule show -vserver vserver3 -policyname policy_with_no_root_squash
             Policy          Rule    Access   Client                RO
Vserver      Name            Index   Protocol Match                 Rule
------------ --------------- ------  -------- --------------------- ---------
vserver3     policy_with_no_root_squash 
                             1       nfs3     192.168.1.0/24        any

otsc::> export-policy rule show -vserver vserver3 -policyname trident_qtree_pool_export_policy
             Policy          Rule    Access   Client                RO
Vserver      Name            Index   Protocol Match                 Rule
------------ --------------- ------  -------- --------------------- ---------
vserver3     trident_qtree_pool_export_policy 
                             1       nfs      0.0.0.0/0             any
vserver3     trident_qtree_pool_export_policy 
                             2       nfs      ::/0                  any
2 entries were displayed.

```

**Comment by scaleoutsean** [comment]
Just realized that in the latest Trident documentation there's a note that autoExportPolicy works only with Trident CSI, which in my case isn't (OCP 3.11). 

![image](https://user-images.githubusercontent.com/16622642/122161931-363fab00-cea5-11eb-8fe9-df88407690d5.png)

Before I didn't use the latest documentation (which also has this notice, but it's not emphasized, so I had missed it).

I suppose I could close this as invalid, but I'd also say `is only available for CSI Trident` should instead be `is only supported`.  It does (more or less) work with pre-CSI Trident as we can see from this bug report.

**Comment by gnarl** [comment]
Thanks for the clarification, @scaleoutsean. Closing this issue for the additional reason of OCP 3.11 and pre-CSI Kubernetes version support ended with the Trident 21.04 release. Expect an updated support statement for Trident 21.07.0.
