### ISSUE TITLE
Unable to create backend

### ISSUE THREAD

**Issue by bhuwan1009** [NetApp/trident#588]
While running the backend create, I am getting below error

./tridentctl -n trident create backend -f backend.json
Error: could not create backend: problem initializing storage driver 'ontap-nas-economy': could not configure storage pools: could not get storage pools from array: SVM XXXXXXX has no assigned aggregates (400 Bad Request)
command terminated with exit code 1

My trident version is 
./tridentctl version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.04.0        | 21.04.0        |
+----------------+----------------+

My Kubectl version is
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1-5-g76a04fc"

**Comment by YvosOnTheHub** [comment]
Hi
can you check if aggregates have been assigned to the SVM in ONTAP ?

Fyi, "assigned" does not mean "dedicated", it just tells Trident in what aggregates volumes can be created

cf https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operations/tasks/backends/ontap.html?highlight=aggregate#preparation

**Comment by YvosOnTheHub** [comment]
if you dont have access to the SVM in CLI or via System Manager, you can run the following:
(replace svmlogin, svmpassword & SVM_Mgmt_IP with the values you have in your backend file)

1. `curl -X GET -ku svmlogin:svmpassword  "https://SVM_Mgmt_IP/api/svm/svms" -H "accept: application/json"`
=> this will return a UUID

2. `curl -X GET -ku svmlogin:svmpassword  "https://SVM_Mgmt_IP/api/svm/svms/UUID?fields=aggregates_delegated,aggregates" -H "accept: application/json"`
(replace UUID with the value returned in 1.
=> this will show you whether you have delegated/assigned aggregates

**Comment by bhuwan1009** [comment]
I have received below error while executing the 1st point. Is it compulsory to have admin privileges for my user.

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>401 Unauthorized</title>
</head><body>
<h1>Unauthorized</h1>
<p>This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.</p>
</body></html>

**Comment by YvosOnTheHub** [comment]
Do you have access to the ONTAP CLI ?
if yes, can you run "vserver show -fields aggr-list"
it must not be empty for Trident to work

**Comment by bhuwan1009** [comment]
I don't have access to the ONTAP CLI. I will get it done from my storage team.

I got my account added as an admin account which resolved my first point and i am seeing 2 UUIDs

But now when i am trying for 2nd point by placing UUIDs, i am getting below error

<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>400 Bad Request</title>
</head><body>
<h1>Bad Request</h1>
<p>Your browser sent a request that this server could not understand.<br />
</p>
</body></html>

**Comment by bhuwan1009** [comment]
The command  vserver show -fields aggr-list   shows the list of aggregators

**Comment by gnarl** [comment]
Hi @bhuwan1009,

I suggest that you contact NetApp support for additional assistance. 

Your original post indicates that the vserver being used by the ontap-nas-economy storage driver does not have any aggregates assigned. NetApp support will be able to help you troubleshoot this issue better than we can via this forum.

**Comment by bhuwan1009** [comment]
I have asked storage team for the output

vserver          aggr-list
---------------- ---------
N2DC-NTP03-CLU01 -
N2DC-NTP03-CLU01-01 -
N2DC-NTP03-CLU01-02 -
N2DC-NTP03-CLU01-03 -
N2DC-NTP03-CLU01-04 -
N2NTP03_NAS      -
N2NTP03_SAN      -

**Comment by wonderland** [comment]
There are no aggregates (a pool of disks) assigned to any of the vservers (output "-"). The storage admin needs to assign an aggregate to the vserver (a tenant on the storage system), otherwise your Trident user does not have the permissions to work with it, e.g. create volumes. 

Please ask you storage admin to run

vserver add-aggregates -vserver <vserver-name> -aggregates <aggregate-name>
