### ISSUE TITLE
lun pool question

### ISSUE THREAD

**Issue by sjlee-tech** [NetApp/trident#589]
My customer are using ontap-san-economy
It was difficult to find documentation related to some of my customers' questions.

At first there was one lun_pool per node, but as it grows,
I want to know  which conditions the lun_pool count increases.

      **trident_lun_pool_trident_TZCRAQSHQA Thu Jun 10 17:59:34 2021**  -> node1 new generated lun pool 
      trident_lun_pool_trident_WKPHIBIYWL Wed May 26 15:34:45 2021 -> node1  
     trident_lun_pool_trident_XSAUYYDMUE Wed May 26 15:30:35 2021  -> node2
     **trident_lun_pool_trident_ZPSNYUNQKS Thu Jun 10 17:59:08 2021**  -> node2 new generated lun pool 

$ ./tridentctl version -n trident
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 20.10.0        | 20.10.0        |
+----------------+----------------+
$ ./tridentctl get backends -n trident
+-------------------------------+-------------------+--------------------------------------+----------+---------+
|             NAME              |  STORAGE DRIVER   |                 UUID                 |  STATE   | VOLUMES |
+-------------------------------+-------------------+--------------------------------------+----------+---------+
| sc-netapp8300-bee-san-economy | ontap-san-economy | 2f391ae1-6ab0-491a-afcd-64bd5db34dd7 | online   |     123 |
| sc-netapp8300-bee-nas         | ontap-nas         | 70bc7af4-5fb0-40d0-ab1f-02fbc558fe55 | online   |       1 |

**Comment by clintonk** [comment]
Hello @sjlee-tech.  When creating a new LUN, the ontap-san-economy driver selects an aggregate (assuming virtual pools have not been configured) at random, then searches that aggregate for a suitable Flexvol to contain the LUN.  A suitable Flexvol has the necessary characteristics (spaceReserve, snapshot policy, tiering policy, snapshot directory visibility, encryption, etc.), isn't too large already, and has no more than 100 LUNs already (cap configurable between 50 & 200, not including "snapshot" LUNs).  If such a Flexvol is found, the new LUN is created there.  If not, and the chosen aggregate has sufficient space, a new Flexvol is created for the LUN.  If the aggregate does not have space, another aggregate is selected at random and the process repeats.  The result is a potentially large number of LUNs distributed across multiple aggregates and Flexvols, which should spread the load and provide better overall performance.

**Comment by sjlee-tech** [comment]
Thx clintonk. 
When the free space of the Flexvol is left, will a new Flexvol be created? 
There is enough free capacity for aggregation.

## the new LUN is created there. If not, and the chosen aggregate has sufficient space, a new Flexvol is created for the LUN.
##he result is a potentially large number of LUNs distributed across multiple aggregates and Flexvols, which should spread the load and provide better overall performance.

If so, I understood that if there is enough aggregation space, a lun_pool is created as LUNs are continuously added,
What happens when a LUN is deleted and the new lun_pool is no longer needed??

**Comment by clintonk** [comment]
>> When the free space of the Flexvol is left, will a new Flexvol be created?

Free space in the Flexvol is largely immaterial, as Trident will adjust the Flexvol size as LUNs are created or deleted.

>> What happens when a LUN is deleted and the new lun_pool is no longer needed?

When a LUN is deleted and no LUNs remain in the Flexvol pool, Trident deletes the Flexvol.  In other words, Trident manages the full lifecycle of the pool Flexvols automatically.

**Comment by gnarl** [comment]
Closing this issue as the questions on how the ontap-san-economy driver works were answered.

**Comment by sjlee-tech** [comment]
I would like to know the exact conditions under which the FlexVol(lun_pool) is created.

**Comment by sjlee-tech** [comment]
> > > When the free space of the Flexvol is left, will a new Flexvol be created?
> 
> Free space in the Flexvol is largely immaterial, as Trident will adjust the Flexvol size as LUNs are created or deleted.
> 
> > > What happens when a LUN is deleted and the new lun_pool is no longer needed?
> 
> When a LUN is deleted and no LUNs remain in the Flexvol pool, Trident deletes the Flexvol. In other words, Trident manages the full lifecycle of the pool Flexvols automatically.

I would like to know the exact conditions under which the FlexVol(lun_pool) is created.
