### ISSUE TITLE
Slow response from Trident

### ISSUE THREAD

**Issue by anvpetrov** [NetApp/trident#590]
Time-out waiting PV mounting on app POD when trident do some other work.

- Trident version: 20.01.1
- Container runtime: [cri-o 1.19.1]
- Kubernetes version: [1.19.1]
- Kubernetes orchestrator: [ OpenShift v4.6.30]
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: [RHEL CoreOS 46.82]
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7]
- Other:

**To Reproduce**
Create 40 PVC with 10Mi request.
All this PVC will be in state Pending and error about minimal size limit.

**Expected behavior**
at this time pods not starting with error : time-out waiting PV mounting

If i run command
tridentctl -n trident get backend , it return response after about 40 seconds!

**Comment by anvpetrov** [comment]
Some diagnostic info
./tridentctl -n trident version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 21.01.1        | 21.01.1        |


1. Normal work
Response after  0.5 sec.

# time ./tridentctl -n trident get backend

+---------------------------+----------------+--------------------------------------+--------+---------+
|           NAME            | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+---------------------------+----------------+--------------------------------------+--------+---------+
| backend1 | ontap-nas      | 207ee0d5-6990-4d83-a38b-84397605b82f | online |       2 |
+---------------------------+----------------+--------------------------------------+--------+---------+
real    0m0.796s
user    0m0.551s
sys     0m0.146s

2. Create many PVCs with size 10Mb.
All PVC will be in Pending state.

# oc get pvc
NAME         STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS    AGE
pvctest-1    Pending                                                                        sc-nfs-netapp   24s
pvctest-10   Pending                                                                        sc-nfs-netapp   20s
pvctest-11   Pending                                                                        sc-nfs-netapp   19s
pvctest-12   Pending                                                                        sc-nfs-netapp   19s
pvctest-13   Pending                                                                        sc-nfs-netapp   18s
pvctest-14   Pending                                                                        sc-nfs-netapp   18s
pvctest-15   Pending                                                                        sc-nfs-netapp   17s
pvctest-16   Pending                                                                        sc-nfs-netapp   17s
pvctest-17   Pending                                                                        sc-nfs-netapp   16s
pvctest-18   Pending                                                                        sc-nfs-netapp   16s
pvctest-19   Pending                                                                        sc-nfs-netapp   15s
pvctest-2    Pending                                                                        sc-nfs-netapp   23s
pvctest-20   Pending                                                                        sc-nfs-netapp   15s
pvctest-21   Pending                                                                        sc-nfs-netapp   14s
pvctest-22   Pending                                                                        sc-nfs-netapp   14s
pvctest-23   Pending                                                                        sc-nfs-netapp   13s
pvctest-24   Pending                                                                        sc-nfs-netapp   13s
pvctest-25   Pending                                                                        sc-nfs-netapp   12s
pvctest-26   Pending                                                                        sc-nfs-netapp   12s
pvctest-27   Pending                                                                        sc-nfs-netapp   11s
pvctest-28   Pending                                                                        sc-nfs-netapp   11s
pvctest-29   Pending                                                                        sc-nfs-netapp   10s
pvctest-3    Pending                                                                        sc-nfs-netapp   23s
pvctest-30   Pending                                                                        sc-nfs-netapp   10s
pvctest-31   Pending                                                                        sc-nfs-netapp   9s
pvctest-32   Pending                                                                        sc-nfs-netapp   9s
pvctest-33   Pending                                                                        sc-nfs-netapp   8s
pvctest-34   Pending                                                                        sc-nfs-netapp   8s
pvctest-35   Pending                                                                        sc-nfs-netapp   7s
pvctest-36   Pending                                                                        sc-nfs-netapp   6s
pvctest-37   Pending                                                                        sc-nfs-netapp   6s
pvctest-38   Pending                                                                        sc-nfs-netapp   5s
pvctest-39   Pending                                                                        sc-nfs-netapp   5s
pvctest-4    Pending                                                                        sc-nfs-netapp   22s
pvctest-40   Pending                                                                        sc-nfs-netapp   4s
pvctest-5    Pending                                                                        sc-nfs-netapp   22s
pvctest-6    Pending                                                                        sc-nfs-netapp   21s
pvctest-7    Pending                                                                        sc-nfs-netapp   21s
pvctest-8    Pending                                                                        sc-nfs-netapp   20s
pvctest-9    Pending                                                                        sc-nfs-netapp   20s
test         Bound     pvc-2dda7ba5-d582-4ee6-b73d-f3d5723e5f66   1Gi        RWO            sc-nfs-netapp   3d6h


In this case operations with tridentctl are performed about 40 sec

# time ./tridentctl -n trident get backend

+---------------------------+----------------+--------------------------------------+--------+---------+
|           NAME            | STORAGE DRIVER |                 UUID                 | STATE  | VOLUMES |
+---------------------------+----------------+--------------------------------------+--------+---------+
| backend1 | ontap-nas      | 207ee0d5-6990-4d83-a38b-84397605b82f | online |       2 |
+---------------------------+----------------+--------------------------------------+--------+---------+

real    0m39.467s
user    0m0.512s
sys     0m0.090s

Pod with PVC pvc-2dda7ba5-d582-4ee6-b73d-f3d5723e5f66 will not starting. Error: time-out waiting volume.

**Comment by clintonk** [comment]
Thanks, @anvpetrov.  This is currently a known issue, as all operations including read APIs share a common lock.  We aim to improve the lock granularity in the future, at a minimum to allow for reading state at the same time as provisioning volumes.  At this time I can't say when that work might be scheduled.

**Comment by gnarl** [comment]
The team was able to fix this issue by returning the correct error to Kubernetes. The issue was fixed with [commit 2fa392f](https://github.com/NetApp/trident/commit/2fa392f516d3f2a8a4cd8433e1d3472fc1859a00) and is included in the Trident v21.10 release.
