### ISSUE TITLE
Backend remaining deleting

### ISSUE THREAD

**Issue by sjlee-tech** [NetApp/trident#591]
After removing the storage fas8200 used as the k8s environment,
Migration was performed using server-side data replication to fas8300.
then, remove FAS8200 and,  only use FAS8300

Backend state that was used in the existing remains the "deleting" is shown.
There is no svm or lif (fas8200) left in the backend setting in the current "deleting" state.
What should I do to resolve this situation?

### delete pvc
$ k -n bee-live delete pvc san-master-nfs-pvc 
 
# check pvc and pv deleted
$ k -n bee-live get pvc san-master-nfs-pvc 
$ k get pv pvc-22226658-ff64-4759-a959-679996fea073

Delete Storageclass
 
$ k delete sc bee-blk-nonretain
$ k delete sc bee-blk-nonretain-economy
$ k delete sc bee-fs-nonretain
 
# check (return nothing)
$ k get sc | grep -v -e sc-netapp8300 -e ceph
# Delete backend
 
bee.admin@LGEMSBEEP01P:~/wwjung/trident/trident-installer$ ./tridentctl -n trident delete backend sc-bee-san
bee.admin@LGEMSBEEP01P:~/wwjung/trident/trident-installer$ ./tridentctl -n trident delete backend sc-bee-san-economy
bee.admin@LGEMSBEEP01P:~/wwjung/trident/trident-installer$ ./tridentctl -n trident delete backend sc-bee-nas
 
-----------------------------

bee.admin@LGEMSBEEP01P:~/wwjung/trident/trident-installer$ ./tridentctl -n trident get backend

LGECTO_Bee::> vol show
Vserver   Volume                                            Aggregate    State      Type       Size  Available Used%
--------- ------------                                      ------------ ---------- ---- ---------- ---------- -----

LGECTO_Bee trident_pvc_803157ca_376d_46c7_ab88_c661d5edd9c8 Node2_Bee    online     RW      500.1GB    242.7GB   51% ==> Appears to be created by kubernetes, but no PV. Asked the storage manager to delete it

$ ./tridentctl -n trident get backend sc-bee-san
+------------+----------------+--------------------------------------+----------+---------+
| NAME | STORAGE DRIVER | UUID | STATE | VOLUMES |
+------------+----------------+--------------------------------------+----------+---------+
| sc-bee-san | ontap-san | 3e9070bd-2c92-40b0-81ef-cb3a3e88cb1d | deleting | 1 |
+------------+----------------+--------------------------------------+----------+---------+

bee.admin@EMSBEEP01P:~/wwjung/trident/trident-installer$ ./tridentctl -n trident delete volume pvc-803157ca-376d-46c7-ab88-c661d5edd9c8
Error: could not delete volume pvc-803157ca-376d-46c7-ab88-c661d5edd9c8: error checking for existing volume: Post "https://xx.xxx.xx.xxx/servlets/netapp.servlets.admin.XMLrequest_filer": dial tcp xx.xxx.xx.xxx:443: connect: no route to host (400 Bad Request)

$ ./tridentctl version -n trident
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 20.10.0 | 20.10.0 |
+----------------+----------------+
$ ./tridentctl get backends -n trident
+-------------------------------+-------------------+--------------------------------------+----------+---------+
| NAME | STORAGE DRIVER | UUID | STATE | VOLUMES |
+-------------------------------+-------------------+--------------------------------------+----------+---------+
| sc-netapp8300-bee-san-economy | ontap-san-economy | 2f391ae1-6ab0-491a-afcd-64bd5db34dd7 | online | 123 |
| sc-netapp8300-bee-nas | ontap-nas | 70bc7af4-5fb0-40d0-ab1f-02fbc558fe55 | online | 1 |

**Comment by balaramesh** [comment]
Hello @sjlee-tech

Can you confirm that you have moved the data to the FAS8300 cluster, and that the volumes are now present and accessible? From the output you have shared it looks like that is the case

To delete the old FAS8200 backend (`sc-bee-san`), you will first need to delete the volume that is present on that backend. `tridentctl get backend sc-bee-san -o yaml` will list the name of the volume that is present. Since this volume is probably pointing to a volume that doesn't exist anymore (the migration has already been performed), you should be able to go ahead and delete it by either 1. deleting the associated PVC or 2. deleting the volume with `tridentctl` (`tridentctl delete volume`). Once the volume is deleted, the backend can also be deleted (`tridentctl delete backend`)
