### ISSUE TITLE
unable to determine if TridentBackendConfig was not able to bound to a TridentBackend

### ISSUE THREAD

**Issue by Cajga** [NetApp/trident#595]
**Describe the bug**
We are using ArgoCD to bootstrap our K8s clusters. ArgoCD has the possibility to write custom health checks for CRDs. When a resource has a health check, it will be marked as "Healthy" only in case the health check passes. The check can have two more statuses: Progressing and Degraded.

We have created two custom health checks for trident and would like to contribute them back to the project ([PR](https://github.com/argoproj/argo-cd/pull/6552)):
* trident.netapp.io/TridentOrchestrator
* trident.netapp.io/TridentBackendConfig

The first one is to verify if the trident operator was able to install trident properly. Based on the official [documentation](https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/deploying/operator-deploy.html#observing-the-status-of-the-operator) the pseudo code (which seems to be fine) is something like:
```
if the TridentOrchestrator CRD's status.status equals "Installed" then the CRD is Healthy.
if the status.status == "Failed" or "Error" then it is Degraded
else it is Progressing
```

The problem is with the TridentBackendConfig resource check. Based on the [documentation](https://netapp-trident.readthedocs.io/en/stable-v21.04/kubernetes/operations/tasks/managing-backends/tbc.html#step-3-verify-the-status-of-the-tridentbackendconfig-cr) the resource can have multiple "Phases". Based on this our pseudo code would be somthing like:
```
if the TridentBackendConfig CRD's status.phase equals "Bound" then the resource is Healthy.
if the status.phase equals "Lost" or "Unknown" then it is Degraded
else it is Progressing
```

Unfortunately, when we wipe out trident from the cluster and forget to manually delete the TridentBackend and than we try to recreate the CRD we end up with the following status of TridentBackendConfig:
```yaml
status:
  backendInfo:
    backendName: ''
    backendUUID: ''
  deletionPolicy: retain
  lastOperationStatus: Failed
  message: 'Failed to create backend: backend tbc-ontap-nas already exists'
  phase: ''
```

This means that the CRD is still in the "Unbound" phase and it stays there forever but at the same time, based on the message, we know it is failed to bound with a backend.

Would there be a way to determine such situation reliably? Would it be possible to switch the status to Unknown in such situation?

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: v21.04
- Trident installation flags used: Used the trident operator with default installation
- Container runtime: AWS EKS (K8s version string: v1.20.4-eks-6b7464) on AWS Outpost
- Kubernetes version: v1.20.4-eks-6b7464
- Kubernetes orchestrator: AWS EKS
- Kubernetes enabled feature gates: ?
- OS: AWS K8s optimized AMI
- NetApp backend types: ONTAP
- Other:

**To Reproduce**
Try to wipe out and then reinstall trident without deleting the TridentBackend created at the first install

**Expected behavior**
Be able to reliably determine if the TridentBackendConfig was unable to bound to a TridentBackend based on it's CRD status.

**Comment by ntap-arorar** [comment]
@Cajga 

The phase represents the relation between a TridentBackendConfig CR and the TridentBackend, If there is no TridentBackend CR then TridentBackendConfig CR is not bound to any backend, hence the phase unbound (`''`).

What you do need to look at (and is different than the TridentOrchestrator implementation) is the `lastOperationStatus` field, which is more representative of the status of the operation a user or a system is trying to perform, 'Failed', 'Success'.

So, you are looking at something like:
```
if the TridentBackendConfig CRD's status.lastOperationStatus equals "Success" then the resource is Healthy.
if the status.lastOperationStatus equals "Failed" then it is Degraded
else it is Progressing
```

**Comment by Cajga** [comment]
Hi @ntap-arorar,

Thanks for the feedback. I am happy to see your proposed solution as I ended up with a very similar approach and my PR to Argo CD is based on this.
The only difference is that I included the Phase into the healthy state like:
`if the TridentBackendConfig CRD's status.lastOperationStatus equals "Success" AND the status.phase equals "Bound"  then the resource is Healthy.`

I somehow feel that we should say that the installation/configuration is "good" when the TridentBackendConfig is bound to a TridentBackend. Does this make sense?

**Comment by ntap-arorar** [comment]
@Cajga,

You can include `phase` to make a judgement if a backend configuration is healthy or not. Please ensure to handle the following scenarios:
1. When `phase` is `Unknown` or `Lost`, the `lastOperationStatus` automatically changes to `Failed`.  So I think your above statement is in line with this case and would flag it Unhealthy.
2. When the `phase` is `Unbound`, then your backend may be in a progressing or unhealthy state depending on how you handle it.
3. For deletion, if you have `deletionPolicy: retain` then you have nothing to worry about as there will not be any TridentBackendConfig for your backend, so I think your backend should be notified as healthy. 
4. For deletion, if you have `deletionPolicy: delete`, then your above statement may flag it as unhealthy if the backend is bound to a PVC or has a snapshot and cannot be deleted immediately which would change the `phase` to `deleting`. In my opinion, this is not an unhealthy state but you can choose to call it unhealthy depending on your automation need.

**Comment by Cajga** [comment]
Thanks a lot for the feedback. From my point of view, we got enough information in this ticket to be able to judge the state based on the `phase` and `lastOperationStatus`.  I am closing this.
