### ISSUE TITLE
SolidFire VAGs - change "No" to "Yes" (required) in SF config table

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#60]
The table under https://github.com/NetApp/trident#solidfire-configurations says SolidFire Access Groups aren't required, but earlier in README it says VAGs must be created **before** Trident installation. This seems inconsistent.

**Comment by kangarlou** [comment]
The creation of the Access Group is required but specifying the Access Group ID in the backend config JSON is not. If you don't specify an Access Group ID in the backend config, Trident assumes you're using Access Group `trident` and it automatically discovers the ID for that Access Group.
