### ISSUE TITLE
Set specific volumes in psp

### ISSUE THREAD

**Issue by rjbrown57** [NetApp/trident#606]
https://github.com/NetApp/trident/blob/94e34e8f6db39386ef2db4dd11f1787dce172fa9/helm/trident-operator/templates/podsecuritypolicy.yaml#L18

Could this be more specific? It would be best to follow least privilege here.

**Comment by natke889** [comment]
Join to the question.
I found two psp that need to get the least privilege

tridentoperatorpods     false               RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
tridentpods             true    SYS_ADMIN   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
