### ISSUE TITLE
Discrepancy between RNs/Code and Docs wrt E/EF-Series driver

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#609]
According to the [release notes v21.07](https://github.com/NetApp/trident/releases/tag/v21.07.0), E-Series driver has been [disabled](https://github.com/NetApp/trident/commit/d20d1fb62d097cf10a6d3b92e6c711e524c0231d).

But the Trident documentation v21.07 shows E/EF-Series as [supported](https://netapp-trident.readthedocs.io/en/stable-v21.07/support/requirements.html)

**Comment by balaramesh** [comment]
@scaleoutsean the `eseries-iscsi` driver has been disabled with v21.07. The E/EF-Series section will be removed from the docs

**Comment by gnarl** [comment]
This was fixed with [commit 6186bee ](https://github.com/NetApp/trident/commit/6186bee1369fc826a6220c7354aeb8c893447180).
