### ISSUE TITLE
Can we use same backend.json in 2 kubernetes cluster

### ISSUE THREAD

**Issue by bhuwan1009** [NetApp/trident#615]
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by gnarl** [comment]
Hi @bhuwan1009,

You can use the same Trident backend configuration in two Kubernetes clusters. This will basically be a shared storage pool where each Trident instance is only aware of the volumes that it provisions.

**Comment by bhuwan1009** [comment]
Hi @gnarl

When i am trying to create backend from the same json file on new cluster, i am getting below error

# ./tridentctl -n trident create backend -f backend.json -d
Operating mode = tunnel, Trident pod = trident-csi-bb64c6cb4-7m9fh, Namespace = trident, CLI = oc
Invoking tunneled command: oc exec trident-csi-bb64c6cb4-7m9fh -n trident -c trident-main -- tridentctl --debug create backend --base64 eyJkYXRhTElGIjoiMTAuNS43NS4xMTUiLCJtYW5hZ2VtZW50TElGIjoiMTAuMjQxLjMuMTMiLCJwYXNzd29yZCI6IkFpcnRlbEAxMjMiLCJzdG9yYWdlRHJpdmVyTmFtZSI6Im9udGFwLW5hcy1lY29ub215Iiwic3ZtIjoiVFJJREVOVF9TVk0iLCJ1c2VybmFtZSI6InRyaWRlbnRfdXNlciIsInZlcnNpb24iOjF9
Operating mode = direct, Server = 127.0.0.1:8000, Autosuport server = 127.0.0.1:8003
Trident URL: http://127.0.0.1:8000/trident/v1
--------------------------------------------------------------------------------
Request Method: POST
Request URL: http://127.0.0.1:8000/trident/v1/backend
Request headers: map[Content-Type:[application/json]]
Request body: {"dataLIF":"10.5.75.115","managementLIF":"10.241.3.13","password":"XXXXXX","storageDriverName":"ontap-nas-economy","svm":"TRIDENT_SVM","username":"trident_user","version":1}
................................................................................
Error: Post "http://127.0.0.1:8000/trident/v1/backend": EOF
command terminated with exit code 1


In the logs :-

time="2021-08-06T14:01:22Z" level=warning msg="Cannot terminate an uninitialized backend." backend=ontapnaseco_10.5.75.115 backendUUID=c0c57f1d-23de-4994-b776-90dff9431068 driver=ontap-nas-economy requestID=892ad3e9-0c79-4cd3-b5a4-35ccb99a46b3 requestSource=REST state=failed
time="2021-08-06T14:01:22Z" level=error msg="problem initializing storage driver 'ontap-nas-economy': error initializing ontap-nas-economy driver: could not create Data ONTAP API client: error reading SVM details: Post \"https://10.241.3.13/servlets/netapp.servlets.admin.XMLrequest_filer\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" backend=ontapnaseco_10.5.75.115 handler=AddBackend requestID=892ad3e9-0c79-4cd3-b5a4-35ccb99a46b3 requestSource=REST

Do i need to create backend again if i have to use same on the other trident instance.

**Comment by gnarl** [comment]
@bhuwan1009,

From the error message it doesn't look like the ONTAP management LIF is reachable from that K8S cluster.

**Comment by balaramesh** [comment]
@gnarl is right. You should confirm if the management LIF (10.241.3.13) is reachable from your Kubernetes cluster

**Comment by bhuwan1009** [comment]
@gnarl @balaramesh 

I am able to reach it . Please find output of telnet and curl

telnet 10.241.3.13 443
Trying 10.241.3.13...
Connected to 10.241.3.13.
Escape character is '^]'.
^]
telnet> q
Connection closed.
[root@n4vl-pa-ansible01 trident-installer]# curl -kv https://10.241.3.13
* About to connect() to 10.241.3.13 port 443 (#0)
*   Trying 10.241.3.13...
* Connected to 10.241.3.13 (10.241.3.13) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
*       subject: C=US,CN=N2DC-NTP03-CLU01
*       start date: Nov 23 13:46:10 2020 GMT
*       expire date: Nov 23 13:46:10 2021 GMT
*       common name: N2DC-NTP03-CLU01
*       issuer: C=US,CN=N2DC-NTP03-CLU01
> GET / HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 10.241.3.13
> Accept: */*
>
< HTTP/1.1 303 See Other
< Date: Fri, 06 Aug 2021 15:44:45 GMT
< Server: Apache
< X-Content-Type-Options: nosniff
< Cache-Control: no-cache, no-store, must-revalidate
< Pragma: no-cache
< Expires: 0
< X-Frame-Options: SAMEORIGIN
< Location: https://10.241.3.13/sysmgr/v4/
< Content-Length: 237
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>303 See Other</title>
</head><body>
<h1>See Other</h1>
<p>The answer to your request is located <a href="https://10.241.3.13/sysmgr/v4/">here</a>.</p>
</body></html>
* Connection #0 to host 10.241.3.13 left intact

**Comment by balaramesh** [comment]
Was this from a node on the Kubernetes cluster or a bastion host?

**Comment by gnarl** [comment]
Hi @bhuwan1009,

Were you able to resolve your connectivity issue?

**Comment by gnarl** [comment]
Closing this issue as we haven't received a response from @bhuwan1009. If you are still experiencing this issue it is suggested that you contact NetApp support.
