### ISSUE TITLE
Any installation steps for VMware Tanzu? Many other tools already start support VMware Tanzu!

### ISSUE THREAD

**Issue by calvinwonghk** [NetApp/trident#621]
**Describe the solution you'd like**
There is no instruction for how to get this CSI driver to install on VMware Tanzu! 

**Describe alternatives you've considered**
VVOL may be a option but looks like CSI drivers native integration is the best.

**Additional context**
I have tried to search around on internet for NetApp Trident + VMware Tanzu, there is no such info yet!

**Comment by balaramesh** [comment]
Hello @calvinwonghk 

The installation instructions for Trident are available [here](https://netapp-trident.readthedocs.io/en/latest/kubernetes/deploying/deploying.html). You can choose b/w installing Trident using `tridentctl`, the operator, or the Helm chart. The installation methods are agnostic of the distribution being used. There are only the following caveats to be aware of for Tanzu:

1. If using NFS, you must enable mount propagation is enabled. Here's the [KB article](https://kb.vmware.com/s/article/79424)
2. Tanzu must allow privileged containers to spin up. Depending on the Tanzu flavor you are using, this can be enabled when the cluster is spun up.

**Comment by gnarl** [comment]
Closing this issue as @balaramesh was able to provide a suitable explanation.

**Comment by viju2008** [comment]
Dear Sir

Request that issue is opened as we tried but we are not able to install on tanzu
