### ISSUE TITLE
make ontap go client external available

### ISSUE THREAD

**Issue by FalcoSuessgott** [NetApp/trident#623]
**Describe the solution you'd like**
Hi, any chance you externalize the generated [ontap-go-client](https://github.com/NetApp/trident/tree/master/storage_drivers/ontap/api/rest) in an extra repository? go behaves differently if the major version is `< v1` (currently its `v21`) you would have to change the go mod import path to `github.com/netapp/trident/v21` in order to make it importable.

Ref.:
* https://blog.golang.org/v2-go-modules
* https://donatstudios.com/Go-v2-Modules

We would love to work with ONTAP via REST and go and I think many other as well. 

Appreciate any feedback :)

**Comment by gnarl** [comment]
Hi @FalcoSuessgott,

Thanks for your interest but a generalized ontap-go-client isn't something that the Trident team can support as a NetApp solution. I suggest contacting your account team to make a request for NetApp to create and support a go client for all ONTAP REST APIs.

**Comment by ish-xyz** [comment]
This would have been useful...
