### ISSUE TITLE
Restore from snapshot failed - aggregate not found

### ISSUE THREAD

**Issue by aglitke** [NetApp/trident#625]
**Describe the bug**
We have some long-lived PVCs (around 6 months old) that we frequently clone to new PVCs using a workflow that: creates a snapshot, restores the snapshot to a new PVC, and deletes the snapshot.  Recently the restore operation started failing with a message such as the following:

failed to create cloned volume pvc-93f73e3a-7a7a-4ff3-9eb1-2ddd44e8c432 on backend ontapnas_10.46.29.80: error creating clone: API status: failed, Reason: Aggregate aggr2_900_b not found. Reason: entry doesn't exist. , Code: 14420

Newly created PVCs are able to be cloned successfully using this procedure.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 21.07.1
- Trident installation flags used: -n trident
- Container runtime: cri-o://1.21.2-5.rhaos4.8.gitb27d974.el8
- Kubernetes version: v1.21.1+051ac4f
- Kubernetes orchestrator: OpenShift 4.8.2
- Kubernetes enabled feature gates: 
- OS: Red Hat Enterprise Linux CoreOS 48.84.202107202156-0 (Ootpa)
- NetApp backend types: Ontap NAS / Ontap SAN
- Other:

**To Reproduce**
- Create VolumeSnapshot using old PVC
- Create PVC using the snapshot as the DataSource
- New PVC remains pending

**Expected behavior**
The new PVC should be bound and contain the contents of the snapshot

**Additional context**

**Comment by gnarl** [comment]
Hi @aglitke,

Can you confirm that aggregate aggr2_900_b is still assigned to the SVM? If it was unassigned then that would explain the error message you are seeing.

**Comment by balaramesh** [comment]
@aglitke can you share the output of `tridentctl get backend -o yaml <backend-name>`? It looks like the aggregate was unassigned from the SVM that is being used for the Trident backend

**Comment by aglitke** [comment]
That looks to be the case.  It seems we have only one aggregate and it is different.  I will close this issue and I really appreciate your responsiveness!
