### ISSUE TITLE
trident installer failing with no matches for /, Kind=ClusterRoleBinding

### ISSUE THREAD

**Issue by rushins** [NetApp/trident#63]
Hello 

i have K8S 1.7.3 and trident v17.07.0. 

while running install had error with no matches for /, Kind=ClusterRoleBinding

also the installer is looking openshift but not K8S.

./install_trident.sh -n trident
Installer assumes you have deployed OpenShift.
You are running in namespace default.
Trident will be deployed in namespace default.
For maximum security, we recommend running Trident in its own namespace: ./install_trident.sh -n trident
unable to recognize "/Users/i811144/rushi/devops/kubernetes/sapinternalprojects/saplama-lvm/virtual-colo-cluster/storageclass/trident-installer/trident-clusterrolebindings-openshift.yaml": no matches for /, Kind=ClusterRoleBinding
unable to recognize "/Users/i811144/rushi/devops/kubernetes/sapinternalprojects/saplama-lvm/virtual-colo-cluster/storageclass/trident-installer/trident-clusterrolebindings-openshift.yaml": no matches for /, Kind=ClusterRoleBinding

can someone give me a clue or solution

**Comment by adkerr** [comment]
What OS are you running on? Also, what distribution of kubernetes are you using (openshift, kubeadm, minishift, etc)?
