### ISSUE TITLE
Issue while creating backend 

### ISSUE THREAD

**Issue by bhuwan1009** [NetApp/trident#630]
Hi

I am facing issue while creating the backend

./tridentctl -n trident create backend -f backend.json -d
Operating mode = tunnel, Trident pod = trident-csi-bb64c6cb4-hbvvc, Namespace = trident, CLI = oc
Invoking tunneled command: oc exec trident-csi-bb64c6cb4-hbvvc -n trident -c trident-main -- tridentctl --debug create backend --base64 XXXXXXXXXXXXX
Operating mode = direct, Server = 127.0.0.1:8000, Autosuport server = 127.0.0.1:8003
Trident URL: http://127.0.0.1:8000/trident/v1
--------------------------------------------------------------------------------
Request Method: POST
Request URL: http://127.0.0.1:8000/trident/v1/backend
Request headers: map[Content-Type:[application/json]]
Request body: {"backendName":"airtel_works_ontap_nas_economy","dataLIF":"”10.5.75.125”","managementLIF":"10.241.3.51","password":"netapp@12345","storageDriverName":"ontap-nas-economy","svm":"Trident_NTP05_SVM","username":"trident_user","version":1}
................................................................................
Error: could not create backend: problem initializing storage driver 'ontap-nas-economy': error validating ontap-nas-economy driver: driver validation failed: data LIF validation failed: lookup ”10.5.75.125”: no such host (400 Bad Request)
Response status: 400 Bad Request
Response headers: map[Content-Length:[248] Content-Type:[application/json; charset=UTF-8] Date:[Tue, 24 Aug 2021 11:28:54 GMT]]
Response body: {"backend":"airtel_works_ontap_nas_economy","error":"problem initializing storage driver 'ontap-nas-economy': error validating ontap-nas-economy driver: driver validation failed: data LIF validation failed: lookup ”10.5.75.125”: no such host"}

================================================================================
command terminated with exit code 1

**Comment by gnarl** [comment]
Hi @bhuwan1009,

From the error message Trident is unable to reach the data LIF 10.5.75.125 and the storage driver for that backend is unable to start. You should troubleshoot why that IP address is not reachable from the Kubernetes node where the Trident controller is running.

**Comment by bhuwan1009** [comment]
We were able to ping, and do telnet on this server for the port 111,2049,635,4045 and 4046.
Is there any other port that we need to check for this.

**Comment by gnarl** [comment]
Closing this issue as we have not heard back from @bhuwan1009.
