### ISSUE TITLE
Default ImageRegistry is "quay.io or k8s.gcr.io"  but trident image is on docker hub.

### ISSUE THREAD

**Issue by zakkg3** [NetApp/trident#640]
so then we get...

```
quay.io/netapp/trident: unauthorized: access to the requested resource is not authorized
```

```
ErrImagePull, Message: rpc error: code = Unknown desc = Error reading manifest 21.01 in quay.io/netapp/trident-autosupport: unauthorized: access to the requested resource is not authorized trident-main: Reason: ErrImagePull, Message: rpc error: code = Unknown desc = Error reading manifest 21.07.1 in quay.io/netapp/trident: unauthorized: access to the requested resource is not authorized]
```

- Trident version: [21.07.1]
- RuntimeName:  cri-o
- RuntimeVersion:  1.21.2

worked arround by manually (using clush) pulled image from docker and because pull policy is if its not present then it worked out.

did i make a mistake or the setup is broken?

**Comment by wonderland** [comment]
Hi,

were is that default coming from in your environment? Trident uses standard CSI sidecar containers in addition to Trident itself. Those sidecars live on quay.io or k8s.gcr.io (depending on the K8s version), but Trident images themselves have always been on Docker hub. You can override the registry for Trident as well as the sidecars, if you prefer to use an internal registry.

What deployment method did you choose? (Helm, Operator, tridentctl)

**Comment by zakkg3** [comment]
we used tridentctl for the install. I reached the docker hub limit thats why ended up trying to fetch from quay. worked arround by login into docker hub.
