### ISSUE TITLE
Trident CSI Driver for Iterative Testing

### ISSUE THREAD

**Issue by juveras** [NetApp/trident#648]
Further to your request to summary the “impact/issue” with the current way INODES per VOLUME with ANF works, I will outline the scenario below and hopefully that outlines why the current method, in a CI/CD world where teams are doing to do 100 tests a day, the idea of us having to call Azure each time to adjust the INODEs simply doesn’t work.

The Situation:
-	We use Azure AKS along with Azure NetApp Files (ANF) and the accompanying Trident CSI driver for AKS.  This combination allows us dynamically create, modify and delete Volumes out of the pre-purchased Capacity Pool in ANF from a programmatic way – i.e this is all orchestrated via pipelines that have statically defined K8s manifests that do what we want.
-	In production, the volumes that ‘run’ are persistent and as such, we don’t have such a problem with having to call Azure 1 time once they are created and then the inodes are tuned to the requirement.  
-	In testing, integration and development environments, where we are required to spin up that same 10TB+ volume from scratch, fill it up to 99%, observe and then restart, this idea that each iteration, in order to use fully the purchased capacity to our needs, we have to call and open an Azure ticket becomes untenable over time.
-	While there “quick solution” is to say “just clean out the volumes” that is a lot of time spent deleting data, when dropping the volume, in a dynamic manner as is the nature of K8s and the CSI plugins, is to be instant (or rather very close) and thus, from an integration/testing and verification standpoint, this adds additional hours to cycles again, work around this or having to call Azure – you can imagine when we get up to 50TB and greater, it could be days to clean up those file (we use lots and lots of little files, with deep tree depth, so it’s a challenge as it is already and such a procedure creates a very large “cycle delay” in all CI/CD based iterative loops.

The solution we would like to see is a INODE “settings” by default per CAP Pool, so that any volumes that are created out of a given CAP POOL that are greater than 8TB – are set as we like.  A better solution would be to provide a tunable / automated quota system per CAP Pool / or ANF account level itself.

**Comment by wonderland** [comment]
It seems this has some "history" that I'm unaware of. Apologies if this has been asked in other channels already.

I'd like to understand more of the use case. Is the generation of the data (e.g. writing 10+TB of small files) part of the test? Or does the test focus on the "observe" part you described and data generation is just a necessary prerequisite?

Just trying to figure out if snapshots and/or clones might help you short term. Reverting volumes back to a well-defined state instead of deleting the volume content or creating an entirely new volume (that then has the default maxfiles/inodes setting).

**Comment by juveras** [comment]
Hi this was actually sent to me by a customer - after bubbling to our internal support folks they recommended me putting it into GitHub.

What’s my best course of action at this time to bring my customer in?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by wonderland** [comment]
If they are OK with it, this issue should be fine. 

Allowing the automatic maxfiles setting outside of a support request ultimately is a decision Azure needs to make (as Azure NetApp Files is a native Azure product). Trident cannot implement this if ANF doesn't have an automated way to do this. Depending on the use case, snapshots or clones might help though.

**Comment by juveras** [comment]
Sorry I'm not sure I undrestand. Would you like me to set up a call or an email thread?


_______________________________________________________
Justin Veras, MBA
Sr. Customer Success Account Manager | U.S.
Office: +1 (860) 606-7382
***@***.******@***.***>

Premier Support: 800-936-3100/1-425-454-7946
https://ServicesHub.Microsoft.com<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fserviceshub.microsoft.com%2F&data=02%7C01%7CJustin.Veras%40microsoft.com%7C6822fa7ad61e4e087cc908d85ef2cdd5%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637363744246750722&sdata=LwOQD3g8XntTbcRjoX1gI6v2M1yaCtqiN3rQex3iwBs%3D&reserved=0>
[Microsoft Logo]

[Microsoft Global ***@***.***[https://images.credly.com/images/5c96fc59-1174-4dd0-a5c1-56772e38d8c7/microsoft365-fundamentals-600x600.png]

**Comment by gnarl** [comment]
Hi @juveras,

The issue you are raising appears to be with ANF and should be opened with a support ticket with Microsoft that can then be worked on in cooperation with NetApp support.
