### ISSUE TITLE
Create helm repo in order to facilitate installation and upgrades using GitOps

### ISSUE THREAD

**Issue by snorwin** [NetApp/trident#649]
**Describe the solution you'd like**
In order to directly use the helm chart in a GitOps setup a helm repo is needed. Cloud you please create a GitHub Action (https://github.com/helm/chart-releaser-action) that provides automatically a helm repo using GitHub pages. If you consider this as an option, I'm willing to create a PR.

**Describe alternatives you've considered**
Install and upgrade the trident-operator helm chart always manually 😞

**Comment by balaramesh** [comment]
Hello @snorwin! Thank you for opening this issue.

Trident's Helm chart is hosted on artifactory here: https://artifacthub.io/packages/helm/netapp-trident/trident-operator

You can add the Trident Helm repo using `https://netapp.github.io/trident-helm-chart`. I believe this will solve your problem!

**Comment by snorwin** [comment]
Perfect that helps. Thanks a lot :)

**Comment by sennerholm** [comment]
Could that be added to the documentation page, for example on: 

https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/deploying/operator-deploy.html so it's easier to find?
