### ISSUE TITLE
Trident doesn't recover from failure if Trident pod is deleted while it was working on a PVC

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#65]
Trident doesn't recover if trident pod is deleted while trident is working on PVCs

**Env**
Trident: 17.10
OpenShift Enterprise: 3.6
Docker : 1.12.6

# **Setup:**
multiple ontap-nas backends including ontap-nas-economy
multiple storage classes
1) media type ssd and hdd
2) required storage with aggr
3) backendType ontap-nas-economy

# **Steps to recreate:**
1) run a script to create multiple PVCs in loop for type with required storage 
2) while trident is working on PVCs and creating PVs : delete the trident pod
3) trident pod terminates and a new trident port is started
4) Trident pod fails to start 

# **Workaround:**
1) delete txn record from etcd database
 
#etcdctl --peers 127.0.0.1:8001  rm /trident/v1/txn/trident-pvc-sil/ # etcdctl --peers 127.0.0.1:8001  rm /trident/v1/txn/trident-pvc-sil
ver-7-305a
c
PrevNode.Value: {"Config":{"version":"1","name":"trident-pvc-silver-7-305ac","internalName":"","size":"1073741824","protocol":"","storageCla
ss":"silver","accessMode":"ReadWriteOnce","accessInformation":{},"blockSize":"","fileSystem":"ext4"},"Op":"addVolume"}

2) delete trident pod so that a new instance starts
3) trident starts working normally

# **Logs:**
time="2017-10-25T12:22:07Z" level=info msg="Running Trident storage orchestrator." build_time="Wed Oct 18 19:55:39 UTC 2017" version=17.10.0
time="2017-10-25T12:22:07Z" level=info msg="Kubernetes frontend determined the container orchestrator version." gitVersion="v1.6.1+5115d708d7" version=1.6
time="2017-10-25T12:22:07Z" level=info msg="Added frontend." name=kubernetes
time="2017-10-25T12:22:07Z" level=info msg="Starting REST interface on localhost:8000"
time="2017-10-25T12:22:07Z" level=warning msg="Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005"
time="2017-10-25T12:22:08Z" level=info msg="Newly added backend satisfies no storage classes." backend="ontapnas_10.165.245.131"
time="2017-10-25T12:22:08Z" level=info msg="Added an existing backend." backend="ontapnas_10.165.245.131" handler=Bootstrap
time="2017-10-25T12:22:08Z" level=warning msg="Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005"
time="2017-10-25T12:22:08Z" level=info msg="Newly added backend satisfies no storage classes." backend="ontapnas_10.165.245.138"
time="2017-10-25T12:22:08Z" level=info msg="Added an existing backend." backend="ontapnas_10.165.245.138" handler=Bootstrap
time="2017-10-25T12:22:08Z" level=warning msg="Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005"
time="2017-10-25T12:22:09Z" level=info msg="Newly added backend satisfies no storage classes." backend="ontapnas_10.165.245.222"
time="2017-10-25T12:22:09Z" level=info msg="Added an existing backend." backend="ontapnas_10.165.245.222" handler=Bootstrap
time="2017-10-25T12:22:09Z" level=warning msg="Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005"
time="2017-10-25T12:22:10Z" level=info msg="Newly added backend satisfies no storage classes." backend="ontapnas_10.165.245.223"
time="2017-10-25T12:22:10Z" level=info msg="Added an existing backend." backend="ontapnas_10.165.245.223" handler=Bootstrap
time="2017-10-25T12:22:10Z" level=warning msg="Could not determine controller serial numbers. API status: failed, Reason: Unable to find API: system-node-get-iter, Code: 13005"
time="2017-10-25T12:22:10Z" level=info msg="Newly added backend satisfies no storage classes." backend="ontapnaseco_10.165.245.131"
time="2017-10-25T12:22:10Z" level=info msg="Added an existing backend." backend="ontapnaseco_10.165.245.131" handler=Bootstrap
time="2017-10-25T12:22:10Z" level=info msg="Added an existing storage class." handler=Bootstrap storageClass=basic
time="2017-10-25T12:22:10Z" level=info msg="Added an existing storage class." handler=Bootstrap storageClass=bronze
time="2017-10-25T12:22:10Z" level=info msg="Added an existing storage class." handler=Bootstrap storageClass=economy
time="2017-10-25T12:22:10Z" level=info msg="Added an existing storage class." handler=Bootstrap storageClass=gold
time="2017-10-25T12:22:10Z" level=info msg="Added an existing storage class." handler=Bootstrap storageClass=silver
time="2017-10-25T12:22:10Z" level=info msg="Added an existing volume." handler=Bootstrap volume=trident-pvc-silver-1-2f8c4
time="2017-10-25T12:22:10Z" level=info msg="Added an existing volume." handler=Bootstrap volume=trident-pvc-silver-2-2fae2
time="2017-10-25T12:22:10Z" level=info msg="Added an existing volume." handler=Bootstrap volume=trident-pvc-silver-3-2fd02
time="2017-10-25T12:22:10Z" level=info msg="Added an existing volume." handler=Bootstrap volume=trident-pvc-silver-4-2ff2b
time="2017-10-25T12:22:10Z" level=info msg="Added an existing volume." handler=Bootstrap volume=trident-pvc-silver-5-30168
time="2017-10-25T12:22:10Z" level=info msg="Added an existing volume." handler=Bootstrap volume=trident-pvc-silver-6-3038f
time="2017-10-25T12:22:10Z" level=info msg="Processed volume transaction log." op=addVolume size=1073741824 storageClass=silver volume=trident-pvc-silver-7-305ac
time="2017-10-25T12:22:10Z" level=warning msg="Volume already deleted." volume="trident_trident_pvc_silver_7_305ac"
time="2017-10-25T12:22:10Z" level=warning msg="Volume already deleted." volume="trident_trident_pvc_silver_7_305ac"
time="2017-10-25T12:22:11Z" level=warning msg="Volume already deleted." volume="trident_trident_pvc_silver_7_305ac"
time="2017-10-25T12:22:11Z" level=warning msg="Volume already deleted." volume="trident_trident_pvc_silver_7_305ac"
time="2017-10-25T12:22:11Z" level=warning msg="Qtree not found." qtree="trident_trident_pvc_silver_7_305ac"
time="2017-10-25T12:22:11Z" level=error msg="Qtree rename failed. API status: failed, Reason: Failed to rename qtree "" for volume "trident_trident_pvc_silver_7_305ac" on Vserver "LTT210". Reason: dst volume not same as src volume., Code: 22"
time="2017-10-25T12:22:11Z" level=fatal msg="Could not bootstrap from persistent store! Bootstrap might have failed, persistent store might be down, or persistent store may not have any backend, volume, or storage class state: Error attempting to clean up volume trident-pvc-silver-7-305ac from backend ontapnaseco_10.165.245.131:  Volume deletion failed."

**Comment by kangarlou** [comment]
Thanks Kapil. This problem should be limited to the ontap-nas-economy driver. Other drivers should handle pod restarts during volume creation or deletion fine as we made the necessary changes to nDVP such that volume deletion is an idempotent operation. The problem with the ontap-nas-economy driver is that based on the timing of the pod failure, different actions can fail during the cleanup that takes place as part of the bootstrapping: https://github.com/NetApp/netappdvp/blob/master/storage_drivers/ontap_nas_qtree.go#L332:L356.

We should have a patch to address this problem. We also need a test in our CI system to capture this sort of bugs. Thanks again!

**Comment by kapilarora** [comment]
@kangarlou FYI, Our test PVCs are not created for ontap nas economy. 
But we do have a the economy backed configured.
If you look at the transaction in etcd which is causing the problem. it is for storage class silver which uses requiredStorage and is unrelated to ontap nas economy backend.

**Comment by kangarlou** [comment]
The only problematic messages in the bootstrapping log are the following:
`time="2017-10-25T12:22:11Z" level=warning msg="Qtree not found." qtree="trident_trident_pvc_silver_7_305ac"
time="2017-10-25T12:22:11Z" level=error msg="Qtree rename failed. API status: failed, Reason: Failed to rename qtree "" for volume "trident_trident_pvc_silver_7_305ac" on Vserver "LTT210". Reason: dst volume not same as src volume., Code: 22"`

As you see above, pvc_silver_7 is clearly using the ontap-nas-economy driver. Please share the definition for your storage class.

**Comment by kangarlou** [comment]
I can now see what's going on. Even if you're not using the ontap-nas-economy driver, just because such a backend is added to Trident, this driver is involved during the bootstrapping process. This is very similar to https://github.com/NetApp/trident/issues/32. ontap-nas-economy should gracefully handle deletion of volumes that no longer exist (i.e. support idempotency).

**Comment by pjos** [comment]
@kangarlou if still relevant, here is the storage class definition used:

```
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: null
  name: silver
parameters:
  requiredStorage: ontapnas_10.165.245.138:aggr1_SAS_L11225;ontapnas_10.165.245.223:aggr3_SAS_L11112
provisioner: netapp.io/trident
```
