### ISSUE TITLE
outdated image tags in requirements.rst for airgapped installation

### ISSUE THREAD

**Issue by phhutter** [NetApp/trident#650]
Could you please update the tags in your documentation.
They seems to be a bit outdated.

Current container tags which are used in trident 21.07:
https://github.com/NetApp/trident/commit/e405347210feae72a2eb79a52abd8854f63df8b6#diff-5cf530bccef759cce84cc98888d03cefb0b0b6381b4d662372919d9209b75959

Outdated container tags for airgapped installation:
https://github.com/NetApp/trident/blob/4551de78791912277cc9f700ad7c9fe102f5d3d3/docs/support/requirements.rst#container-images-and-corresponding-kubernetes-versions

**Comment by gnarl** [comment]
Hi @phhutter,

We do review these tags before we do a major release. The next release, Trident 21.10, is scheduled to be released at the end of 10/2021.

**Comment by wonderland** [comment]
I think it is a valid enhancement request to update the docs for minor releases as well. If preparing for a Trident deployment -based on the docs - people will transfer incorrect images into their internal registry. 

https://netapp-trident.readthedocs.io/en/stable-v21.07/support/requirements.html#container-images-and-corresponding-kubernetes-versions lists not only the old/outdated 21.7.0 Trident images, it also lists incorrect sidecar tags. Such as csi-provisioner:v2.1.1 for K8s 1.21 whereas Trident actually needs v2.2.2.

The docs are just wrong and it would be great if that could be fixed outside of a major release cycle.

**Comment by clintonk** [comment]
Hi, @phhutter.  One thing you can do that is always correct is run ```tridentctl images```.  That shows the K8s versions supported by that Trident build along with the needed images.
```
$ ./tridentctl images
INFO[0000] Created Kubernetes clients.                   namespace=trident version=v1.20.6
+--------------------+---------------------------------------------------------+
| KUBERNETES VERSION |                     CONTAINER IMAGE                     |
+--------------------+---------------------------------------------------------+
| v1.17.0            | netapp/trident:21.07.1 netapp/trident-autosupport:21.01 |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.2.1              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.2.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0 |
+--------------------+---------------------------------------------------------+
| v1.18.0            | netapp/trident:21.07.1 netapp/trident-autosupport:21.01 |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.2.1              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.2.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0 |
+--------------------+---------------------------------------------------------+
| v1.19.0            | netapp/trident:21.07.1 netapp/trident-autosupport:21.01 |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.2.1              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.2.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v3.0.3           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0 |
+--------------------+---------------------------------------------------------+
| v1.20.0            | netapp/trident:21.07.1 netapp/trident-autosupport:21.01 |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.2.1              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.2.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0 |
+--------------------+---------------------------------------------------------+
| v1.21.0            | netapp/trident:21.07.1 netapp/trident-autosupport:21.01 |
|                    | k8s.gcr.io/sig-storage/csi-provisioner:v2.2.2           |
|                    | k8s.gcr.io/sig-storage/csi-attacher:v3.2.1              |
|                    | k8s.gcr.io/sig-storage/csi-resizer:v1.2.0               |
|                    | k8s.gcr.io/sig-storage/csi-snapshotter:v4.1.1           |
|                    | k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0 |
+--------------------+---------------------------------------------------------+
```

**Comment by wonderland** [comment]
Yes, the "only" thing needed is a process that dumps this into the docs every time a new trident release is made available (major or minor).

**Comment by phhutter** [comment]
> Hi @phhutter,
> 
> We do review these tags before we do a major release. The next release, Trident 21.10, is scheduled to be released at the end of 10/2021.

Could we please keep the documentation updated?
If I'm right, the current released version is 21.10, however  https://netapp-trident.readthedocs.io/en/stable-v21.07/ only shows version 21.07.

**Comment by wonderland** [comment]
The docs have been moved here: https://docs.netapp.com/us-en/trident/index.html
I believe there is work underway to point this out more clearly on the old docs site.

**Comment by juliantap** [comment]
Hi @phhutter , @wonderland  is correct. There is an effort under way to reinforce that the docs have moved. 

Adding @balaramesh as I am unable to assign myself to issues in this repo.  

Thanks!
