### ISSUE TITLE
custom node-selector for csiDeployment117/csiDeployment120

### ISSUE THREAD

**Issue by phhutter** [NetApp/trident#651]
Often you would like to bind infrastructure/core related workload (csiDeployment120YAMLTemplate and csiDeployment117YAMLTemplate) on specific nodes. Therefore it could be useful to have an ability to add node-selectors.
A configuration via helm values.yaml would be preferred.

https://github.com/NetApp/trident/blob/16e84e6826b6591cb33aae9ccdb120918d3c0eae/cli/k8s_client/yaml_factory.go#L666-L668

**Comment by gnarl** [comment]
This issue is resolved with commits [e167c7 ](https://github.com/NetApp/trident/commit/e167c7e92e143e4bb4a8373ff0dc9f41c374cd42) and [c7c167d ](https://github.com/NetApp/trident/commit/c7c167da22657559ae2c330e3aa8ef7150300214). This change will be included with the Trident 22.01 release.
