### ISSUE TITLE
Helm Installation Step

### ISSUE THREAD

**Issue by calvinwonghk** [NetApp/trident#659]
**Describe the solution you'd like**
I tried to install trident via Helm, but it keeps saying "Error: INSTALLATION FAILED: Chart.yaml file is missing.
Referring to other products on the market, they use simple add repo.

e.g.
"helm repo add kasten https://charts.kasten.io/"

that saved the day, would consider using that?

**Describe alternatives you've considered**
Need to use back old school installation method by using installer

**Additional context**
Need more info to troubleshoot the issues !! already using debug but no ideas what need to be done to fix the installation issues

**Comment by darthVikes** [comment]
Can the helm repo install method be added to the documentation?    Is this prefered over downloading the tar and installing that way?

**Comment by dc232** [comment]
> Can the helm repo install method be added to the documentation? Is this prefered over downloading the tar and installing that way?

I prefer it as it means you get the lastest updates without having to do the tar extraction and makes it more CI/CD friendly
