### ISSUE TITLE
Unable to mount volumes for pod "trident-launcher_default(

### ISSUE THREAD

**Issue by rushins** [NetApp/trident#66]
hi 

i get this error while doing install...any clue
Unable to mount volumes for pod "trident-launcher_default(

Normal   Started                3m    kubelet, lvvxc023.sjc.sap.corp  Started container
  Warning  FailedMount            1m    kubelet, lvvxc023.sjc.sap.corp  Unable to mount volumes for pod "trident-launcher_default(d8df877a-c4f6-11e7-bd3f-0050568420b4)": timeout expired waiting for volumes to attach/mount for pod "default"/"trident-launcher". list of unattached/unmounted volumes=[config-volume trident-launcher-token-j1x6s]
  Warning  FailedSync             1m    kubelet, lvvxc023.sjc.sap.corp  Error syncing pod

BR
Rushi

**Comment by adkerr** [comment]
There's a few possibilities of whats going wrong here: there could be a legitimate issue with mounting the volumes from the storage array (have you verified you are able to mount to the host from the array manually?); this could also simply be the mount process being too slow for trident's default timeout (60s). You can adjust this using the `k8s_timeout` option in `trident-installer/launcher-pod.yaml`

Also, what driver backend are you using to deploy trident onto? Which version of trident are you using? And what version/deployment of kubernetes are you using?

**Comment by rushins** [comment]
i checked  and verified my backend.json file user configuration and i have all authroization . as you stated volue, i dont see any volume requested to during setup. Its only storage class which backend.json data needed with management  ip address, data IP addresss, username and password with SVM (storage virtual machine) in NetApp CLuster level access. THe same setup worked for another cluster with different trident release but now i am testing with new trident release which was what failing.

as per your recommedation i have changed timeout from 60 to 300 and ran it again.

No luck its the same error

**Comment by kangarlou** [comment]
I don't think the problem is trident. Most likely you haven't configured your cluster properly. The only "volumes" attached to the launcher are the ConfigMap and Service Account and the latter seems to be failing, which has nothing to do with Trident or NetApp storage.

Please share the output of `tridentctl logs -l all`.

**Comment by rushins** [comment]
i am using mac and tridentctl seems not working for me ...does tridentctl binary is available for mAC too.

**Comment by rushins** [comment]
i get message ./tridentctl : cannot execute binary file error

**Comment by kangarlou** [comment]
`tridentctl` runs only on Linux: https://netapp-trident.readthedocs.io/en/latest/operations/requirements.html#supported-host-operating-systems

**Comment by rushins** [comment]
ok i assume the same before asking you. not sure where the error but i keep getting the same message 

Unable to mount volumes for pod "trident-launcher_default(c04a45a2-c8ca-11e7-bd49-00505692012d)": timeout expired waiting for volumes to attach/mount for pod "default"/"trident-launcher". list of unattached/unmounted volumes=[config-volume trident-launcher-token-rxsz6]

**Comment by adkerr** [comment]
I have compiled a Mac version of tridentctl in the past. Let me see if I can make another modern one and find a way to share it.

Andrew Kerr
Test Automation Engineer
Open EcoSystems

NetApp
919.476.4899 Direct Phone
Andrew.Kerr@netapp.com
________________________________

**Comment by adkerr** [comment]
Here is the darwin (MAC) compiled tridentctl
[tridentctl.gz](https://github.com/NetApp/trident/files/1470925/tridentctl.gz)

**Comment by rushins** [comment]
thanks, Andrew.
it works on mac.
