### ISSUE TITLE
Custom role or no custom role for Trident

### ISSUE THREAD

**Issue by mac-chaffee** [NetApp/trident#663]
**Describe the solution you'd like**
This page recommends creating a custom role for Trident: https://netapp-trident.readthedocs.io/en/stable-v21.07/docker/install/ndvp_ontap_config.html#user-permissions

> Trident does not need full permissions on the ONTAP cluster and should not be used with the cluster-level admin account. Below are the ONTAP CLI comands to create a dedicated user for Trident with specific permissions.

But this page cautions against creating a custom role, instead recommending using an existing role: https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/operations/tasks/backends/ontap/ontap-nas/preparing.html#credential-based-authentication

> Trident requires the credentials to an SVM-scoped/Cluster-scoped admin to communicate with the ONTAP backend. It is recommended to make use of standard, pre-defined roles such as admin or vsadmin. This ensures forward compatibility with future ONTAP releases that may expose feature APIs to be used by future Trident releases. A custom security login role can be created and used with Trident, but is not recommended.

Is one recommendation preferred over the other?

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by balaramesh** [comment]
@mac-chaffee Trident recommends you utilize a pre-defined security login role in your backend definition, for the following reason. ONTAP login roles can change with releases and that can introduce problems with compatibility. Creating a custom security login role may need the addition/removal of command directories, which is difficult to maintain and validate.
The page that talks about a custom login role for Trident is for the Docker Plugin mode. For Kubernetes, I would recommend using the login roles that are pre-defined with ONTAP
