### ISSUE TITLE
Delete a directroy with about 7 million files, slow

### ISSUE THREAD

**Issue by sjlee-tech** [NetApp/trident#664]
Hello everyone

using NetApp FAS8300 , hdd 1,8tb disk with k8s.
using ontap-san-economy

When deleting the binary file after the build test, delete delayed in random pv.
The delete command proceeded at the same time
The delete command was performed on 5 Pods at the same time.
5 PODs in same host server
Each pv has the same data, about 7.7 million files.
rm delay pv is located the volume trident_lun_pool_trident_ZPZHAKNZCT

how to delete : rm -rf ./*

![image](https://user-images.githubusercontent.com/86052364/140023325-7ecd7435-ab88-4cf7-925d-803a5664d9c6.png)

How can I find out why deletion is slow on only one lun at random?
Also, compared to the deletion time in aws gp3, can the slow part be seen as the difference between hdd and ssd?

**Comment by balaramesh** [comment]
@sjlee-tech did you try to delete files from the LUN? `rm -rf ./*` is a command you would run on the volume. I am confirming if you are deleting the contents of the LUN, or deleting the LUN itself.

If it is the former case, then Trident has nothing to do here. The first place to look at for any troubles would be Trident's logs (`tridentctl logs -n trident`)

**Comment by gnarl** [comment]
Closing this issue as there hasn't been a response to the request for additional information.
