### ISSUE TITLE
Adding AWS FSx for ONTAP as supported backend in FAQ

### ISSUE THREAD

**Issue by jsuarezs** [NetApp/trident#665]
**Describe the solution you'd like**
Adding the more incoming question if AWS FSx for ONTAP is Trident supported. Same question and answer like for CVO and CVS.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by gnarl** [comment]
Hi @jsuarezs, you can find information on what Trident supports here https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html.
