### ISSUE TITLE
Problem with creating backend for Trident on Openshift v4

### ISSUE THREAD

**Issue by Anna-LenaSchroeder** [NetApp/trident#667]
**Describe the bug**
The installation of Trident worked fine had no issues, we already can see the created pods.
When we try to create the backends with ontap-nas -  we are facing following message within the trident logs:

```
time="2021-11-02T15:06:46Z" level=warning msg="Cannot terminate an uninitialized backend." backend=storage-name1
 backendUUID=43369699-d635-455c-b2b2-dad7d6280e39 driver=ontap-nas requestID=640061ca-0ef4-4790-b72a-2baf93b55742 requestSource=REST state=failed
time="2021-11-02T15:06:46Z" level=error msg="problem initializing storage driver 'ontap-nas': error initializing ontap-nas driver: could not create Data ONTAP API client: error reading SVM details: Post 
\"https://192.168.xxx.xxx/servlets/netapp.servlets.admin.XMLrequest_filer\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" backend=storage-name1 handler=AddBackend requestID=640051ca-0ef4-4790-b72a-2baf93b55742 requestSource=REST
```

**Environment**
Installation of Trident on a fresh openshift v4.8 Cluster.
VM has networkinterface in  in Storage-Network and granted access to desired NFS-Filer 

- Trident version:  21.07.2
- Trident installation flags used:  -n trident
- Container runtime: ...
- Kubernetes version: v1.21.1+9807387
- Kubernetes orchestrator: OpenShift v4.8.10
- Kubernetes enabled feature gates: -
- OS: Red Hat Enterprise Linux Server release 7.9
- NetApp backend types: ONTAP-NAS
- Other:

**To Reproduce**
1. Clean install of Openshift with Nic towards storage network
2. Install trident with tridentctl into -n trident
3. Create backend from following file:

```
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "192.168.xxx.xxx",
    "dataLIF": "192.168.xxx.xxx",
    "svm": "dehamfsxxx-nfs-dmzxx",
    "storagePrefix": "ocp4_",
    "username": "trident",
    "password": "randompassword"
}
```

**Expected behavior**
Trident creates backends without error.
I am quite new to Trident and maybe I just did something wrong in the backend file, but anyway I would appreciate your help and explanations a lot.

**Comment by gnarl** [comment]
Hi @Anna-LenaSchroeder,

From the error message it doesn't appear that Trident was able to connect to the SVM. You may want to verify that you can login to the SVM from the Kubernetes node running the Trident controller.

**Comment by Anna-LenaSchroeder** [comment]
Hey @gnarl,
just a stupid question, how would I test the login to the SVM?
Sorry I really have no idea about commands plus I just started working with Openshift/Kubernetes and Linux a couple months ago. So still a real newbie.

**Comment by wonderland** [comment]
Trident tries to reach the API endpoint on the management IP of your backend configuration. That runs on port 443. A simple test to validate basic network connectivity could be done via either telnet or nc. If the K8s node can reach the SVM management IP, it should look something like this (replace 192.168.0.10 with your actual IP address):


**Telnet**

telnet 192.168.0.10 443
Trying 192.168.0.10...
Connected to 192.168.0.10.
Escape character is '^]'.
^C
Connection closed by foreign host.


**nc**

nc -z -v  192.168.0.10 443
Connection to 192.168.0.10 443 port [tcp/https] succeeded!

**Comment by Anna-LenaSchroeder** [comment]
@wonderland 
Thank you for the explanation and example! :)

I tried to connect via telnet to the management IP with the specified port and it worked fine. No problem there.

**Comment by gnarl** [comment]
Hi @Anna-LenaSchroeder,

I looked at the error again and it looks like you might have enabled REST in your backend config file. Please update the backend config useREST setting to false or remove the useREST setting. With Trident 21.07.2 useREST is in Tech Preview for the ontap-nas driver. Let me know which version of ONTAP you are using if this works.

**Comment by Anna-LenaSchroeder** [comment]
@gnarl 
thanks for having another look at it.

Unfortunately I don't know which config file you mean. My backend json file doesn't contain such an option.

**Comment by innergy** [comment]
I don't think that was an issue in this case.

What you want to do next is confirm that your worker nodes can talk to the ONTAP API server.

You can do that by interactively exec'ing into a pod that has curl in it and running this command, using the same details you're supplying in your backend config:

`curl -k --user [user] -d "<netapp><system-get-version/></netapp>" https://[mgmt LIF IP]/servlets/netapp.servlets.admin.XMLrequest_filer`

This verifies that your pod network can talk to the ONTAP API server and that the credentials you have are generally working.

**Comment by Anna-LenaSchroeder** [comment]
@innergy 
Thank you very much! 

Turns out not all workers did have access granted to the svms. I only checked the connection from a jumpbox outside the OpenShift cluster before, which of course worked.
