### ISSUE TITLE
OpenShift Bare Metal 4.7.32 NFS PVC fails to mount.

### ISSUE THREAD

**Issue by rmclaughlin-code** [NetApp/trident#668]
**Describe the bug**
OpenShift 4.7.32 Bare Metal Worker Nodes fail to mount NFS PVCs.

**Environment**
OpenShift 4.7.32 with Bare Metal Worker Nodes.

- Trident version: 21.01.0, then upgraded to 21.10.0 and the issue persisted.
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml]
- Container runtime: CRI-O
- Kubernetes version: v1.20.0+bbbc079
- Kubernetes orchestrator: OpenShift 4.7.32
- Kubernetes enabled feature gates: N/A
- OS: Red Hat CoreOS
- NetApp backend types: OnTap NAS and Solidfire
- Other:

**To Reproduce**
On OpenShift cluster install trident, for an unknown amount of time NFS mounts will succeed, then they will fail with the below errors.

`time="2021-11-02T18:21:09Z" level=error msg="exit status 1" requestID=a7d53e60-a9f1-4f9e-ade1-171aee958bb5 requestSource=CSI
time="2021-11-02T18:21:09Z" level=error msg="exit status 1" requestID=a7d53e60-a9f1-4f9e-ade1-171aee958bb5 requestSource=CSI
time="2021-11-03T14:08:26Z" level=error msg="GRPC error: rpc error: code = Internal desc = error mounting NFS volume 10.25.176.110:/gp_6_pvs_pvc_64b1b431_02a2_45cd_8ca7_9708c17ed4ae on mountpoint /var/lib/kubelet/pods/26a6fa11-1f54-4f19-9dd3-c6a6f1f24da0/volumes/kubernetes.io~csi/pvc-64b1b431-02a2-45cd-8ca7-9708c17ed4ae/mount: exit status 32" requestID=0f0ba09b-dae4-4b9d-b6fd-94f3db0468ad requestSource=CSI
time="2021-11-03T14:08:26Z" level=error msg="GRPC error: rpc error: code = Internal desc = error mounting NFS volume 10.25.176.110:/gp_6_pvs_pvc_64b1b431_02a2_45cd_8ca7_9708c17ed4ae on mountpoint /var/lib/kubelet/pods/26a6fa11-1f54-4f19-9dd3-c6a6f1f24da0/volumes/kubernetes.io~csi/pvc-64b1b431-02a2-45cd-8ca7-9708c17ed4ae/mount: exit status 32" requestID=1c77a11c-bb0f-4e2c-a7c7-9778af75251e requestSource=CSI
time="2021-11-03T14:08:27Z" level=error msg="GRPC error: rpc error: code = Internal desc = error mounting NFS volume 10.25.176.110:/gp_6_pvs_pvc_64b1b431_02a2_45cd_8ca7_9708c17ed4ae on mountpoint /var/lib/kubelet/pods/26a6fa11-1f54-4f19-9dd3-c6a6f1f24da0/volumes/kubernetes.io~csi/pvc-64b1b431-02a2-45cd-8ca7-9708c17ed4ae/mount: exit status 32" requestID=68d1f08a-8345-478d-be95-778dc61ef852 requestSource=CSI
time="2021-11-03T14:08:30Z" level=error msg="GRPC error: rpc error: code = Internal desc = error mounting NFS volume 10.25.176.110:/gp_6_pvs_pvc_64b1b431_02a2_45cd_8ca7_9708c17ed4ae on mountpoint /var/lib/kubelet/pods/26a6fa11-1f54-4f19-9dd3-c6a6f1f24da0/volumes/kubernetes.io~csi/pvc-64b1b431-02a2-45cd-8ca7-9708c17ed4ae/mount: exit status 32" requestID=a50260f2-68c8-4ea1-a2e5-8a9c3c66b4a1 requestSource=CSI
time="2021-11-03T14:08:34Z" level=error msg="GRPC error: rpc error: code = Internal desc = error mounting NFS volume 10.25.176.110:/gp_6_pvs_pvc_64b1b431_02a2_45cd_8ca7_9708c17ed4ae on mountpoint /var/lib/kubelet/pods/26a6fa11-1f54-4f19-9dd3-c6a6f1f24da0/volumes/kubernetes.io~csi/pvc-64b1b431-02a2-45cd-8ca7-9708c17ed4ae/mount: exit status 32" requestID=17d20e33-9a68-440e-85dd-883b099b2d8a requestSource=CSI
time="2021-11-03T14:08:42Z" level=error msg="GRPC error: rpc error: code = Internal desc = error mounting NFS volume 10.25.176.110:/gp_6_pvs_pvc_64b1b431_02a2_45cd_8ca7_9708c17ed4ae on mountpoint /var/lib/kubelet/pods/26a6fa11-1f54-4f19-9dd3-c6a6f1f24da0/volumes/kubernetes.io~csi/pvc-64b1b431-02a2-45cd-8ca7-9708c17ed4ae/mount: exit status 32" requestID=56d77cc0-4d80-4824-8eb0-de0aec494eef requestSource=CSI`

This does not seem to be an issue in our other clusters that are running VM's on the same version of trident/openshift

**Expected behavior**
I expect the mounts to succeed?

**Additional context**

**Comment by gnarl** [comment]
Hi @rmclaughlin-code,

When customers have reported an issue like this in the past it is typically an issue of the Trident daemonset not being able to reach NetApp storage. This can be caused by several factors including a change in the networking in the Kubernetes environment. I encourage you to use the #containers channel in Slack or to contact NetApp support to help troubleshoot your Trident issues.
