### ISSUE TITLE
Log aggregation

### ISSUE THREAD

**Issue by willemdh** [NetApp/trident#68]
Hello,

We are thinking about starting to use Trident. In https://netapp-trident.readthedocs.io/en/latest/reference/tridentctl.html#logs I do not see any option to send logs to an external syslog server (such as the Elastic stack in my case)

Is there any technical reason there is no way to send logs to an external log aggregator? if not, this seem like a good feature to add the option to send Trident logs to an external syslog server to ease log correlation for analytics, troubleshooting and debugging.

Grtz

Willem

**Comment by tgoetheyn** [comment]
👍

**Comment by adkerr** [comment]
Trident writes its logs to the stdout/stderr as recommended by kubernetes. You could use of one of the available solutions like [fluentd](https://docs.fluentd.org/v0.12/articles/kubernetes-fluentd) to forward these logs to elasticsearch.

**Comment by willemdh** [comment]
Ah good to know. W'll use Logstash to forward them from there. Tx
