### ISSUE TITLE
wrong image for trident-installer 21.10.1 -> ErrImagePull

### ISSUE THREAD

**Issue by ledroide** [NetApp/trident#685]
Trident-installer tarball from [21.10.1 assets](https://github.com/NetApp/trident/releases/tag/v21.10.1) installs _deployment/trident-csi_ and _daemonset/trident-csi_ with image **nexus.barnacle.netapp.com:5001/trident:21.10.1** for _trident-main_ container, instead of netapp/trident:21.10.1.

To reproduce :
* download and untar the latest trident-installer.tar.gz (21.10.1)
* install with tridentctl
* no image can be pulled -> kubelet reports `ImagePullBackOff` then `ErrImagePull` with error : 
```
Failed to pull image "nexus.barnacle.netapp.com:5001/trident:21.10.1": rpc error: code = Unknown desc = pinging container registry nexus.barnacle.netapp.com:5001: Get "https://nexus.barnacle.netapp.com:5001/v2/": dial tcp: lookup nexus.barnacle.netapp.com : no such host
```

Workaround : 

```bash
tridentctl install -n trident
kubectl set image daemonset/trident-csi deployment.apps/trident-csi trident-main=netapp/trident:21.10.1
```

Also found occurrences of `nexus.barnacle.netapp.com:5001/trident-operator:21.10.1` in files deploy/bundle.yaml and deploy/operator.yaml.

**Comment by gnarl** [comment]
Hi @ledroide,

Thanks for bringing this issue to our attention. The team is working on fixing this issue.

**Comment by gnarl** [comment]
Hi @ledroide, this issue has been fixed. Thanks again for bringing this to our attention.

**Comment by ledroide** [comment]
I confirm the image name is now fixed in the the latest trident-installer.tar.gz. Thanks !
