### ISSUE TITLE
Support for Kubernetes 1.23

### ISSUE THREAD

**Issue by thiagomiranda3** [NetApp/trident#687]
It's not an issue, more like a question.
In my company we are going to upgrade Kubernetes from 1.21 to 1.23 to keep up with the latest improvements, but we need to update trident version too.
We cannot update Kubernetes unless we have trident running, because we use a lot of Netapp applications.
Anyone has a clue when trident will support the new Kubernetes version 1.23?

Thanks

**Comment by gnarl** [comment]
Hi @thiagomiranda3,

Kubernetes v1.23 was [released on 12/07/21](https://www.kubernetes.dev/resources/release/) and the next Trident release will be Trident v22.01 which occurs towards the end of January 2022. The Trident v22.01 release will claim support for Kubernetes v1.23.

**Comment by thiagomiranda3** [comment]
Cool, thanks
