### ISSUE TITLE
Fruther customization of deployment+daemonset via helm chart

### ISSUE THREAD

**Issue by rjbrown57** [NetApp/trident#688]
**Describe the solution you'd like**
It would be very useful to add further daemonset/deployment options to the spec via the helm chart. 

Options that I would like to see
- NodeSelector/Affinity
- ResourceQuotas
- Enabling Metrics(For the DS)

**Describe alternatives you've considered**
You can currently deploy with tridentctl + custom yaml, but then we don't get the numerous benefits of the operator and a helm chart.

**Comment by wonderland** [comment]
At least for NodeSelector/Affinity (as well as tolerations) this is solved by 84cdd03e54af27c08354cd4cf0bb91e3d3cf7a2e 
Therefore should be part of the upcoming 22.01 release.

**Comment by rjbrown57** [comment]
Those seem to effect the operator deployment. I need to be able to configure the trident-csi(deployment/daemonset) the operator deploys.

**Comment by rjbrown57** [comment]
To elaborate I would like the same ability as with imagePullSecrets for the above mentioned configurations

- https://github.com/NetApp/trident/blob/master/helm/trident-operator/values.yaml#L29
- https://github.com/NetApp/trident/blob/master/cli/k8s_client/yaml_factory.go#L844

**Comment by wonderland** [comment]
Sorry, my bad. Yes, the above was for the operator. Noticed a further commit, that addresses it for the daemonset: e167c7e92e143e4bb4a8373ff0dc9f41c374cd42

For NodeSelector and Tolerations.

**Comment by rjbrown57** [comment]
Awesome that looks perfect!
