### ISSUE TITLE
Set priority class to critical in trident CSI daemonset

### ISSUE THREAD

**Issue by fhke** [NetApp/trident#694]
**Describe the solution you'd like**
Set the `priorityClassName` field of the trident CSI daemonset to a critical priority class (`system-cluster-critical` or `system-node-critical`).

**Describe alternatives you've considered**
We could use a mutating admission controller to set the priorityClassName field on the daemonset or its pods. This would be less preferable as it is a workaround rather than a fix and adds unnecessary complexity to clusters using trident.

**Additional context**
This is to allow trident to work correctly with graceful node shutdown ([KEP 2000](https://github.com/kubernetes/enhancements/tree/master/keps/sig-node/2000-graceful-node-shutdown)). Currently graceful node shutdown terminates the trident CSI pod at the same time as other pods, meaning that trident persistent volumes are not properly unmounted and cleaned up in kubernetes. If the trident pods have a priority class of `system-cluster-critical` or `system-node-critical` they will be terminated after other pods on the node, allowing them to clean up trident-managed persistent volumes properly.

**Comment by gnarl** [comment]
This issue is fixed with [commit 1254a19](https://github.com/NetApp/trident/commit/1254a190e0cb1166a73fabcf57e6e51849a32016) and will be included in the 22.04 release.
