### ISSUE TITLE
Document setting securityContext.fsGroup="nfs" in ontap-nas

### ISSUE THREAD

**Issue by mac-chaffee** [NetApp/trident#695]
**Describe the solution you'd like**
When a pod specifies `securityContext.fsGroup`, I'd like the option for all files to be `chown`'d to that group ID. My default installation using ontap-nas (NFS) doesn't seem to perform that `chown` operation.

I'm not sure if this is already supported or not. If it is, this is a request to just document how to enable it.

I think this is an important feature to consider since the many users might be used to EKS or GKE which do support `fsGroup`. And setting `fsGroup` is becoming more and more important as applications are starting to run as non-root users for increased security. In fact, `fsGroup` is very commonly set in the popular bitnami helm charts: https://github.com/bitnami/charts/search?q=fsGroup+filename%3Avalues.yaml

More info here: https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#delegating-volume-permission-and-ownership-change-to-csi-driver

**Describe alternatives you've considered**

There are some issues that mention fsGroup:

- #454 says to set `fsType` on the StorageClass, but that seems to only apply to iSCSI/block storage. [The docs say](https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/concepts/objects.html#kubernetes-storageclass-objects) it only applies to ontap-san.
- #561 involves ontap-nas, but the user was told to set `fsType` which seems incorrect based on the above issue.
- #527 concludes that trident sets `fsGroupPolicy: ReadWriteOnceWithFSType` by default, which means without an fsType, Kubernetes will never `chown` files. Does trident support changing that value?

So that means the options would be:

1. If ~~ontap-san~~ ontap-nas strictly cannot support `chown`ing files based on `fsGroup`, it might be nice to document that given how cloud providers typically support that with their block storage products.
2. If ~~ontap-san~~ ontap-nas can't support `chown`ing files based on `fsGroup`, but the feature could be added, I think it would be a good feature.
3. If ~~ontap-san~~ ontap-nas does support `chown`ing files based on `fsGroup` (either by adding an fsType or changing fsGroupPolicy), the documentation could be updated to reflect that

In the meantime, if anyone else has this issue, you can work around it by adding an `initContainer` that manually performs the `chown` operation (perhaps using the downward API to grab the fsGroup value and mount paths)

Open for feedback since this subject is new to me. Thanks in advance!

**Comment by mac-chaffee** [comment]
This comment says "fsGroup was not designed to handle nfs": https://github.com/kubernetes/kubernetes/issues/90123#issuecomment-613133490 But it doesn't elaborate on why.

**Comment by wonderland** [comment]
Is your ask about ontap-nas (as stated in the title) or for ontap-san (in your options 1-3)? 

In any case, you can use the fsGroup security context with Trident. Both, NAS and SAN. But Kubernetes has a few prerequisites for that (e.g. these are not Trident specific), especially:

- storageClass needs to have a fsType configured. If not, K8s assumes there is no file system or a file system that does not support chown. In case of NFS/ontap-nas, simply add a fsType: "nfs" entry to your storage class (could be any string, as it is ignored anyway but "nfs" kind of makes sense...)

- PVC needs to be RWO. K8s does not support it for RWX (read-write-many) volumes as this could lead to permission flapping (e.g. one pods requests a different fsGroup than the other).

**Comment by mac-chaffee** [comment]
I'm using ontap-nas (NFS), but the reason I mention ontap-san (block) is that other users of ontap-nas (NFS) were being told advice that allegedly only applies to ontap-san (block). Specifically, setting `fsType: etx4` in #561 

If setting `fsType: nfs` works, then I think we need more docs on the subject. Like here: https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/concepts/objects.html?highlight=fstype#kubernetes-storageclass-objects

and here: https://netapp-trident.readthedocs.io/en/stable-v21.07/kubernetes/known-issues.html?highlight=fstype#known-issues

and the sample storage class doesn't include an fstype either: https://github.com/NetApp/trident/blob/master/trident-installer/sample-input/pvc-samples/pvc-basic.yaml

**Comment by mac-chaffee** [comment]
Oh actually I see #561 was just recommending setting fstype to something (no specifically ext4).

**Comment by balaramesh** [comment]
@wonderland thank you for pointing that out. @mac-chaffee , you can use `securityContext.fsGroup` to provide a GID for an NFS volume, provided it is RWO and the storageClass has `fsType` defined on it. There are a few items to note here:

1. The ownership of the volume and files within it will be determined by the securityContext provided in the application deployment. `runAsUser`, `runAsGroup`, `fsGroup` are the parameters that can help here.
2. To share PVCs across multiple pods (RWX), `supplementalGroups` is what is required. Is this something you are interested in?
3. The ownership of the volume and its contents is enforced through Kubernetes, and not on the actual NFS volume.

**Comment by mac-chaffee** [comment]
Now that I understand that you can set `fsType: nfs`, the goal of this ticket is to request for that information to be added to the documentation.

**Comment by balaramesh** [comment]
@mac-chaffee this was reported with https://github.com/NetAppDocs/trident/issues/75 and has been resolved with https://github.com/NetAppDocs/trident/pull/79!
