### ISSUE TITLE
Importing volumes with different access controls for different apps

### ISSUE THREAD

**Issue by vrmerlin** [NetApp/trident#697]
**Describe the solution you'd like**
I need some apps to access an imported volume as read-only, and others to access the same data in the same Kubernetes cluster with read/write access.  This doesn't appear to be possible with Trident.

**Describe alternatives you've considered**
As I understand it, a PV can only be bound to a single PVC so I would need to use a different PV. But, Trident doesn't have the ability to create a second PV for an already imported volume.

**Comment by balaramesh** [comment]
@vrmerlin were you able to give this a try?

**Comment by vrmerlin** [comment]
I will try it soon as I can; sorry had some family issues come up
