### ISSUE TITLE
Simplify the behavior of using different images(Registries and image/tag overrides) in the helm chart

### ISSUE THREAD

**Issue by BadLiveware** [NetApp/trident#699]
**Describe the bug**
The behavior of overriding the images/tags/registries is non-obvious. 

As of right now, setting the imageRegistry sets all of the registries image are pulled from. However images are by default pulled from both [docker.io/netapp](https://hub.docker.com/u/netapp) and k8s.gcr.io/sig-storage. In my case, as an example, I have to use two different proxy caches in [harbor ](https://goharbor.io/) for these registries and for this chart that means setting the imageRegistry to a cache for k8s.gcr.io and then overriding the trident images with another.

When overriding the images in the helm chart, the tag is assumed to be inline with the image even though there is a value for a tag override. I find this to be a behavior that deviates from what is expected when seeing these values.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.
- Other: Helm chart

**Expected behavior**
* Allow both the trident/netapp and k8s.gcr.io registries to be overriden separately
* If the ...imageTag is set, append that to the image used
    - if it is not, use the default `.Chart.AppVersion` even if the image is overriden

**Additional context**
I have forked the repo and implemented changes to make the behavior more apparent, https://github.com/BadLiveware/trident

**Comment by BadLiveware** [comment]
Related issue: https://github.com/NetApp/trident/issues/679#issuecomment-982898472

**Comment by gnarl** [comment]
Trident customers use private registries in multiple ways when installing Trident. We've updated our installation documentation to include offline install instructions. The offline install instructions, like [Trident Operator (Offline)](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-operator-mirror.html#step-4-update-the-image-registry-location-in-the-tridentorchestrator), can support using one or more registry locations for your Trident installs.
