### ISSUE TITLE
Request for Enhancement - Security

### ISSUE THREAD

**Issue by rileynjohnson** [NetApp/trident#7]
Client is under strict HIPAA and security requirements and needs some mechanism to guarantee containers require some form of handshake with their correct exports/LUNs.  This probably includes some form of intelligence to know which LUN to present to which container.  That functionality probably belongs higher in the orchestration layer but may require some adaptions in storage, so I’m submitting to raise visibility to the request.

**Comment by adkerr** [comment]
Tracked internally by [US2284](https://rally1.rallydev.com/#/47479883219d/detail/userstory/93731618208)

**Comment by scaleoutsean** [comment]
Multiple instances of Trident + CHAP (different user for each Trident instance) can do that (assuming two-way CHAP authentication - I haven't yet looked how CHAP is implemented, as one- or two-way auth).

**Comment by gnarl** [comment]
As @scaleoutsean has pointed out Trident support CHAP for ONTAP-SAN, ONTAP-SAN-economy, and SOLIDFIRE-SAN drivers.
