### ISSUE TITLE
Solidfire iSCSI CHAP not working

### ISSUE THREAD

**Issue by rtouillet** [NetApp/trident#70]
Hello,
We have a SolidFire cluster version 10 and have deployed the latest Trident version on a Kubernetes 1.7 cluster. Unfortunatly the CHAP setting isn't working during the two phases of the deployement ("UseCHAP": true,):
- during the install_trident.sh deployement -> we must create an access group with some IQNs to be able to start Trident Pods. CHAP isn't working.
- during backend deployment -> backend deployment is ok, but cluster can't use CHAP to authenticate. We must have IQNs on the Trident access group to be able to mount volumes to Kub cluster. Cluster is again not able to use CHAP authentication to access volumes.

Many thanks.

**Comment by adkerr** [comment]
You may also want to make sure that user account you're using to communicate with SF has at a minimum the following permissions:

`volumes, accounts, clusterAdmins`

**Comment by rtouillet** [comment]
Hello Andrew,

Here is our backend definition:

{
    "version": 1,
    "storageDriverName": "solidfire-san",
    "Endpoint": "https://kubernetes:PASSWORD@MVIP/json-rpc/7.0",
    "SVIP": "SVIP:3260",
    "TenantName": "kube-int",
    "UseCHAP": true,
    "Types": [{"Type": "Bronze", "Qos": {"minIOPS": 1000, "maxIOPS": 2000, "burstIOPS": 4000}},
              {"Type": "Silver", "Qos": {"minIOPS": 2000, "maxIOPS": 4000, "burstIOPS": 8000}},
              {"Type": "Gold", "Qos": {"minIOPS": 3000, "maxIOPS": 6000, "burstIOPS": 10000}}]
}

Our user, kubernetes, has full rights (reporting/volumes/nodes/accounts/drives/cluster admin). We gave all rights to be sure this is not a rights issue.

Thanks.

**Comment by innergy** [comment]
What version of Trident are you using? You can run 'tridentctl version' to find out. CHAP is only available in the 18.01 beta. I'm not sure if we will return an error if you're running an older version of Trident and specify 'UseCHAP', we may just ignore it and use the default (a 'trident' access group), which would explain the behavior you're seeing.

**Comment by adkerr** [comment]
@innergy You are correct that we will simply ignore it as an unused config option

**Comment by rtouillet** [comment]
Hello,
Thank your for your reply. We have today version 17.10.1. 
So we'll test with version 18.01 to see if it works.
I'll keep you posted.
Many thanks.

**Comment by korenaren** [comment]
Thanks for confirming your version number. As Garrett mentioned, CHAP is not supported in 17.10. See issue #42 for the earlier requirement for CHAP. Will be great to hear your experience with 18.01 beta, and if that doesn't work, we can re-open this issue. Thanks!

**Comment by rtouillet** [comment]
@adkerr @korenaren @innergy Chap is working on version 18.01 Beta with SolidFire! Many thanks for your help.
