### ISSUE TITLE
TridentOrchestrator not deploying trident using IPV6 after useIPv6 is true

### ISSUE THREAD

**Issue by karloshs** [NetApp/trident#712]
**Describe the bug**
We are deploying the trident operator 22.01.0 to instantiate the trident pods, in the spec we have defined useIPv6: true but the trident deployment is done on IPv4 

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [e.g. 19.10]
- Trident installation flags used: [tridentoperator install using kubectl]
- Container runtime: [contianerd ]
- Kubernetes version: [v1.21.5]
- Kubernetes orchestrator: [K8s]
- OS: [Centos 8]
- NetApp backend types: [ONTAP 9.8p7,]
- Other:

**To Reproduce**
deploy the trident operator and define the orchestrator yaml as follows
apiVersion: trident.netapp.io/v1
kind: TridentOrchestrator
metadata:
  name: trident
spec:
  debug: true
  useIPv6: true
  uninstall: false
  namespace: trident
  tridentImage: netapp/trident:22.01.0
  autosupportImage: netapp/trident-autosupport:22.01.0
  silenceAutosupport: true
  imageRegistry: internalrepo/sig-storage
  controllerPluginNodeSelector:
    network: "LAN-INTERNAL"

**Expected behavior**
I expected the trident deployment to be instantiated with ipv6 support instead of ipv4

**Additional context**
here is the torc describe

Name:         trident
Namespace:
Labels:       <none>
Annotations:  <none>
API Version:  trident.netapp.io/v1
Kind:         TridentOrchestrator
Metadata:
  Creation Timestamp:  2022-03-10T18:07:43Z
  Generation:          1
  Managed Fields:
    API Version:  trident.netapp.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:autosupportImage:
        f:controllerPluginNodeSelector:
          .:
          f:network:
        f:debug:
        f:imageRegistry:
        f:namespace:
        f:silenceAutosupport:
        f:tridentImage:
        f:uninstall:
        f:useIPv6:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2022-03-10T18:07:43Z
    API Version:  trident.netapp.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:currentInstallationParams:
          .:
          f:IPv6:
          f:autosupportHostname:
          f:autosupportImage:
          f:autosupportProxy:
          f:autosupportSerialNumber:
          f:debug:
          f:enableNodePrep:
          f:httpRequestTimeout:
          f:imagePullSecrets:
          f:imageRegistry:
          f:k8sTimeout:
          f:kubeletDir:
          f:logFormat:
          f:probePort:
          f:silenceAutosupport:
          f:tridentImage:
        f:message:
        f:namespace:
        f:status:
        f:version:
    Manager:         trident-operator
    Operation:       Update
    Time:            2022-03-10T18:07:45Z
  Resource Version:  283566915
  UID:               bbd0a287-eaa4-44f6-9aa6-9608301b444f
Spec:
  Autosupport Image:  netapp/trident-autosupport:22.01.0
  Controller Plugin Node Selector:
    Network:            LAN-INTERNAL
  Debug:                true
  Image Registry:        internalrepo/sig-storage
  Namespace:            trident
  Silence Autosupport:  true
  Trident Image:        netapp/trident:22.01.0
  Uninstall:            false
  useIPv6:              true
Status:
  Current Installation Params:
    IPv6:                       false
    Autosupport Hostname:
    Autosupport Image:          netapp/trident-autosupport:22.01.0
    Autosupport Proxy:
    Autosupport Serial Number:
    Debug:                      true
    Enable Node Prep:           false
    Http Request Timeout:       90s
    Image Pull Secrets:
    Image Registry:        internalrepo/sig-storage
    k8sTimeout:           30
    Kubelet Dir:          /var/lib/kubelet
    Log Format:           text
    Probe Port:           17546
    Silence Autosupport:  true
    Trident Image:        netapp/trident:22.01.0
  Message:                Trident installed
  Namespace:              trident
  Status:                 Installed
  Version:                v22.01.0
Events:                   <none>

**Comment by gnarl** [comment]
Hi @karloshs, 

There isn't enough information in this Github Issue to understand why the deployment is failing in your environment. We do test Trident with IPv6 and have not seen the issue that you are reporting. I understand that there is now a NetApp support case open on this issue and ask that you work with the support team to help determine where the issue is.

**Comment by torirevilla** [comment]
@karloshs When using the Trident Orchestrator, the "UseIPv6" option was shortened to "IPv6". Setting IPv6: true in the torc yaml will solve this issue and deploy on IPv6.

**Comment by karloshs** [comment]
Nice, I'll try with this spec, it will be helpful if those changes are can be documented because everything I read so far point to the spec UseIPv6: true and the specs on the torc output I thought it was referring to the  autosupport container
https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy.html and
https://netapp-trident.readthedocs.io/en/latest/kubernetes/deploying/operator-deploy.html

**Comment by karloshs** [comment]
this is what I'll read in the future :)
https://github.com/NetApp/trident/blob/master/operator/controllers/provisioner/apis/netapp/v1/types.go#L32-L48
thanks for the help @torirevilla

**Comment by gnarl** [comment]
Hi @karloshs,

It was determined today that the [documentation](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy.html) is incorrect and we will get the docs updated soon.  @torirevilla did the problem determination and has suggested that the "useIPv6" option be updated to "IPv6".

**Comment by gnarl** [comment]
The Trident [documentation](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy.html) is now updated to indicate that "IPv6" is the correct parameter to use when installing Trident, via the Operator, in an IPv6 environment.
