### ISSUE TITLE
Import folder within volume?

### ISSUE THREAD

**Issue by vrmerlin** [NetApp/trident#713]
We have a data archive that I need to mount. With traditional fstab and and NFS, i can mount it as nfsdev01:/dataarchive/foo/bar, where nfsdev01 is the server, dataarchvie is the volume, and /foo/bar is the path within the volume.

Can this be done with Trident? I am able to use the tridentctl import volume command to mount the dataarchive volume, but I really want the "top" of the tree to be a folder within the volume, as I can do with fstab. Is this possible?

Thanks,
John

**Comment by crossond** [comment]
The Trident import command does not support ONTAP qtrees (ie. the ontap-nas-economy driver which creates qtrees inside flexvols).  IF you need this volume to be managed by Trident, I suppose you could use an ontap-nas-economy backend to create a qtree in the flexvol.  Then copy the data (externally from Trident) from the current volume into the qtree.

**Comment by gnarl** [comment]
Hi @vrmerlin,

Provisioning a path as a PV within a volume isn't supported by Trident. The recommendation is to copy the data at the path to a new FlexVol and to then import that volume using Trident.
