### ISSUE TITLE
Updating a backend exportPolicy does not update volume export on ontap-nas driver

### ISSUE THREAD

**Issue by Peyoz** [NetApp/trident#714]
**Describe the bug**
We have updated a backend config which uses ontap-nas driver to move from the default export policy to a purpose built export policy
Volume exports where not updated after the backend was applied, and are still exported through the default export policy

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 21.10.1
- Trident installation flags used: -n trident -e tridentSilenceAutosupport=true
- Container runtime: Docker-CE 20.10.10
- Kubernetes version: v1.19.16
- Kubernetes orchestrator: RKE 1.3.6
- Kubernetes enabled feature gates: none
- OS: RHEL 7.9
- NetApp backend types: Ontap 9.8
- Other:

**To Reproduce**
Configure a backend using driver ontap-nas, do/do not specify an exportPolicy, but do not enable AutoExport
Deploy an app through Helm
Update Backend with a different export policy
Volumes are still bound to the old export policy
Additionally, you can delete and reinstall the app through Helm, but it will not apply the new export policy

**Expected behavior**
Updating the backend config should reflect to the volumes configuration

**Backend Config**
```
{
  "version": 1,
  "backendName": "ontap-nas",
  "storageDriverName": "ontap-nas",
  "managementLIF": "REDACTED",
  "dataLIF": "REDACTED",
  "svm": "ldr1-k8s-nfs-trident1",
  "storagePrefix": "trident",
  "nfsMountOptions": "nfsvers=3",
  "username": "REDACTED",
  "password": "REDACTED",
  "aggregate": "aggr_SSD_LDR1_MC_01",
  "limitVolumeSize": "40Gi",
  "defaults": {
    "spaceReserve": "none",
    "snapshotPolicy": "trident_prod",
    "snapshotReserve": "10",
    "exportPolicy": "default"
  }
}
```

**Comment by clintonk** [comment]
Hello, @Peyoz.  What you are describing is expected behavior.  Trident does not apply backend config settings (or PVC annotations) to volumes retroactively.  But you can safely modify the export policy setting for preexisting volumes outside Trident without affecting Trident's operation.

**Comment by Peyoz** [comment]
We changed the export policy and everything kept working, thanks for the clarification
Cheers!
