### ISSUE TITLE
Unable to delete failed backend

### ISSUE THREAD

**Issue by dbarreda** [NetApp/trident#718]
**Describe the bug**
Got a failed backend that needs to be deleted as couldn't be recovered (lab appliance of ONTAP).
All PV and PVC's have been removed, however we cannot delete the failed backend.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 22.01.1
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml]
- Container runtime: cri-o
- Kubernetes version: v1.23.3+e419edf
- Kubernetes orchestrator: Openshift 4.10.4
- OS: CoreOS
- NetApp backend types: ONTAP
- Other:

**To Reproduce**
Steps to reproduce the behavior: Have a working backend, it got corrupted. PV and PVC's were deleted, some of them not gracefully. Trying to delete backend but unable to do so.

**Expected behavior**
Remove the failed backend from trident

**Additional context**
I can still see the volumes deleted when doing `tridentctl get volumes`, I'm assuming it is trying to delete them before deleting the backend but unable. When trying to delete volume this is the output:
```
-bash-4.2$ ./tridentctl delete volume pvc-d3e55705-73d4-47c5-9171-61b002bd2026
Error: could not delete volume pvc-<UUID>: backend <backend-name> is not Online or Deleting (400 Bad Request)
```

**Comment by scaleoutsean** [comment]
See issue #543

My current workaround is reinstall Trident (which necessitates import of volumes from both existing and failed back-end - quite disruptive for production, but okay for lab use).

**Comment by dbarreda** [comment]
Was able to delete the backend after deleting the tvol's as mentioned in the KB that  @crossond mentioned.

```
for i in `./tridentctl get volumes | grep <BACKEND-UUID> | awk '{print $2}'` ; do oc delete tvol $i ; done
tridentvolume.trident.netapp.io "pvc-<PVC-UUID>" deleted
tridentvolume.trident.netapp.io "pvc-<PVC-UUID>" deleted
... many more ...
```

After that I was able to execute `./tridenctl delete backend <backend-name>` and worked fine.

Thanks. 

I'll close the issue for now. I guess can be re-opened there it's needed to add this into either documentations or to do changes in trident.

**Comment by scaleoutsean** [comment]
For the benefit of others that come across this issue, that workaround doesn't work for me when a SolidFire back-end is already stuck in deleting. I had no snapshots - just one back-end and one volume. I powered off the back-end and then tried to delete it, after which it got stuck in deleting.

```
sean@k1:~$ ./tridentctl get backend -n trident
+--------------------------+----------------+--------------------------------------+----------+---------+
|           NAME           | STORAGE DRIVER |                 UUID                 |  STATE   | VOLUMES |
+--------------------------+----------------+--------------------------------------+----------+---------+
| solidfire_192.168.103.30 | solidfire-san  | 6038b85a-2725-4569-8fe6-051979b3c427 | deleting |       1 |
+--------------------------+----------------+--------------------------------------+----------+---------+

sean@k1:~$ ./tridentctl get volume -n trident
+------------------------------------------+---------+---------------+----------+--------------------------------------+--------+---------+
|                   NAME                   |  SIZE   | STORAGE CLASS | PROTOCOL |             BACKEND UUID             | STATE  | MANAGED |
+------------------------------------------+---------+---------------+----------+--------------------------------------+--------+---------+
| pvc-f1df4988-86e9-4480-8692-7c7acaf9c98f | 1.0 GiB | iscsi-bronze  | block    | 6038b85a-2725-4569-8fe6-051979b3c427 | online | true    |
+------------------------------------------+---------+---------------+----------+--------------------------------------+--------+---------+


sean@k1:~$ for i in `./tridentctl -n trident get volumes | grep 6038b85a-2725-4569-8fe6-051979b3c427 | awk '{print $2}'` ; do kubectl delete tvol $i ; done
Error from server (NotFound): tridentvolumes.trident.netapp.io "pvc-f1df4988-86e9-4480-8692-7c7acaf9c98f" not found

sean@k1:~$ ./tridentctl -n trident delete backend 6038b85a-2725-4569-8fe6-051979b3c427
Error: could not delete backend 6038b85a-2725-4569-8fe6-051979b3c427: backend 6038b85a-2725-4569-8fe6-051979b3c427 was not found (404 Not Found)
command terminated with exit code 1

sean@k1:~$ ./tridentctl get backend -n trident
+--------------------------+----------------+--------------------------------------+----------+---------+
|           NAME           | STORAGE DRIVER |                 UUID                 |  STATE   | VOLUMES |
+--------------------------+----------------+--------------------------------------+----------+---------+
| solidfire_192.168.103.30 | solidfire-san  | 6038b85a-2725-4569-8fe6-051979b3c427 | deleting |       1 |
```
