### ISSUE TITLE
Support storage replication

### ISSUE THREAD

**Issue by gfranceschi** [NetApp/trident#72]
Some of our users would like to setup their containerized applications in an active/standby setup, using multiple k8s clusters as sites. We would like to offer them storage replication of the NFS volumes through snapmirror to support that, however currently any trident-provisioned volumes are of course standard volumes that cannot be replication targets. If we setup replication targets by ourselves, then the new volumes are not known to trident. They can be connected to the containers manually, but we lose the easy integration.
Is there anything in the works to support such a scenario? Is anyone else interested in replicated volumes?
Thanks

**Comment by wonderland** [comment]
I guess this would need some coordination from the k8s side as well to really make this work across clusters. This is mentioned in https://github.com/kubernetes/kubernetes/issues/27710

**Comment by rajshrivastava22** [comment]
Hi Team, kindly suggest when we can expect this solution implemented. We have request from customer as well.

**Comment by gnarl** [comment]
We've examined storage replication and have found that it is best supported outside of Trident. As @wonderland pointed out above there isn't any coordination in Kubernetes to support replication today. Articles on how to perform replication outside of Trident are available on [NetApp.io](https://netapp.io/2019/10/08/trident-and-disaster-recovery-part-1/).
