### ISSUE TITLE
Support Kubernetes v1.24

### ISSUE THREAD

**Issue by ysakashita** [NetApp/trident#731]
**Describe the solution you'd like**
Could NetApp/Trident support Kubernetes v1.24 ASAP?
We are working on Kubernetes v1.24, but Trident v22.04.0 is not yet supported. 
So Trident is a blocker in our service.
We want to support Kubernetes v1.24 in the patch version of Trident. (e.g., v22.04.1)

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by gnarl** [comment]
Hi @ysakashita,

Thanks for inquiring about Kubernetes v1.24. Qualification of Kubernetes v1.24 for Trident has not been completed yet. We will update this issue once that qualification is completed.

**Comment by ysakashita** [comment]
@gnarl There is no mention of K8S v1.24 in the release notes, but the Trident v22.07.0 support it, right?

I find the commit for updating KubernetesVersionMax.
https://github.com/NetApp/trident/commit/4b6c3c63c108e038414f78b5a2c3bd3e2d3dc09b#diff-fe44f09c4d5977b5f5eaea29170b6a0748819c9d02271746a20d81a5f3efca17R142

**Comment by gnarl** [comment]
Hi @ysakashita,

[Trident v22.07's requirements documentation](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#supported-frontends-orchestrators) claims support for Kubernetes v1.24. Recently we were able to also update [Trident v22.04's requirements documentation](https://docs.netapp.com/us-en/trident-2204/trident-get-started/requirements.html) to also claim support for Kubernetes v1.24.

**Comment by ysakashita** [comment]
@gnarl Great! Thank you for supporting it.
