### ISSUE TITLE
Feature request : Bring an existing Volume into Trident Management

### ISSUE THREAD

**Issue by kapilarora** [NetApp/trident#74]
The ability to bring existing ONTAP/SolidFire volumes into Trident management.

Usecase 1 : Migrate existing workloads to Kubernetes e.g. a Database
Usecase 2: Bring a volume into trident management, clone it and run tests or a data job.

**Comment by litroma** [comment]
It's an expectation for three of my customer : BNP, ORANGE (two G100 account) and BPCE another major Bank account in France

**Comment by oliviermasson** [comment]
Hello,

It's an expectation for three of my customer : BNP and ORANGE (two G100 accounts) and BPCE

**Comment by si-heger** [comment]
The ability to "import" volumes into kubernetes via trident is also an important use case for inter-kubernetes-cluster ability to move volumes.

Many customers operate multiple kubernetes clusters e.g . one for dev, one for test, one for prod etc. Sometimes it would be useful to be able to "move" a volume from one cluster to the next. For that some kind of "import" functionality would be the first step

**Comment by kapilarora** [comment]
Is this in the feature pipeline? Just checking as a customer asked about it today.
Kapil

**Comment by grimm514** [comment]
Our customers also want such a feature.

**Comment by lari-ch** [comment]
Same request from our customers. We would like this feature. Thx

**Comment by korenaren** [comment]
@kapilarora Yes, in the pipeline. No commitment, but we are actively discussing this one.

**Comment by Matthias-Beck** [comment]
We are also interested to have this option

**Comment by forgosh** [comment]
I also have a large customer asking for this. The use case is slightly different however. They want to be able to clone from a PV, not a PVC, so that the clones can cross namespaces. They are saying that it is a competitive weakness today for us.

**Comment by kangarlou** [comment]
@forgosh Cloning a volume to a different namespace is currently being discussed by the community: https://github.com/erinboyd/community/blob/patch-3/contributors/design-proposals/storage/cloning.md. The manual cloning by the admin and the manual construction of the corresponding PVC and PV is the recommended approach for now. Once Trident supports volume import (this issue), Trident can manage the manually provisioned clones.

**Comment by git001** [comment]
Any Update on this topic.
We need to *migrate* one trident/etcd compo from one cluster to another and it would be very helpfully to be able to do something like this.

* export etcd data from cluster A
* import etcd data to cluster B
* copy data from pv storage A to pv storage B

**Comment by kirklandia** [comment]
This is very important for the Data Fabric.  Not only do we need the ability to import PVs, we need the ability to import them from SnapMirror destinations.

**Comment by si-heger** [comment]
Any update on this? This is probably the most important missing features that directly aligns with the Data Fabric and ability to move workloads from one cluster to another (or one cloud to another)

**Comment by clintonk** [comment]
Hi, @si-heger.  We're working on this at high priority.

**Comment by psingh59** [comment]
We are also in desperate need of this. When will it be likely to release??

**Comment by korenaren** [comment]
Volume Import is targeted for the 19.04 release (April 2019) and will include support in the following drivers: ontap-nas, ontap-nas-flexgroup, solidfire-san, and aws-cvs.

**Comment by sarangrakhecha** [comment]
Addressed in 56bd0dd7d172baa79b06c8014bd5d762a5dd8c3a
