### ISSUE TITLE
Renamed data aggregate breaks trident backend

### ISSUE THREAD

**Issue by amehub** [NetApp/trident#743]
**Describe the solution you'd like**
After rename of data aggregate dynamically update the Trident backend.   Do not statically define the data aggregate in the backend spec.

**Describe alternatives you've considered**
None

**Additional context**
We manage trident backends using tridentbackendconfig.  We noticed that the data aggregate appears to be statically defined in the trident backend when the trident backend is created.  After the data aggregate was renamed we are unable to create pvcs using the storage class that uses the backend.  The error complains that the data aggregate cannot be found.   Clearly because the backend has the data aggregate statically defined :-(

**Comment by gnarl** [comment]
Hi @amehub,

There is an `aggregate` option available for [ONTAP backend configurations](https://docs.netapp.com/us-en/trident/trident-docker/stor-config.html#global-configuration-options). You can use this option to restrict which aggregates Trident uses for provisioning and it also allows you to build automation to update the aggregate name(s) as needed.

If you don't specify the aggregate(s) in the backend config then the storage driver will read the aggregates assigned to the SVM, specified in the backend configuration, when the driver starts. Trident does not poll the storage backend for changes to minimize the amount of load on the storage backend. In this scenario, you simply restart the Trident controller pod when the aggregate names have changed and Trident will pick up the new aggregate names to use for provisioning volumes.
