### ISSUE TITLE
documentation has not been updated for 22.01

### ISSUE THREAD

**Issue by cbf123** [NetApp/trident#746]
Just noticed that [trident](https://github.com/NetApp/trident/tree/stable/v21.07)/[docs](https://github.com/NetApp/trident/tree/stable/v21.07/docs)/[support](https://github.com/NetApp/trident/tree/stable/v21.07/docs/support)/requirements.rst is still talking about trident 21.07 as the latest version, which is quite a bit out of date now.

**Comment by adkerr** [comment]
Hi @cbf123, the official documentation has moved to https://docs.netapp.com/us-en/trident/index.html

Hope that helps!

**Comment by cbf123** [comment]
Thanks, that does help although it's a bit odd that the embedded docs here are left stale rather than updated with a link to that site.

Just a heads-up, https://mysupport.netapp.com/site/info/trident-support also ends at 21.07.
