### ISSUE TITLE
Add support for setting priorityClassName

### ISSUE THREAD

**Issue by djjudas21** [NetApp/trident#747]
**Describe the solution you'd like**
Add support for setting `priorityClassName` on all Pods deployed using the Helm chart.

We use pod priority classes and the Trident pods should have a higher priority than workload pods so they start up first.

I can put in a PR for this change if it would help. Thanks.

**Comment by jwebster7** [comment]
Hi @djjudas21 thanks for opening this! We've briefly explore adding this, but chose to 

Starting in v22.04 the Trident DaemonSet will use the system-node-critical PriorityClass (https://github.com/NetApp/trident/blob/master/cli/k8s_client/yaml_factory.go#L1033). 

This should ensure the Trident Node Pods have the highest possible priority in a given namespace. Currently the Trident Deployment does not have this field. 

Are you requesting to make the specified PriorityClass a configurable option for both the Deployment and DaemonSet? Or an optional flag to ensure the PriorityClass we are already using (`system-node-critical`) is applied for _both_ the Deployment and DaemonSet?

**Comment by djjudas21** [comment]
If it's already using `system-node-critical` then that's fine, and I don't need to override it.

My deployment was done with v22.01 so I will upgrade to v22.04 and this should solve my problem - thanks.

**Comment by gnarl** [comment]
Closing this issue based on the above conversation.
