### ISSUE TITLE
Trident CSI sitll connecting on FCOS 36.20220716.3.1 

### ISSUE THREAD

**Issue by pmokrz** [NetApp/trident#750]
**Describe the bug**
After doing upgrade Fedora CoreOS to ver 36.20220716.3.1 the Node-CSI driver still connecting.

time="2022-08-02T14:24:57Z" level=warning msg="Could not update Trident controller with node registration, will retry." error="could not log into the Trident CSI Controller: error communicating with Trident CS
I Controller; Put \"https://10.233.51.147:34571/trident/v1/node/l8101\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" increment=10.496269484s requestID=e3e2d6c4-c6d7-497a-93c4-95

I have this problem only with OS:
Fedora CoreOS 36.20220618.3.1
Fedora CoreOS 36.20220703.3.1
Fedora CoreOS 36.20220716.3.1

**Environment**

$ tridentctl version
+----------------+----------------+
| SERVER VERSION | CLIENT VERSION |
+----------------+----------------+
| 22.07.0        | 22.04.0        |
+----------------+----------------+
$ k get node -o wide
NAME    STATUS   ROLES                  AGE   VERSION     OS-IMAGE                        KERNEL-VERSION            CONTAINER-RUNTIME
l8101   Ready    control-plane,master   78d   v1.23.7     Fedora CoreOS 36.20220716.3.1   5.18.11-200.fc36.x86_64   containerd://1.6.4
l8102   Ready    control-plane,master   78d   v1.23.7     Fedora CoreOS 36.20220605.3.0   5.17.12-300.fc36.x86_64   containerd://1.6.4
l8103   Ready    control-plane,master   78d   v1.23.7     Fedora CoreOS 36.20220605.3.0   5.17.12-300.fc36.x86_64   containerd://1.6.4
l8104   Ready    <none>                       78d   v1.23.7     Fedora CoreOS 36.20220605.3.0   5.17.12-300.fc36.x86_64   containerd://1.6.4

$ k get pod -o wide
NAME                                READY   STATUS    AGE     IP                      NODE    
trident-csi-5pplc                   2/2     Running   34m     10.226.11.133   l8103 
trident-csi-6f2wr                   1/2     Running   8m58s  10.226.11.131   l8101   
trident-csi-cvz7d                   2/2     Running   34m     10.226.11.132   l8102  
trident-csi-vsgn8                   2/2     Running   34m     10.226.11.134   l8104   
trident-operator-7c98557778-ftqq5   1/1     Running         34m     10.233.121.86   l8105  
trident-csi-797999d774-rq5ch        6/6     Running   34m     10.233.80.77    l8108  

**Logs**
k logs -f trident-csi-6f2wr trident-main
time="2022-08-02T14:24:27Z" level=info msg="Running Trident storage orchestrator." binary=/trident_orchestrator build_time="Fri Jul 29 11:24:51 EDT 2022" version=22.07.0
time="2022-08-02T14:24:27Z" level=info msg="Initializing plain CSI helper frontend."
time="2022-08-02T14:24:27Z" level=info msg="Added frontend." name=plain_csi_helper
time="2022-08-02T14:24:27Z" level=info msg="Initializing CSI frontend." name=l8101 version=22.07.0
time="2022-08-02T14:24:27Z" level=info msg="Enabling node service capability." capability=STAGE_UNSTAGE_VOLUME
time="2022-08-02T14:24:27Z" level=info msg="Enabling node service capability." capability=EXPAND_VOLUME
time="2022-08-02T14:24:27Z" level=info msg="Enabling node service capability." capability=GET_VOLUME_STATS
time="2022-08-02T14:24:27Z" level=info msg="Enabling volume access mode." mode=SINGLE_NODE_WRITER
time="2022-08-02T14:24:27Z" level=info msg="Enabling volume access mode." mode=SINGLE_NODE_READER_ONLY
time="2022-08-02T14:24:27Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_READER_ONLY
time="2022-08-02T14:24:27Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_SINGLE_WRITER
time="2022-08-02T14:24:27Z" level=info msg="Enabling volume access mode." mode=MULTI_NODE_MULTI_WRITER
time="2022-08-02T14:24:27Z" level=info msg="Added frontend." name=csi
time="2022-08-02T14:24:27Z" level=info msg="Initializing HTTPS REST frontend." address=":17546"
time="2022-08-02T14:24:27Z" level=info msg="Added frontend." name="HTTPS REST"
time="2022-08-02T14:24:27Z" level=info msg="Added 0 existing volume(s)" requestID=34eb6d49-a684-4f89-b6fa-6e1767e351a0 requestSource=Internal
time="2022-08-02T14:24:27Z" level=info msg="Trident bootstrapped successfully."
time="2022-08-02T14:24:27Z" level=info msg="Activating plain CSI helper frontend."
time="2022-08-02T14:24:27Z" level=info msg="Activating HTTPS REST frontend." address=":17546"
time="2022-08-02T14:24:27Z" level=info msg="Activating CSI frontend." requestID=e3e2d6c4-c6d7-497a-93c4-959fb1bf0bfe requestSource=Internal
time="2022-08-02T14:24:27Z" level=info msg="Starting periodic node access reconciliation service." requestID=dc00598e-6109-4b50-b622-517187516267 requestSource=Periodic
time="2022-08-02T14:24:27Z" level=info msg="Discovered iSCSI initiator name." IQN="iqn.1994-05.com.redhat:de886ad0c8f6" requestID=e3e2d6c4-c6d7-497a-93c4-959fb1bf0bfe requestSource=Internal
time="2022-08-02T14:24:27Z" level=info msg="Discovered IP addresses." IP Addresses="[10.226.11.131 10.233.84.0 172.17.0.1]" requestID=e3e2d6c4-c6d7-497a-93c4-959fb1bf0bfe requestSource=Internal
time="2022-08-02T14:24:57Z" level=warning msg="Could not update Trident controller with node registration, will retry." error="could not log into the Trident CSI Controller: error communicating with Trident CSI Controller; Put \"https://10.233.51.147:34571/trident/v1/node/l8101\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" increment=10.496269484s requestID=e3e2d6c4-c6d7-497a-93c4-959fb1bf0bfe requestSource=Internal
time="2022-08-02T14:25:38Z" level=warning msg="Could not update Trident controller with node registration, will retry." error="could not log into the Trident CSI Controller: error communicating with Trident CSI Controller; Put \"https://10.233.51.147:34571/trident/v1/node/l8101\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" increment=19.057534053s requestID=e3e2d6c4-c6d7-497a-93c4-959fb1bf0bfe requestSource=Internal
time="2022-08-02T14:26:27Z" level=warning msg="Could not update Trident controller with node registration, will retry." error="could not log into the Trident CSI Controller: error communicating with Trident CSI Controller; Put \"https://10.233.51.147:34571/trident/v1/node/l8101\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" increment=40.699091843s requestID=e3e2d6c4-c6d7-497a-93c4-959fb1bf0bfe requestSource=Internal

$ k logs -f trident-csi-6f2wr driver-registrar
I0802 14:24:27.601972    3484 main.go:166] Version: v2.5.1
I0802 14:24:27.602066    3484 main.go:167] Running node-driver-registrar in mode=registration
I0802 14:24:27.603799    3484 main.go:191] Attempting to open a gRPC connection with: "/plugin/csi.sock"
W0802 14:24:37.604947    3484 connection.go:173] Still connecting to unix:///plugin/csi.sock
W0802 14:24:47.603983    3484 connection.go:173] Still connecting to unix:///plugin/csi.sock
W0802 14:24:57.604876    3484 connection.go:173] Still connecting to unix:///plugin/csi.sock
W0802 14:25:07.604311    3484 connection.go:173] Still connecting to unix:///plugin/csi.sock
W0802 14:25:17.604232    3484 connection.go:173] Still connecting to unix:///plugin/csi.sock

**Comment by gnarl** [comment]
Hi @pmokrz,

Fedora CoreOS isn't one of the supported [Operating Systems ](https://docs.netapp.com/us-en/trident/trident-get-started/requirements.html#feature-requirements) that we test. Considering that you are only having issues with the most recent version of [FCOS](https://getfedora.org/en/coreos?stream=stable) I'd suspect that there is a breaking change in FCOS and not Trident. 

You can check on network connectivity from your Kubernetes node, where the Trident daemonset pod is running, with the Kubernetes node where the Trident controller is running. There may have been a configuration change in FCOS that is preventing the needed network connection to register the Trident daemonset pod with the Trident controller.

**Comment by gnarl** [comment]
Closing this issue as there hasn't been a response from @pmokrz recently and previous FCOS versions are known to work with Trident.

**Comment by pmokrz** [comment]
From what I found it somewhere after the update, some strange way is blocking communication between the pods in the k8s cluster. Maybe someone had a similar case?

I think this bug can be hooked up together with:  Could not update Trident controller with node registration, will retry." error="could not log into the Trident CSI Controller: error communicating with Trident CSI Controller #752

**Comment by pmokrz** [comment]
My solution: sudo ethtool --offload vxlan.calico rx off tx off was done on every node
