### ISSUE TITLE
Trident 17.10.1 doesn't respect defined export-policy

### ISSUE THREAD

**Issue by dxlr8r** [NetApp/trident#76]
Hello, I follow the instructions as per: <https://netapp-trident.readthedocs.io/en/latest/getting-started/deploying-trident.html> and had some issues: 

# 4: Install Trident

Here I used this backend.json config: 

```
{
    "version": 1,
    "storageDriverName": "ontap-nas",
    "managementLIF": "192.168.1.1",
    "dataLIF": "192.168.1.1",
    "svm": "firm_openshift",
    "username": "ocp-trident",
    "password": "foobar",
    "storagePrefix": "env_ocp",
    "defaults": {
        "export-policy": "trident",
        "spaceReserve": "none",
        "snapshotDir": "false"
    }
}
```

Installation didn't work, because it didn't use the supplied export-policy, instead it used "default"; which doesn't expose shares because we want security by default. 

After changing the export-policy of the volume trident, the pods eventually started spinning: 

`modify env_ocp_trident -policy trident`

The export-policy "trident" was made prior to installation. 

# 5: Add your first backend

Here I used this backend.json config: 

```
{
    "version": 1,
    "storageDriverName": "ontap-nas-economy",
    "managementLIF": "192.168.1.1",
    "dataLIF": "192.168.1.1",
    "svm": "firm_openshift",
    "username": "ocp-trident",
    "password": "foobar",
    "storagePrefix": "env_ocp",
    "defaults": {
        "export-policy": "trident",
        "spaceReserve": "none",
        "snapshotDir": "false"
    }
}
```

This is just for referance, installation worked.

# 7: Provision your first volume

While the volume is being made, it isn't mountable because it doesn't use the defined "export-policy". For the flexvolume it creates it's own export-policy "trident_qtree_pool_export_policy"; while the qtree volume uses "default".

**Comment by kangarlou** [comment]
Please change "export-policy" to "exportPolicy" and report the result. Here are the description of the fields and some examples: http://netapp-trident.readthedocs.io/en/latest/operations/tasks/backends/ontap.html?#backend-configuration-options

**Comment by dxlr8r** [comment]
*facepalm* , how could I overlook that? I'll try again and close the case if it works as it should.

**Comment by dxlr8r** [comment]
That did work for volume created in step 4 and for qtree volumes. But it still creates and uses "trident_qtree_pool_export_policy" for the qtree flex (economy) volume. 

Meaning that I can mount this flex volume and view all qtree volumes by default, since "trident_qtree_pool_export_policy" is exposed to 0.0.0.0/0. I can ofcourse alter this export policy. By default I don't think anyone should be able to access it.

**Comment by dxlr8r** [comment]
By default the enclosed qtrees uses the "default" export policy, or the one the user supplied. So by default one has access to them. 

I was just raising a consern, if you don't see this as an issue I'll close the case. But I think exposing the flexvolume and thus all the qtree volumes to the world by default is perhaps not the best default settings; even though most of us protect the access with firewalls as well.
