### ISSUE TITLE
Docker plugin update from 20.07 to 22.04 / 22.07

### ISSUE THREAD

**Issue by Cryptenom** [NetApp/trident#760]
I wanted to update the Trident plugin from 20.07 to 22.04, but I encountered errors which I can't easily fix. 

**Environment**

- Trident version: 20.07
- Trident installation flags used: `docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin:22.04 config=/etc/netappdvp/netapp.jsonl`
- Container runtime: Docker 20.10.12
- OS: Ubuntu 20.04.4
- NetApp backend types: ONTAP 

**To Reproduce**
``` 
docker plugin disable -f netapp:latest
docker plugin rm netapp:latest

docker plugin install --grant-all-permissions --alias netapp netapp/trident-plugin/new:22.04 config=/etc/netappdvp/netapp.json
22.04: Pulling from netapp/trident-plugin
Digest: sha256:30bb4e6292df74830f6317f3af0e360039bdd509ef1089d1161976e385c7ccdc
006b910162ba: Complete
Error response from daemon: dial unix /run/docker/plugins/e4d7644e51d7e3352663105995cf5508ac462d6a5729f7dc625ed08bc2c3b131/netapp.sock: connect: no such file or directory
```
`netapp.sock: connect: no such file or directory`  Info that the container could not be started,  the logs:

``` 
[...] level=error msg="time=\"2022-08-16T08:11:33Z\" level=info msg=\"Running Trident storage orchestrator.\" binary=/netapp/trident build_time=\"Fri Apr 29 17:02:09 UTC 2022\" version=22.04.0" plugin=e4d7644e51d7e3352663105995cf5508ac462d6a5729f7dc625ed08bc2c3b131
[...] level=info msg="time=\"2022-08-16T08:11:33Z\" level=info msg=\"Initialized logging.\" buildTime=\"Fri Apr 29 17:02:09 UTC 2022\" logFileLocation=/var/log/trident/netapp.log logLevel=info" plugin=e4d7644e51d7e3352663105995cf5508ac462d6a5729f7dc625ed08bc2c3b131
[...] level=error msg="time=\"2022-08-16T08:11:33Z\" level=fatal msg=\"Unable to start the Docker frontend. plugin.hostVolumePath /docker/plugins/e4d7644e51d7e3352663105995cf5508ac462d6a5729f7dc625ed08bc2c3b131/propagated-mount does not exist on /host path\"" plugin=e4d7644e51d7e3352663105995cf5508ac462d6a5729f7dc625ed08bc2c3b131
``` 
On a test server I have Ubuntu 21.04 running, here  was the installation of the trident plugin 22.04  without any problems. Probably the 20.04.4 version is too "old", unfortunately an update is currently not possible. 
There was a similar error in #507.
I had used the same config settings images on my  server and test server.
(i testet it also with 22.07, same error)

**Comment by gnarl** [comment]
Hi @tperelle,

Please open a NetApp support case for your Docker related issue. We continue to struggle to obtain a way to reproduce an environment where the Trident Docker Plugin fails.
