### ISSUE TITLE
Define resources requests and limits for operator in helm template

### ISSUE THREAD

**Issue by claudex** [NetApp/trident#765]
**Describe the solution you'd like**
The [Helm template for the operator deployment](https://github.com/NetApp/trident/blob/master/helm/trident-operator/templates/deployment.yaml) should allow to configure resources requests and limits for the container as it defined as best practices in Docker CIS Benchmark. And it would be better is default values are defined with sane values.

**Describe alternatives you've considered**
I didn't find any alternatives.

**Additional context**
 - https://learn.cisecurity.org/benchmarks
 - https://www.aquasec.com/cloud-native-academy/docker-container/docker-cis-benchmark/

**Comment by gnarl** [comment]
Hi @claudex,

We are not currently planning to extend every possible option available in Trident to Helm. You can create a [customized Trident deployment ](https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-customize-deploy-tridentctl.html) that works with GitOps management tools. 

I looked at the docker-cis-benchmark link that you provided and most of the content is regarding the docker container runtime and security. The container runtime is outside of the scope of what Trident configures. We continually work to improve the level of security in Trident as can be recently seen in the [Trident 22.07 release notes](https://github.com/NetApp/trident/releases/tag/v22.07.0).
