### ISSUE TITLE
stable/v22.07 branch not tidy

### ISSUE THREAD

**Issue by bernot-dev** [NetApp/trident#767]
**Describe the bug**
When running `go mod tidy` on the stable branch, a diff is generated.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 22.07
- Trident installation flags used: N/A
- Container runtime: N/A
- Kubernetes version: N/A
- Kubernetes orchestrator: N/A
- Kubernetes enabled feature gates: N/A
- OS: N/A
- NetApp backend types: N/A
- Other:

**To Reproduce**
```
~/trident (stable/v22.07|u=)$ go mod tidy
~/trident (stable/v22.07 *|u=)$ git diff
diff --git a/go.sum b/go.sum
index b43300a6..ce464a58 100644
--- a/go.sum
+++ b/go.sum
@@ -418,8 +418,6 @@ github.com/imdario/mergo v0.3.12/go.mod h1:jmQim1M+e3UYxmgPu/WyfjB3N3VflVyUjjjwH
 github.com/inconshreveable/mousetrap v1.0.0 h1:Z8tu5sraLXCXIcARxBp/8cbvlwVa7Z1NHg9XEKhtSvM=
 github.com/inconshreveable/mousetrap v1.0.0/go.mod h1:PxqpIevigyE2G7u3NXJIT2ANytuPF1OarO4DADm73n8=
 github.com/jessevdk/go-flags v1.4.0/go.mod h1:4FA24M0QyGHXBuZZK/XkWh8h0e1EYbRYJSGM75WSRxI=
-github.com/jinzhu/copier v0.3.5 h1:GlvfUwHk62RokgqVNvYsku0TATCF7bAHVwEXoBh3iJg=
-github.com/jinzhu/copier v0.3.5/go.mod h1:DfbEm0FYsaqBcKcFuvmOZb218JkPGtvSHsKg8S8hyyg=
 github.com/joho/godotenv v1.3.0/go.mod h1:7hK45KPybAkOC6peb+G5yklZfMxEjkZhHbwpqxOKXbg=
 github.com/jonboulle/clockwork v0.1.0/go.mod h1:Ii8DK3G1RaLaWxj9trq07+26W01tbo22gdxWY5EU2bo=
 github.com/jonboulle/clockwork v0.2.2/go.mod h1:Pkfl5aHPm1nk2H9h0bjmnJD/BcgbGXUBGnn1kMkgxc8=
```

**Expected behavior**
go.sum on the branch should be in sync with go.mod.

**Additional context**
I am using an automated build system that expects the repo to be in a good state, and errors out due to this difference.

**Comment by gnarl** [comment]
Hi @bernot-dev,

It was determined that an additional change went in to 22.07 after the dependency update commit was merged that caused this issue. The team is taking steps to improve our automation so that this doesn't happen with a future release Trident release.

**Comment by bernot-dev** [comment]
Does it make sense for me to open a PR to fix this? Or is there another change forthcoming that will include this fix?

**Comment by gnarl** [comment]
Hi @bernot-dev,

It doesn't really make sense to open a PR to fix this. The team may decide to add this check in the CI/CD pipeline instead of adding it to the Makefile. Thanks for the offer though.

**Comment by jwebster7** [comment]
@bernot-dev Thank you for reporting this. The Trident team has added automation to catch untidy modules in future releases. Closing this as it is now addressed.
