### ISSUE TITLE
Support for Kubernetes v1.25+

### ISSUE THREAD

**Issue by SNY93** [NetApp/trident#778]
Install failed; could not delete pod security policy; the server could not find the requested resource.  Resolve the issue; use 'tridentctl uninstall' to clean up; and try again.

Pod Security Policies are deprecated and removed on 1.25 onwards
https://kubernetes.io/docs/concepts/security/pod-security-policy/

**Comment by wonderland** [comment]
This should be addressed with the upcoming 22.10 release within the next few days.

**Comment by gnarl** [comment]
Hi @SNY93,

Kubernetes v1.25.0 was released  on 08/22/22 which was after the last Trident Release. The Trident v22.10.0 release will support Kubernetes v1.25.
