### ISSUE TITLE
RFE: Specify the default min/max/burst IOPS with the SolidFire driver

### ISSUE THREAD

**Issue by adkerr** [NetApp/trident#78]
_Originally opened by @acsulli as netapp/netappdvp#8_

When creating a volume using the SolidFire driver, and no type is specified during the create process, the SolidFire array will create the volume with a default QoS policy of minimum 50 IOPS, max 15000 IOPS, and burst of 15000 IOPS. It would be better if default values could be specified in the driver config file during startup.

Andrew

**Comment by korenaren** [comment]
See https://netapp-trident.readthedocs.io/en/stable-v19.07/docker/use/backends/solidfire_options.html#element-os-solidfire-volume-options

If you don't specify these settings, the default will be set by the backend.

**Comment by balaramesh** [comment]
You can also define types and Virtual Storage Pools in Trident's backend config for Kubernetes. See https://netapp-trident.readthedocs.io/en/stable-v19.07/kubernetes/operations/tasks/backends/element.html#example-configuration for more information.
