### ISSUE TITLE
Tag 99.99.99 appeared in docker registry

### ISSUE THREAD

**Issue by felixhuettner** [NetApp/trident#782]
**Describe the bug**
On hub.docker.com the trident releases `99.99` and `99.99.99` appeared.
https://hub.docker.com/r/netapp/trident-operator/tags?page=1&name=99.99

Image link is this: https://hub.docker.com/layers/netapp/trident-operator/99.99/images/sha256-e149ba58aa0ce87566fee9c4c79b4c65907c1d113833478817af969a7806e856?context=explore

This would be quite a large version jump and there is also no matching github release for that. So i assume it was pushed in error.

However since the releases are valid semver versions any tool for automated updates will now suggest to their users to update to this version.

I guess it should be removed and found out how it came there in the first place

**Comment by bassplay3r** [comment]
Sorry about that. It was a script escape. The offending tags have been removed

**Comment by felixhuettner** [comment]
ok, thank you

**Comment by bassplay3r** [comment]
I need to do some more testing to ensure there are no more escapes. You might see some more 99 versions but I will monitor and remove them ASAP.
