### ISSUE TITLE
nouuid mount option for XFS volumes lost when mountOptions are defined in StorageClass

### ISSUE THREAD

**Issue by tongpu** [NetApp/trident#788]
**Describe the bug**
In our environment we've run into the issue reported in #514, but we're already running v22.01.1, which should contain the fix.

After further investigation we believe that this is caused, because we've configured the `discard` mount option in our StorageClass, which seems to cause the `nouuid` option to not be added anymore.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 22.01.1
- Trident installation flags used: -
- Container runtime: CRI-O 1.23.3
- Kubernetes version: 1.23.5
- Kubernetes orchestrator: OpenShift 4.10.35
- Kubernetes enabled feature gates: -
- OS: Red Hat Enterprise Linux CoreOS 410.84
- NetApp backend types: ONTAP

**To Reproduce**
* Create a StorageClass using ontap-san (or ontap-san-economy)
* Configure `mountOptions: ["discard"]` in the StorageClass
* Create a PV and attach it to a pod

**Expected behavior**
* Mount options for the PV should contain `nouuid` and `discard`

**Observed behavior**
* Mount options only contains `discard`

**Comment by clintonk** [comment]
Hello, @tongpu.  This is expected, as the set of mount options specified in the storage class (if present) fully replace the set of mount options configured in a Trident backend.  Mount options specified in both places could easily conflict, and given the wide array of available mount options, attempting to cleanly resolve such conflicts doesn't sound feasible.

https://github.com/NetApp-openstack-dev/trident/blob/master/frontend/csi/controller_server.go#L365
