### ISSUE TITLE
RFE: Ability to specify a Protection Policy

### ISSUE THREAD

**Issue by adkerr** [NetApp/trident#79]
_Originally opened by @jamespohl as netapp/netappdvp#67_

In our environment we have a filer back up volumes to another filer.

When a docker volume is created with the plugin, the volume is not backed up automatically.

It would be nice to have the ability to specify/create the backup relationship automatically.

---

@innergy:
This hasn't been well-documented yet, but you can specify a snapshot policy for any volume created through the nDVP by specifying a 'snapshotPolicy' in your create command.

For example:
docker volume create -d netapp --name=vol -o snapshotPolicy=default

Does that suffice for your use case? Or were you looking for something more?

---

@jamespohl:
My thought was to have the ability for protection policy set up to replicate to another filer. So, the volume is created and mounted on filer1, then a protection policy is set up to replicate to the backup cluster.

**Comment by gnarl** [comment]
Closing this issue as the snapshotPolicy feature is supported for nDVP created volumes.
