### ISSUE TITLE
Do I still need tridentctl to create a Backend?

### ISSUE THREAD

**Issue by gprossliner** [NetApp/trident#790]
The documentation [Deploying with the Trident Operator](https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/operator-install.html) mentions `tridentctl` is multiple places, like in the "Creating a Trident Backend" section.

But if I install a TridentOrchestrator object, I have a CRD named `TridendBackend`. Is it possible to configure a backend using the kubernetes api only? Or do I really need to use `tridentctl`, even with the operator?

Thank you

**Comment by wonderland** [comment]
No, you don't :-) 

Documentation has been moved here (readthedocs is outdated): https://docs.netapp.com/us-en/trident/index.html

And specifically on creating/managing backends via kubectl: https://docs.netapp.com/us-en/trident/trident-use/backend-kubectl.html

**Comment by gprossliner** [comment]
It works perfectly.
