### ISSUE TITLE
Support running on single SVM

### ISSUE THREAD

**Issue by carlcantprogram** [NetApp/trident#8]
Does the plugin support logging in to a cluster/data vserver?

**Comment by adkerr** [comment]
Currently trident requires a cluster-scoped user account to work, however we do have SVM-scoped account support on the roadmap

**Comment by adkerr** [comment]
Tracked internally as [US2167](https://rally1.rallydev.com/#/47479883219d/detail/userstory/86443088400)

**Comment by carlcantprogram** [comment]
I built docker images based off the latest code base. They are at https://hub.docker.com/r/carln/
Using the latest code trident container is now able to provision volumes on an SVM, using the SVM interface.
Thanks guys.

**Comment by innergy** [comment]
Fixed in 17.04.0
