### ISSUE TITLE
How add tag on NetApp Volume

### ISSUE THREAD

**Issue by dtrouillet** [NetApp/trident#805]
**Describe the solution you'd like**
Add the availibilty to add tag from pvc to a NetApp Volume

**Additional context**
We wants to add tag on NetApp Volume to manage it easily. On NetApp I see that we can use tag on volume creation https://docs.netapp.com/us-en/ontap/fabricpool/assign-new-tag-volume-creation-task.html but cannot find anything else on Astra Trident documentation.

Regards

**Comment by wonderland** [comment]
I don't think that is possible today. The tag mechanism referenced in the link is for tiering data off to an object store, it does not provide a generic tagging/labeling mechanism for volumes in Ontap. 

Not sure if duplicating tags/labels would be the best approach. The Ontap volume name includes the K8s PV name so you can always cross-reference. Or use the tridentvolume CRD, which has the "Internal name" field that gives you the full Ontap volume name for any PV. That way you can do any filtering/sorting/... natively in K8s and still relate to the Ontap volume whenever needed.

But not sure what the use case is and if this would work.
