### ISSUE TITLE
Guidance on configuring NFSv3 and/or NFSv4 across host, trident and ontap

### ISSUE THREAD

**Issue by martencassel** [NetApp/trident#807]
**Describe the solution you'd like**

Configuring NFSv3 or NFSv4 on ONTAP can quite be complex task in the field and very easily lead to misconfigurations on a multitude of places (host, ontap svm (export policy, nfs settings, auth methods, trident).

In many cases people just might be wants just NFSv4 to work as NFSv3. When it comes to Kerberos, not many customers i worked with use this, if they do then its because the security team mandates it. But this is perhaps another story.

In many cases there are two parties involved, the devops team that sets up Trident and then the ONTAP administrator, and also the administrator who need to configure linux hosts. In my experience setting up Trident end-to-end with all this, could takes many days.
Perhaps consider some guidance on good defaults for example ONTAP NFS v3 and NFSv4 to help someone speed up the deployment of Trident.

In the best of worlds, why couldn't trident cli auto-configure an SVM for various common scenarios or give you configuration defaults to get started ? 

**Describe alternatives you've considered**
Learn the nitty gritty details of configuring ONTAP and NFSv3 and NFSv4.

**Comment by gnarl** [comment]
@martencassel, thanks for the feedback on Trident examples. We'll consider how to improve the documentation as far as having some quick start examples. To really understand how to apply different NFS options, in your StorageClass's mountOptions, you will want to refer to the [NFS in NetApp ONTAP Technical Report](https://www.netapp.com/media/10720-tr-4067.pdf).
