### ISSUE TITLE
podsecuritypolicy on kubernetes 1.25 with helm deployment throwing error Error: UPGRADE FAILED: unable to build kubernetes objects 

### ISSUE THREAD

**Issue by rakkatta424** [NetApp/trident#809]
**Describe the bug**

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: [e.g. 19.10]
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml]
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: [e.g. 1.15.1]
- Kubernetes orchestrator: [e.g. OpenShift v3.11, Rancher v2.3.3]
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: [e.g. RHEL 7.6, Ubuntu 16.04]
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7]
- Other:

**To Reproduce**

**Expected behavior**

**Additional context**

**Comment by rakkatta424** [comment]
we are trying to install trident 22.10.0 on anthos 1.14.1 -which is using kubernetes version 1.25 and facing below error 
fatal: [localhost]: FAILED! => changed=false 
  attempts: 4
  command: /usr/local/bin/helm --version=22.10.5 upgrade -i --reset-values --wait --create-namespace --values=/tmp/values.yaml trident-operator-release anthos-onPrem/trident-operator
  msg: |-
    Failure when executing Helm command. Exited 1.
    stdout:
    stderr: Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "tridentoperatorpods" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
    ensure CRDs are installed first
  stderr: |-
    Error: UPGRADE FAILED: unable to build kubernetes objects from current release manifest: resource mapping not found for name: "tridentoperatorpods" namespace: "" from "": no matches for kind "PodSecurityPolicy" in version "policy/v1beta1"
    ensure CRDs are installed first
  stderr_lines: <omitted>
  stdout: ''

**Comment by gnarl** [comment]
Hi @rakkatta424,

We recommend that you open a NetApp support case to help you out with this upgrade issue. 

If you want to try and solve this issue via this GitHub Issue then you'll need to fill out the information that we request in the GitHub Issue template. We need this information so that we can give you proper instructions.

**Comment by sjpeeris** [comment]
Closing. Please re-open if you notice this issue with newer versions of Trident.
