### ISSUE TITLE
SolidFire: Manipulate the Attributes reported for ndvp/trident managed volumes

### ISSUE THREAD

**Issue by adkerr** [NetApp/trident#81]
_Originally created by @plz as netapp/netappdvp#83_

In our company we use ndvp via trident for our openshift cluster.

It would be good to append extra information to the volume attributes upon creation, like for example the openshift project.

I logged the issue here because I saw solidfire_san.go:Create is the function that actually populates these attributes, but probably trident should be providing them.

The use case behind this is that when looking at resource usage on a SF cluster, all volumes belong to the same account, in this case trident so having extra metadata regarding each individual volume could give our usage reports better granularity.

Pablo

**Comment by gnarl** [comment]
This enhancement is included in the Trident 20.07 release.
