### ISSUE TITLE
K8S PSP getting created after setting excludePodSecurityPolicy to true

### ISSUE THREAD

**Issue by KuldeepSharmaTR** [NetApp/trident#819]
**Describe the bug**

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 23.01.1
- Trident installation flags used: Using Helm
- Container runtime: containerd
- Kubernetes version: 1.23
- Kubernetes orchestrator: EKS 1.23
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: Amazon Linux
- NetApp backend types: [e.g. CVS for AWS, ONTAP AFF 9.5, HCI 1.7]
- Other:

**To Reproduce**
Steps to reproduce the behavior: Deploy trident-operator helm chart with excludePodSecurityPolicy: true

**Expected behavior**
No PodSecurityPolicy should be created for trident.

**Additional context**
trident-controller and trident-node-linux PSPs are getting created even after setting excludePodSecurityPolicy to true.

**Comment by Xavier-0965** [comment]
The same problem occures with Trident version 23.04 on openshift 4.11.33 (with kubernetes 1.24)

    $ oc get psp
    Warning: policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
    NAME                 PRIV    CAPS   SELINUX    RUNASUSER   FSGROUP    SUPGROUP   READONLYROOTFS   VOLUMES
    trident-controller   false          RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            hostPath,projected,emptyDir
    trident-node-linux   true           RunAsAny   RunAsAny    RunAsAny   RunAsAny   false            hostPath,projected,emptyDir

**Comment by mreiche** [comment]
Seems to be fixed in helm chart `23.07.1`. After removing the PSPs manually, there weren't recreated during helm deployment. Can anyone confirm too?

**Comment by sjpeeris** [comment]
Hi @KuldeepSharmaTR Please let us know if this issue still exists with the newer versions of Trident. If not, please close the issue.

**Comment by sjpeeris** [comment]
Closing. Please re-open if you notice this issue with newer versions of Trident.
