### ISSUE TITLE
Ugrade backend question

### ISSUE THREAD

**Issue by mmcalcagni** [NetApp/trident#820]
I have some trident backends for which I would like to introduce new attributes to limit the size of the volumes that are generated. The parameters in question are the following: _limitAggregateUsage_ and _limitVolumeSize_. Could there be any impact or disruption as far as the pods present?

I guess not, but would like to confirm.
Thanks

**Comment by clintonk** [comment]
Hello, @mmcalcagni.  No, those parameters are applied only when provisioning new volumes.

**Comment by gnarl** [comment]
Closing this issue as answered.
