### ISSUE TITLE
Problem initializing storage driver 'ontap-san'

### ISSUE THREAD

**Issue by rageanilkumar** [NetApp/trident#823]
Trying to deploy backend-tbc-ontap-san.yaml but it's throwing some errors with Problem initializing storage driver 'ontap-san'

PFB YAML FILE of backend-tbc-ontap-san.yaml:

apiVersion: v1
kind: Secret
metadata:
  name: backend-fsx-ontap-san-secret
type: Opaque
stringData:
  username: ZnN4YWRtaW4=
  password: cHJpbWVmb2N1c0AyMDIwJA==
---
apiVersion: trident.netapp.io/v1
kind: TridentBackendConfig
metadata:
  name: backend-fsx-ontap-san
spec:
  version: 1
  storageDriverName: ontap-san
  managementLIF: 10.206.16.51
  svm: "nv-pp-usdc-eks-fsxontap1-svm1"
  credentials: 
    name: backend-fsx-ontap-san-secret   

PFB ERROR Message from kubectl describe tridentbackendconfig -n trident:

D:\USDCPREP\usdcprep\trident> kubectl describe tridentbackendconfig -n trident
Name:         backend-fsx-ontap-san
Namespace:    trident
Labels:       <none>
Annotations:  <none>
API Version:  trident.netapp.io/v1
Kind:         TridentBackendConfig
Metadata:
  Creation Timestamp:  2023-05-12T05:23:09Z
  Finalizers:
    trident.netapp.io
  Generation:  1
  Managed Fields:
    API Version:  trident.netapp.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:credentials:
          .:
          f:name:
        f:managementLIF:
        f:storageDriverName:
        f:svm:
        f:version:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-05-12T05:23:09Z
    API Version:  trident.netapp.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"trident.netapp.io":
    Manager:      trident_orchestrator
    Operation:    Update
    Time:         2023-05-12T05:23:09Z
    API Version:  trident.netapp.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:backendInfo:
          .:
          f:backendName:
          f:backendUUID:
        f:deletionPolicy:
        f:lastOperationStatus:
        f:message:
        f:phase:
    Manager:         trident_orchestrator
    Operation:       Update
    Subresource:     status
    Time:            2023-05-12T05:23:13Z
  Resource Version:  48428015
  UID:               5628dca7-273a-476a-8b77-191ab7af7cd3
Spec:
  Credentials:
    Name:               backend-fsx-ontap-san-secret
  Management LIF:       10.206.16.51
  Storage Driver Name:  ontap-san
  Svm:                  nv-pp-usdc-eks-fsxontap1-svm1
  Version:              1
Status:
  Backend Info:
    Backend Name:
    Backend UUID:
  Deletion Policy:        delete
  Last Operation Status:  Failed
  Message:                Failed to create backend: problem initializing storage driver 'ontap-san': error initializing ontap-san driver: could not create Data ONTAP API client: error creating ONTAP API client: error reading SVM details: response code 401 (Unauthorized): incorrect or missing credentials
  Phase:
Events:
  Type     Reason  Age               From                    Message
  ----     ------  ----              ----                    -------
  Warning  Failed  3s (x3 over 12s)  trident-crd-controller  Failed to create backend: problem initializing storage driver 'ontap-san': error initializing ontap-san driver: could not create Data ONTAP API client: error creating ONTAP API client: error reading SVM details: response code 401 (Unauthorized): incorrect or missing credentials

Need help to fix this issue

Regards,
Rage Anilkumar

**Comment by balaramesh** [comment]
@rageanilkumar sorry for being late to respond. You are likely using the wrong ONTAP password/username. Were you able to get past this issue?

**Comment by BrankoPavlovic10** [comment]
@sjpeeris Any update on this?
I am facing the same issue..

**Comment by sjpeeris** [comment]
Hi @BrankoPavlovic10 Have you tried upgrading to a newer version of Trident. This does not seem to be a Trident bug. Can you please open a NetApp support case for this and the support engineers will help troubleshoot this issue.

**Comment by scaleoutsean** [comment]
I don't know why no one can post updates and expects others to post theirs but FWIW one case where this can happen is if you base64-encode the password (and perhaps the username, too?) without stripping `\n` from the string.
As such, it is more likely to affect deployments that use K8s secrets, whereas with `tridentctl` you can still supply plaintext password in backend config file and avoid experiencing this problem due to base64 encoding.
There are other reasons why this happens (ONTAP f/w, ONTAP API not enabled and ZAPI disabled, etc.).
