### ISSUE TITLE
Document uninstallation

### ISSUE THREAD

**Issue by adkerr** [NetApp/trident#83]
_Originally created by @scaleoutsean as netapp/netappdvp#101_

Plugin uninstallation is not documented. Can it be added?

There are two ways to install, so if one wants to switch from one to another, I suppose it's reasonable to need these steps.

Edit: one reason why I created this issue is that sometimes plugin uninstall doesn't work properly and a host reboot is required (probably a Docker issue, but later we can debug it or document that a reboot is required).

---

@miguelgm:
👍 

It would be great to also add an upgrade procedure if there is other than uninstall and install the new version.

**Comment by dxlr8r** [comment]
+1 for upgrade procedure

**Comment by innergy** [comment]
We have this mostly documented already:

Docker upgrade: http://netapp-trident.readthedocs.io/en/stable-v18.01/docker/install/upgrade.html

Kubernetes upgrade and uninstall: http://netapp-trident.readthedocs.io/en/stable-v18.01/kubernetes/operations/tasks/trident.html#updating-trident

The only thing missing is the Docker uninstall, which is simply the standard Docker plugin management method of a “docker plugin disable” followed by a “docker plugin rm”. We will be adding that soon.
