### ISSUE TITLE
Docker plugin: Debugging not working since 23:04

### ISSUE THREAD

**Issue by melck** [NetApp/trident#833]
**Describe the bug**
I have no debug log when i set debug=true with docker plugin in trident version 23.04.

**Environment**
OS: Debian 11
Docker: docker-ce:24.0.2-1~debian.11~bullseye
Trident: 23.04
Netapp backend ONTAP 9.11 

**To Reproduce**

- `docker plugin install netapp/trident-plugin:23:04 --alias netapp debug=true` 
- journalctl -u docker 

**Expected behavior**

I'm suppose too some level=debug on logs.

**Additional context**

I saw [this line](https://github.com/NetApp/trident/blob/stable/v23.01/main.go#L221) disapeared for version 23:04.

**Comment by sjpeeris** [comment]
Hi @melck Please let us know if this issue still exists with the newer versions of Trident.

**Comment by sjpeeris** [comment]
Closing. Please re-open if you notice this issue with newer versions of Trident.
