### ISSUE TITLE
Expand PVC uses VolumeSize and ignored Snapshot reserve

### ISSUE THREAD

**Issue by tgoetheyn** [NetApp/trident#834]
**Describe the bug**
Fails to expand PVC if the new requested size is smaller than the total volume size.
This should be calculated on the DataSize instead (= Volume size - SnapshotReserve)

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 22.10
- Trident installation flags used: Default install through Helm
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: v1.25.8+37a9a08
- Kubernetes orchestrator: Openshift 4.12.18
- Kubernetes enabled feature gates:
- OS: RHEL CoreOS 412.86.202305161131-0 (Ootpa)
- NetApp backend types: ONTAP 9.12.1P2
- Other:

**To Reproduce**

- Create a TridentBackendConfig with the "ontap-nas" storagedriver and a default snapshotreserve of 30%
- Create PVC of 10GB using this TridentBackendConfig 
- Expand the PVC to 11GB
- PVC expand fails with an error because 11Gb is smaller than the current volume size which is 13Gb (10Gb data + 3G snapshotreserve)

**Expected behavior**
recalculate new size while take in account the snapshotreserve => set Volume size to 14,3Gb (= 11Gb data space + 30% snapshot reserve)

**Additional context**

**Comment by tgoetheyn** [comment]
Problem still exists in 23.07

**Comment by sjpeeris** [comment]
Closing. Please re-open if you notice this issue with newer versions of Trident.
