### ISSUE TITLE
E-Series support with Embedded API systems

### ISSUE THREAD

**Issue by adkerr** [NetApp/trident#84]
_Originally created by @plz as netapp/netappdvp#104_

[Current docs](http://netappdvp.readthedocs.io/en/stable/install/ndvp_e_config.html#example-e-series-config-file) have references to systems running behind the E-Series rest proxy, but are systems running the Embedded System Manager(like e2800 family) also supported on netapp dvp?

If so, it would be good to have the documentation stating it, and also some of the configurations directives, make less sense or need to be named differently.

_(edited from original to fix link)_

---

@adkerr:
Yes, the embedded proxy is also supported. Will take an action to clarify the documentation.

**Comment by gnarl** [comment]
This issue was fixed with the [Trident 20.01.1 ](https://github.com/NetApp/trident/releases/tag/v20.01.1)release.
