### ISSUE TITLE
Trident v22.10 - mount.nfs: access denied by server while mounting

### ISSUE THREAD

**Issue by vveeregandha** [NetApp/trident#845]
**Describe the bug**
As the latest Trident releases auto export the subnet to the export policy for the target volume, we are still seeing access denied errors randomly on some of the nodes in our Kubernetes 1.22 cluster. The issue goes away when we restart the trident pod on the particular node where the issue is seen.

**Environment**
Kubernetes 1.22 cluster, os on the nodes: ubuntu 20.04

- Trident version: 22.10
- Container runtime: contained v1.6.4
- Kubernetes version: v1.22.8
- Kubernetes orchestrator: kubespray
- Kubernetes enabled feature gates: [e.g. CSINodeInfo]
- OS: Ubuntu 20.04
- NetApp backend types: ontap-nas

**To Reproduce**
The problem appears randomly on some nodes in the cluster and goes away after the restart of the trident pod.

**Expected behavior**
No issues seen with mount access when using trident v22.10 version

**Comment by sjpeeris** [comment]
Closing. Please re-open if you notice this issue with newer versions of Trident.
