### ISSUE TITLE
Logical validation of values in config.json

### ISSUE THREAD

**Issue by adkerr** [NetApp/trident#85]
_Originally created by @scaleoutsean as netapp/netappdvp#105_

I came across this today, using `netapp:17.07` - it seems some values aren't sanity-checked - for example SVIP in the example below:

```json
{
	"version": 1,
	"storageDriverName": "solidfire-san",
	"Endpoint": "https://admin:admin@192.168.160.3/json-rpc/7.0",
	"SVIP": " 10.0.0.7:3260",
	"TenantName": "docker",
	"InitiatorIFace": "default"
}
```
Clearly this is a valid JSON file, but the SVIP value is incorrect and results in some interesting problems down the road.

This is similar to netapp/netappdvp#56.

_(edited from original to fix issue reference)_

**Comment by gnarl** [comment]
This was fixed with commit [7e82882](https://github.com/NetApp/trident/commit/7e82882d2098841dfb963f6f9057e8ce5fd0e659).
