### ISSUE TITLE
Permission denied to mount fs with docker usernamespace

### ISSUE THREAD

**Issue by adkerr** [NetApp/trident#86]
_Originally created by @tbouvet as netapp/netappdvp#110_

My docker engine is configured with usernamespace.

> ```
> "userns-remap": "dockremap"
> ```

I try to mount a netapp volume but an error occurred :

```
docker: Error response from daemon: oci runtime error: container_linux.go:265: starting container process caused "process_linux.go:368: container init caused \"rootfs_linux.go:57: mounting \\\"/var/lib/docker/100000.100000/plugins/4ce13dd16de418316548a799f3857fa6986217829b6e015afa388cd2b288a46d/rootfs/var/lib/docker-volumes/netapp/secondVolume\\\" to rootfs \\\"/var/lib/docker/100000.100000/overlay2/953c331d0b1b8bff4981da209c8385071e33274abca12689abfe64c3e19c6dc4/merged\\\" at \\\"/my_vol\\\" caused \\\"stat /var/lib/docker/100000.100000/plugins/4ce13dd16de418316548a799f3857fa6986217829b6e015afa388cd2b288a46d/rootfs/var/lib/docker-volumes/netapp/secondVolume: permission denied\\\"\"".
```
To reproduce :

- add userns option to the docker daemon
- docker volume create -d netapp --name secondVolume
- docker run --rm -it --volume-driver netapp --volume secondVolume:/my_vol alpine ash

The result is the error.

**Comment by rverpillot** [comment]
Same issue with user namespace enabled and Trident plugin 18.04
Can't run container after installing this plugin. Moreover we must reboot the VM after disabling it to start containers.

**Comment by kangarlou** [comment]
@tbouvet @rverpillot Could you please answer the following questions? 

1. What OS are you using?  
2. How did you enable the user namespace feature?  
There seem to be a few options to enable this feature from reading the docs and it would be helpful to know if Docker is creating the user manually or if you created the user and populated the /etc/subguid /etc/subuid files manually.
3. For the older version of nDVP that worked, which version are you using and how are you running it?  Plugin mode?  Binary mode?

Thanks!

**Comment by tbouvet** [comment]
1. Ubuntu 16.04 OS
2. User is manually created and then the 2 files /etc/subguid and /etc/subuid are populated.
3. Version nDVP: netapp/ndvp-plugin:17.10. Plugin mode is used.
```
docker plugin install --grant-all-permissions --alias netapp netapp/ndvp-plugin:17.10
```

**Comment by innergy** [comment]
Fixed by https://github.com/NetApp/trident/commit/3393e515bfabeb5a82962f4c5416bb67de0dff15
