### ISSUE TITLE
No 23.10.0 tag or release

### ISSUE THREAD

**Issue by tmsdce** [NetApp/trident#863]
**Describe the bug**
Not really a bug per se.
A new chart version v23.10.0 seems to have been published 4 days ago. The docker image 23.10.0 is also available. But there is no associated git tag nor release for 23.10.0 on the github repo. Is it expected (maybe the release process has changed since 23.07.1) ? It is quite confusing and I'd like to be sure that this is actually a working release before upgrading

**Environment**
Any environment

**To Reproduce**
No git tag (or release)

**Expected behavior**
A proper git tag and release should be created, similar to the past releases

**Additional context**
Not relevant

**Comment by tmsdce** [comment]
Hi @bassplay3r thanks for your quick reply
I wrongly assumed that the container image and chart were to be published at release time. I'll wait for the full release then

**Comment by wonderland** [comment]
Release is now available :-)
https://github.com/NetApp/trident/releases/tag/v23.10.0

**Comment by tmsdce** [comment]
Thanks @wonderland and sorry for the noise
