### ISSUE TITLE
Prevent/Suppress "ACP is not enabled." and "Trident-ACP version is empty." messages

### ISSUE THREAD

**Issue by RuairiSinkler** [NetApp/trident#866]
**Describe the solution you'd like**
Since upgrading from `23.01.0` to `23.10.0` I am repeatedly seeing the "ACP is not enabled." and "Trident-ACP version is empty." messages in our Trident Controller `trident-main` logs.

I am using Trident on its own, without any of the other Astra services, and would like these log lines to not appear.

There should be a way of specifying this feature is not needed to prevent the noisy log line, and/or the documentation updated to describe how.

**Describe alternatives you've considered**
I have tried to search the documentation for a way to prevent these messages from appearing, but ACP does not appear anywhere in the Trident config documentation.

I did find the `tridentLogWorkflows` and `tridentLogLayers` configuration options here https://docs.netapp.com/us-en/trident/trident-get-started/kubernetes-deploy-helm.html - they say they can be "enabled for trace logging or **_log suppression_**", but it is not clear how they should be specified, in particular how to use them for log **_suppression_**.

From the log messages, it appears the `rest_frontend` layer and/or (more likely) the `core=version` workflow could be suppressed to hide this message, but as I say the documentation is not clear on how to achieve this.

**Comment by elmazzun** [comment]
I wonder if it is possible to mute this error by specifying a version of ACP or, if doing so, I risk making the situation worse.

**Comment by RuairiSinkler** [comment]
I don't think I would want to specify a version if it isn't in use, I'm not sure what that would cause (i.e. would it attempt to install ACP?)

I'm also not sure where I would specify the version

**Comment by Cajga** [comment]
We run into the same here. Just to make it clear: **a warning and an error message appears in the logs every 5 seconds**:
```
time="2023-11-16T15:23:05Z" level=warning msg="ACP is not enabled." logLayer=rest_frontend requestID=b7b60117-b6fb-486b-a809-56fd224fb8b1 requestSource=REST workflow="core=version"
time="2023-11-16T15:23:05Z" level=error msg="Trident-ACP version is empty." error="<nil>" logLayer=rest_frontend requestID=b7b60117-b6fb-486b-a809-56fd224fb8b1 requestSource=REST workflow="core=version"
time="2023-11-16T15:23:10Z" level=warning msg="ACP is not enabled." logLayer=rest_frontend requestID=ee442efa-c3ed-419f-9994-2c37aafef9b9 requestSource=REST workflow="core=version"
time="2023-11-16T15:23:10Z" level=error msg="Trident-ACP version is empty." error="<nil>" logLayer=rest_frontend requestID=ee442efa-c3ed-419f-9994-2c37aafef9b9 requestSource=REST workflow="core=version"
```

**Comment by elmazzun** [comment]
@Cajga the very same is happening to me: couple of warning and error messages each time

**Comment by ntap-arorar** [comment]
For non-ACP installations (Trident-only), these should be debug messages and not warnings.
There is a need to convert the warning to debug messages [here](https://github.com/NetApp/trident/blob/80ffc0265f99cf29d91dc5567358c56559f8aa95/acp/client.go#L62) and [here](https://github.com/NetApp/trident/blob/80ffc0265f99cf29d91dc5567358c56559f8aa95/acp/client.go#L87).

Also, the error "Trident-ACP version is empty." should only be thrown for ACP installations.

**Comment by elmazzun** [comment]
@ntap-arorar so those messages are pretty much harmless?

**Comment by Cajga** [comment]
Yes, they are (unless you want/configured to use ACP of course :) ). They are just annoying as there are many of them (and they are error messages not warning)...

**Comment by bert-jan** [comment]
+1 to fix this issue. It's very confusing when debugging other trident issues for example when running into issue #490.

**Comment by josesimon** [comment]
It is really annoying to read logs with these unnecessary messages. Being able to exclude them from the configuration would be a good idea for me.

**Comment by ntap-arorar** [comment]
Fixes: https://github.com/NetApp/trident/commit/c921c8b31adc85159566b2ce1ef39735aa7a0db8 and https://github.com/NetApp/trident/commit/d7aa5002f0d7bee2c566478448cc38b6482592b3 should address this issue and will be part of the upcoming release.
