### ISSUE TITLE
Keep operatorhub.io current

### ISSUE THREAD

**Issue by lukasertl** [NetApp/trident#867]
Right now you can install version 22.10 through operatorhub.io; this version is more than a year old.

Could you please keep the version on operatorhub.io more current?

Thank you.

**Comment by abhinov-netapp** [comment]
Hello, we have updated the Trident version to v23.10, please refer to: https://operatorhub.io/operator/trident-operator

**Comment by uppuluri123** [comment]
operatorhub.io is updated. Closing the issue.
