### ISSUE TITLE
Trident can not delete, create or map nvme/tcp namespaces to subsystems while in failover on a metrocluster ip

### ISSUE THREAD

**Issue by sithglan** [NetApp/trident#869]
**Describe the bug**
Trident v23.10.0 can not delete, create, map nvme/tcp namespaces to subsystems while in failover on a metrocluster ip.

**Environment**
Upstream Kubernetes v1.28.3, trident v23.10.0, metrocluster ip aff a220 9.13.1P2

- Trident version: v23.10.0
- Trident installation flags used:

curl -sL https://github.com/NetApp/trident/releases/download/v23.10.0/trident-installer-23.10.0.tar.gz | tar -xzf -
cd trident-installer
sudo cp tridentctl /usr/local/bin
kubectl apply -f deploy/namespace.yaml
echo '  enableACP: true' >> ~/trident-installer/deploy/crds/tridentorchestrator_cr.yaml
echo '  acpImage: registry-06.d.tg.st/trident-acp:23.10.0' >> ~/trident-installer/deploy/crds/tridentorchestrator_cr.yaml
echo '  imagePullSecrets:' >> ~/trident-installer/deploy/crds/tridentorchestrator_cr.yaml
echo '  - astra-registry-cred' >> ~/trident-installer/deploy/crds/tridentorchestrator_cr.yaml
kubectl create -f deploy/bundle_post_1_25.yaml
kubectl create -f deploy/crds/tridentorchestrator_cr.yaml

- Container runtime: containerd.io - 1.6.24-1
- Kubernetes version: v1.28.3
- Kubernetes orchestrator: kubeadm
- Kubernetes enabled feature gates: n/a
- OS: Debian 12
- NetApp backend types: Metrocluster IP AFF A220 v9.13.1.P2
- Other:

**To Reproduce**
https://tg.st/u/ea96f55c3d0cea869670eef24a479972afe70755d90893d548d658f7918a7eb0.txt

**Expected behavior**
When metrocluster ip is in switchover, I expect to be able to create and remove nvme/tcp pv(c)s.

**Additional context**
default      25s         Warning   FailedAttachVolume        pod/nvme-pod                                                AttachVolume.Attach failed for volume "pvc-31688855-f55c-441d-b8b0-12abe5c15519" : volume attachment is being deleted
default      1s          Warning   VolumeFailedDelete        persistentvolume/pvc-31688855-f55c-441d-b8b0-12abe5c15519   persistentvolume pvc-31688855-f55c-441d-b8b0-12abe5c15519 is still attached to node debian-01-02

**Comment by wonderland** [comment]
To my best knowledge, NVMe/TCP ist currently not supported on Metrocluster, and the docs seem to agree: "MetroCluster configurations are not supported on NVMe/TCP."

https://docs.netapp.com/us-en/ontap/nvme/support-limitations.html#features 

In essence, I think this is not a Trident issue, as the underlying storage configuration itself is currently unsupported. 

Sorry for being the bearer of bad news :-(

**Comment by sithglan** [comment]
You're right. Thank you for the heads up. I was under the impression that I read that nvme/tcp is supported for metrocluster ip and I'm using it since 30th March. Anyway the neither the documentation nor IMT says it is supported. So I must have been mistaken.
