### ISSUE TITLE
Trident Operator Helm Chart - unable to get Trident Image version information

### ISSUE THREAD

**Issue by LarsWinters** [NetApp/trident#880]
**Describe the bug**
We have an airgapped environment and want to install the trident operator via the helm chart. We have some policies so we added Resource Quotas and some labels/annotations. However, we have problems with the CRD of the Helm chart.
We pushed the 3 images of the helm chart to our private registry. I already double checked the correct images/versions/tags. 
We get this error message:

`Failed to install Trident; err: unable to get Trident image version information, please ensure correct Trident image has been provided; err: failed to create Trident Version pod from the image provided; failed to create Trident version pod; yamlDocument --- apiVersion: v1 kind: Pod metadata: name: transient-trident-version-pod labels: app: pod.version.trident.netapp.io k8s_version: 1.25.13 ownerReferences: - name: trident uid: 3dbcc4cd-ea10-4528-8abb-7d0e171653bb apiVersion: trident.netapp.io/v1 controller: true kind: TridentOrchestrator spec: serviceAccount: trident-node-linux restartPolicy: Never containers: - name: trident-main imagePullPolicy: Always image: <our_private_registry/netapp/trident:23.10.0> command: ["tridentctl"] args: ["pause"] securityContext: capabilities: drop: - all tolerations: [] affinity: nodeAffinity: requiredDuringSchedulingIgnoredDuringExecution: nodeSelectorTerms: - matchExpressions: - key: kubernetes.io/arch operator: In values: - arm64 - amd64 - key: kubernetes.io/os operator : In values: - linux was not created after 30.00 seconds`

**Environment**
Provide accurate information about the environment to help us reproduce the issue.
Installed via pipelines (argocd)

- Trident version: 23.10
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: 1.25.13
- Kubernetes orchestrator: vmware tkgi 1.16.4-build.7
- Netapp Version: NetApp Release 9.12.1P2
- NetApp backend types: ONTAP AFF 9.5

**To Reproduce**
Deploy trident operator with custom adjustments: ResourceQuotas for Deployment, Annotations/Labels using ArgoCD.

**Expected behavior**
Successfully deployment of trident image.

**Comment by ntap-arorar** [comment]
Hello @LarsWinters 

From the error message, it looks like you have successfully deployed the Trident Operator, however when Trident Operator is trying to deploy Trident it is failing. The error message does not explain the installation's failure, so can you please check the trident-operator logs for the same?
