### ISSUE TITLE
Helm Release 100.2402.0

### ISSUE THREAD

**Issue by JoshPasek** [NetApp/trident#890]
Can someone explain the jump to version 100.2402.0? What would cause chart version 24.02.0 to not work? Is this a permanent change? 

$ helm search repo netapp-trident -l

NAME                            CHART VERSION   APP VERSION     DESCRIPTION
**netapp-trident/trident-operator 100.2402.0      24.02.0         A Helm chart for deploying NetApp's Trident CSI...**
netapp-trident/trident-operator 23.10.0         23.10.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 23.07.1         23.07.1         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 23.07.0         23.07.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 23.04.0         23.04.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 23.01.1         23.01.1         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 23.01.0         23.01.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 22.10.0         22.10.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 22.07.0         22.07.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 22.04.0         22.04.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 22.01.1         22.01.1         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 22.01.0         22.01.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.10.1         21.10.1         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.10.0         21.10.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.07.2         21.07.2         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.07.1         21.07.1         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.04.1         21.04.1         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.04.0         21.04.0         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.01.2         21.01.2         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.01.1         21.01.1         A Helm chart for deploying NetApp's Trident CSI...
netapp-trident/trident-operator 21.01.0         21.01.0         A Helm chart for deploying NetApp's Trident CSI...

**Comment by clintonk** [comment]
Hi, @JoshPasek.  Helm supports SemVer versioning only, while Trident has always used CalVer.  That never caused a problem until we started building Helm-based [add-ons](https://bluexp.netapp.com/blog/aws-fsxn-blg-astra-trident-now-available-as-an-eks-add-on-with-fsx-for-ontap) for managed K8s services.  We don't plan to change Trident versioning, but we needed a way to map that to SemVer for Helm in a way that doesn't look like a downgrade from previous versions.  A secondary goal was to have the Helm version be visually mappable to the Trident version.  So the chart version maps year.month.patch to 100.yearmonth.patch.  Hopefully this doesn't have to change again.

**Comment by lindhe** [comment]
Thank you for bringing this up! It was introduced [here](https://github.com/NetApp/trident/commit/f15c4b21015fced95a94e5b97c7f2ce412bc3375#diff-1d33bd02669c5c0b04dfdaf11d4a4f93064a069376b013639df73f88b9ebbf3e) without any comment and it was so startling that I too wanted to investigate so it wasn't a typo. Changing numbering scheme is fine, but maybe we can be a bit more verbose in the commit messages for larger changes like these? 😄

Is 100 planned to be static, or will you increment it every time there's a breaking change?

I have a related question! In Artifact Hub, the version numbers listed are 23.7.1, 23.10.0, 100.2402.0:

![image](https://github.com/NetApp/trident/assets/7773090/fd869d54-9941-462c-acdd-8e10be306e1b)

But here on GitHub, the chart version number seems to have been 1.24.1, etc., so I wonder if the numbers are changed by some release pipeline or what's going on?

**Comment by clintonk** [comment]
@lindhe  Acknowledged on commit message verbosity.  The 100 should be static unless there is a breaking change, which isn't planned.  And yes, the chart version is updated in automation during release deployment.
