### ISSUE TITLE
Dead 'Edit on Github' link in Trident docs

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#90]
For example, if you go to https://netapp-trident.readthedocs.io/en/stable-v18.01/docker/install/host_config.html#traditional-install-method-docker-1-12 and click on Edit on Github, it's a dead link

**Comment by adkerr** [comment]
This is a bug with readthedocs. We do not add that link in our docs ourselves. Readthedocs seems to be replacing the `/` in `stable/v18.01` with a `-` which is not how GitHub forms the url. I’m not sure we can actually do anything about this.

**Comment by scaleoutsean** [comment]
A fix PR has been merged by RTFD, but not yet deployed.
