### ISSUE TITLE
Add support for disconnected environments

### ISSUE THREAD

**Issue by Klaas-** [NetApp/trident#91]
Hi,
could you enhance your installer to support a disconnected (openshift-enterprise) environment, ie no access to dockerhub to get the images. You could put the images into your installer :)

Greetings
Klaas

**Comment by korenaren** [comment]
We are fixing this with #103, but we're not adding the images to the installer. You'll have to use docker save and docker load to get the images into your environment, if you can't reach dockerhub directly.

**Comment by korenaren** [comment]
Fixed in a0805a4a13888d8a52eb4c3fad2cf1bd2e718f17
