### ISSUE TITLE
Error expanding PVC in OpenShift ARO  

### ISSUE THREAD

**Issue by mcipamo** [NetApp/trident#910]
Hi there,

**Describe the problem:** Customer cannot expand PVC size on ARO cluster using Netapp storage, getting an error: 

`Ignoring the PVC: didn't find a plugin capable of expanding the volume; waiting for an external controller to process this PVC`.

Confirmed that the StorageClass has the `allowVolumeExpansion` flag set to true.

OpenShift Version: 4.13.23

Is there any additional requirement or specific setup needed for the Trident CSI driver, to enable volume expansion in the ARO environment?

Thanks for your assistance

**Comment by wonderland** [comment]
Can you please provide additional details of the PVC, PV and storage class, e.g.

`oc get pvc <pvc-name> -o yaml`

`oc get pv <pv name> -o yaml`  <-- PV Name will be listed in previous output as volumeName

`oc get sc <storage class name> -o yaml`
