### ISSUE TITLE
Autosupport image for 24.06.1 missing

### ISSUE THREAD

**Issue by nheinemans-asml** [NetApp/trident#919]
**Describe the bug**
After upgrading to 24.06.1, we noticed that the corresponding autosupport image is not available on docker hub.

**Environment**
Provide accurate information about the environment to help us reproduce the issue.

- Trident version: 24.06.1

**To Reproduce**
Upgrade helm chart from 24.02.0 to 24.06.1, deployment can't create pods because image version 24.06.1 is not available.

**Expected behavior**
I would expect all images with version tags identical to helm chart version to be available on docker hub.

**Additional context**

**Comment by clintonk** [comment]
Hello, @nheinemans-asml.  We didn't bump that image to 24.06.1, so you should be able to use `netapp/trident-autosupport:24.06.0` or even `netapp/trident-autosupport:24.06`.

**Comment by wonderland** [comment]
I tried to reproduce this in a lab, going from 24.02.0 to 24.06.1 via Helm:

```
helm repo update
helm upgrade trident netapp-trident/trident-operator -n trident --version =100.2406.1
```

This correctly upgraded and all containers (including autosupport) are up and running again afterwards. Which makes sense, as the Helm chart only upgrades the operator, which then handles everything else - and the 24.06.1 operator uses the 24.06 image tag for the autosupport container.

**Comment by nheinemans-asml** [comment]
We were told that all images would always be updated with each release of the helm chart. Our cluster deployment automation and templating is based on that statement (from a NetApp person).

**Comment by clintonk** [comment]
@nheinemans-asml  The Trident YAML omits the patch version on the autosupport image tag so that we don't have to re-release it every time.
