### ISSUE TITLE
 Feature request: Ability to add custom label to backends and then use them for storage classes

### ISSUE THREAD

**Issue by kaparora** [NetApp/trident#92]
When adding a backend add ability to add custom labels to the backed e.g. type=performance \
This will enable them to tag their backends and then define storage class with that tag/label selector.

**Comment by korenaren** [comment]
As of 19.07, this works for the solidfire, e-series, and aws-cvs drivers. Still working on the rest.

**Comment by gnarl** [comment]
The addition of [Virtual Storage Pools](https://netapp-trident.readthedocs.io/en/stable-v20.04/kubernetes/concepts/virtual_storage_pools.html?highlight=virtual%20pools) meets the OP's request.
