### ISSUE TITLE
Tidy up the docs to standardize on plugin version, config file names and aliases

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#94]
Too many people get stuck with due to a variety of versions, config file name and plugin aliases strewn around the docs...  Even the file names are sometimes wrong. For example:

* right now, the docs say to `wget trident-18... ` whereas the actual file name is `trident-installer-18....`
* from time to time, in some places version information can be outdated
* Aliases and configuration filenames are different by product, which is fine, but they could be consistent unless there's some special reason why that isn't a good idea. Or, if we wanted to use different names we should start from the beginning. For example https://netapp-trident.readthedocs.io/en/stable-v18.01/docker/deploying.html suggests to use the alias of `netapp` but the another page (https://netapp-trident.readthedocs.io/en/stable-v18.01/docker/install/host_config.html) uses `ontap-nas.json`, so anyone who reads deploying.html and then follows the other page is likely spend the next 15-30 minutes googling or worse (debugging the network and whatnot). Deploying.html (.rst) should explain that aliases and configuration names differ throughout the document and why that is a good practice (rather than consistent names and aliases).

I am in favor of two improvements:

* use `$LATEST` as the generic version descriptor and publish/symlink the latest release to `trident-latest.tar.gz` and avoid having to constantly crate trivial PRs with hard-coded fixes.
* rename all configuration files `config.json` and all aliases to `netapp`. Otherwise add a small section on best practices and reasons why this shouldn't be done (deploying.rst).

**Comment by korenaren** [comment]
Mostly fixed, at least those that we feel should be corrected.
