### ISSUE TITLE
issues with incorrect NFS mount path for creating rwx volumes in Openshift 4.14.25. Mount path from backend Netapp svm is not considered.

### ISSUE THREAD

**Issue by barani129** [NetApp/trident#943]
**Describe the bug**
We are trying to create a RWX NFS volume with a NFS backend (say: svm-k8s-cluster and backend is /svm_k8s-cluster_NFS_vol).
But trident operator ignores the mount path from backend and updates volume.source.volumeAttributes.internalName with trident_<pvc_name>), this is the expected behaviour as per below code, but why the NFS mount path from the actual backend is not considered in the code?

https://github.com/NetApp/trident/blob/2da1ca087fc7967db1ab450ce299add860804ad6/storage_drivers/ontap/ontap_common.go#L3597

**Environment**
Openshift 4.14.25

- Trident version: 24.02.1
- Trident installation flags used: [e.g. -d -n trident --use-custom-yaml]
- Container runtime: [e.g. Docker 19.03.1-CE]
- Kubernetes version: 1.27.13
- Kubernetes orchestrator: Openshift 4.14.25
- Kubernetes enabled feature gates: NA
- OS: CoreOS (RHEL 9.2)
- NetApp backend types: ONTAP 9

**To Reproduce**
Create a NFS backendconfig with svm name, and create an actual ontap NFS volume with mountpath /svm_k8s_cluster_NFS_vol)

**Expected behavior**
trident updates internalName (mountpath) to /trident_pvc-name instead of /<mountpath from svm>/trident_pvc-name

**Comment by sjpeeris** [comment]
@barani129 is this causing a problem for you in your environment ? Do you mean that Trident is missing an / in the internalName ?

**Comment by barani129** [comment]
Hi @sjpeeris , thanks for responding. Trident volumes are created with an "/" + internalName as seen in the code, but the problem is that it is hardcoded, so mounting the volumes at non-root paths at netapp backend becomes a problem, the backend administrator is forced to give root path access of the SVM to the k8s clusters volumes. 

The expectation is that when a volumes get created with the given NFS Storage class (mounting volumes at /svm_nfs_vol), the internalName should be updated to include /svm_nfs_vol like /svm_nfs_vol/volumeName rather than /volumeName (which is accessing / path irrespective of NFS SC configuration).

**Comment by wonderland** [comment]
Maybe you can describe the use case behind this a bit more? 

In general, you would dedicate an entire SVM to Trident. That SVM can be assigned upper limits in terms of capacity, IOPS, bandwidth and number of volumes. But everything inside that SVM is handled/automated by Trident, including creation of volumes, export policies,... 

As you observed, all volumes are mounted at / within the SVM (which is probably the most common configuration, even outside of Trident use cases). You configure the default export policy (or any other policy you assign for /) with read-only access, as the NFS client needs to be able to traverse it. No further access permissions to / are required (and traversal is required even if you mount the volume at a sub-path within the SVM). The actual export policy of the volume is then managed by Trident (assumed you enabled autoExport) and automatically set to the minimum necessary.

**Comment by barani129** [comment]
Hi @wonderland thanks for your comment. I take it that changing the default "/SVM" mount point behavior for NFS volumes is not an option right now. We will implement storage limits per namespace to avoid the vendor overutilizing the available SVM space and causing volume creation failures for others.

**Comment by wonderland** [comment]
It isn't possible with Trident today. I'm not in a position to decide if that can/should change. Just trying to facilitate the discussion by better understanding what you intend to achieve.  It sounds like you are implementing multi-tenancy within a shared K8s cluster? Though still not sure how a different volume mount path would play into that?

**Comment by clintonk** [comment]
> I take it that changing the default "/SVM" mount point behavior for NFS volumes is not an option right now.

This is correct.  Trident has worked like this since 2016 and any change could affect many users.  Thanks for understanding.
