### ISSUE TITLE
Unable to reference "release" tags for certain source using the Web interface

### ISSUE THREAD

**Issue by scaleoutsean** [NetApp/trident#95]
For example, go to https://github.com/NetApp/trident/blob/2a7bd72b5803b439d50af6692613767f5d39b5d6/storage_drivers/solidfire/solidfire_san.go and then pick `stable/v18.01`. I get the 404 error.

Were some references lost in migration?

I know I could download or clone that release, but it's inconvenient.

**Comment by adkerr** [comment]
Some areas of the code have been significantly refactored with the merging of ndvp’s and trident’s code bases. In your specific example the storage_drivers/solidfire/solidfire_san.go used to be under a top level “storage” directory. The code has been flattened to remove that directory.

Unfortunately when dealing with major refactors these kinds of broken links when jumping between releases is unavoidable.
