### ISSUE TITLE
Trident Protect can't create application

### ISSUE THREAD

**Issue by talorh** [NetApp/trident#955]
**Describe the bug**
I'm following https://docs.netapp.com/us-en/trident/trident-protect/trident-protect-manage-applications.html to create an application for protection.

**Environment**

- Trident version: 24.10
- Container runtime: cri-o 10.30.7.2
- Kubernetes version: v1.30.5
- Kubernetes orchestrator: OpenShift 4.17
- OS: Red Hat Enterprise Linux CoreOS 417.94.202411070820-0 Kernel 5.14.0-427.44.1.el9_4.x86_64
- NetApp backend types: ONTAP 9.15.1 iSCSI Backend

**To Reproduce**
```
$ cat app.yaml
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: test-app
  namespace: test-app
spec:
  includedNamespaces:
    labelSelector: {}
    namespace: test-app
$ oc apply -f app.yaml
The Application "test-app" is invalid:
* spec.includedNamespaces: Invalid value: "object": spec.includedNamespaces in body must be of type array: "object"
* <nil>: Invalid value: "null": some validation rules were not checked because the object was invalid; correct the existing errors to complete validation
$ 
```

**Expected behavior**
That the application is protected, and can be viewed with $ tridentctl-protect  get applications -n test-app

**Additional context**
Creating the app vault worked fine, however I can't proceed without creating an application.

**Comment by wonderland** [comment]
The YAML manifest is incorrect. As an app can span across multiple namespaces, an array is expected for the includedNamespaces. Most of the time it will just be a single namespace though but you still need to provide it as an array. The following will work:

```
apiVersion: protect.trident.netapp.io/v1
kind: Application
metadata:
  name: test-app
  namespace: test-app
spec:
  includedNamespaces:
    - namespace: test-app
```

I noticed this is wrong in the Trident documentation. I will open an issue for that to get it corrected. Hope this helps.

**Comment by talorh** [comment]
Ah Thanks, that works :)
