### ISSUE TITLE
Trident user generating security.invalid.login: Failed to authenticate login attempt to Vserver: message on NetApp filer

### ISSUE THREAD

**Issue by virtualistic** [NetApp/trident#958]
**Describe the solution you'd like**
Would like some clarification on the rationale of Trident generating http error messages on the NetApp filer  when all the trident user has, is api access. There seems to be no clear indication when this happens, we only get notified by the NetApp admins that our Trident user has generated below event.

**Additional context**
- Trident version used: 24.06.1
- Trident is soley used to create NFS PVs on a separate SVM reserved for a K8S cluster
- The message that gets generated on the filer:
`11/27/2024 14:46:01 filer01      ALERT         security.invalid.login: Failed to authenticate login attempt to Vserver: vserver123, username: tridentuser, application: http.`

The Trident user is created with SVM privileges like described below:
```
User/Group                 Authentication                 Acct          Authentication
Name           Application Method        Role Name        Locked        Method
+++++++++ +++++++++ ++++++++ +++++++++     ++++++++  ++++++++++
tridentuser        ontapi      password      vsadmin          no         none
```

Documentation also points that ontapi access should be enough: 
https://docs.netapp.com/us-en/trident/trident-use/ontap-nas.html#ontap-nas-driver-details
https://docs.netapp.com/us-en/trident/trident-use/ontap-nas-prep.html#update-authentication-methods-or-rotate-credentials

Any clarification what could cause this behaviour and how to mitigate it,  is very much appreciated!

**Comment by wonderland** [comment]
Ontap is in a transition phase from the traditional API (ZAPI, ontapi) to a RESTful API. Trident supports both APIs. It will attempt RESTful API first, then fallback to the traditional API if needed. I guess that initial REST API attempt is what triggers the log messages for you.

With future Ontap versions only REST API will be available so I'd suggest to enable http (which really is https/TLS of course) for the user account already. 

So for your setup:
`
security login create -username tridentuser -application http -authmethod password -role vsadmin –vserver vserver123 
`

**Comment by virtualistic** [comment]
> Ontap is in a transition phase from the traditional API (ZAPI, ontapi) to a RESTful API. Trident supports both APIs. It will attempt RESTful API first, then fallback to the traditional API if needed. I guess that initial REST API attempt is what triggers the log messages for you.
> 
> With future Ontap versions only REST API will be available so I'd suggest to enable http (which really is https/TLS of course) for the user account already.
> 
> So for your setup:
> 
> ```
> security login create -username tridentuser -application http -authmethod password -role vsadmin –vserver vserver123 
> ```
Many thanks @wonderland that makes sense, will update the storage team with this info, thanks for the quick reply!
